#!/bin/sh

error()
{
    echo ""
    echo "ERROR: bootstrap failed!"
    echo ""
    exit 1
}

# check for autotools

for program in automake aclocal autoconf autoheader
    do
    ($program --version ) > /dev/null 2>&1 || { 
    echo "ERROR: $program not found" >&2
    exit 1
    }
done

# checking for the GLOBUS_LOCATION

if test "x$GLOBUS_LOCATION" = "x"; then
    echo "ERROR Please specify GLOBUS_LOCATION" >&2
    exit 1
fi

config="-I ./config"

if test ! -f "$GLOBUS_LOCATION/share/globus_aclocal/gpt_autoconf_macros.m4"; then
    if test "x$GPT_LOCATION" = "x"; then
        echo "ERROR Globus Packaging Tools not found" >&2
        echo "ERROR either set GPT_LOCATION or install them in $GLOBUS_LOCATION" >&2
        exit 1
    else
        config="$config -I $GPT_LOCATION/share/globus_aclocal"
    fi
else
    config="$config -I $GLOBUS_LOCATION/share/globus_aclocal"
fi

 echo "running libtoolize --automake --copy --force"
libtoolize --automake --copy --force || error

echo "running aclocal $config"
aclocal $config || error

if test -f acconfig.h ; then
 echo "running autoheader"
   autoheader || error
fi

echo "running automake --copy -add-missing --foreign"
automake --copy --add-missing --foreign || \
  automake --copy --add-missing --foreign  || error

echo "running autoconf"
autoconf || error
exit 0
