#!/bin/sh

error()
{
    echo ""
    echo "ERROR: bootstrap failed!"
    echo ""
    exit 1
}

libtoolize --copy --force || error
aclocal -I config || error
if test -f acconfig.h ; then
    autoheader || error
fi
automake --copy --add-missing --foreign || \
  automake --copy --add-missing --foreign  || error
autoconf || error
exit 0
