#line 2 "globus_rsl_parser.lex.c"

#line 4 "globus_rsl_parser.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer globus_rsl_create_buffer
#define yy_delete_buffer globus_rsl_delete_buffer
#define yy_flex_debug globus_rsl_flex_debug
#define yy_init_buffer globus_rsl_init_buffer
#define yy_flush_buffer globus_rsl_flush_buffer
#define yy_load_buffer_state globus_rsl_load_buffer_state
#define yy_switch_to_buffer globus_rsl_switch_to_buffer
#define yyin globus_rslin
#define yyleng globus_rslleng
#define yylex globus_rsllex
#define yylineno globus_rsllineno
#define yyout globus_rslout
#define yyrestart globus_rslrestart
#define yytext globus_rsltext
#define yywrap globus_rslwrap
#define yyalloc globus_rslalloc
#define yyrealloc globus_rslrealloc
#define yyfree globus_rslfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE globus_rslrestart(globus_rslin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t globus_rslleng;

extern FILE *globus_rslin, *globus_rslout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up globus_rsltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up globus_rsltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via globus_rslrestart()), so that the user can continue scanning by
	 * just pointing globus_rslin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when globus_rsltext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t globus_rslleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow globus_rslwrap()'s to do buffer switches
 * instead of setting up a fresh globus_rslin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void globus_rslrestart (FILE *input_file  );
void globus_rsl_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE globus_rsl_create_buffer (FILE *file,int size  );
void globus_rsl_delete_buffer (YY_BUFFER_STATE b  );
void globus_rsl_flush_buffer (YY_BUFFER_STATE b  );
void globus_rslpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void globus_rslpop_buffer_state (void );

static void globus_rslensure_buffer_stack (void );
static void globus_rsl_load_buffer_state (void );
static void globus_rsl_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER globus_rsl_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE globus_rsl_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE globus_rsl_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE globus_rsl_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *globus_rslalloc (yy_size_t  );
void *globus_rslrealloc (void *,yy_size_t  );
void globus_rslfree (void *  );

#define yy_new_buffer globus_rsl_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        globus_rslensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            globus_rsl_create_buffer(globus_rslin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        globus_rslensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            globus_rsl_create_buffer(globus_rslin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

typedef unsigned char YY_CHAR;

FILE *globus_rslin = (FILE *) 0, *globus_rslout = (FILE *) 0;

typedef int yy_state_type;

extern int globus_rsllineno;

int globus_rsllineno = 1;

extern char *globus_rsltext;
#define yytext_ptr globus_rsltext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up globus_rsltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	globus_rslleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 30
#define YY_END_OF_BUFFER 31
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[55] =
    {   0,
        0,    0,    3,    3,    0,    0,    0,    0,    0,    0,
        0,    0,   31,   12,   28,   28,   29,    8,   27,   10,
       25,   13,   15,   29,   24,   20,   18,   22,   29,   26,
        3,    3,   29,   14,   17,    5,    5,    6,    6,    1,
        1,   12,   11,   28,   19,    7,   21,   23,    9,    3,
        4,    2,   16,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    1,    8,    5,    9,
       10,   11,   12,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   13,
       14,   15,   16,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   17,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   18,    1,   16,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[19] =
    {   0,
        1,    2,    2,    2,    2,    2,    1,    1,    2,    2,
        3,    1,    2,    2,    2,    2,    2,    1
    } ;

static yyconst flex_int16_t yy_base[63] =
    {   0,
        0,    0,   16,   17,   12,   14,   67,   66,   65,   64,
       63,   62,   64,   56,   23,   27,   48,   71,   71,   71,
       71,   50,   71,   71,   71,   46,   71,   45,    0,   71,
        0,    0,   48,   25,   30,   71,   71,   71,   71,   71,
       71,   28,   71,   30,   71,   71,   71,   71,   71,    0,
       71,   71,   71,   71,   37,   40,   43,   46,   33,   49,
       52,   54
    } ;

static yyconst flex_int16_t yy_def[63] =
    {   0,
       54,    1,   55,   55,    1,    1,   56,   56,   57,   57,
       58,   58,   54,   59,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   60,   54,
       61,   61,   62,   54,   54,   54,   54,   54,   54,   54,
       54,   59,   54,   54,   54,   54,   54,   54,   54,   61,
       54,   54,   54,    0,   54,   54,   54,   54,   54,   54,
       54,   54
    } ;

static yyconst flex_int16_t yy_nxt[90] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   24,   29,   30,   32,   32,
       34,   35,   34,   35,   44,   44,   33,   33,   44,   44,
       53,   44,   44,   42,   43,   46,   53,   31,   31,   31,
       36,   36,   36,   38,   38,   38,   40,   40,   40,   49,
       49,   49,   50,   50,   51,   51,   51,   52,   48,   47,
       46,   45,   43,   54,   41,   41,   39,   39,   37,   37,
       13,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54
    } ;

static yyconst flex_int16_t yy_chk[90] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        5,    5,    6,    6,   15,   15,    3,    4,   16,   16,
       35,   44,   44,   59,   42,   34,   35,   55,   55,   55,
       56,   56,   56,   57,   57,   57,   58,   58,   58,   60,
       60,   60,   61,   61,   62,   62,   62,   33,   28,   26,
       22,   17,   14,   13,   12,   11,   10,    9,    8,    7,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int globus_rsl_flex_debug;
int globus_rsl_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *globus_rsltext;
#line 1 "globus_rsl_parser.l"
/*
 * Copyright 1999-2006 University of Chicago
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#line 17 "globus_rsl_parser.l"
/* NOTE: You MUST run flex with the -s option (to disable the default rule)
 *   for this to work.  Of course you should always do this anyway
 *   if you care about correctness...
 * NOTE: You must use bison with %pure_parser and flex for this to work */


/* needed to read input from string rather than stdin
 * from page 157 of Nutshell lex & yacc
 * NOTE: only works if using flex and not lex
 */

#undef YY_INPUT
#define YY_INPUT(b,r,ms) (r = my_yyinput(b, ms))

/* end from page 157 of Nutshell lex & yacc
 */


/*
 * The following macros give globus_rsllex() the appropriate
 * arguments, as expected by bison with %pure_parser
 */
#ifdef YYPURE
#ifdef YYLSP_NEEDED
#ifdef YYLEX_PARAM
#define YY_DECL       int globus_rsllex (YYSTYPE *yylval, YYLTYPE *yylloc, void *YYLEX_PARAM)
#else
#define YY_DECL       int globus_rsllex (YYSTYPE *yylval, YYLTYPE *yylloc)
#endif
#else /* not YYLSP_NEEDED */
#ifdef YYLEX_PARAM
#define YY_DECL       int globus_rsllex (YYSTYPE *yylval, void *YYLEX_PARAM)
#else
#define YY_DECL       int globus_rsllex (YYSTYPE *yylval)
#endif
#endif /* not YYLSP_NEEDED */
#define GRAMI_YYLVAL_DOT yylval->
#endif

  /* the token types used by our parser */

/* #include "globus_rsl_tokens.tab.h" */


  /* variables etc. used by the lexer rules below */

#include "globus_common.h"


  /* this lexer uses exclusive start-conditions to implement
   * several inter-related lexical languages.
   *
   * the INITIAL state implements the top-level RSL lexical language
   * consisting of operators, comments, value-expressions, and 
   * variable-reference expressions.
   *
   * the VARIABLE state implements the embedded variable-reference
   * scanner for tokens in value expressions (as the INITIAL state does),
   * but also maintains context to recognize when the end of a variable
   * reference in the RSL grammar has been reached (by matching parens).
   * the beginning and end of variable references mark points in the input
   * stream where we must pay particular attention to whitespace to
   * recognize the implicit concatenation lexical notation.  when we
   * encounter this notation, we inject a concatenation operator into
   * the token stream so that the parser doesn't have to do anything
   * special for implicit concatenate.
   *
   * the IMPLICIT_CONCATENATE state doesn't scan any characters, but
   * generates a single concatenate operator token.  this is used by
   * the INITIAL and VARIABLE states to emit the extra token at certain
   * transition points.
   *
   * the COMMENT state implements the embedded scanner that eats
   * the body and terminating delimiter of comments once the comment
   * sublanguage has been recognized by the INITIAL and VARIABLE scanners.
   *
   * the QUOTE and QUOTE_HIT_DELIM states implement the embedded 
   * quoted-literal lexical language, generating quoted-literal tokens 
   * once the quoted-literal sublanguage has been recognized by the 
   * INITIAL and VARIABLE scanners.
   *
   * start-state machine:
   *
   *   INITIAL->COMMENT->INITIAL
   *   INITIAL->QUOTE->QUOTE_HIT_DELIM->INITIAL
   *   INITIAL->VARIABLE
   *   INITIAL->IMPLICIT_CONCATENATE->VARIABLE
   *
   *   VARIABLE->COMMENT->VARIABLE
   *   VARIABLE->QUOTE->QUOTE_HIT_DELIM->VARIABLE
   *   VARIABLE->IMPLICIT_CONCATENATE->INITIAL
   *   VARIABLE->INITIAL
   *   VARIABLE->IMPLICIT_CONCATENATE->VARIABLE
   * 
   *   the calling_state variable below is used to return
   *   from non-recursive quote/comment/implicit-concatenate states to the 
   *   appropriate initial/variable state.
   *
   *   the recursive variable/initial transitions are controlled
   *   by the stack documented below.
   */

int calling_state;  /* one of INITIAL, VARIABLE */

char             quote_delimiter = '\0';
globus_fifo_t  * quote_text_fifo = NULL; /* completely dynamic buffer */


  /* the scanner matches left and right-parens by
   * introducing a new counter at the beginning of each
   * variable reference expression.  this allows it to
   * detect the terminating right-paren of the variable reference
   * and check whether the enjambed implicit-concatenation
   * syntax is being used.  it then restores the previous
   * paren counter and keeps going (to recognize the end
   * of any enclosing variable reference expression).
   */
typedef struct paren_count_stack_elem_s {
  int count;
} paren_count_stack_elem_t;

/* manipulate this list as stack...
 * introduced as a list rather than an abstract-data-type
 * so we can simply init it here as the constant NULL. */
globus_list_t * paren_count_stack = NULL; 



/* the following sections define:
 *    symbolic regular-expression names (put all char-set details together)
 *    start-condition (state) definitions
 *    pattern/action rules
 */

/* notes about the character classes:
 *   because unquoted literals can contain '/', the comment
 *   syntax must be separated from prefix unquoted literals by whitespace.
 * 
 *   in this implementation, the comment-start notation '/''*' match 
 *   will win over the alternate match of '/' as an unquoted literal 
 *   followed by the invalid single char '*' since it is a longer match.
 */
/*
COMMENT_BODY               ((("*"[^)])|([^*]))*)
*/
#line 195 "globus_rsl_parser.l"
  /* the following are all exclusive states.  the use of the states
   * are explained above.
   *
   * the difference between exclusive and inclusive states in flex
   * is that in exclusive states any bare pattern/action rules 
   * are disabled, so _only_ rules explicitly labeled as being active
   * in the exclusive state are active when that state is entered.
   * inclusive states activate both explicitly labeled rules and
   * the bare unlabeled rules.
   *
   * this flex file does not use any unlabeled rules, so this distinction
   * doesn't really matter.  please keep it that way if you modify it.
   *
   * this flex file also does not rely on the order of pattern/action
   * rules to resolve anything.  each of the rule sets active in a given
   * state are resolved only by the basic greatest-matching-prefix
   * distinction.
   */





#line 686 "globus_rsl_parser.lex.c"

#define INITIAL 0
#define COMMENT 1
#define VARIABLE 2
#define QUOTE 3
#define QUOTE_HIT_DELIM 4
#define IMPLICIT_CONCATENATE 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int globus_rsllex_destroy (void );

int globus_rslget_debug (void );

void globus_rslset_debug (int debug_flag  );

YY_EXTRA_TYPE globus_rslget_extra (void );

void globus_rslset_extra (YY_EXTRA_TYPE user_defined  );

FILE *globus_rslget_in (void );

void globus_rslset_in  (FILE * in_str  );

FILE *globus_rslget_out (void );

void globus_rslset_out  (FILE * out_str  );

yy_size_t globus_rslget_leng (void );

char *globus_rslget_text (void );

int globus_rslget_lineno (void );

void globus_rslset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int globus_rslwrap (void );
#else
extern int globus_rslwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( globus_rsltext, globus_rslleng, 1, globus_rslout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( globus_rslin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( globus_rslin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, globus_rslin))==0 && ferror(globus_rslin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(globus_rslin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int globus_rsllex (void);

#define YY_DECL int globus_rsllex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after globus_rsltext and globus_rslleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 223 "globus_rsl_parser.l"


#line 876 "globus_rsl_parser.lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! globus_rslin )
			globus_rslin = stdin;

		if ( ! globus_rslout )
			globus_rslout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			globus_rslensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				globus_rsl_create_buffer(globus_rslin,YY_BUF_SIZE );
		}

		globus_rsl_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of globus_rsltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 55 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 71 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 225 "globus_rsl_parser.l"
{ BEGIN (calling_state);
   /* we just ate a character "by accident", so push it back */
   yyless(globus_rslleng-1);

   return (RSL_OP_CONCATENATE);
dummy_implicit_concatenate_label: ;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 234 "globus_rsl_parser.l"
{ BEGIN (calling_state);
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 237 "globus_rsl_parser.l"
{ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up globus_rsltext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up globus_rsltext again */
YY_RULE_SETUP
#line 238 "globus_rsl_parser.l"
{ }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 240 "globus_rsl_parser.l"
{ /* conditional BEGIN */
  if ( globus_rsltext[0] != quote_delimiter ) {
    /* another quoted character */

    globus_fifo_enqueue (quote_text_fifo,
			 (void *) (globus_rsltext[0]));
  }
  else {

    BEGIN (QUOTE_HIT_DELIM);
  }
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 253 "globus_rsl_parser.l"
{ /* conditional BEGIN */
  if ( globus_rsltext[0] == quote_delimiter ) {
    /* an escaped delimiter */
    globus_fifo_enqueue (quote_text_fifo,
			 (void *) (globus_rsltext[0]));

    /* continue scanning the quoted literal */
    BEGIN (QUOTE);
  }
  else {
    /* we just ate a character after the delimiter, so push it back */
    yyless(globus_rslleng-1);

    BEGIN (calling_state);

    /* return the quoted literal token */
    {
      char * buf;
      char c;
      int i;

      buf = globus_malloc (sizeof(char)
			   * (globus_fifo_size (quote_text_fifo)
			      + 1));
      assert (buf!=NULL);
      
      i = 0;
      while ( ! globus_fifo_empty (quote_text_fifo) ) {
	buf[i] = (char) (long) globus_fifo_dequeue (quote_text_fifo);
	i++;
      }
      buf[i] = '\0';

      GRAMI_YYLVAL_DOT String = buf;

      globus_fifo_destroy (quote_text_fifo);
      globus_free (quote_text_fifo);
      quote_text_fifo = NULL;

      return (RSL_STRING);
    dummy_quoted_literal_label: ;
    }
  }
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 299 "globus_rsl_parser.l"
{ 
  calling_state = YY_START;
  BEGIN (COMMENT);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 304 "globus_rsl_parser.l"
{
  calling_state = YY_START;
  BEGIN (QUOTE);
  quote_delimiter = globus_rsltext[0];
  quote_text_fifo = globus_malloc (sizeof (globus_fifo_t));
  assert (quote_text_fifo!=NULL);
  globus_fifo_init (quote_text_fifo);
}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 313 "globus_rsl_parser.l"
{ 
  calling_state = YY_START;
  BEGIN (QUOTE);
  quote_delimiter = globus_rsltext[1]; /* the user's quote character */
  quote_text_fifo = globus_malloc (sizeof (globus_fifo_t));
  assert (quote_text_fifo!=NULL);
  globus_fifo_init (quote_text_fifo);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 322 "globus_rsl_parser.l"
{ BEGIN (VARIABLE);
  {
    paren_count_stack_elem_t * frame;
    frame = globus_malloc (sizeof (paren_count_stack_elem_t));
    assert (frame!=NULL);
    frame->count = 0;
    globus_list_insert (&paren_count_stack, (void *) frame);
  }

  return (RSL_VARIABLE_START);
dummy_variable_start_label: ;
}
	YY_BREAK
case 11:
*yy_cp = (yy_hold_char); /* undo effects of setting up globus_rsltext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up globus_rsltext again */
YY_RULE_SETUP
#line 335 "globus_rsl_parser.l"
{ 
  calling_state = YY_START;
  BEGIN (IMPLICIT_CONCATENATE);
  /* this unquoted literal is enjambed with a variable,
   * so we bounce through the IMPLICIT_CONCATENATE state to
   * generate an extra CONCATENATE token and bounce back to 
   * the calling state, where the variable will be recognized
   * as usual.
   */
  GRAMI_YYLVAL_DOT String = strdup (globus_rsltext);
  return (RSL_STRING);
dummy_unquoted_literal_label_1: ;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 349 "globus_rsl_parser.l"
{
  GRAMI_YYLVAL_DOT String = strdup (globus_rsltext);
  return (RSL_STRING);
dummy_unquoted_literal_label_2: ;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 355 "globus_rsl_parser.l"
{ 
  return (RSL_LPAREN); 
dummy_lparen_label_1: ;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 360 "globus_rsl_parser.l"
{
  assert (! globus_list_empty (paren_count_stack));
  (((paren_count_stack_elem_t *) 
    globus_list_first (paren_count_stack))->count) += 1;
  return (RSL_LPAREN);
dummy_lparen_label_2: ;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 368 "globus_rsl_parser.l"
{
  return (RSL_RPAREN);
dummy_rparen_label_1: ;
}
	YY_BREAK
case 16:
*yy_cp = (yy_hold_char); /* undo effects of setting up globus_rsltext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up globus_rsltext again */
YY_RULE_SETUP
#line 373 "globus_rsl_parser.l"
{ 
						  /* conditional BEGIN */
  int * paren_countp;

  assert (! globus_list_empty (paren_count_stack));
  paren_countp = &(((paren_count_stack_elem_t *) 
		    globus_list_first (paren_count_stack))->count);

  (*paren_countp) -= 1;

  if ((*paren_countp) == 0) {
    /* this right-paren closes a variable reference expression,
     * and is enjambed with a quoted-literal or variable,
     * so we bounce through the IMPLICIT_CONCATENATE state to
     * generate an extra CONCATENATE token and bounce back to 
     * the calling state, where the variable will be recognized
     * as usual.
     */

    /* pop our completed counter from the stack */
    globus_free ((paren_count_stack_elem_t *) 
		 globus_list_first (paren_count_stack));
    globus_list_remove (&paren_count_stack, paren_count_stack);

    if ( globus_list_empty (paren_count_stack)) {
      /* we were the outermost variable reference, so the 
       * implicit-concatenation state should return to the INITIAL state
       * after generating a token.
       */
      calling_state = INITIAL;
    }
    else {
      calling_state = VARIABLE;
    }

    BEGIN (IMPLICIT_CONCATENATE);
  }

  return (RSL_RPAREN);
dummy_rparen_label_2: ;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 415 "globus_rsl_parser.l"
{ /* conditional BEGIN */
  int * paren_countp;

  assert (! globus_list_empty (paren_count_stack));
  paren_countp = &(((paren_count_stack_elem_t *) 
		    globus_list_first (paren_count_stack))->count);

  (*paren_countp) -= 1;

  if ((*paren_countp) == 0) {
    /* this right-paren closes a variable reference expression */
    /* pop our completed counter from the stack */
    globus_free ((paren_count_stack_elem_t *) 
		 globus_list_first (paren_count_stack));
    globus_list_remove (&paren_count_stack, paren_count_stack);

    if ( globus_list_empty (paren_count_stack)) {
      /* we were the outermost variable reference, so the 
       * next state should be INITIAL */

      BEGIN (INITIAL);
    }
    else {

      BEGIN (VARIABLE);
    }
  }

  return (RSL_RPAREN);
dummy_rparen_label_4: ;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 447 "globus_rsl_parser.l"
{
  return (RSL_OP_EQ);
dummy_op_eq_label: ;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 452 "globus_rsl_parser.l"
{
  return (RSL_OP_NEQ);
dummy_op_neq_label: ;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 457 "globus_rsl_parser.l"
{
  return (RSL_OP_LT);
dummy_op_lt_label: ;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 462 "globus_rsl_parser.l"
{
  return (RSL_OP_LTEQ);
dummy_op_lteq_label: ;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 467 "globus_rsl_parser.l"
{
  return (RSL_OP_GT);
dummy_op_gt_label: ;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 472 "globus_rsl_parser.l"
{
  return (RSL_OP_GTEQ);
dummy_op_gteq_label: ;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 477 "globus_rsl_parser.l"
{
  return (RSL_OP_MULTIREQ);
dummy_op_multireq_label: ;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 482 "globus_rsl_parser.l"
{
  return (RSL_OP_AND);
dummy_op_conjunction_label: ;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 487 "globus_rsl_parser.l"
{
  return (RSL_OP_OR);
dummy_op_disjunction_label: ;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 492 "globus_rsl_parser.l"
{
  return (RSL_OP_CONCATENATE);
dummy_op_concatenate_label: ;
}
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 497 "globus_rsl_parser.l"
{ }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 500 "globus_rsl_parser.l"
{
  /* we ran into a character not matched by any of the
   * above patterns.  let the parser sort it out. */
  yyterminate();
dummy_invalid_char_label: ;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(VARIABLE):
case YY_STATE_EOF(QUOTE):
case YY_STATE_EOF(QUOTE_HIT_DELIM):
case YY_STATE_EOF(IMPLICIT_CONCATENATE):
#line 508 "globus_rsl_parser.l"
{
  /* we ran into EOF in any of the states.  maybe error, maybe not.
   * let the parser sort it out. */
  yyterminate();
dummy_eof_label: ;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 514 "globus_rsl_parser.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1361 "globus_rsl_parser.lex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed globus_rslin at a new source and called
			 * globus_rsllex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = globus_rslin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( globus_rslwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * globus_rsltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of globus_rsllex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					globus_rslrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			globus_rslrestart(globus_rslin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) globus_rslrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 55 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 55 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 54);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up globus_rsltext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					globus_rslrestart(globus_rslin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( globus_rslwrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve globus_rsltext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void globus_rslrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        globus_rslensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            globus_rsl_create_buffer(globus_rslin,YY_BUF_SIZE );
	}

	globus_rsl_init_buffer(YY_CURRENT_BUFFER,input_file );
	globus_rsl_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void globus_rsl_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		globus_rslpop_buffer_state();
	 *		globus_rslpush_buffer_state(new_buffer);
     */
	globus_rslensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	globus_rsl_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (globus_rslwrap()) processing, but the only time this flag
	 * is looked at is after globus_rslwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void globus_rsl_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	globus_rslin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE globus_rsl_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) globus_rslalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in globus_rsl_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) globus_rslalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in globus_rsl_create_buffer()" );

	b->yy_is_our_buffer = 1;

	globus_rsl_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with globus_rsl_create_buffer()
 * 
 */
    void globus_rsl_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		globus_rslfree((void *) b->yy_ch_buf  );

	globus_rslfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a globus_rslrestart() or at EOF.
 */
    static void globus_rsl_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	globus_rsl_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then globus_rsl_init_buffer was _probably_
     * called from globus_rslrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void globus_rsl_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		globus_rsl_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void globus_rslpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	globus_rslensure_buffer_stack();

	/* This block is copied from globus_rsl_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from globus_rsl_switch_to_buffer. */
	globus_rsl_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void globus_rslpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	globus_rsl_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		globus_rsl_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void globus_rslensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)globus_rslalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in globus_rslensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)globus_rslrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in globus_rslensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE globus_rsl_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) globus_rslalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in globus_rsl_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	globus_rsl_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to globus_rsllex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       globus_rsl_scan_bytes() instead.
 */
YY_BUFFER_STATE globus_rsl_scan_string (yyconst char * yystr )
{
    
	return globus_rsl_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to globus_rsllex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE globus_rsl_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) globus_rslalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in globus_rsl_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = globus_rsl_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in globus_rsl_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up globus_rsltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		globus_rsltext[globus_rslleng] = (yy_hold_char); \
		(yy_c_buf_p) = globus_rsltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		globus_rslleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int globus_rslget_lineno  (void)
{
        
    return globus_rsllineno;
}

/** Get the input stream.
 * 
 */
FILE *globus_rslget_in  (void)
{
        return globus_rslin;
}

/** Get the output stream.
 * 
 */
FILE *globus_rslget_out  (void)
{
        return globus_rslout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t globus_rslget_leng  (void)
{
        return globus_rslleng;
}

/** Get the current token.
 * 
 */

char *globus_rslget_text  (void)
{
        return globus_rsltext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void globus_rslset_lineno (int  line_number )
{
    
    globus_rsllineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see globus_rsl_switch_to_buffer
 */
void globus_rslset_in (FILE *  in_str )
{
        globus_rslin = in_str ;
}

void globus_rslset_out (FILE *  out_str )
{
        globus_rslout = out_str ;
}

int globus_rslget_debug  (void)
{
        return globus_rsl_flex_debug;
}

void globus_rslset_debug (int  bdebug )
{
        globus_rsl_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from globus_rsllex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    globus_rslin = stdin;
    globus_rslout = stdout;
#else
    globus_rslin = (FILE *) 0;
    globus_rslout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * globus_rsllex_init()
     */
    return 0;
}

/* globus_rsllex_destroy is for both reentrant and non-reentrant scanners. */
int globus_rsllex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		globus_rsl_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		globus_rslpop_buffer_state();
	}

	/* Destroy the stack itself. */
	globus_rslfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * globus_rsllex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *globus_rslalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *globus_rslrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void globus_rslfree (void * ptr )
{
	free( (char *) ptr );	/* see globus_rslrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 514 "globus_rsl_parser.l"
