#! /bin/sh

# checking for the GLOBUS_LOCATION

if test "x$GLOBUS_LOCATION" = "x"; then
    echo "Using default GLOBUS_LOCATION of /usr"
    GLOBUS_LOCATION="/usr"
fi

if [ ! -f ${GLOBUS_LOCATION}/share/globus/globus-bootstrap.sh ]; then
    echo "ERROR: Unable to locate \${GLOBUS_LOCATION}/share/globus/globus-bootstrap.sh"
    echo "       Please ensure that you have installed the globus-core package and"
    echo "       that GLOBUS_LOCATION is set to the proper directory"
    exit
fi

. ${GLOBUS_LOCATION}/share/globus/globus-bootstrap.sh
