#! /bin/sh

. $GLOBUS_LOCATION/libexec/globus-sh-tools.sh

echo "
***************************************************************************

Note: To complete setup of the example Globus Gridmap Callout you need to 
run the following script as root:

$GLOBUS_LOCATION/setup/globus/setup-globus-gridmap-callout

This script will create the /etc/grid-security/gsi-authz.conf file if it does 
not already exist and register the callout.
For further information on using the setup-globus-gridmap-callout script, 
use the -help option.  The -nonroot can be used on systems where root access
is not available.

***************************************************************************
"
exit 0
