#! /bin/sh

# YYYY-MM-DD;Package_Name-Version.Version;Toolkit Version;Type (bug sec enh);Description
IFS=";"
echo "<advisories>"

curl -Ls http://www.globus.org/toolkit/advisories.txt | \
while read date pkg toolkit type desc; do
    if expr $date : "#" > /dev/null 2>&1 ; then
        continue
    fi

    cat <<EOF
    <item>
        <date>$date</date>
        <pkg>$pkg</pkg>
        <version>$toolkit</version>
        <type>$type</type>
        <description><![CDATA[$desc]]></description>
    </item>
EOF

done 

echo "</advisories>"
