.TH myproxy-server.config 5 "2005-6-8" "NCSA" "MyProxy"
.SH NAME
myproxy-server.config \- myproxy-server configuration file
.SH DESCRIPTION
The
.B myproxy-server.config
file sets the policy for the 
.BR myproxy-server (8),
specifying what credentials may be stored in the server's
repository and who is authorized to retrieve credentials.
By default, the
.BR myproxy-server (8)
looks for this file in
.I /etc/myproxy-server.config
and if it is not found there, it looks in
.IR $GLOBUS_LOCATION/etc/myproxy-server.config .
The
.B myproxy-server -c
option can be used to specify an alternative location.
The file installed by default does not allow any requests.
.PP
The file also supports a
.B passphrase_policy_program
command for specifying an external program for evaluating the quality
of users' passphrases.  A sample program is installed in
.I $GLOBUS_LOCATION/share/myproxy/myproxy-passphrase-policy
but is not enabled by default.
.PP
Lines in the configuration file use limited regular expressions
for matching the distinguished names (DNs) of classes of users.
The limited regular expressions support the shell-stype characters '*'
and '?', where '*' matches any number of characters and '?' matches
any single character.
.PP
The DN limited regexes should be delimited with double quotes 
(\*(lqDN regex\*(rq).
.PP
The configuration file has the following types of lines:
.TP
.BI accepted_credentials " \*(lqDN regex\*(rq"
Each of these lines allows any clients whose DNs match the
given limited regex to connect to the myproxy-server and store
credentials with it for future retrieval.  Any number of these
lines may appear.  For backwards compatibility, these lines
can also start with 
.B allowed_clients 
instead of
.BR accepted_credentials .
If no 
.B accepted_credentials
lines are specified, the server will not allow any clients to store
credentials.
.TP
.BI authorized_retrievers " \*(lqDN regex\*(rq"
Each of these lines allows the server administrator to set
server-wide policies for authorized retrievers. If the client
DN does not match the given limited regex the client is not
allowed to retrieve the credentials previously stored by a
client.  In addition to the server-wide policy, myproxy also
provides support for per-credential policy. The user can
specify the regex DN of the allowed retrievers of the
credential when uploading the credential (using
.BR myproxy-init (1)).
The retrieval client
DN must also match the user specified regex. In order to
retrieve credentials the client also needs to know the name
and pass phrase provided by the client when the credentials
were stored. Any number of these lines may appear.  For
backwards compatibility, these lines can also start with
.B allowed_services 
instead of 
.BR authorized_retrievers .
If no 
.B authorized_retrievers
lines are specified, the server will not allow any clients to retrieve
credentials.
.TP
.BI default_retrievers " \*(lqDN regex\*(rq"
Each of these lines allows the server administrator to set
server-wide default policies. The regex specifies the clients
who can access the credentials. The default retriever policy
is enforced if a per-credential policy is not specified on
upload (using
.BR myproxy-init (1)
or
.BR myproxy-store (1)).
In other words, the client can override this policy
for a credential on upload.  The per-credential policy is
enforced in addition to the server-wide policy specified by
the authorized_retrievers line (which clients can not
override).  Any number of these lines may be present.  For
backwards compatibility, if no 
.B default_retrievers 
line is
specified, the default policy is "*", which allows any client
to pass the per-credential policy check.  (The client must
still pass the 
.B authorized_retrievers 
check.)
.TP
.BI authorized_key_retrievers " \*(lqDN regex\*(rq"
This policy controls who can retrieve credentials (certificates and
keys) directly from the repository using
.BR myproxy-retrieve (1).
Clients must also match the
.B authorized_retrievers
policy.
If no 
.B authorized_key_retrievers
lines are specified, the server will not allow any clients to retrieve
keys directly from the repository.
.TP
.BI default_key_retrievers " \*(lqDN regex\*(rq"
This policy applies if a per-credential policy is not specified on
upload (using
.BR myproxy-init (1)
or
.BR myproxy-store (1)).
In other words, the client can override this policy
for a credential on upload.  The per-credential policy is
enforced in addition to the server-wide policy specified by
the authorized_key_retrievers line (which clients can not
override).  Any number of these lines may be present.  
If no 
.B default_key_retrievers 
line is
specified, the default policy is "*", which allows any client
to pass the per-credential policy check.  (The client must
still pass the 
.B authorized_key_retrievers 
check.)
.TP
.BI slave_servers " server:port;"
This value is for use with the 
.BR myproxy-replicate (1)
utility.  This tag provides a list of servers that will be used as secondary
repositories for the MyProxy database.  Each server should be seperated by
a ";".  Also, a port may be provided if the slave server is using a port
other then the default.  The server name maybe a recognized DNS or an IP
address.
.TP
.BI master_server " server:port;"
This value is used by the MyProxy failover logic.  This tag provides either the
DNS or IP address of the server acting as the MASTER.  Also, a port may be 
provided if the slave server is using a port other then the default.
.TP
.BI authorized_renewers " \*(lqDN regex\*(rq"
Each of these lines allows the server administrator to set
server-wide policies for authorized renewers. If the client DN
does not match the given limited regex the client is not
allowed to renew the credentials previously stored by a
client.  In addition to the server-wide policy, myproxy also
provides support for per-credential policy. The user can
specify the regex DN of the allowed renewers of the credential
on upload (using
.BR myproxy-init (1)).
The renewal client DN must match both this regex
and the user specified regex. In this case, the client must
also already have a credential with a DN matching the DN of
the credentials to be retrieved, to be used in a second
authorization step (see the
.B -a
options for
.BR myproxy-logon (1)
and
.BR myproxy-retrieve (1)).
.TP
.BI default_renewers " \*(lqDN regex\*(rq"
Each of these lines allows the server administrator to set
server-wide default renewer policies. The regex specifies the
clients who can renew the credentials. The default renewer
policy is enforced if a per-credential policy is not specified
on upload (using
.BR myproxy-init (1)).
This is enforced in addition to the server-wide
policy specified by the 
.B authorized_renewers 
line. Any number
of these lines may appear.  For backwards compatibility, if no
default_renewers line is specified, the default policy is "*",
which allows any client to pass the per-credential policy
check.  (The client must still pass the 
.B authorized_renewers
check.)
.TP
.BI passphrase_policy_program " full-path-to-script"
This line specifies a program to run whenever a passphrase is set or
changed for implementing a local password policy.
The program is passed the new passphrase via stdin and is passed the
following arguments: username, distinguished name, credential name (if
any), per-credential retriever policy (if any), and per-credential
renewal policy (if any).
If the passphrase is acceptable, the program should exit with status 0.
Otherwise, it should exit with non-zero status, causing the operation
in progress (credential load, passphrase change) to fail with the error
message provided by the program's stdout.
Note: You must specify the full path to the external program.
$GLOBUS_LOCATION can't be used in the myproxy-server.config file.
.TP
.BI pam " option"
This line
governs the use of PAM to check passphrases.
MyProxy will attempt to
authenticate via PAM, with the supplied username and passphrase.
Note that PAM will need to be configured externally for the
application "myproxy" (usually in /etc/pam.d/), or for the
application named by pam_id, below.
Accepted values:
.RS
.TP
.B required
PAM password authentication is required under all conditions.  If the
credential is unencrypted (that is, it has no passphrase), a PAM
password check is still required for authentication.  If the
credential is encrypted, its passphrase must match the PAM password.
.TP
.B sufficient
The user's passphrase may match either the credential passphrase or,
if the credential is unencrypted, the PAM passphrase.  If the
credential is encrypted, then the PAM password is not relevant.
.TP
.BR disabled " (default)"
PAM is not used to check passphrases.
.RE
.TP
.BI pam_id " string"
The name that myproxy uses to identify itself to PAM.  Default is
"myproxy".
For example, on most Unix-like systems, if pam_id is set to "login",
MyProxy will authenticate against the system's own usernames and
passwords.
.TP
.BI max_proxy_lifetime " hours"
This line specifies a server-wide maximum lifetime for retrieved proxy
credentials.  By default, no server-wide maximum is enforced.
However, if this option is specified, the server will limit the
lifetime of any retrieved proxy credentials to the value given.
.SH FILES
.TP
.I /etc/myproxy-server.config
Default location for the server configuration file.
.TP
.I $GLOBUS_LOCATION/etc/myproxy-server.config
Alternate location for the server configuration file.
A different location can be specified by using the
.BR myproxy-server (8)
.B -c
option.
.TP
.I $GLOBUS_LOCATION/share/myproxy/myproxy-passphrase-policy
A sample program for evaluating passphrase quality.
.SH ENVIRONMENT
.TP
.B GLOBUS_LOCATION
Specifies the root of the MyProxy installation, used to find the
default location of the 
.I myproxy-server.config
file.
.SH AUTHORS
Bill Baker,
Jim Basney,
Shiva Shankar Chetan,
Patrick Duda,
Jarek Gawor,
Daniel Kouril,
Zhenmin Li,
Jason Novotny,
Miroslav Ruda,
Benjamin Temko,
and Von Welch
.SH "SEE ALSO"
.BR myproxy-change-pass-phrase (1),
.BR myproxy-destroy (1),
.BR myproxy-info (1),
.BR myproxy-init (1),
.BR myproxy-logon (1),
.BR myproxy-retrieve (1),
.BR myproxy-store (1),
.BR myproxy-admin-adduser (8),
.BR myproxy-admin-change-pass (8),
.BR myproxy-admin-load-credential (8),
.BR myproxy-admin-query (8),
.BR myproxy-server (8)
