#!/bin/sh
cp gssapi-openssh/nmi/tasklist.nmi .
# skip GT4 builds on x86_64_macos_10.6-updated
if test "x$NMI_PLATFORM" == "xx86_64_macos_10.6-updated"; then
    grep -v GT4 tasklist.nmi > tasklist.nmi.new
    mv -f tasklist.nmi.new tasklist.nmi
fi
exit 0
