#!/bin/sh
set -e # exit on any error
if test "$NMI_PLATFORM" = "ia64_sles_9"; then
  GT_INSTALLER=gt4.0.3-all-source-installer.tar.gz
  GT_INSTALLER_URL=http://www.globus.org/ftppub/gt4/4.0/4.0.3/installers/src/$GT_INSTALLER
else
  GT_INSTALLER=gt4.0.3-$NMI_PLATFORM-installer.tar.gz
  GT_INSTALLER_URL=http://www.globus.org/ftppub/gt4/4.0/4.0.3/installers/bin/$GT_INSTALLER
fi
GLOBUS_LOCATION=$_CONDOR_SCRATCH_DIR/globus
ZLIB_LOCATION=$_CONDOR_SCRATCH_DIR/zlib
LOGNAME=$USER
X509_CERT_DIR=$GLOBUS_LOCATION/share/certificates
export GLOBUS_LOCATION LOGNAME X509_CERT_DIR
(
echo ==================================================
echo Environment variables:
env
echo ==================================================
echo Directory contents:
ls -Rl
echo ==================================================
echo PATHs:
echo `which wget`
echo `which curl`
echo `which ncftpget`
echo `which ftp`
echo ==================================================
echo Installing Globus Toolkit...
if test -x `which wget`; then
  wget $GT_INSTALLER_URL
else
  curl $GT_INSTALLER_URL > $GT_INSTALLER
fi
tar xfz $GT_INSTALLER
cd gt*-installer
./configure --prefix=$GLOBUS_LOCATION --with-buildopts="-verbose"
make gsi-openssh install
. $GLOBUS_LOCATION/etc/globus-user-env.sh
cd ..
echo ==================================================
echo Building zlib-1.2.3...
ls -l
cd zlib-1.2.3
./configure --prefix=$ZLIB_LOCATION
make
make install
echo ==================================================
flavor=`gpt-query -name=gsi_openssh | perl -n -e 'if (/gsi_openssh-(.*)-pgm/){print "$1\n";}'|head -1`
echo GPT flavor is $flavor.  Installing globus_core.
gpt-build -nosrc $flavor
echo ==================================================
echo Building GSI-OpenSSH...
gpt-build -force -verbose gsi_openssh_bundle-*.tar.gz $flavor \
  GSI_OPENSSH_GPTMACRO="--with-zlib=$ZLIB_LOCATION"
) 2>&1 # we want stdout & stderr mixed in the output file
