#!/bin/sh

TEST=$1

if [ x$GLOBUS_LOCATION = "x" ]; then
   echo Error: GLOBUS_LOCATION must be set.
   exit 1
fi

if [ x$TEST = "x" ]; then
   echo "Usage: $0 test_package"
   echo "          where test_package is a subdir of \$GLOBUS_LOCATION/test"
   exit 1
fi

cd $GLOBUS_LOCATION/test

# Setup the ordinary client environment
. $GLOBUS_LOCATION/etc/globus-user-env.sh

# Setup the grid-mapfile and such
globus_test/testcred-setup.sh

# Setup the test credentials/CA/gridmap environment
. $GLOBUS_LOCATION/test/globus_test/testcred-env.sh

# Setup container env vars to deal with potential missing persistence dir
# Also avoid weird debian container IPv6 startup problems
GLOBUS_OPTIONS="-Dorg.globus.wsrf.container.persistence.dir=$GLOBUS_LOCATION/test -Djava.net.preferIPv4Stack=true"
export GLOBUS_OPTIONS

# GRAM depends on us to set this to avoid using the normal startup
# directory of a user's home as defined in /etc/passwd.  That directory
# does not exist in the Metronome build pool.  $HOME has already been
# set to $GL/ by the build scrips.
GRAM4_TESTING_USER_HOME=$HOME
export GRAM4_TESTING_USER_HOME

if [ ${TEST} = "myproxy_test" ]; then
   $GLOBUS_LOCATION/sbin/myproxy-test -startserver
   exit $?
fi

# These things are supposed to go under test/, but the ant
# build system for java packages makes it easier to put
# them under share/ instead, so I check both places, but
# prefer the test/ subdir.
cd $GLOBUS_LOCATION/test/${TEST}
if [ $? -ne 0 ]; then
   if [ -f $GLOBUS_LOCATION/share/${TEST}/TESTS.pl ]; then
      cd $GLOBUS_LOCATION/share/${TEST}
      chmod +x TESTS.pl
   else
      echo Channot change to $GLOBUS_LOCATION/test/${TEST}
      exit 1
   fi
fi

echo Copying in test security descriptor

cp $GLOBUS_LOCATION/etc/globus_wsrf_core/global_security_descriptor.xml \
   $GLOBUS_LOCATION/etc/globus_wsrf_core/global_sec_desc.xml.old
cp $GLOBUS_LOCATION/test/globus_test/global_security_descriptor.xml \
   $GLOBUS_LOCATION/etc/globus_wsrf_core

./TESTS.pl
if [ $? -ne 0 ]; then
   echo find . -type f
   find . -type f
   for F in `find . -name '*.log.stdout'`; do
      echo; echo $F; cat $F
   done
   for F in `find . -name '*.log.stderr'`; do
      echo; echo $F; cat $F
   done
   if [ -d ./tests/test-reports ]; then
      for F in `find ./tests/test-reports -print`; do
         echo; echo $F; cat $F
      done
   fi

   if [ -f submit_test/submit_test_script.log ]; then
      for F in `find . -name '*test_script.log'`; do
         echo; echo $F; cat $F
      done
   fi

   # restore sec desc
   cp $GLOBUS_LOCATION/etc/globus_wsrf_core/global_sec_desc.xml.old\
      $GLOBUS_LOCATION/etc/globus_wsrf_core/global_security_descriptor.xml 
   rm $GLOBUS_LOCATION/etc/globus_wsrf_core/global_sec_desc.xml.old
   exit 1
fi

cp $GLOBUS_LOCATION/etc/globus_wsrf_core/global_sec_desc.xml.old\
      $GLOBUS_LOCATION/etc/globus_wsrf_core/global_security_descriptor.xml 
rm $GLOBUS_LOCATION/etc/globus_wsrf_core/global_sec_desc.xml.old
exit 0
