.TH globus-connect-multiuser-id-cleanup 8

.SH NAME
globus-connect-multiuser-id-cleanup - Remove Globus Online-related MyProxy server configuration

.SH SYNOPSIS
.HP
globus-connect-multiuser-id-cleanup [-h|--help]
.HP
globus-connect-multiuser-id-cleanup
.br
{-c FILENAME|--config-file=FILENAME}
.br
{-v|--verbose}
.br
{-r PATH|--root=PATH}

.SH DESCRIPTION
.P
The
.B globus-connect-multiuser-id-cleanup
command deletes MyProxy service configuration previously created by running
.BR "globus-connect-multiuser-id-setup".
It deletes configuration files, stops, and
disables the MyProxy server.
.P
If the
.B "-r PATH
or
.B "--root=PATH"
command-line option is used,
.B globus-connect-multiuser-id-cleanup
will delete MyProxy configuration and certificates from a subdirectory rooted
at
.I PATH
instead of /. This means, for example, that
.B globus-connect-multiuser-id-cleanup
deletes MyProxy configuration files in
.IR "PATH/etc/myproxy.d".
.P
The following options are available:
.HP
.B "-h, --help"
.br
Display help information
.HP
.B "-c FILENAME, --config-file=FILENAME"
.br
Use configuration file FILENAME instead of
.I "/etc/globus-connect-multiuser.conf"
.HP
.B "-v, --verbose"
.br
Print more information about tasks
.HP
.B "-r PATH, --root=PATH"
.br
Add PATH as the directory prefix for the configuration files that
.B globus-connect-multiuser-id-cleanup
writes

.SH ENVIRONMENT
.HP
.B GLOBUSONLINE_USER
.br
Default GlobusOnline user name
.HP
.B GLOBUSONLINE_PASSWORD
.br
Default GlobusOnline password

.SH "SEE ALSO"
.B "globus-connect-multiuser-id-setup(8)"
