.TH globus-connect-multiuser-web-cleanup 8
.SH NAME
globus-connect-multiuser-web-cleanup - Clean up MyProxy OAuth server configuration

.SH SYNOPSIS
.HP
globus-connect-multiuser-web-cleanup [-h|--help]
.HP
globus-connect-multiuser-web-cleanup
.br
{-c FILENAME|--config-file=FILENAME}
.br
{-v|--verbose}
.br
{-r PATH|--root=PATH}

.SH DESCRIPTION
.P
The
.B globus-connect-multiuser-web-cleanup
command deletes MyProxy OAuth service configuration previously created by
running globus-connect-multiuser-web-setup. It deletes configuration files,
stops, and disables the MyProxy server.
.P
If the
.B "-r PATH" or
.B "--root=PATH"
command-line option is used,
.B globus-connect-multiuser-web-cleanup
will delete MyProxy configuration in a subdirectory rooted at
.I PATH
instead of /. This means, for example, that
.B globus-connect-multiuser-web-cleanup
deletes MyProxy OAuth configuration files in
.I PATH/etc/apache2
or
.IR "PATH/etc/httpd" .
.P
The following options are available:
.HP
.B "-h, --help"
.br
Display help information
.HP
.B "-c FILENAME, --config-file=FILENAME"
.br
Use configuration file
.I FILENAME
instead of
.I /etc/globus-connect-multiuser.conf
.HP
.B "-v, --verbose"
.br
Print more information about tasks
.HP
.B "-r PATH, --root=PATH"
.br
Add
.I PATH
as the directory prefix for the configuration files that
.B globus-connect-multiuser-web-cleanup
writes

.SH ENVIRONMENT
.HP
.B GLOBUSONLINE_USER
.br
Default GlobusOnline user name
.HP
.B GLOBUSONLINE_PASSWORD
.br
Default GlobusOnline password

.SH "SEE ALSO"
.B "globus-connect-multiuser-web-setup(8)"
