# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






SHELL = /bin/sh

srcdir = .
top_srcdir = .
prefix = $(GLOBUS_LOCATION)
exec_prefix = $(GLOBUS_LOCATION)

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/myproxy
pkglibdir = $(libdir)/myproxy
pkgincludedir = $(includedir)/myproxy

top_builddir = .

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = @host_alias@
host_triplet = @host@
AR = /usr/bin/ar
ARFLAGS = ruv
AS = @AS@
CC = /usr/bin/gcc
CFLAGS = -g   -Wall
CPP = /usr/bin/gcc -E
CPPFLAGS =  -I/usr/grid/include -I/usr/grid/include/gcc32dbg
CROSS = no
CXX = /usr/bin/c++
CXXCPP = /usr/bin/c++ -E
CXXFLAGS = -g  
DIRT_BRANCH_ID = 99999
DIRT_TIMESTAMP = 1047427167
DLLTOOL = @DLLTOOL@
DOT = 
DOXYFILE = Doxyfile
DOXYGEN = 
EXEEXT = 
F77 = /usr/bin/f77
F77FLAGS =  
F90 = 
F90FLAGS =  
FILELIST_FILE = /home/myproxy/sasl-branch/pkgdata/master.filelist
GLOBUS_FLAVOR_NAME = gcc32dbg
GPT_CFLAGS =  -D_FILE_OFFSET_BITS=64 
GPT_CONFIG_CFLAGS =  -D_FILE_OFFSET_BITS=64 
GPT_CONFIG_INCLUDES =  
GPT_CONFIG_LIBS =  -ldl 
GPT_CONFIG_PKG_LIBS = -lglobus_gss_assist_gcc32dbg -lglobus_gssapi_gsi_gcc32dbg -lglobus_gsi_proxy_core_gcc32dbg -lglobus_gsi_credential_gcc32dbg -lglobus_gsi_callback_gcc32dbg -lglobus_oldgaa_gcc32dbg -lglobus_gsi_sysconfig_gcc32dbg -lglobus_gsi_cert_utils_gcc32dbg -lglobus_openssl_error_gcc32dbg -lglobus_openssl_gcc32dbg -lglobus_proxy_ssl_gcc32dbg -lssl_gcc32dbg -lcrypto_gcc32dbg -lglobus_common_gcc32dbg 
GPT_EXTERNAL_INCLUDES = 
GPT_EXTERNAL_LIBS = 
GPT_INCLUDES = -I/usr/grid/include/gcc32dbg  
SASL_INCLUDES = -I/home/myproxy/cyrus-sasl-2.1.7/include 
GPT_IS_2 = yes
GPT_LDFLAGS =  -L/usr/grid/lib
SASL_LDFLAGS = -L/usr/kerberos/lib /usr/grid/lib/libsasl2.so -ldl -lresolv -Wl,--rpath -Wl,/home/myproxy/cyrus-sasl-2.1.7/lib
#SASL_LDFLAGS = -L/usr/kerberos/lib /usr/kerberos/lib/libgssapi_krb5.so /usr/grid/lib/libsasl2.so -ldl -lresolv -Wl,--rpath -Wl,/home/myproxy/cyrus-sasl-2.1.7/lib
GPT_LIBS = -lglobus_gss_assist_gcc32dbg -lglobus_gssapi_gsi_gcc32dbg -lglobus_gsi_proxy_core_gcc32dbg -lglobus_gsi_credential_gcc32dbg -lglobus_gsi_callback_gcc32dbg -lglobus_oldgaa_gcc32dbg -lglobus_gsi_sysconfig_gcc32dbg -lglobus_gsi_cert_utils_gcc32dbg -lglobus_openssl_error_gcc32dbg -lglobus_openssl_gcc32dbg -lglobus_proxy_ssl_gcc32dbg -lssl_gcc32dbg -lcrypto_gcc32dbg -lglobus_common_gcc32dbg   -ldl 
GPT_LIB_LINKS = -lglobus_gss_assist_gcc32dbg -lglobus_gssapi_gsi_gcc32dbg -lglobus_gsi_proxy_core_gcc32dbg -lglobus_gsi_credential_gcc32dbg -lglobus_gsi_callback_gcc32dbg -lglobus_oldgaa_gcc32dbg -lglobus_gsi_sysconfig_gcc32dbg -lglobus_gsi_cert_utils_gcc32dbg -lglobus_openssl_error_gcc32dbg -lglobus_openssl_gcc32dbg -lglobus_proxy_ssl_gcc32dbg -lssl_gcc32dbg -lcrypto_gcc32dbg -lglobus_common_gcc32dbg   -ldl 
GPT_LINKTYPE = shared
GPT_LOCATION = /usr/grid
GPT_MAJOR_VERSION = 1
GPT_MINOR_VERSION = 4
GPT_PGM_LINKS = -lglobus_gss_assist_gcc32dbg -lglobus_gssapi_gsi_gcc32dbg -lglobus_gsi_proxy_core_gcc32dbg -lglobus_gsi_credential_gcc32dbg -lglobus_gsi_callback_gcc32dbg -lglobus_oldgaa_gcc32dbg -lglobus_gsi_sysconfig_gcc32dbg -lglobus_gsi_cert_utils_gcc32dbg -lglobus_openssl_error_gcc32dbg -lglobus_openssl_gcc32dbg -lglobus_proxy_ssl_gcc32dbg -lssl_gcc32dbg -lcrypto_gcc32dbg -lglobus_common_gcc32dbg   -ldl 
GPT_PKG_CFLAGS = 
HAVE_DOT = 
INSURE = 
LD = /usr/bin/gcc
LDFLAGS = -L/usr/grid/lib 
LIBS =  
LIBTOOL = $(SHELL) $(GLOBUS_LOCATION)/sbin/libtool-$(GLOBUS_FLAVOR_NAME)
LN_S = 
MAINT = #
MAKEINFO = makeinfo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = myproxy
PERL = /usr/bin/perl
RANLIB = /usr/bin/ranlib
SYSLIBS = 
VERSION = 1.4
builddir = /home/myproxy/sasl-branch
cross_compiling = no
lac_doxygen_examples = 
lac_doxygen_file_patterns = 
lac_doxygen_installdox = 
lac_doxygen_internal_tagfiles = 
lac_doxygen_output_tagfile = 
lac_doxygen_predefines = 
lac_doxygen_project = 
lac_doxygen_srcdirs = 
lac_doxygen_tagfiles = 

setupdir = $(GLOBUS_LOCATION)/setup/globus

testdir = $(GLOBUS_LOCATION)/test/$(PACKAGE)

scriptsysconfdir = $(GLOBUS_LOCATION)/etc

flavorincludedir = $(GLOBUS_LOCATION)/include/$(GLOBUS_FLAVOR_NAME)

pkgdir = $(GLOBUS_LOCATION)/etc/globus_packages/$(PACKAGE)

aclocaldir = $(GLOBUS_LOCATION)/share/globus_aclocal

amdirdir = $(GLOBUS_LOCATION)/share/globus_amdir

doxygendir = $(GLOBUS_LOCATION)/share/doxygen

docdir = $(GLOBUS_LOCATION)/share/doc

LINK_BAK = orig
AUTOMAKE_OPTIONS = no-dependencies

SUBDIRS =  	pkgdata 	doxygen 	web 	man


LibSources =  	gnu_getopt.c 	gnu_getopt.h 	gnu_getopt_long.c 	gsi_socket.c 	gsi_socket.h 	myproxy.c 	myproxy.h 	myproxy_authorization.c 	myproxy_authorization.h 	myproxy_common.h 	myproxy_delegation.c 	myproxy_delegation.h 	myproxy_read_pass.c 	myproxy_read_pass.h 	myproxy_log.c 	myproxy_log.h 	ssl_utils.c 	ssl_utils.h 	string_funcs.c 	string_funcs.h 	verror.c 	verror.h


ServerSources =  	myproxy_creds.c 	myproxy_creds.h 	myproxy_server.c 	myproxy_server.h 	myproxy_server_config.c 	vparse.c 	vparse.h


INCLUDES =  $(GPT_INCLUDES) $(SASL_INCLUDES)

Scripts =  	myproxy-test


sbin_SCRIPTS = $(Scripts)

flavorinclude_HEADERS =  	myproxy.h 	myproxy_creds.h


lib_LTLIBRARIES = libmyproxy_$(GLOBUS_FLAVOR_NAME).la

libmyproxy___GLOBUS_FLAVOR_NAME__la_SOURCES = $(LibSources)

libmyproxy___GLOBUS_FLAVOR_NAME__la_LDFLAGS = $(GPT_LDFLAGS)

libmyproxy___GLOBUS_FLAVOR_NAME__la_LIBADD = $(GPT_LIB_LINKS)

bin_PROGRAMS =  	myproxy-init 	myproxy-info 	myproxy-destroy 	myproxy-get-delegation 	myproxy-change-pass-phrase


sbin_PROGRAMS =  	myproxy-server 	myproxy-admin-load-credential 	myproxy-admin-query


myproxy_init_SOURCES = myproxy_init.c

myproxy_init_LDFLAGS = $(GPT_LDFLAGS) $(SASL_LDFLAGS)

myproxy_init_LDADD = $(GPT_PGM_LINKS) ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la

myproxy_info_SOURCES = myproxy_info.c

myproxy_info_LDFLAGS = $(GPT_LDFLAGS) $(SASL_LDFLAGS)

myproxy_info_LDADD = $(GPT_PGM_LINKS) ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la

myproxy_destroy_SOURCES = myproxy_destroy.c

myproxy_destroy_LDFLAGS = $(GPT_LDFLAGS)  $(SASL_LDFLAGS)

myproxy_destroy_LDADD = $(GPT_PGM_LINKS) ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la

myproxy_server_SOURCES = $(ServerSources)
myproxy_server_LDFLAGS = $(GPT_LDFLAGS) $(SASL_LDFLAGS)

myproxy_server_LDADD = $(GPT_PGM_LINKS) ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la

myproxy_get_delegation_SOURCES = myproxy_get_delegation.c

myproxy_get_delegation_LDFLAGS = $(GPT_LDFLAGS) $(SASL_LDFLAGS)

myproxy_get_delegation_LDADD = $(GPT_PGM_LINKS) ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la

myproxy_change_pass_phrase_SOURCES = myproxy_cp.c

myproxy_change_pass_phrase_LDFLAGS = $(GPT_LDFLAGS) $(SASL_LDFLAGS)

myproxy_change_pass_phrase_LDADD = $(GPT_PGM_LINKS) ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la

myproxy_admin_query_SOURCES = myproxy_arq.c myproxy_creds.c myproxy_creds.h

myproxy_admin_query_LDFLAGS = $(GPT_LDFLAGS) $(SASL_LDFLAGS)

myproxy_admin_query_LDADD = $(GPT_PGM_LINKS) ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la

myproxy_admin_load_credential_SOURCES = myproxy_alcf.c ssl_utils.c ssl_utils.h myproxy_creds.c myproxy_creds.h

myproxy_admin_load_credential_LDFLAGS = $(GPT_LDFLAGS) $(SASL_LDFLAGS)

myproxy_admin_load_credential_LDADD = $(GPT_PGM_LINKS) ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la

noinst_PROGRAMS = gsi_socket_test

gsi_socket_test_SOURCES = gsi_socket_test.c gsi_socket.c

gsi_socket_test_LDFLAGS = $(GPT_LDFLAGS) $(SASL_LDFLAGS)

gsi_socket_test_LDADD = $(GPT_PGM_LINKS)  ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la

sysconf_DATA = myproxy-server.config

pkgdata_DATA = README INSTALL LICENSE VERSION PROTOCOL                etc.services.modifications etc.inetd.conf.modifications                etc.init.d.myproxy etc.xinetd.myproxy


EXTRA_DIST = $(Scripts) LICENSE VERSION PROTOCOL myproxy-server.config                etc.services.modifications etc.inetd.conf.modifications                etc.init.d.myproxy etc.xinetd.myproxy bootstrap         globus_automake_pre         globus_automake_post         globus_automake_pre_top         globus_automake_post_top 	dirt.sh

ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_CLEAN_FILES =  myproxy.cron
LTLIBRARIES =  $(lib_LTLIBRARIES)


DEFS =  -DPACKAGE=\"myproxy\" -DVERSION=\"1.4\" -DHAVE_REGEX_H=1 -DHAVE_REGCOMP=1 -DHAVE_VSNPRINTF=1 -DHAVE_SETENV=1 -DHAVE_UNSETENV=1  -I. -I$(srcdir) 
libmyproxy___GLOBUS_FLAVOR_NAME__la_DEPENDENCIES = 
libmyproxy___GLOBUS_FLAVOR_NAME__la_OBJECTS =  gnu_getopt.lo \
gnu_getopt_long.lo gsi_socket.lo myproxy.lo myproxy_authorization.lo \
myproxy_delegation.lo myproxy_read_pass.lo myproxy_log.lo ssl_utils.lo \
string_funcs.lo verror.lo
PROGRAMS =  $(bin_PROGRAMS) $(noinst_PROGRAMS) $(sbin_PROGRAMS)

myproxy_init_OBJECTS =  myproxy_init.o
myproxy_init_DEPENDENCIES =  ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la
myproxy_info_OBJECTS =  myproxy_info.o
myproxy_info_DEPENDENCIES =  ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la
myproxy_destroy_OBJECTS =  myproxy_destroy.o
myproxy_destroy_DEPENDENCIES =  ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la
myproxy_get_delegation_OBJECTS =  myproxy_get_delegation.o
myproxy_get_delegation_DEPENDENCIES =  \
./libmyproxy_$(GLOBUS_FLAVOR_NAME).la
myproxy_change_pass_phrase_OBJECTS =  myproxy_cp.o
myproxy_change_pass_phrase_DEPENDENCIES =  \
./libmyproxy_$(GLOBUS_FLAVOR_NAME).la
gsi_socket_test_OBJECTS =  gsi_socket_test.o gsi_socket.o
gsi_socket_test_DEPENDENCIES =  ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la
myproxy_server_OBJECTS =  myproxy_creds.o myproxy_server.o \
myproxy_server_config.o vparse.o
myproxy_server_DEPENDENCIES =  ./libmyproxy_$(GLOBUS_FLAVOR_NAME).la
myproxy_admin_load_credential_OBJECTS =  myproxy_alcf.o ssl_utils.o \
myproxy_creds.o
myproxy_admin_load_credential_DEPENDENCIES =  \
./libmyproxy_$(GLOBUS_FLAVOR_NAME).la
myproxy_admin_query_OBJECTS =  myproxy_arq.o myproxy_creds.o
myproxy_admin_query_DEPENDENCIES =  \
./libmyproxy_$(GLOBUS_FLAVOR_NAME).la
SCRIPTS =  $(sbin_SCRIPTS)

COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DATA =  $(pkgdata_DATA) $(sysconf_DATA)

HEADERS =  $(flavorinclude_HEADERS)

DIST_COMMON =  README INSTALL Makefile.am Makefile.in TODO aclocal.m4 \
config.guess config.sub configure configure.in install-sh ltconfig \
ltmain.sh missing mkinstalldirs myproxy.cron.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libmyproxy___GLOBUS_FLAVOR_NAME__la_SOURCES) $(myproxy_init_SOURCES) $(myproxy_info_SOURCES) $(myproxy_destroy_SOURCES) $(myproxy_get_delegation_SOURCES) $(myproxy_change_pass_phrase_SOURCES) $(gsi_socket_test_SOURCES) $(myproxy_server_SOURCES) $(myproxy_admin_load_credential_SOURCES) $(myproxy_admin_query_SOURCES)
OBJECTS = $(libmyproxy___GLOBUS_FLAVOR_NAME__la_OBJECTS) $(myproxy_init_OBJECTS) $(myproxy_info_OBJECTS) $(myproxy_destroy_OBJECTS) $(myproxy_get_delegation_OBJECTS) $(myproxy_change_pass_phrase_OBJECTS) $(gsi_socket_test_OBJECTS) $(myproxy_server_OBJECTS) $(myproxy_admin_load_credential_OBJECTS) $(myproxy_admin_query_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) $(top_srcdir)/globus_automake_pre $(top_srcdir)/globus_automake_pre_top $(top_srcdir)/globus_automake_post $(top_srcdir)/globus_automake_post_top
	cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$@ CONFIG_HEADERS= $(SHELL) ./config.status

$(ACLOCAL_M4): # configure.in 
	cd $(srcdir) && $(ACLOCAL)

config.status: $(srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck
$(srcdir)/configure: #$(srcdir)/configure.in $(ACLOCAL_M4) $(CONFIGURE_DEPENDENCIES)
	cd $(srcdir) && $(AUTOCONF)
myproxy.cron: $(top_builddir)/config.status myproxy.cron.in
	cd $(top_builddir) && CONFIG_FILES=$@ CONFIG_HEADERS= $(SHELL) ./config.status

mostlyclean-libLTLIBRARIES:

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)

distclean-libLTLIBRARIES:

maintainer-clean-libLTLIBRARIES:

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo "$(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p; \
	done

.c.o:
	$(COMPILE) -c $<

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libmyproxy_$(GLOBUS_FLAVOR_NAME).la: $(libmyproxy___GLOBUS_FLAVOR_NAME__la_OBJECTS) $(libmyproxy___GLOBUS_FLAVOR_NAME__la_DEPENDENCIES)
	$(LINK) -rpath $(libdir) $(libmyproxy___GLOBUS_FLAVOR_NAME__la_LDFLAGS) $(libmyproxy___GLOBUS_FLAVOR_NAME__la_OBJECTS) $(libmyproxy___GLOBUS_FLAVOR_NAME__la_LIBADD) $(LIBS)

mostlyclean-binPROGRAMS:

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

distclean-binPROGRAMS:

maintainer-clean-binPROGRAMS:

install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`"; \
	    $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	list='$(bin_PROGRAMS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	done

mostlyclean-noinstPROGRAMS:

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)

distclean-noinstPROGRAMS:

maintainer-clean-noinstPROGRAMS:

mostlyclean-sbinPROGRAMS:

clean-sbinPROGRAMS:
	-test -z "$(sbin_PROGRAMS)" || rm -f $(sbin_PROGRAMS)

distclean-sbinPROGRAMS:

maintainer-clean-sbinPROGRAMS:

install-sbinPROGRAMS: $(sbin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(sbindir)
	@list='$(sbin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(sbindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`"; \
	    $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(sbindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	  else :; fi; \
	done

uninstall-sbinPROGRAMS:
	@$(NORMAL_UNINSTALL)
	list='$(sbin_PROGRAMS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(sbindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	done

myproxy-init: $(myproxy_init_OBJECTS) $(myproxy_init_DEPENDENCIES)
	@rm -f myproxy-init
	$(LINK) $(myproxy_init_LDFLAGS) $(myproxy_init_OBJECTS) $(myproxy_init_LDADD) $(LIBS)

myproxy-info: $(myproxy_info_OBJECTS) $(myproxy_info_DEPENDENCIES)
	@rm -f myproxy-info
	$(LINK) $(myproxy_info_LDFLAGS) $(myproxy_info_OBJECTS) $(myproxy_info_LDADD) $(LIBS)

myproxy-destroy: $(myproxy_destroy_OBJECTS) $(myproxy_destroy_DEPENDENCIES)
	@rm -f myproxy-destroy
	$(LINK) $(myproxy_destroy_LDFLAGS) $(myproxy_destroy_OBJECTS) $(myproxy_destroy_LDADD) $(LIBS)

myproxy-get-delegation: $(myproxy_get_delegation_OBJECTS) $(myproxy_get_delegation_DEPENDENCIES)
	@rm -f myproxy-get-delegation
	$(LINK) $(myproxy_get_delegation_LDFLAGS) $(myproxy_get_delegation_OBJECTS) $(myproxy_get_delegation_LDADD) $(LIBS)

myproxy-change-pass-phrase: $(myproxy_change_pass_phrase_OBJECTS) $(myproxy_change_pass_phrase_DEPENDENCIES)
	@rm -f myproxy-change-pass-phrase
	$(LINK) $(myproxy_change_pass_phrase_LDFLAGS) $(myproxy_change_pass_phrase_OBJECTS) $(myproxy_change_pass_phrase_LDADD) $(LIBS)

gsi_socket_test: $(gsi_socket_test_OBJECTS) $(gsi_socket_test_DEPENDENCIES)
	@rm -f gsi_socket_test
	$(LINK) $(gsi_socket_test_LDFLAGS) $(gsi_socket_test_OBJECTS) $(gsi_socket_test_LDADD) $(LIBS)

myproxy-server: $(myproxy_server_OBJECTS) $(myproxy_server_DEPENDENCIES)
	@rm -f myproxy-server
	$(LINK) $(myproxy_server_LDFLAGS) $(myproxy_server_OBJECTS) $(myproxy_server_LDADD) $(LIBS)

myproxy-admin-load-credential: $(myproxy_admin_load_credential_OBJECTS) $(myproxy_admin_load_credential_DEPENDENCIES)
	@rm -f myproxy-admin-load-credential
	$(LINK) $(myproxy_admin_load_credential_LDFLAGS) $(myproxy_admin_load_credential_OBJECTS) $(myproxy_admin_load_credential_LDADD) $(LIBS)

myproxy-admin-query: $(myproxy_admin_query_OBJECTS) $(myproxy_admin_query_DEPENDENCIES)
	@rm -f myproxy-admin-query
	$(LINK) $(myproxy_admin_query_LDFLAGS) $(myproxy_admin_query_OBJECTS) $(myproxy_admin_query_LDADD) $(LIBS)

install-sbinSCRIPTS: $(sbin_SCRIPTS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(sbindir)
	@list='$(sbin_SCRIPTS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(INSTALL_SCRIPT) $$p $(DESTDIR)$(sbindir)/`echo $$p|sed '$(transform)'`"; \
	    $(INSTALL_SCRIPT) $$p $(DESTDIR)$(sbindir)/`echo $$p|sed '$(transform)'`; \
	  else if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_SCRIPT) $(srcdir)/$$p $(DESTDIR)$(sbindir)/`echo $$p|sed '$(transform)'`"; \
	    $(INSTALL_SCRIPT) $(srcdir)/$$p $(DESTDIR)$(sbindir)/`echo $$p|sed '$(transform)'`; \
	  else :; fi; fi; \
	done

uninstall-sbinSCRIPTS:
	@$(NORMAL_UNINSTALL)
	list='$(sbin_SCRIPTS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(sbindir)/`echo $$p|sed '$(transform)'`; \
	done

install-pkgdataDATA: $(pkgdata_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(pkgdatadir)
	@list='$(pkgdata_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(pkgdatadir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(pkgdatadir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(pkgdatadir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(pkgdatadir)/$$p; \
	  fi; fi; \
	done

uninstall-pkgdataDATA:
	@$(NORMAL_UNINSTALL)
	list='$(pkgdata_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(pkgdatadir)/$$p; \
	done

install-sysconfDATA: $(sysconf_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(sysconfdir)
	@list='$(sysconf_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(sysconfdir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(sysconfdir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(sysconfdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(sysconfdir)/$$p; \
	  fi; fi; \
	done

uninstall-sysconfDATA:
	@$(NORMAL_UNINSTALL)
	list='$(sysconf_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(sysconfdir)/$$p; \
	done

install-flavorincludeHEADERS: $(flavorinclude_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(flavorincludedir)
	@list='$(flavorinclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(flavorincludedir)/$$p"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(flavorincludedir)/$$p; \
	done

uninstall-flavorincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	list='$(flavorinclude_HEADERS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(flavorincludedir)/$$p; \
	done

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.



all-recursive install-data-recursive install-exec-recursive \
installdirs-recursive install-recursive uninstall-recursive  \
check-recursive installcheck-recursive info-recursive dvi-recursive:
	@set fnord $(MAKEFLAGS); amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

mostlyclean-recursive clean-recursive distclean-recursive \
maintainer-clean-recursive:
	@set fnord $(MAKEFLAGS); amf=$$2; \
	dot_seen=no; \
	rev=''; list='$(SUBDIRS)'; for subdir in $$list; do \
	  rev="$$subdir $$rev"; \
	  test "$$subdir" = "." && dot_seen=yes; \
	done; \
	test "$$dot_seen" = "no" && rev=". $$rev"; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
   if test "$$subdir" = .; then :; else \
	    test -f $$subdir/TAGS && tags="$$tags -i $$here/$$subdir/TAGS"; \
   fi; \
	done; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	-rm -rf $(distdir)
	GZIP=$(GZIP_ENV) $(TAR) zxf $(distdir).tar.gz
	mkdir $(distdir)/=build
	mkdir $(distdir)/=inst
	dc_install_base=`cd $(distdir)/=inst && pwd`; \
	cd $(distdir)/=build \
	  && ../configure --srcdir=.. --prefix=$$dc_install_base \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) dist
	-rm -rf $(distdir)
	@banner="$(distdir).tar.gz is ready for distribution"; \
	dashes=`echo "$$banner" | sed s/./=/g`; \
	echo "$$dashes"; \
	echo "$$banner"; \
	echo "$$dashes"
dist: distdir
	-chmod -R a+r $(distdir)
	GZIP=$(GZIP_ENV) $(TAR) chozf $(distdir).tar.gz $(distdir)
	-rm -rf $(distdir)
dist-all: distdir
	-chmod -R a+r $(distdir)
	GZIP=$(GZIP_ENV) $(TAR) chozf $(distdir).tar.gz $(distdir)
	-rm -rf $(distdir)
distdir: $(DISTFILES)
	-rm -rf $(distdir)
	mkdir $(distdir)
	-chmod 777 $(distdir)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
	for subdir in $(SUBDIRS); do \
	  if test "$$subdir" = .; then :; else \
	    test -d $(distdir)/$$subdir \
	    || mkdir $(distdir)/$$subdir \
	    || exit 1; \
	    chmod 777 $(distdir)/$$subdir; \
	    (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir=../$(distdir) distdir=../$(distdir)/$$subdir distdir) \
	      || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) top_distdir="$(top_distdir)" distdir="$(distdir)" dist-hook
info-am:
info: info-recursive
dvi-am:
dvi: dvi-recursive
check-am: all-am
check: check-recursive
installcheck-am:
installcheck: installcheck-recursive
install-exec-am: install-libLTLIBRARIES install-binPROGRAMS \
		install-sbinPROGRAMS install-sbinSCRIPTS \
		install-sysconfDATA
install-exec: install-exec-recursive

install-data-am: install-pkgdataDATA install-flavorincludeHEADERS
install-data: install-data-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-recursive
uninstall-am: uninstall-libLTLIBRARIES uninstall-binPROGRAMS \
		uninstall-sbinPROGRAMS uninstall-sbinSCRIPTS \
		uninstall-pkgdataDATA uninstall-sysconfDATA \
		uninstall-flavorincludeHEADERS
uninstall: uninstall-recursive
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(SCRIPTS) $(DATA) \
		$(HEADERS)
all-redirect: all-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs: installdirs-recursive
installdirs-am:
	$(mkinstalldirs)  $(DESTDIR)$(libdir) $(DESTDIR)$(bindir) \
		$(DESTDIR)$(sbindir) $(DESTDIR)$(sbindir) \
		$(DESTDIR)$(pkgdatadir) $(DESTDIR)$(sysconfdir) \
		$(DESTDIR)$(flavorincludedir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-libLTLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-binPROGRAMS \
		mostlyclean-noinstPROGRAMS mostlyclean-sbinPROGRAMS \
		mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-recursive

clean-am:  clean-libLTLIBRARIES clean-compile clean-libtool \
		clean-binPROGRAMS clean-noinstPROGRAMS \
		clean-sbinPROGRAMS clean-tags clean-generic \
		mostlyclean-am

clean: clean-recursive

distclean-am:  distclean-libLTLIBRARIES distclean-compile \
		distclean-libtool distclean-binPROGRAMS \
		distclean-noinstPROGRAMS distclean-sbinPROGRAMS \
		distclean-tags distclean-generic clean-am
	-rm -f libtool

distclean: distclean-recursive
	-rm -f config.status

maintainer-clean-am:  maintainer-clean-libLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-binPROGRAMS \
		maintainer-clean-noinstPROGRAMS \
		maintainer-clean-sbinPROGRAMS maintainer-clean-tags \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-recursive
	-rm -f config.status

.PHONY: mostlyclean-libLTLIBRARIES distclean-libLTLIBRARIES \
clean-libLTLIBRARIES maintainer-clean-libLTLIBRARIES \
uninstall-libLTLIBRARIES install-libLTLIBRARIES mostlyclean-compile \
distclean-compile clean-compile maintainer-clean-compile \
mostlyclean-libtool distclean-libtool clean-libtool \
maintainer-clean-libtool mostlyclean-binPROGRAMS distclean-binPROGRAMS \
clean-binPROGRAMS maintainer-clean-binPROGRAMS uninstall-binPROGRAMS \
install-binPROGRAMS mostlyclean-noinstPROGRAMS distclean-noinstPROGRAMS \
clean-noinstPROGRAMS maintainer-clean-noinstPROGRAMS \
mostlyclean-sbinPROGRAMS distclean-sbinPROGRAMS clean-sbinPROGRAMS \
maintainer-clean-sbinPROGRAMS uninstall-sbinPROGRAMS \
install-sbinPROGRAMS uninstall-sbinSCRIPTS install-sbinSCRIPTS \
uninstall-pkgdataDATA install-pkgdataDATA uninstall-sysconfDATA \
install-sysconfDATA uninstall-flavorincludeHEADERS \
install-flavorincludeHEADERS install-data-recursive \
uninstall-data-recursive install-exec-recursive \
uninstall-exec-recursive installdirs-recursive uninstalldirs-recursive \
all-recursive check-recursive installcheck-recursive info-recursive \
dvi-recursive mostlyclean-recursive distclean-recursive clean-recursive \
maintainer-clean-recursive tags tags-recursive mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs-am \
installdirs mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


dirt.sh:
	touch dirt.sh

dist-hook:
	$(GPT_LOCATION)/sbin/gpt_create_automake_rules --excludes=doxygen -srcdir=$(top_distdir)

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
link-am:

unlink-am:

filelist-am:

link: link-recursive link-binPROGRAMS link-flavorincludeHEADERS link-libLTLIBRARIES link-noinstPROGRAMS link-pkgdataDATA link-sbinPROGRAMS link-sbinSCRIPTS link-sysconfDATA 
	:

unlink: unlink-recursive unlink-binPROGRAMS unlink-flavorincludeHEADERS unlink-libLTLIBRARIES unlink-noinstPROGRAMS unlink-pkgdataDATA unlink-sbinPROGRAMS unlink-sbinSCRIPTS unlink-sysconfDATA 
	:

.PHONY: link unlink link-recursive unlink-recursive link-am unlink-am filelist-amlink-binPROGRAMS unlink-binPROGRAMS filelist-binPROGRAMS link-flavorincludeHEADERS unlink-flavorincludeHEADERS filelist-flavorincludeHEADERS link-libLTLIBRARIES unlink-libLTLIBRARIES filelist-libLTLIBRARIES link-noinstPROGRAMS unlink-noinstPROGRAMS filelist-noinstPROGRAMS link-pkgdataDATA unlink-pkgdataDATA filelist-pkgdataDATA link-sbinPROGRAMS unlink-sbinPROGRAMS filelist-sbinPROGRAMS link-sbinSCRIPTS unlink-sbinSCRIPTS filelist-sbinSCRIPTS link-sysconfDATA unlink-sysconfDATA filelist-sysconfDATA 

filelist: filelist-recursive filelist-binPROGRAMS filelist-flavorincludeHEADERS filelist-libLTLIBRARIES filelist-noinstPROGRAMS filelist-pkgdataDATA filelist-sbinPROGRAMS filelist-sbinSCRIPTS filelist-sysconfDATA 
	:




link-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	  	mydir=`pwd`; \
		target_p=$(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$mydir/$$p $$target_p"; \
			ln -s $$mydir/$$p $$target_p; \
		fi; \
	  else :; fi; \
	done

unlink-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
		target_p=$(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
		if test -h $$target_p; then \
			echo "rm $$target_p"; \
			rm $$target_p; \
		fi; \
		if test -f $$target_p.$(LINK_BAK); then \
			echo "mv $$target_p.$(LINK_BAK) $$target_p"; \
			mv $$target_p.$(LINK_BAK) $$target_p; \
		fi; \
	done

filelist-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  echo "$(DESTDIR)$(bindir)/$$p" >> $(FILELIST_FILE); \
	done





link-flavorincludeHEADERS: $(flavorinclude_HEADERS)
	@$(NORMAL_INSTALL)
	@$(mkinstalldirs) $(DESTDIR)$(flavorincludedir)
	@list='$(flavorinclude_HEADERS)'; for p in $$list; do \
	  	mydir=`pwd`; \
		target_p="$(DESTDIR)$(flavorincludedir)/$$p"; \
		cd $(srcdir); \
		fullsrcdir=`pwd`; \
		cd $$mydir; \
		if test -f "$$p"; then d="$$mydir/"; else d="$$fullsrcdir/"; fi; \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$d$$p $$target_p"; \
			ln -s $$d$$p $$target_p; \
		fi; \
	done

unlink-flavorincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(flavorinclude_HEADERS)'; for p in $$list; do \
		target_p="$(DESTDIR)$(flavorincludedir)/$$p"; \
		if test -h $$target_p; then \
			echo "rm $$target_p"; \
			rm $$target_p; \
		fi; \
		if test -f $$target_p.$(LINK_BAK); then \
			echo "mv $$target_p.$(LINK_BAK) $$target_p"; \
			mv $$target_p.$(LINK_BAK) $$target_p; \
		fi; \
	done

filelist-flavorincludeHEADERS:
	@list='$(flavorinclude_HEADERS)'; for p in $$list; do \
	  echo "$(DESTDIR)$(flavorincludedir)/$$p" >> $(FILELIST_FILE); \
	done





link-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	  	mydir=`pwd`; \
	    	target_p=$(DESTDIR)$(libdir)/$$p; \
		target_dir="$(DESTDIR)$(libdir)/"; \
		root_p=`echo $$p | sed "s,.la,,"`; \
		liblist=`ls $$mydir/.libs/$$root_p.so*`; for so in $$liblist; do \
			if test ! -h $$so; then \
				so_name=`echo $$so | sed "s,$$mydir/.libs/,,"`; \
				so_list="$$so_list $$so_name"; \
			fi; \
		done; \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
			for so in $$so_list; do \
				echo "mv $$target_dir/$$so $$target_dir/$$so.$(LINK_BAK)"; \
				mv $$target_dir/$$so $$target_dir/$$so.$(LINK_BAK); \
			done; \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$mydir/$$p $$target_p"; \
			ln -s $$mydir/$$p $$target_p; \
			for so in $$so_list; do \
				echo "ln -s $$mydir/.libs/$$so $$target_dir/$$so"; \
				ln -s $$mydir/.libs/$$so $$target_dir/$$so; \
			done; \
		fi; \
	  else :; fi; \
	done

unlink-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	    	target_p=$(DESTDIR)$(libdir)/$$p; \
		target_dir="$(DESTDIR)$(libdir)/"; \
		root_p=`echo $$p | sed "s,.la,,"`; \
		so_list=`ls $$target_dir/$$root_p.so*.$(LINK_BAK)`; \
		if test -h $$target_p; then \
			echo "rm $$target_p"; \
			rm $$target_p; \
			for so in $$so_list; do \
				so_name=`echo $$so | sed "s,.$(LINK_BAK),,"`; \
				echo "rm $$so_name"; \
				rm $$so_name; \
			done; \
		fi; \
		if test -f $$target_p.$(LINK_BAK); then \
			echo "mv $$target_p.$(LINK_BAK) $$target_p"; \
			mv $$target_p.$(LINK_BAK) $$target_p; \
			for so in $$so_list; do \
				so_name=`echo $$so | sed "s,.$(LINK_BAK),,"`; \
				mv $$so_name.$(LINK_BAK) $$so_name; \
			done; \
		fi; \
	done

filelist-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  $(GPT_LOCATION)/sbin/gpt_get_lib_names $$p $(DESTDIR)$(libdir) >> $(FILELIST_FILE); \
	done





link-noinstPROGRAMS: $(noinst_PROGRAMS)
	@$(NORMAL_INSTALL)
	@$(mkinstalldirs) $(DESTDIR)$(noinstdir)
	@list='$(noinst_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	  	mydir=`pwd`; \
		target_p=$(DESTDIR)$(noinstdir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$mydir/$$p $$target_p"; \
			ln -s $$mydir/$$p $$target_p; \
		fi; \
	  else :; fi; \
	done

unlink-noinstPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(noinst_PROGRAMS)'; for p in $$list; do \
		target_p=$(DESTDIR)$(noinstdir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
		if test -h $$target_p; then \
			echo "rm $$target_p"; \
			rm $$target_p; \
		fi; \
		if test -f $$target_p.$(LINK_BAK); then \
			echo "mv $$target_p.$(LINK_BAK) $$target_p"; \
			mv $$target_p.$(LINK_BAK) $$target_p; \
		fi; \
	done

filelist-noinstPROGRAMS:
	@list='$(noinst_PROGRAMS)'; for p in $$list; do \
	  echo "$(DESTDIR)$(noinstdir)/$$p" >> $(FILELIST_FILE); \
	done





link-pkgdataDATA: $(pkgdata_DATA)
	@$(NORMAL_INSTALL)
	@$(mkinstalldirs) $(DESTDIR)$(pkgdatadir)
	@list='$(pkgdata_DATA)'; for p in $$list; do \
	  mydir=`pwd`; \
	  target_p=$(DESTDIR)$(pkgdatadir)/$$p; \
	  if test -f $(srcdir)/$$p; then \
		cd $(srcdir); \
		fullsrcdir=`pwd`; \
		cd $$mydir; \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$fullsrcdir/$$p $$target_p"; \
			ln -s $$fullsrcdir/$$p $$target_p; \
		fi; \
	  else if test -f $$p; then \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$mydir/$$p $$target_p"; \
			ln -s $$mydir/$$p $$target_p; \
		fi; \
	  fi; fi; \
	done

unlink-pkgdataDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgdata_DATA)'; for p in $$list; do \
	target_p=$(DESTDIR)$(pkgdatadir)/$$p; \
	if test -h $$target_p; then \
		echo "rm $$target_p"; \
		rm $$target_p; \
	fi; \
	if test -f $$target_p.$(LINK_BAK); then \
		echo "mv $$target_p.$(LINK_BAK) $$target_p"; \
		mv $$target_p.$(LINK_BAK) $$target_p; \
	fi; \
	done

filelist-pkgdataDATA:
	@list='$(pkgdata_DATA)'; for p in $$list; do \
	  echo "$(DESTDIR)$(pkgdatadir)/$$p" >> $(FILELIST_FILE); \
	done





link-sbinPROGRAMS: $(sbin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@$(mkinstalldirs) $(DESTDIR)$(sbindir)
	@list='$(sbin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	  	mydir=`pwd`; \
		target_p=$(DESTDIR)$(sbindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$mydir/$$p $$target_p"; \
			ln -s $$mydir/$$p $$target_p; \
		fi; \
	  else :; fi; \
	done

unlink-sbinPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(sbin_PROGRAMS)'; for p in $$list; do \
		target_p=$(DESTDIR)$(sbindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
		if test -h $$target_p; then \
			echo "rm $$target_p"; \
			rm $$target_p; \
		fi; \
		if test -f $$target_p.$(LINK_BAK); then \
			echo "mv $$target_p.$(LINK_BAK) $$target_p"; \
			mv $$target_p.$(LINK_BAK) $$target_p; \
		fi; \
	done

filelist-sbinPROGRAMS:
	@list='$(sbin_PROGRAMS)'; for p in $$list; do \
	  echo "$(DESTDIR)$(sbindir)/$$p" >> $(FILELIST_FILE); \
	done





link-sbinSCRIPTS: $(sbin_SCRIPTS)
	@$(NORMAL_INSTALL)
	@$(mkinstalldirs) $(DESTDIR)$(sbindir)
	@list='$(sbin_SCRIPTS)'; for p in $$list; do \
	  mydir=`pwd`; \
	  target_p=$(DESTDIR)$(sbindir)/`echo $$p|sed '$(transform)'`; \
	  if test -f $$p; then \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$mydir/$$p $$target_p"; \
			ln -s $$mydir/$$p $$target_p; \
		fi; \
	  else if test -f $(srcdir)/$$p; then \
		cd $(srcdir); \
		fullsrcdir=`pwd`; \
		cd $$mydir; \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$fullsrcdir/$$p $$target_p"; \
			ln -s $$fullsrcdir/$$p $$target_p; \
		fi; \
	  else :; fi; fi; \
	done

unlink-sbinSCRIPTS:
	@$(NORMAL_UNINSTALL)
	@list='$(sbin_SCRIPTS)'; for p in $$list; do \
	    	target_p=$(DESTDIR)$(sbindir)/`echo $$p|sed '$(transform)'`; \
		if test -h $$target_p; then \
			echo "rm $$target_p"; \
			rm $$target_p; \
		fi; \
		if test -f $$target_p.$(LINK_BAK); then \
			echo "mv $$target_p.$(LINK_BAK) $$target_p"; \
			mv $$target_p.$(LINK_BAK) $$target_p; \
		fi; \
	done

filelist-sbinSCRIPTS:
	@list='$(sbin_SCRIPTS)'; for p in $$list; do \
	  echo "$(DESTDIR)$(sbindir)/$$p" >> $(FILELIST_FILE); \
	done





link-sysconfDATA: $(sysconf_DATA)
	@$(NORMAL_INSTALL)
	@$(mkinstalldirs) $(DESTDIR)$(sysconfdir)
	@list='$(sysconf_DATA)'; for p in $$list; do \
	  mydir=`pwd`; \
	  target_p=$(DESTDIR)$(sysconfdir)/$$p; \
	  if test -f $(srcdir)/$$p; then \
		cd $(srcdir); \
		fullsrcdir=`pwd`; \
		cd $$mydir; \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$fullsrcdir/$$p $$target_p"; \
			ln -s $$fullsrcdir/$$p $$target_p; \
		fi; \
	  else if test -f $$p; then \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$mydir/$$p $$target_p"; \
			ln -s $$mydir/$$p $$target_p; \
		fi; \
	  fi; fi; \
	done

unlink-sysconfDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(sysconf_DATA)'; for p in $$list; do \
	target_p=$(DESTDIR)$(sysconfdir)/$$p; \
	if test -h $$target_p; then \
		echo "rm $$target_p"; \
		rm $$target_p; \
	fi; \
	if test -f $$target_p.$(LINK_BAK); then \
		echo "mv $$target_p.$(LINK_BAK) $$target_p"; \
		mv $$target_p.$(LINK_BAK) $$target_p; \
	fi; \
	done

filelist-sysconfDATA:
	@list='$(sysconf_DATA)'; for p in $$list; do \
	  echo "$(DESTDIR)$(sysconfdir)/$$p" >> $(FILELIST_FILE); \
	done


link-recursive unlink-recursive filelist-recursive:
	@set fnord $(MAKEFLAGS); amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

