'\" t
.\"     Title: globus-job-run
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/18/2010
.\"    Manual: GRAM5 Commands
.\"    Source: University of Chicago
.\"  Language: English
.\"
.TH "GLOBUS\-JOB\-RUN" "1" "03/18/2010" "University of Chicago" "GRAM5 Commands"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-job-run \- Execute a job using GRAM
.SH "SYNOPSIS"
.HP \w'\fBglobus\-job\-run\fR\ 'u
\fBglobus\-job\-run\fR [\-dumprsl] [\-dryrun] [\-verify]
.br
[\-file\ \fIARGUMENT_FILE\fR]
.br
\fISERVICE_CONTACT\fR
.br
[\-np\ \fIPROCESSES\fR | \-count\ \fIPROCESSES\fR]
.br
[\-m\ \fIMAX_TIME\fR | \-maxtime\ \fIMAX_TIME\fR]
.br
[\-p\ \fIPROJECT\fR | \-project\ \fIPROJECT\fR]
.br
[\-q\ \fIQUEUE\fR | \-queue\ \fIQUEUE\fR]
.br
[\-d\ \fIDIRECTORY\fR | \-directory\ \fIDIRECTORY\fR] [\-env\ \fINAME\fR=\fIVALUE\fR]... 
.br
[\-stdin\ [\-l\ |\ \-s]\ \fISTDIN_FILE\fR] [\-stdout\ [\-l\ |\ \-s]\ \fISTDOUT_FILE\fR] [\-stderr\ [\-l\ |\ \-s]\ \fISTDERR_FILE\fR]
.br
[\-x\ \fIRSL_CLAUSE\fR]
.br
[\-l | \-s] \fIEXECUTABLE\fR [ARGUMENT...]
.HP \w'\fBglobus\-job\-run\fR\ 'u
\fBglobus\-job\-run\fR [\-help] [\-usage] [\-version] [\-versions]
.SH "DESCRIPTION"
.PP
The
\fBglobus\-job\-run\fR
program constructs a job description from its command\-line options and then submits the job to the GRAM service running at
\fISERVICE_CONTACT\fR\&. The executable and arguments to the executable are provided on the command\-line after all other options\&. Note that the
\fB\-dumprsl\fR,
\fB\-dryrun\fR,
\fB\-verify\fR, and
\fB\-file\fR
command\-line options must occur before the first non\-option argument, the
\fISERVICE_CONTACT\fR\&.
.PP
The
\fBglobus\-job\-run\fR
provides similar functionality to
\fBglobusrun\fR
in that it allows interactive start\-up of GRAM jobs\&. However, unlike
\fBglobusrun\fR, it uses command\-line parameters to define the job instead of RSL expressions\&.
.SH "OPTIONS"
.PP
The full set of options to
\fBglobus\-job\-run\fR
are:
.PP
\fB\-help\fR, \fB\-usage\fR
.RS 4
Display a help message to standard error and exit\&.
.RE
.PP
\fB\-version\fR
.RS 4
Display the software version of the
\fBglobus\-job\-run\fR
program to standard output\&.
.RE
.PP
\fB\-version\fR
.RS 4
Display the software version of the
\fBglobus\-job\-run\fR
program including DiRT information to standard output\&.
.RE
.PP
\fB\-dumprsl\fR
.RS 4
Translate the command\-line options to
\fBglobus\-job\-run\fR
into an RSL expression that can be used with tools such as
\fBglobusrun\fR\&.
.RE
.PP
\fB\-dryrun\fR
.RS 4
Submit the job request to the GRAM service with the
dryrun
option enabled\&. When this option is used, the GRAM service prepares to execute the job but stops before submitting the job to the LRM\&. This can be used to diagnose some problems such as missing files\&.
.RE
.PP
\fB\-verify\fR
.RS 4
Submit the job request to the GRAM service with the
dryrun
option enabled and then without it enabled if the dryrun is successful\&.
.RE
.PP
\fB\-file \fR\fB\fIARGUMENT_FILE\fR\fR
.RS 4
Read additional command\-line options from
\fIARGUMENT_FILE\fR\&.
.RE
.PP
\fB\-np \fR\fB\fIPROCESSES\fR\fR, \fB\-count \fR\fB\fIPROCESSES\fR\fR
.RS 4
Start
\fIPROCESSES\fR
instances of the executable as a single job\&.
.RE
.PP
\fB\-m \fR\fB\fIMAX_TIME\fR\fR, \fB\-maxtime \fR\fB\fIMAX_TIME\fR\fR
.RS 4
Schedule the job to run for a maximum of
\fIMAX_TIME\fR
minutes\&.
.RE
.PP
\fB\-p \fR\fB\fIPROJECT\fR\fR, \fB\-project \fR\fB\fIPROJECT\fR\fR
.RS 4
Request that the job use the allocation
\fIPROJECT\fR
when submitting the job to the LRM\&.
.RE
.PP
\fB\-q \fR\fB\fIQUEUE\fR\fR, \fB\-queue \fR\fB\fIQUEUE\fR\fR
.RS 4
Request that the job be submitted to the LRM using the named
\fIQUEUE\fR\&.
.RE
.PP
\fB\-d \fR\fB\fIDIRECTORY\fR\fR, \fB\-directory \fR\fB\fIDIRECTORY\fR\fR
.RS 4
Run the job in the directory named by
\fIDIRECTORY\fR\&. Input and output files will be interpreted relative to this directory\&. This directory must exist on the file system on the LRM\-managed resource\&. If not specified, the job will run in the home directory of the user the job is running as\&.
.RE
.PP
\fB\-env \fR\fB\fINAME\fR\fR\fB=\fR\fB\fIVALUE\fR\fR
.RS 4
Define an environment variable named by
\fINAME\fR
with the value
\fIVALUE\fR
in the job environment\&. This option may be specified multiple times to define multiple environment variables\&.
.RE
.PP
\fB\-stdin [\-l | \-s] \fR\fB\fISTDIN_FILE\fR\fR
.RS 4
Use the file named by
\fISTDIN_FILE\fR
as the standard input of the job\&. If the
\fB\-l\fR
option is specified, then this file is interpreted to be on a file system local to the LRM\&. If the
\fB\-s\fR
option is specified, then this file is interpreted to be on the file system where
\fBglobus\-job\-run\fR
is being executed, and the file will be staged via GASS\&. If neither is specified, the local behavior is assumed\&.
.RE
.PP
\fB\-stdout [\-l | \-s] \fR\fB\fISTDOUT_FILE\fR\fR
.RS 4
Use the file named by
\fISTDOUT_FILE\fR
as the destination for the standard output of the job\&. If the
\fB\-l\fR
option is specified, then this file is interpreted to be on a file system local to the LRM\&. If the
\fB\-s\fR
option is specified, then this file is interpreted to be on the file system where
\fBglobus\-job\-run\fR
is being executed, and the file will be staged via GASS\&. If neither is specified, the local behavior is assumed\&.
.RE
.PP
\fB\-stderr [\-l | \-s] \fR\fB\fISTDERR_FILE\fR\fR
.RS 4
Use the file named by
\fISTDERR_FILE\fR
as the destination for the standard error of the job\&. If the
\fB\-l\fR
option is specified, then this file is interpreted to be on a file system local to the LRM\&. If the
\fB\-s\fR
option is specified, then this file is interpreted to be on the file system where
\fBglobus\-job\-run\fR
is being executed, and the file will be staged via GASS\&. If neither is specified, the local behavior is assumed\&.
.RE
.PP
\fB\-x \fR\fB\fIRSL_CLAUSE\fR\fR
.RS 4
Add a set of custom RSL attributes described by
\fIRSL_CLAUSE\fR
to the job description\&. The clause must be an RSL conjunction and may contain one or more attributes\&. This can be used to include attributes which can not be defined by other command\-line options of
\fBglobus\-job\-run\fR\&.
.RE
.PP
\fB\-l\fR
.RS 4
When included outside the context of
\fB\-stdin\fR,
\fB\-stdout\fR, or
\fB\-stderr\fR
command\-line options,
\fB\-l\fR
option alters the interpretation of the executable path\&. If the
\fB\-l\fR
option is specified, then the executable is interpreted to be on a file system local to the LRM\&.
.RE
.PP
\fB\-s\fR
.RS 4
When included outside the context of
\fB\-stdin\fR,
\fB\-stdout\fR, or
\fB\-stderr\fR
command\-line options,
\fB\-l\fR
option alters the interpretation of the executable path\&. If the
\fB\-s\fR
option is specified, then the executable is interpreted to be on the file system where
\fBglobus\-job\-run\fR
is being executed, and the file will be staged via GASS\&. If neither is specified, the local behavior is assumed\&.
.RE
.SH "ENVIRONMENT"
.PP
If the following variables affect the execution of
\fBglobus\-job\-run\fR\&.
.PP
\fBX509_USER_PROXY\fR
.RS 4
Path to proxy credential\&.
.RE
.PP
\fBX509_CERT_DIR\fR
.RS 4
Path to trusted certificate directory\&.
.RE
.SH "SEE ALSO"
.PP

\fBglobusrun\fR(1),
\fBglobus-job-submit\fR(1),
\fBglobus-job-clean\fR(1),
\fBglobus-job-get-output\fR(1),
\fBglobus-job-cancel\fR(1)
