#! /bin/sh -f

. ${GLOBUS_LOCATION}/libexec/globus-script-initializer
globus_source ${libexecdir}/globus-sh-tools.sh


#  CVS Information:
#     $Source$
#     $Date$
#     $Revision$
#     $Author$

progname=`echo $0 | ${GLOBUS_SH_SED-sed} -e 's|^.*/\([^/]*\)|\1|g'`

short_usage="$progname [-help] [jobID]"

long_usage ()
{
${GLOBUS_SH_CAT-cat} >&2 <<EOF

Usage: ${short_usage}

    $progname prints out the status of a job previously started by
    globus-job-submit, identified by the string "jobID". A valid proxy
    certificate is required for this operation to succeed.

    Valid job states are PENDING, ACTIVE, DONE and FAILED.

    Options:
      -help | -usage       Display usage
      -version             Display version


EOF
}

globus_source ${libexecdir}/globus-args-parser-header $*

if [ $# -lt 1 ]; then
    globus_args_short_usage
    exit 1
fi

case "$1" in
    -*)
	globus_args_unrecognized_option "$1"
	;;
esac

${bindir}/grid-proxy-info -exists
if [ $? -ne 0 ]; then
    echo "ERROR: could not find a valid proxy" >&2
    globus_args_short_usage
    exit 1
fi

${bindir}/globusrun -status "$1"

