#!/bin/sh
cp myproxy/nmi/tasklist.nmi .
# only build VOMS on x86_64_rhap_6.2 for now
if test "x$NMI_PLATFORM" != "xx86_64_rhap_6.2"; then
    grep -v VOMS tasklist.nmi > tasklist.nmi.new
    mv -f tasklist.nmi.new tasklist.nmi
fi
# skip valgrind on x86_64_rhap_6.2
if test "x$NMI_PLATFORM" = "xx86_64_rhap_6.2"; then
    grep -v ValgrindCheck tasklist.nmi > tasklist.nmi.new
    mv -f tasklist.nmi.new tasklist.nmi
fi
exit 0
