#!/bin/sh
set -e # exit on any error
GT_INSTALLER=gt4.0.2-$NMI_PLATFORM-installer.tar.gz
GT_INSTALLER_URL=http://www.globus.org/ftppub/gt4/4.0/4.0.2/installers/bin/$GT_INSTALLER
GLOBUS_LOCATION=$_CONDOR_SCRATCH_DIR/globus
export GLOBUS_LOCATION
(
echo ==================================================
echo Environment variables:
env
echo ==================================================
echo Directory contents:
ls -Rl
echo ==================================================
echo Installing Globus Toolkit...
curl $GT_INSTALLER_URL > $GT_INSTALLER
tar xfz $GT_INSTALLER
cd gt*-installer
./configure --prefix=$GLOBUS_LOCATION --with-buildopts="-verbose"
make gsi-myproxy install
. $GLOBUS_LOCATION/etc/globus-user-env.sh
echo ==================================================
flavor=`gpt-query -name=myproxy | perl -n -e 'if (/myproxy-(.*)-pgm/){print "$1\n";}'|head -1`
echo GPT flavor is $flavor.  Installing globus_core.
gpt-build -nosrc $flavor
echo ==================================================
echo Installing autotools...
cd ../autotools
./install-autotools $GLOBUS_LOCATION
echo ==================================================
echo Building MyProxy...
cd ../myproxy
./bootstrap
./configure --with-flavor=$flavor
make dist
gpt-uninstall myproxy
gpt-build -verbose myproxy-*.tar.gz $flavor
echo ==================================================
echo Testing MyProxy...
mkdir $GLOBUS_LOCATION/share/certificates
cp nmi/*.0 nmi/*.signing_policy $GLOBUS_LOCATION/share/certificates
grid-proxy-init -cert nmi/usercert.pem -key nmi/userkey.pem
myproxy-test -startserver
) 2>&1 # we want stdout & stderr mixed in the output file
