#! /bin/sh

destdir="${1:-.}"
gsi_openssh_version=7.1p2
gsi_openssh_release_url=https://github.com/globus/gsi-openssh/archive
gsi_openssh_release_tarball="${gsi_openssh_version}.tar.gz"
gsi_openssh_release_tarball_url="${gsi_openssh_release_url}/${gsi_openssh_release_tarball}"
gsi_openssh_dir="${destdir}/gsi_openssh"

if command -v curl > /dev/null 2>&1; then
    download()
    {
        curl -Ls "$1" > "${2}.tmp"
        mv "${2}.tmp" "${2}"
    }
elif command -v wget > /dev/null 2>&1; then
    download()
    {
        wget -q -O "${2}.tmp" "$1"
        mv "${2}.tmp" "${2}"
    }
else
    download()
    {
        echo "Can't download ${1}" 1>&2
        exit 1
    }
fi

if [ ! -f "${gsi_openssh_dir}/${gsi_openssh_release_tarball}" ]; then
    download "${gsi_openssh_release_tarball_url}" \
             "${gsi_openssh_dir}/${gsi_openssh_release_tarball}" 
fi

if [ ! -f "${gsi_openssh_dir}/source/configure.ac" ]; then
    mkdir -p "${gsi_openssh_dir}/source"
    tar --strip 1 -C "${gsi_openssh_dir}/source" -zxf "${gsi_openssh_dir}/${gsi_openssh_release_tarball}" 
fi
if [ ! -f "${gsi_openssh_dir}/source/configure.gnu" ]; then
    cat > "${gsi_openssh_dir}/source/configure.gnu" <<-'EOF'
	#! /bin/sh
	${0%.gnu} --with-gsi "$@"
	EOF
    chmod a+x "${gsi_openssh_dir}/source/configure.gnu"
fi

echo "m4_define([gsissh_version], [${gsi_openssh_version}])" > "${gsi_openssh_dir}/version.m4.new"

if [ ! -f "${gsi_openssh_dir}/version.m4" ] || \
   ! cmp -s "${gsi_openssh_dir}/version.m4" "${gsi_openssh_dir}/version.m4.new"; then
   mv "${gsi_openssh_dir}/version.m4.new" "${gsi_openssh_dir}/version.m4"
else
   rm -f "${gsi_openssh_dir}/version.m4.new"
fi
