'\" t
.\"     Title: globus-fork-starter
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/08/2016
.\"    Manual: Globus Toolkit Manual
.\"    Source: Globus Toolkit 6
.\"  Language: English
.\"
.TH "GLOBUS\-FORK\-STARTE" "8" "09/08/2016" "Globus Toolkit 6" "Globus Toolkit Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-fork-starter \- Start and monitor a fork job
.SH "SYNOPSIS"
.sp
\fBglobus\-fork\-starter\fR
.SH "DESCRIPTION"
.sp
The \fBglobus\-fork\-starter\fR program is executes jobs specified on its standard input stream, recording the job state changes to a file defined in the /etc/globus\-fork\&.conf configuration file\&. It runs until its standard input stream is closed and all jobs it is managing have terminated\&. The log generated by this program can be used by the SEG to provide job state changes and exit codes to the GRAM service\&. The \fBglobus\-fork\-starter\fR program is typically started by the fork GRAM module\&.
.sp
The \fBglobus\-fork\-starter\fR program expects its input to be a series of task definitions, separated by the newline character, each representing a separate job\&. Each task definition contains a number of fields, separated by the colon character\&. The first field is always the literal string 100 indicating the message format, the second field is a unique job tag that will be distinguish the reply from this program when multiple jobs are submitted\&. The rest of fields contain attribute bindings\&. The supported attributes are:
.PP
\fBdirectory\fR
.RS 4
Working directory of the job
.RE
.PP
\fBenvironment\fR
.RS 4
Comma\-separated list of strings defining environment variables\&. The form of these strings is
var=value\&.
.RE
.PP
\fBcount\fR
.RS 4
Number of processes to start\&.
.RE
.PP
\fBexecutable\fR
.RS 4
Full path to the executable to run\&.
.RE
.PP
\fBarguments\fR
.RS 4
Comma\-separated list of command\-line arguments for the job
.RE
.PP
\fBstdin\fR
.RS 4
Full path to a file containing the input of the job\&.
.RE
.PP
\fBstdout\fR
.RS 4
Full path to a file to write the output of the job to\&.
.RE
.PP
\fBstderr\fR
.RS 4
Full path to a file to write the error stream of the job\&.
.RE
.sp
Within each field, the following characters may be escaped by preceding them with the backslash character: \- backslash (\e) \- semicolor (;) \- comma (,) \- equal (=)
.sp
Additionally, newline can be represented within a field by using the escape sequence \en\&.
.sp
For each job the \fBglobus\-fork\-starter\fR processes, it replies by writing a single line to standard output\&. The replies again consist of a number of fields separated by the semicolon character\&.
.sp
For a successful job start, the first field of the reply is the literal 101, the second field is the tag from the input, and the third field is a comma\-separated list of SEG job identifiers which consist the concatenation of a UUID and a process id\&. The \fBglobus\-fork\-starter\fR program will write state changes to the SEG log using these job identifiers\&.
.sp
For a failure, the first field of the reply is the literal 102, the second field is the tag from the input, the third field is the integer representation of a GRAM erorr code, and the fourth field is an string explaining the error\&.
.SH "ENVIRONMENT"
.sp
The following variables affect the execution of \fBglobus\-fork\-starter\fR
.PP
\fBGLOBUS_LOCATION\fR
.RS 4
Path to Globus Toolkit installation\&. This is used to locate the
globus\-fork\&.conf
configuration file\&.
.RE
.SH "FILES"
.sp
The following files affect the execution of \fBglobus\-fork\-starter\fR
.PP
\fB/etc/globus\-fork\&.conf\fR
.RS 4
Path to fork SEG configuration file\&.
.RE
.SH "AUTHOR"
.sp
Copyright \(co 1999\-2016 University of Chicago
