#! /bin/sh

crl_file="%(certdir)s/%(cilogon_hash)s.r0"
new_crl_file="${crl_file}.new"
curl -Ls "%(cilogon_url)s" -o "${new_crl_file}"
if [ -s "${new_crl_file}" ]; then
    mv "${new_crl_file}" "${crl_file}"
else
    rm -f "${new_crl_file}"
fi
