#!/bin/sh
if [ $# -ne 2 ]; then
    # need 2 command line arguments
    exit 1
fi
subjectdn=$1
username=$2

# example 1: verify the DN matches an accepted pattern
#if [ "${subjectdn}" != "/O=Grid/OU=MyProxy CA/CN=${username}" ]; then
#    exit 1
#fi

# example 2: check the DN against a blacklist
#blacklistfile="/etc/myproxy-server-blacklist"
#if [ -r  $blacklistfile ]; then
#    grep "${subjectdn}" $blacklistfile >/dev/null 2>&1
#    if [ $? -eq 0 ]; then
#        logger -t myproxy-server denied blacklisted user: "${subjectdn}"
#        exit 1;
#    fi
#fi

exit 0
