#! /bin/sh

gt6_repo_root="https://downloads.globus.org/toolkit/gt6"
gcs5_repo_root="https://downloads.globus.org/globus-connect-server"
stability_levels="stable testing unstable"
rpmoses="el6 el7 fedora sles12"
deboses="wheezy jessie stretch buster trusty xenial artful bionic"

bin_el6="el/6/\$basearch/"
src_el6="el/6/SRPMS/"
bin_el7="el/7/\$basearch/"
src_el7="el/7/SRPMS/"
bin_fedora="fedora/\$releasever/\$basearch/"
src_fedora="fedora/\$releasever/SRPMS/"
bin_sles12="sles/12"
src_sles12="sles/12"
repo_type_sles12="yast2"

rflag=
dflag=
oflag=

usage()
{
    printf "Usage: %s [-r | -d] [-o \"NAME NAME...\"]\n" $(basename $0)
}

while getopts rdo:h optname; do
    case $optname in
        r)
            rflag=1;;
        d)

            dflag=1;;
        o)
            oflag=$OPTARG;;
        h|?)
            usage
            exit 0
            ;;
    esac
done

if [ "${rflag}${dflag}" = "" ] || [ "${rflag}${dflag}" = 11 ]; then
    usage
    exit 1
fi

if [ "$rflag" = 1 ]; then
    if [ "$oflag" != "" ]; then
        oses="$oflag"
    else
        oses="$rpmoses"
    fi
    for repo in $oses ; do
        repo_enabled=1
        for stability in $stability_levels; do
            initial="$(echo $stability | cut -c1 | tr '[a-z]' '[A-Z]')"
            rest="$(echo $stability | cut -c2-)"
            cap_stability="$initial$rest"

            set -- "$gt6_repo_root" "$gcs5_repo_root"
            for repo_name in Globus-Toolkit-6 Globus-Connect-Server-5; do
                repo_root="$1"
                shift
                lower_repo_name=$(echo $repo_name | tr '[A-Z]' '[a-z]')
                REPO_SECTION_NAME="$repo_name-$cap_stability"
                REPO_NAME="$(echo "$REPO_SECTION_NAME" | tr '-' ' ')"
                eval "REPO_BASE_URL=$repo_root/$stability/rpm/\$bin_$repo"
                REPO_SOURCE_SECTION_NAME="$repo_name-Source-$cap_stability"
                REPO_SOURCE_NAME="$(echo "$REPO_SOURCE_SECTION_NAME" | tr '-' ' ')"
                eval "REPO_BASE_SOURCE_URL=$repo_root/$stability/rpm/\$src_$repo"
                eval "repo_type=\$repo_type_$repo"
                if [ "$repo_type" != "" ]; then
                    REPO_TYPE="type=$repo_type"
                else
                    REPO_TYPE=""
                fi

                sed -e "s!@REPO_SECTION_NAME@!$REPO_SECTION_NAME!g" \
                    -e "s!@REPO_NAME@!$REPO_NAME!g" \
                    -e "s!@REPO_BASE_URL@!$REPO_BASE_URL!g" \
                    -e "s!@REPO_SOURCE_SECTION_NAME@!$REPO_SOURCE_SECTION_NAME!g" \
                    -e "s!@REPO_SOURCE_NAME@!$REPO_SOURCE_NAME!g" \
                    -e "s!@REPO_BASE_SOURCE_URL@!$REPO_BASE_SOURCE_URL!g" \
                    -e "s!@REPO_TYPE@!$REPO_TYPE!g" \
                    -e "s!@REPO_ENABLED@!$repo_enabled!g" \
                    < globus-repo.in > $lower_repo_name-$stability-$repo.repo
                repo_enabled=0
            done
        done
    done
else
    if [ "$oflag" != "" ]; then
        oses="$oflag"
    else
        oses="$deboses"
    fi
    for release in $oses ; do
        repo_enabled=1
        for stability in $stability_levels; do
            set -- "$gt6_repo_root" "$gcs5_repo_root"
            for repo_name in globus-toolkit-6 globus-connect-server; do
                repo_root="$1"
                shift
                if [ $repo_enabled = 1 ]; then
                    enabled=
                else
                    enabled="# "
                fi
                sed -e "s!@REPOSITORY_ROOT@!${repo_root}!g" \
                    -e "s!@ENABLED@!${enabled}!g" \
                    -e "s!@STABILITY@!${stability}!g" \
                    -e "s!@RELEASE@!${release}!g" \
                    < globus-list.in > $repo_name-$stability-$release.list
                repo_enabled=0
            done
        done
    done
fi
