#!/bin/sh

# checking for the GLOBUS_LOCATION

if test "x$GLOBUS_LOCATION" = "x"; then
    echo "ERROR Please specify GLOBUS_LOCATION" >&2
    exit 1
fi

if [ ! -f ${GLOBUS_LOCATION}/libexec/globus-bootstrap.sh ]; then
    echo "ERROR: Unable to locate \${GLOBUS_LOCATION}/libexec/globus-bootstrap.sh"
    echo "       Please ensure that you have installed the globus-core package and"
    echo "       that GLOBUS_LOCATION is set to the proper directory"
    exit
fi

autoconf_location=`type autoconf 2> /dev/null`
if test $? = 0; then
        autoconf_location=`type autoconf | sed -e "s|autoconf is ||"`
fi
                                                                                
globus_autotools_path=`echo $autoconf_location | sed -e "s|/bin/autoconf$||"`
if test -d "$globus_autotools_path/openssl_tools/bin"; then
        openssl_autotools_path="$globus_autotools_path/openssl_tools/bin"
else
        echo ""
        echo "bootstrap FAILED:  You need to have the Globus autotools at the front of your PATH before running bootstrap"
        echo ""
        exit 1
fi
                                                                                
CURRENT_PATH=$PATH
PATH=$openssl_autotools_path:$PATH
export PATH

. ${GLOBUS_LOCATION}/libexec/globus-bootstrap.sh

chmod 755 setup-simple-ca

exit 0
