#!/bin/sh

interactive() {

    INSTALLED_CERTS="`echo $trusted_certs_dir/*.0`"

    if [ -z "${INSTALLED_CERTS}" ]; then
        echo "No CA's have been installed on this host!"
        echo "To set the default CA, you first need to"
        echo "install a CA to the host"
        exit 1;
    else
        echo "The available CA configurations installed on this host are:"
        echo
    fi
    
    index=1
    for cert in $trusted_certs_dir/*.0; do
    
        eval "CA${index}=${cert}"
        TEMP_SUBJECT=`openssl x509 -in ${cert} -noout -subject`
        eval "CA_SUBJECT${index}=\"`echo ${TEMP_SUBJECT} | ${GLOBUS_SH_SED-sed} -e \"s|subject= ||\"`\""
        eval "echo \"$index)  \${CA_SUBJECT${index}}\""
        index=$[ $index + 1 ]
    done
    
    echo
    echo -n "Enter the index number of the CA to set as the default: "
    read CA_CHOSEN_INDEX
    
    if [ $[ 0 < ${CA_CHOSEN_INDEX} ] == 0 ] ||
       [ $[ $index > ${CA_CHOSEN_INDEX} ] == 0 ]; then
        echo "${CA_CHOSEN_INDEX} is not a valid index!"
        exit 1
    fi
    
    eval "CA_SUBJECT=\${CA_SUBJECT${CA_CHOSEN_INDEX}}"
    eval "CA_CERT=\${CA${CA_CHOSEN_INDEX}}"
}

############################################################
# main code section
############################################################
if test -z "${GLOBUS_LOCATION}"; then
    echo 
    echo "ERROR: Please set the GLOBUS_LOCATION to the Globus"
    echo "installation directory before running this script."
    echo
    exit 1
fi

. ${GLOBUS_LOCATION}/libexec/globus-script-initializer
globus_source ${libexecdir}/globus-sh-tools.sh



secconfdir=${GRID_SECURITY_DIR-/etc/grid-security/}
trusted_certs_dir=$secconfdir/certificates/

if [ $secconfdir -ef "${GLOBUS_LOCATION}/etc/" ]; then
    trusted_certs_dir=${GLOBUS_LOCATION}/share/certificates/
fi

if [ ! -d "${secconfdir}" ] || [ ! -d "${trusted_certs_dir}" ]; then
    echo 
    echo "The gsi config files have not been setup correctly."
    echo "Run ${GLOBUS_LOCATION}/setup/globus/setup-gsi"
    echo
    exit 1
fi

if [ ! -w "${secconfdir}" ]; then
    echo
    echo "You do not have permission to set"
    echo "the default CA configuration at"
    echo 
    echo $secconfdir
    echo
    echo "To change the location of the CA config"
    echo "files, set the GRID_SECURITY_DIR environment"
    echo "variable to their location"
    echo
    exit 1
fi

if [ -z $1 ]; then
    interactive
else
    CA_CERT=$1
    TMP_SUBJECT=`openssl x509 -in ${CA_CERT} -noout -subject`
    CA_SUBJECT=`echo ${TMP_SUBJECT} | ${GLOBUS_SH_SED-sed} -e "s|subject= ||"`
fi

echo
echo "setting the default CA to: ${CA_SUBJECT}"
echo

NEW_DEFAULT_CA_HASH=`openssl x509 -in ${CA_CERT} -noout -hash`

GRID_SECURITY_FILE=${trusted_certs_dir}/grid-security.conf.${NEW_DEFAULT_CA_HASH}
CA_SSL_HOST_CONFIG_FILE=${trusted_certs_dir}/globus-host-ssl.conf.${NEW_DEFAULT_CA_HASH}
CA_SSL_USER_CONFIG_FILE=${trusted_certs_dir}/globus-user-ssl.conf.${NEW_DEFAULT_CA_HASH}

error() {

    eval "missing_file=\$$1"

    echo
    echo "The file: ${missing_file} does not exist"
    echo "The CA: ${CA_SUBJECT}"
    echo "has not been setup correctly."
    echo
    exit 1
}


if [ -w ${GRID_SECURITY_FILE} ]; then
    
    echo "linking ${GRID_SECURITY_FILE} to"
    echo "        ${secconfdir}/grid-security.conf"
    echo
    ${GLOBUS_SH_RM-rm} -f ${secconfdir}/grid-security.conf
    ${GLOBUS_SH_LN-ln} -s ${GRID_SECURITY_FILE} \
			  ${secconfdir}/grid-security.conf 
else
    error GRID_SECURITY_FILE
fi

if [ -w ${CA_SSL_HOST_CONFIG_FILE} ]; then

    echo "linking ${CA_SSL_USER_CONFIG_FILE} to"
    echo "        ${secconfdir}/globus-host-ssl.conf"
    echo
    ${GLOBUS_SH_RM-rm} -f ${secconfdir}/globus-host-ssl.conf
    ${GLOBUS_SH_LN-ln} -s ${CA_SSL_USER_CONFIG_FILE} \
		          ${secconfdir}/globus-host-ssl.conf
else
    error CA_SSL_HOST_CONFIG_FILE
fi

if [ -w ${CA_SSL_USER_CONFIG_FILE} ]; then

    echo "linking ${CA_SSL_HOST_CONFIG_FILE} to"
    echo "        ${secconfdir}/globus-user-ssl.conf"
    echo
    ${GLOBUS_SH_RM-rm} -f ${secconfdir}/globus-user-ssl.conf
    ${GLOBUS_SH_LN-ln} -s ${CA_SSL_HOST_CONFIG_FILE} \
	    	          ${secconfdir}/globus-user-ssl.conf
else
    error CA_SSL_USER_CONFIG_FILE
fi

echo 
echo "...done."
echo
exit 0