# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




SHELL = /bin/sh

srcdir = /sandbox/blau/i18n3/i18n/source/pkgdata
top_srcdir = /sandbox/blau/i18n3/i18n/source
VPATH = /sandbox/blau/i18n3/i18n/source/pkgdata
prefix = $(GLOBUS_LOCATION)
exec_prefix = $(GLOBUS_LOCATION)

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/globus_i18n
pkglibdir = $(libdir)/globus_i18n
pkgincludedir = $(includedir)/globus_i18n

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = @host_alias@
host_triplet = @host@
AR = /usr/bin/ar
ARFLAGS = ruv
AS = @AS@
CC = /usr/bin/gcc
CFLAGS = -g   -Wall
CPP = /usr/bin/gcc -E
CPPFLAGS =  -I/sandbox/blau/i18n3/INSTALL/include -I/sandbox/blau/i18n3/INSTALL/include/gcc32dbg
CROSS = no
CXX = /usr/bin/g++
CXXCPP = /usr/bin/g++ -E
CXXFLAGS = -g  
DIRT_BRANCH_ID = 99999
DIRT_TIMESTAMP = 1097492282
DLLTOOL = @DLLTOOL@
DOT = 
DOXYFILE = Doxyfile
DOXYGEN = 
EXEEXT = 
F77 = /usr/bin/g77
F77FLAGS =  
F90 = 
F90FLAGS =  
FILELIST_FILE = /sandbox/blau/i18n3/i18n/source/pkgdata/master.filelist
GLOBUS_FLAVOR_NAME = gcc32dbg
GPT_CFLAGS =  
GPT_CONFIG_CFLAGS =  
GPT_CONFIG_INCLUDES =  
GPT_CONFIG_LIBS =  
GPT_CONFIG_PKG_LIBS = -lglobus_common_gcc32dbg -lltdl_gcc32dbg -licui18n_gcc32dbg -licule_gcc32dbg -licutu_gcc32dbg -licudata_gcc32dbg -licuio_gcc32dbg -liculx_gcc32dbg -licuuc_gcc32dbg 
GPT_EXTERNAL_INCLUDES = 
GPT_EXTERNAL_LIBS = 
GPT_INCLUDES = -I/sandbox/blau/i18n3/INSTALL/include/gcc32dbg  
GPT_IS_2 = yes
GPT_LDFLAGS =  -L/sandbox/blau/i18n3/INSTALL/lib 
GPT_LIBS = -lglobus_common_gcc32dbg -lltdl_gcc32dbg -licui18n_gcc32dbg -licule_gcc32dbg -licutu_gcc32dbg -licudata_gcc32dbg -licuio_gcc32dbg -liculx_gcc32dbg -licuuc_gcc32dbg   
GPT_LIB_LINKS = -lglobus_common_gcc32dbg -lltdl_gcc32dbg -licui18n_gcc32dbg -licule_gcc32dbg -licutu_gcc32dbg -licudata_gcc32dbg -licuio_gcc32dbg -liculx_gcc32dbg -licuuc_gcc32dbg   
GPT_LINKTYPE = shared
GPT_LOCATION = /sandbox/blau/GPT
GPT_MAJOR_VERSION = 0
GPT_MINOR_VERSION = 1
GPT_PGM_LINKS = -lglobus_common_gcc32dbg -lltdl_gcc32dbg -licui18n_gcc32dbg -licule_gcc32dbg -licutu_gcc32dbg -licudata_gcc32dbg -licuio_gcc32dbg -liculx_gcc32dbg -licuuc_gcc32dbg   
GPT_PKG_CFLAGS = 
HAVE_DOT = 
INSURE = 
LD = /usr/bin/gcc
LDFLAGS =  -L/sandbox/blau/i18n3/INSTALL/lib
LIBS =  
LIBTOOL = $(SHELL) $(GLOBUS_LOCATION)/sbin/libtool-$(GLOBUS_FLAVOR_NAME)
LN_S = 
MAINT = #
MAKEINFO = makeinfo
OBJDUMP = @OBJDUMP@
OBJECT_MODE = 
OBJEXT = o
PACKAGE = globus_i18n
PERL = /usr/bin/perl
RANLIB = /usr/bin/ranlib
VERSION = 0.1
builddir = /sandbox/blau/i18n3/i18n/source
cross_compiling = no
lac_doxygen_examples = 
lac_doxygen_file_patterns = 
lac_doxygen_input_filter = 
lac_doxygen_installdox = 
lac_doxygen_internal_tagfiles = 
lac_doxygen_output_tagfile = 
lac_doxygen_predefines = 
lac_doxygen_project = 
lac_doxygen_srcdirs = 
lac_doxygen_tagfiles = 

setupdir = $(GLOBUS_LOCATION)/setup/globus

testdir = $(GLOBUS_LOCATION)/test/$(PACKAGE)

scriptsysconfdir = $(GLOBUS_LOCATION)/etc

flavorincludedir = $(GLOBUS_LOCATION)/include/$(GLOBUS_FLAVOR_NAME)

pkgdir = $(GLOBUS_LOCATION)/etc/globus_packages/$(PACKAGE)

aclocaldir = $(GLOBUS_LOCATION)/share/globus_aclocal

amdirdir = $(GLOBUS_LOCATION)/share/globus_amdir

doxygendir = $(GLOBUS_LOCATION)/share/doxygen

docdir = $(GLOBUS_LOCATION)/share/doc

LINK_BAK = orig
AUTOMAKE_OPTIONS = no-dependencies

flavordir = $(GLOBUS_LOCATION)/etc/$(PACKAGE)

FILELIST_FILES = noflavor_data.filelist 	$(GLOBUS_FLAVOR_NAME)_dev.filelist 	noflavor_doc.filelist 	$(GLOBUS_FLAVOR_NAME)_pgm.filelist 	$(GLOBUS_FLAVOR_NAME)_pgm_static.filelist 	$(GLOBUS_FLAVOR_NAME)_rtl.filelist


METADATA_FILES =  	pkg_data_noflavor_data.gpt 	pkg_data_$(GLOBUS_FLAVOR_NAME)_dev.gpt 	pkg_data_noflavor_doc.gpt 	pkg_data_$(GLOBUS_FLAVOR_NAME)_pgm.gpt 	pkg_data_$(GLOBUS_FLAVOR_NAME)_pgm_static.gpt 	pkg_data_$(GLOBUS_FLAVOR_NAME)_rtl.gpt


pkg_DATA = $(FILELIST_FILES) $(METADATA_FILES)
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_CLEAN_FILES =  pkg_data_src.gpt
DATA =  $(pkg_DATA)

DIST_COMMON =  Makefile.am Makefile.in pkg_data_src.gpt.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) $(top_srcdir)/globus_automake_pre $(top_srcdir)/globus_automake_post
	cd $(top_srcdir) && $(AUTOMAKE) --foreign pkgdata/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status

pkg_data_src.gpt: $(top_builddir)/config.status pkg_data_src.gpt.in
	cd $(top_builddir) && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status

install-pkgDATA: $(pkg_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(pkgdir)
	@list='$(pkg_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(pkgdir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(pkgdir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(pkgdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(pkgdir)/$$p; \
	  fi; fi; \
	done

uninstall-pkgDATA:
	@$(NORMAL_UNINSTALL)
	list='$(pkg_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(pkgdir)/$$p; \
	done
tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = pkgdata

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am: install-pkgDATA
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-pkgDATA
uninstall: uninstall-am
all-am: Makefile $(DATA)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(pkgdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-generic clean-am distclean-local
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: uninstall-pkgDATA install-pkgDATA tags distdir info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


filelist_file: $(MAKEFILE_AMS)
	@mydir=`pwd`; \
	if test -f "master.filelist"; then \
		rm $(FILELIST_FILE); \
	fi

all_filelists: filelist_file
	 @(cd .. && $(MAKE) $(AM_MAKEFLAGS) filelist) \
	  || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac;

$(FILELIST_FILES): sort_filelist

sort_filelist: all_filelists
	@if test "$(GPT_IS_2)" = "yes"; then \
		$(GPT_LOCATION)/sbin/gpt_sort_filelist  \
		--flavor=$(GLOBUS_FLAVOR_NAME) \
		-pkg=./pkg_data_src.gpt.in ./master.filelist; \
	else \
		$(GPT_LOCATION)/sbin/gpt_sort_filelist  \
		--flavor=$(GLOBUS_FLAVOR_NAME) \
		./master.filelist; \
	fi

$(METADATA_FILES): pkg_data_src.gpt
	@$(GPT_LOCATION)/sbin/gpt_generate_bin_pkg_data  \
	--flavor=$(GLOBUS_FLAVOR_NAME) pkg_data_src.gpt

distclean-local:
	@if test -f master.filelist; then \
		rm *.filelist; \
	fi; \
	if test -f pkg_data_noflavor_data.gpt; then \
		rm pkg_data_*.gpt; \
	fi

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
link-am:

unlink-am:

filelist-am:

link: link-recursive link-pkgDATA 
	:

unlink: unlink-recursive unlink-pkgDATA 
	:

.PHONY: link unlink link-recursive unlink-recursive link-am unlink-am filelist-amlink-pkgDATA unlink-pkgDATA filelist-pkgDATA 

filelist: filelist-recursive filelist-pkgDATA 
	:




link-pkgDATA: $(pkg_DATA)
	@$(NORMAL_INSTALL)
	@$(mkinstalldirs) $(DESTDIR)$(pkgdir)
	@list='$(pkg_DATA)'; for p in $$list; do \
	  mydir=`pwd`; \
	  target_p=$(DESTDIR)$(pkgdir)/$$p; \
	  if test -f $(srcdir)/$$p; then \
		cd $(srcdir); \
		fullsrcdir=`pwd`; \
		cd $$mydir; \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$fullsrcdir/$$p $$target_p"; \
			ln -s $$fullsrcdir/$$p $$target_p; \
		fi; \
	  else if test -f $$p; then \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$mydir/$$p $$target_p"; \
			ln -s $$mydir/$$p $$target_p; \
		fi; \
	  fi; fi; \
	done

unlink-pkgDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkg_DATA)'; for p in $$list; do \
	target_p=$(DESTDIR)$(pkgdir)/$$p; \
	if test -h $$target_p; then \
		echo "rm $$target_p"; \
		rm $$target_p; \
	fi; \
	if test -f $$target_p.$(LINK_BAK); then \
		echo "mv $$target_p.$(LINK_BAK) $$target_p"; \
		mv $$target_p.$(LINK_BAK) $$target_p; \
	fi; \
	done

filelist-pkgDATA:
	@list='$(pkg_DATA)'; for p in $$list; do \
	  echo "$(DESTDIR)$(pkgdir)/$$p" >> $(FILELIST_FILE); \
	done


link-recursive unlink-recursive filelist-recursive:
	@set fnord $(MAKEFLAGS); amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

