<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ManagedJobFactory" targetNamespace="http://www.globus.org/namespaces/filestreaming/file_streaming_factory_port_type/bindings" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:filestreamingfactoryporttype="http://www.globus.org/namespaces/filestreaming/file_streaming_factory_port_type" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"><import location="file_streaming_factory_port_type.wsdl" namespace="http://www.globus.org/namespaces/filestreaming/file_streaming_factory_port_type"/><binding name="ManagedJobFactorySOAPBinding" type="filestreamingfactoryporttype:FileStreamingFactoryPortType"><soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/></binding></definitions>