<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ManagedJobFactory"
             targetNamespace="http://www.globus.org/namespaces/filestreaming/file_streaming_factory_port_type"
             xmlns:tns="http://www.globus.org/namespaces/filestreaming/file_streaming_factory_port_type"
             xmlns:fs-types="http://www.globus.org/namespaces/filestreaming/file_streaming_types"
             xmlns:gsdl="http://www.gridforum.org/namespaces/2002/07/gridServices"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/">

<import location="../../base/gram/file_streaming_types.wsdl"
        namespace="http://www.globus.org/namespaces/filestreaming/file_streaming_types"/>

<import location="../../core/factory/factory_port_type.wsdl"
        namespace="http://ogsa.gridforum.org/factory/factory"/>

<gsdl:serviceDataDescription name="FileStreamingHandles"
    element="ogsa-types:ServiceHandleElementType"
    minOccurs="0"
    maxOccurs="unbounded"
    mutability="mutable">
    <documentation>
        A list of this factory's instance handles.
    </documentation>
</gsdl:serviceDataDescription>

<gsdl:serviceDataDescription name="DestinationURLs"
                             element="fs-types:DestinationURL"
                             minOccurs="0"
                             maxOccurs="unbounded"
                             mutability="mutable">
</gsdl:serviceDataDescription>

<portType name="FileStreamingFactoryPortType">

</portType>

</definitions>
