<?xml version="1.0" encoding="UTF-8"?>
<definitions name="FileStreamingDefinition"
    targetNamespace="http://www.globus.org/namespaces/filestreaming/file_streaming_bindings"
    xmlns:file-streaming-port-type="http://www.globus.org/namespaces/filestreaming/file_streaming_port_type"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

 <import location="../../base/gram/file_streaming_port_type.wsdl"
    namespace="http://www.globus.org/namespaces/filestreaming/file_streaming_port_type"/>

<binding name="FileStreamingSOAPBinding" type="file-streaming-port-type:FileStreamingPortType">
  <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="startStreaming">
      <soap:operation soapAction="http://www.globus.org/namespaces/filestreaming#startStreaming"/>
    <input>
      <soap:body use="literal" namespace="http://www.globus.org/namespaces/filestreaming"/>
    </input>
    <output>
      <soap:body use="literal" namespace="http://www.globus.org/namespaces/filestreaming"/>
    </output>
  </operation>
</binding>

</definitions>
