#! /bin/sh

PATH="${PATH}:$(dirname $0):."

echo "   Starting personal gatekeeper"
contact="$(globus-personal-gatekeeper -start | sed -e 's/GRAM contact: //')"

if [ "$?" != 0 ] || [ -z "$contact" ]; then
    exit 99
    globus-personal-gatekeeper -kill "$contact"
fi

export CONTACT_STRING="$contact"
# Perl scripts pass through, otherwise run the program under valgrind
# conditionally
if [ "${1##*.}" = "pl" ]; then
    "$@"
else
    if [ -n "${VALGRIND}" ]; then
        valgrind="${VALGRIND+valgrind --log-file=VALGRIND-$(basename $1).log}"
        if [ -n "$VALGRIND_OPTIONS" ]; then
            valgrind="${valgrind} ${VALGRIND_OPTIONS}"
        fi
        $valgrind "$@"
    else
        "$@"
    fi
fi

rc=$?

globus-personal-gatekeeper -kill "$contact" > /dev/null 2>&1

exit $rc
