<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="XACMLAuthorization" targetNamespace="http://www.globus.org/security/XACMLAuthorization/service" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:binding="http://www.globus.org/security/XACMLAuthorization/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://www.globus.org/security/XACMLAuthorization/bindings" location="xacml_authz_bindings.wsdl"/>
  <wsdl:service name="XACMLAuthorizationService">
    <wsdl:port name="XACMLAuthorizationPortTypePort" binding="binding:XACMLAuthorizationPortTypeSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
