#!/bin/sh

if [ "$GLOBUS_LOCATION" = "" ]; then
  echo "Set GLOBUS_LOCATION before running this script"
  exit 1
fi

. $GLOBUS_LOCATION/etc/globus-user-env.sh

perl $GLOBUS_LOCATION/setup/gsi_openssh_setup/setup-openssh.pl $*
