'\" t
.\"     Title: globus-personal-gatekeeper
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 03/29/2012
.\"    Manual: GRAM5 Commands
.\"    Source: University of Chicago
.\"  Language: English
.\"
.TH "GLOBUS\-PERSONAL\-GA" "1" "03/29/2012" "University of Chicago" "GRAM5 Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-personal-gatekeeper \- Manage a user\*(Aqs personal gatekeeper daemon
.SH "SYNOPSIS"
.HP \w'\fBglobus\-personal\-gatekeeper\fR\ 'u
\fBglobus\-personal\-gatekeeper\fR [\-help] [\-usage] [\-version] [\-versions] [\-list] [\-directory\ \fICONTACT\fR]
.HP \w'\fBglobus\-personal\-gatekeeper\fR\ 'u
\fBglobus\-personal\-gatekeeper\fR [\-debug] {\-start} [\-jmtype\ \fILRM\fR] [\-auditdir\ \fIAUDIT_DIRECTORY\fR] [\-port\ \fIPORT\fR] [\-log\ [=\fIDIRECTORY\fR]] [\-seg] [\-acctfile\ \fIACCOUNTING_FILE\fR]
.HP \w'\fBglobus\-personal\-gatekeeper\fR\ 'u
\fBglobus\-personal\-gatekeeper\fR [\-killall] [\-kill]
.SH "DESCRIPTION"
.PP
The
\fBglobus\-personal\-gatekeeper\fR
command is a utility which manages a gatekeeper and job manager service for a single user\&. Depending on the command\-line arguments it will operate in one of several modes\&. In the first set of arguments indicated in the synopsis, the program provides information about the
\fBglobus\-personal\-gatekeeper\fR
command or about instances of the
\fBglobus\-personal\-gatekeeper\fR
that are running currently\&. The second set of arguments indicated in the synopsis provide control over starting a new
\fBglobus\-personal\-gatekeeper\fR
instance\&. The final set of arguments provide control for terminating one or more
\fBglobus\-personal\-gatekeeper\fR
instances\&.
.PP
The
\fB\-start\fR
mode will create a new subdirectory of
\fB$HOME\fR/\&.globus
and write the configuration files needed to start a
\fBglobus\-gatekeeper\fR
daemon which will invoke the
\fBglobus\-job\-manager\fR
service when new authenticated connections are made to its service port\&. The
\fBglobus\-personal\-gatekeeper\fR
then exits, printing the contact string for the new gatekeeper prefixed by
GRAM contact:
to standard output\&. In addition to the arguments described above, any arguments described in
\fBglobus\-job\-manager(8)\fR
can be appended to the command\-line and will be added to the job manager configuration for the service started by the
\fBglobus\-gatekeeper\fR\&.
.PP
The new
\fBglobus\-gatekeeper\fR
will continue to run in the background until killed by invoking
\fBglobus\-personal\-gatekeeper\fR
with the
\fB\-kill\fR
or
\fB\-killall\fR
argument\&. When killed, it will kill the
\fBglobus\-gatekeeper\fR
and
\fBglobus\-job\-manager\fR
processes, remove state files and configuration data, and then exit\&. Jobs which are running when the personal gatekeeper is killed will continue to run, but their job directory will be destroyed so they may fail in the LRM\&.
.PP
The full set of command\-line options to
\fBglobus\-personal\-gatekeeper\fR
consists of:
.PP
\fB\-help\fR, \fB\-usage\fR
.RS 4
Print command\-line option summary and exit
.RE
.PP
\fB\-version\fR
.RS 4
Print software version
.RE
.PP
\fB\-versions\fR
.RS 4
Print software version including DiRT information
.RE
.PP
\fB\-list\fR
.RS 4
Print a list of all currently running personal gatekeepers\&. These entries will be printed one per line\&.
.RE
.PP
\fB\-directory \fR\fB\fICONTACT\fR\fR
.RS 4
Print the configuration directory for the personal gatekeeper with the contact string
\fICONTACT\fR\&.
.RE
.PP
\fB\-debug\fR
.RS 4
Print additional debugging information when starting a personal gatekeeper\&. This option is ignored in other modes\&.
.RE
.PP
\fB\-start\fR
.RS 4
Start a new personal gatekeeper process\&.
.RE
.PP
\fB\-jmtype \fR\fB\fILRM\fR\fR
.RS 4
Use
\fILRM\fR
as the local resource manager interface\&. If not provided when starting a personal gatekeeper, the job manager will use the default
fork
LRM\&.
.RE
.PP
\fB\-auditdir \fR\fB\fIAUDIT_DIRECTORY\fR\fR
.RS 4
Write audit report files to
\fIAUDIT_DIRECTORY\fR\&. If not provided, the job manager will not write any audit files\&.
.RE
.PP
\fB\-port \fR\fB\fIPORT\fR\fR
.RS 4
Listen for gatekeeper TCP/IP connections on the port
\fIPORT\fR\&. If not provided, the gatekeeper will let the operating system choose\&.
.RE
.PP
\fB\-log\fR\fB[=\fIDIRECTORY\fR]\fR
.RS 4
Write job manager log files to
\fIDIRECTORY\fR\&. If
\fIDIRECTORY\fR
is omitted, the default of
\fB$HOME\fR
will be used\&. If this option is not present, the job manager will not write any log files\&.
.RE
.PP
\fB\-seg\fR
.RS 4
Try to use the SEG mechanism to receive job state change information, instead of polling for these\&. These require either the system administrator or the user to run an instance of the
\fBglobus\-job\-manager\-event\-generator\fR
program for the LRM specified by the
\fB\-jmtype\fR
option\&.
.RE
.PP
\fB\-acctfile \fR\fB\fIACCOUNTING_FILE\fR\fR
.RS 4
Write gatekeeper accounting entries to
\fIACCOUNTING_FILE\fR\&. If not provided, no accounting records are written\&.
.RE
.SH "EXAMPLES"
.PP
This example shows the output when starting a new personal gatekeeper which will schedule jobs via the
lsf
LRM, with debugging enabled\&.
.sp
.if n \{\
.RS 4
.\}
.nf
% \fBglobus\-personal\-gatekeeper \-start \-jmtype lsf\fR

verifying setup\&.\&.\&.
done\&.
GRAM contact: personal\-grid\&.example\&.org:57846:/DC=org/DC=example/CN=Joe User
.fi
.if n \{\
.RE
.\}
.PP
This example shows the output when listing the current active personal gatekeepers\&.
.sp
.if n \{\
.RS 4
.\}
.nf
% \fBglobus\-personal\-gatekeeper \-list\fR

personal\-grid\&.example\&.org:57846:/DC=org/DC=example/CN=Joe User
.fi
.if n \{\
.RE
.\}
.PP
This example shows the output when querying the configuration directory for th eabove personal gatekeeper\&. gatekeepers\&.
.sp
.if n \{\
.RS 4
.\}
.nf
% \fBglobus\-personal\-gatekeeper \-directory "personal\-grid\&.example\&.org:57846:/DC=org/DC=example/CN=Joe User"\fR

/home/juser/\&.globus/\&.personal\-gatekeeper\&.personal\-grid\&.example\&.org\&.1337
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
% \fBglobus\-personal\-gatekeeper \-kill "personal\-grid\&.example\&.org:57846:/DC=org/DC=example/CN=Joe User"\fR

killing gatekeeper: "personal\-grid\&.example\&.org:57846:/DC=org/DC=example/CN=Joe User"
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP

\fBglobusrun\fR(1),
\fBglobus-job-manager\fR(8),
\fBglobus-gatekeeper\fR(8)
