#! /bin/sh

if [ "x${GLOBUS_LOCATION}" = "x" ]; then
    echo "GLOBUS_LOCATION needs to be set before running this script."
    exit 1
fi

if [ "x${GPT_LOCATION}" = "x" ]; then
    echo "GPT_LOCATION needs to be set before running this script."
    exit 1
fi

ant -h > /dev/null
if [ $? -ne 0 ]; then
    echo You need a working version of ant.
    exit 1
fi

perl  -I${GLOBUS_LOCATION}/lib/perl -I${GPT_LOCATION}/lib/perl setup-filestreaming.pl "$@"
