print <<EOF;
/* This file is automatically generated by
 * $0. Do not modify.
 */

#ifndef GLOBUS_GRAM_PROTOCOL_CONSTANTS_H
#define GLOBUS_GRAM_PROTOCOL_CONSTANTS_H
EOF

my $type = 0;
my $comma_nl="";
while(<>)
{
    next if(/^#[^#]/);
    if(/^##/ && $type)
    {
	print "\n}\n$type;\n";
	$comma_nl = "";
    }
    if(/^##/)
    {
	$type = (split(/\s+/))[1] ;
	print "\ntypedef enum\n{\n";
	next;
    }
    if(/=/)
    {
	chomp;
	my @pair = split(/=/);
	print "$comma_nl    $pair[0] = $pair[1]";
	$comma_nl = ",\n";
    }
}

print "\n}\n$type;\n#endif\n";
