#!/usr/local/bin/perl

#
#

$gpt_source_dir='/sandbox/smartin/Packages/globus_build_tools/gpt/perl';
$gpt_web_dir='/mcs/www-unix.globus.org/packaging/GPT';

#----------------------- GPT perl modules -------------------------
system "pod2html --infile=$gpt_source_dir/GPT/BinaryDependency.pm".
               " --outfile=$gpt_web_dir/modules/BinaryDependency_pm.html";

system "pod2html --infile=$gpt_source_dir/GPT/SourceDependency.pm".
               " --outfile=$gpt_web_dir/modules/SourceDependency_pm.html";

system "pod2html --infile=$gpt_source_dir/GPT/Package.pm".
               " --outfile=$gpt_web_dir/modules/Package_pm.html";

system "pod2html --infile=$gpt_source_dir/GPT/XML.pm".
               " --outfile=$gpt_web_dir/modules/XML_pm.html";

system "pod2html --infile=$gpt_source_dir/GPT/Filelist.pm".
               " --outfile=$gpt_web_dir/modules/Filelist_pm.html";

system "pod2html --infile=$gpt_source_dir/GPT/Version.pm".
               " --outfile=$gpt_web_dir/modules/Version_pm.html";

# no documentation for these two yet.
# 
#system "pod2html --infile=$gpt_source_dir/GPT/Definitions.pm".
#               " --outfile=$gpt_web_dir/modules/Definitions_pm.html";
#
#system "pod2html --infile=$gpt_source_dir/GPT/Dependencies.pm".
#               " --outfile=$gpt_web_dir/modules/Dependencies_pm.html";

#----------------------- GPT perl scripts -------------------------

system "pod2html --infile=$gpt_source_dir/scripts/gpt_build_config".
               " --outfile=$gpt_web_dir/scripts/gpt_build_config.html";

# no documentation for this one yet.
# 
#system "pod2html --infile=$gpt_source_dir/scripts/gpt_create_automake_rules".
#              " --outfile=$gpt_web_dir/scripts/gpt_create_automake_rules.html";

system "pod2html --infile=$gpt_source_dir/scripts/gpt_extract_data".
               " --outfile=$gpt_web_dir/scripts/gpt_extract_data.html";

system "pod2html --infile=$gpt_source_dir/scripts/gpt_generate_bin_pkg_data".
               " --outfile=$gpt_web_dir/scripts/gpt_generate_bin_pkg_data.html";

system "pod2html --infile=$gpt_source_dir/scripts/gpt_sort_filelist".
               " --outfile=$gpt_web_dir/scripts/gpt_sort_filelist.html";

system "pod2html --infile=$gpt_source_dir/scripts/gpt_setup".
               " --outfile=$gpt_web_dir/scripts/gpt_setup.html";

system "pod2html --infile=$gpt_source_dir/scripts/gpt_edit".
               " --outfile=$gpt_web_dir/scripts/gpt_edit.html";

system "pod2html --infile=$gpt_source_dir/scripts/gpt_undefines".
               " --outfile=$gpt_web_dir/scripts/gpt_undefines.html";

