#include "globus_gram_client.h"

static char *
globus_l_gram_client_error_strings[] =
{
    "Success",
    "GLOBUS_GRAM_CLIENT_ERROR_PARAMETER_NOT_SUPPORTED",
    "GLOBUS_GRAM_CLIENT_ERROR_INVALID_REQUEST",
    "GLOBUS_GRAM_CLIENT_ERROR_NO_RESOURCES",
    "GLOBUS_GRAM_CLIENT_ERROR_BAD_DIRECTORY",
    "GLOBUS_GRAM_CLIENT_ERROR_BAD_EXECUTABLE",
    "GLOBUS_GRAM_CLIENT_ERROR_INSUFFICIENT_FUNDS",
    "GLOBUS_GRAM_CLIENT_ERROR_AUTHORIZATION",
    "GLOBUS_GRAM_CLIENT_ERROR_USER_CANCELLED",
    "GLOBUS_GRAM_CLIENT_ERROR_SYSTEM_CANCELLED",
    "GLOBUS_GRAM_CLIENT_ERROR_PROTOCOL_FAILED",
    "GLOBUS_GRAM_CLIENT_ERROR_STDIN_NOTFOUND",
    "GLOBUS_GRAM_CLIENT_ERROR_CONNECTION_FAILED",
    "GLOBUS_GRAM_CLIENT_ERROR_INVALID_MAXTIME",
    "GLOBUS_GRAM_CLIENT_ERROR_INVALID_COUNT",
    "GLOBUS_GRAM_CLIENT_ERROR_NULL_SPECIFICATION_TREE",
    "GLOBUS_GRAM_CLIENT_ERROR_JM_FAILED_ALLOW_ATTACH",
    "GLOBUS_GRAM_CLIENT_ERROR_JOB_EXECUTION_FAILED",
    "GLOBUS_GRAM_CLIENT_ERROR_INVALID_PARADYN",
    "GLOBUS_GRAM_CLIENT_ERROR_INVALID_JOBTYPE",
    "GLOBUS_GRAM_CLIENT_ERROR_INVALID_MYJOB",
    "GLOBUS_GRAM_CLIENT_ERROR_BAD_SCRIPT_ARG_FILE",
    "GLOBUS_GRAM_CLIENT_ERROR_ARG_FILE_CREATION_FAILED",
    "GLOBUS_GRAM_CLIENT_ERROR_INVALID_JOBSTATE",
    "GLOBUS_GRAM_CLIENT_ERROR_INVALID_SCRIPT_REPLY",
    "GLOBUS_GRAM_CLIENT_ERROR_INVALID_SCRIPT_STATUS",
    "GLOBUS_GRAM_CLIENT_ERROR_MPI_NOT_SUPPORTED",
    "GLOBUS_GRAM_CLIENT_ERROR_UNIMPLEMENTED",
    "GLOBUS_GRAM_CLIENT_ERROR_TEMP_SCRIPT_FILE_FAILED",
    "GLOBUS_GRAM_CLIENT_ERROR_PROXY_FILE_RELOCATION_FAILED",
    "GLOBUS_GRAM_CLIENT_ERROR_PROXY_FILE_OPEN_FAILED",
    "GLOBUS_GRAM_CLIENT_ERROR_JOB_CANCEL_FAILED",
    "GLOBUS_GRAM_CLIENT_ERROR_MALLOC_FAILED",
    "GLOBUS_GRAM_CLIENT_ERROR_DUCT_INIT_FAILED",
    "GLOBUS_GRAM_CLIENT_ERROR_DUCT_LSP_FAILED",
    "GLOBUS_GRAM_CLIENT_ERROR_INVALID_HOST_COUNT",
    "GLOBUS_GRAM_CLIENT_ERROR_UNSUPPORTED_PARAMETER",
    "GLOBUS_GRAM_CLIENT_ERROR_INVALID_QUEUE",
    "GLOBUS_GRAM_CLIENT_ERROR_INVALID_PROJECT",
    "GLOBUS_GRAM_CLIENT_ERROR_RSL_EVALUATION_FAILED",
    "GLOBUS_GRAM_CLIENT_ERROR_BAD_RSL_ENVIRONMENT",
    "GLOBUS_GRAM_CLIENT_ERROR_DRYRUN",
    "GLOBUS_GRAM_CLIENT_ERROR_ZERO_LENGTH_RSL"
};

const char *
globus_gram_client_error_string(int error_code)
{
    if (error_code < 0 || error_code >= GRAM_ERROR_LAST)
        return("Invalid error code");
    return(globus_l_gram_client_error_strings[error_code]);
} /* globus_gram_client_error_string() */
