#include "globus_gram_client.h"

static char *
globus_l_gram_client_error_strings[] =
{
    "Success",
    "One of The RSL parameters is not supported",
    "the RSL lentgh is greater than the maximum allowed",
    "unused NO_RESOURCES",
    "unable to set default to the directory requested",
    "executable not found",
    "unused INSUFFICIENT_FUNDS",
    "authentication with the remote server failed.",
    "unused USER_CANCELLED",
    "unused SYSTEM_CANCELLED",
    "failure during data transfer to the server",
    "stdin file not found",
    "failed to connect to server, check host and port",
    "invalid maxtime, integer required",
    "invalid count, integer required",
    "job manager received an invalid RSL",
    "job manager failed in allowing others to make contact",
    "job failed when the job manager attempted to run it",
    "Invalid paradyn specified",
    "jobtype RSL parameter is invalid",
    "myjob RSL parameter is invalid",
    "The job manager failed to locate an internal script argument file",
    "The job manager failed to create an internal script argument file",
    "The job manager detected an invalid job state",
    "The job manager detected an invalid script response",
    "The job manager detected an invalid job state",
    "The RSL jobtype is not supported by this job manager",
    "unused ERROR_UNIMPLEMENTED",
    "The job manager failed to create an internal script submission file",
    "The job manager can not find the user proxy",
    "The job manager failed to open the user proxy",
    "The job manager failed to cancel the job as requested",
    "System error: malloc failed",
    "Failed to initialize job interprocess communication",
    "Failed to setup job interprocess communication",
    "The RSL host count parameter is invalid",
    "One of the RSL parameters specified is unsupported",
    "The RSL queue parameter is invalid",
    "The RSL project parameter is invalid",
    "The RSL includes variables that could not be identified",
    "The RSL environment parameter is invalid",
    "The RSL dryrun parameter is invalid",
    "The RSL is invalid, empty string",
    "The job manager failed to stage the executable",
    "The job manager failed to stage the stdin file",
    "Request to run an invalid job manager type",
    "The RSL arguments parameter is invalid",
    "The gatekeeper failed to run the job manager",
    "The RSL is invalid, parse failed",
    "There is a version mismatch between GRAM components",
    "The RSL arguments parameter is invalid",
    "The RSL count parameter is invalid",
    "The RSL directory parameter is invalid",
    "The RSL dryrun parameter is invalid",
    "The RSL environment parameter is invalid",
    "The RSL executable parameter is invalid",
    "The RSL host_count parameter is invalid",
    "The RSL jobtype parameter is invalid",
    "The RSL maxtime parameter is invalid",
    "The RSL myjob parameter is invalid",
    "The RSL paradyn parameter is invalid",
    "The RSL project parameter is invalid",
    "The RSL queue parameter is invalid",
    "The RSL stderr parameter is invalid",
    "The RSL stdin parameter is invalid",
    "The RSL stdout parameter is invalid",
    "The job manager failed to locate an internal script",
    "The job manager failed on the system call pipe()",
    "The job manager failed on the system call fcntl()",
    "The job manager failed to create the temporary stdout filename",
    "The job manager failed to create the temporary stderr filename",
    "The job manager failed on the system call fork()",
    "unable to run the executable because of the file permissions",
    "The job manager failed to open stdout",
    "The job manager failed to open stderr",
    "Unable to open cache file to relocate the user proxy",
    "The job manager failed to open the cache"
};

const char *
globus_gram_client_error_string(int error_code)
{
    if (error_code < 0 || error_code >= GRAM_ERROR_LAST)
        return("Invalid error code");
    return(globus_l_gram_client_error_strings[error_code]);
} /* globus_gram_client_error_string() */
