.\"
.\" Copyright (c) 1999,2000 WU-FTPD Development Group. 
.\" All rights reserved.
.\" 
.\" Portions Copyright (c) 1980, 1985, 1988, 1989, 1990, 1991, 1993, 1994 
.\" The Regents of the University of California.  Portions Copyright (c) 
.\" 1993, 1994 Washington University in Saint Louis.  Portions Copyright 
.\" (c) 1996, 1998 Berkeley Software Design, Inc.  Portions Copyright (c) 
.\" 1998 Sendmail, Inc.  Portions Copyright (c) 1983, 1995, 1996, 1997 Eric 
.\" P. Allman.  Portions Copyright (c) 1989 Massachusetts Institute of 
.\" Technology.  Portions Copyright (c) 1997 Stan Barber.  Portions 
.\" Copyright (C) 1991, 1992, 1993, 1994, 1995, 1996, 1997 Free Software 
.\" Foundation, Inc.  Portions Copyright (c) 1997 Kent Landfield. 
.\"
.\" Use and distribution of this software and its source code are governed 
.\" by the terms and conditions of the WU-FTPD Software License ("LICENSE"). 
.\"
.\"     $Id$
.\"
.TH PRIVATEPW 8
.SH NAME
privatepw \- Change WU\-FTPD Group Access File Information
.SH SYNOPSIS
.B privatepw
[-c] [-f ftpgroups] [-g group] accessgroup
.P
.B privatepw
[-d] [-f ftpgroups] accessgroup
.P
.B privatepw
[-l] [-f ftpgroups] 
.P
.B privatepw
[-V] 

.SH DESCRIPTION
If a site supports the SITE GROUP and SITE GPASS commands it is necessary
to be able to add, delete and list enhanced access group information. The
.I privatepw
utility is used to update this information in the group access 
(aka, ftpgroups) file. This is meant as an administrative tool
and not to be run by the general user population. This command 
requires read/write permission to the appropriate ftpgroups file.

.SH BACKGROUND

After user logs in, the SITE GROUP and SITE GPASS commands
may be used to specify an enhanced access group and associated
password. If the group name and password are valid, the user
becomes (via setegid()) a member of the group list in the group
access file (specified by the _PATH_PRIVATE define in pathnames.h).
.P
The format of the group access file is: 
.P
access_group_name:encrypted_password:real_group_name 
.P
where access_group_name is an arbitrary (alphanumeric +
punctuation) string. encrypted_password is the password encrypted
via crypt(3), exactly like in /etc/passwd. real_group_name is the
name of a valid group listed in /etc/group. 

.SH OPTIONS
.TP
.I \-c
Create a new ftpgroups file.
.TP
.I \-d
Delete the specified accessgroup's information from the ftpgroups file.
.TP
.I \-g group
Set the real system group to the group specified.  This is valid
only when adding a new accessgroup or changing an existing accessgroup's
password.
.TP
.I \-f ftpgroups
Use the specified ftpgroups file for all updates.
.TP
.I \-l
List the contents of the appropriate ftpgroups file.
.TP
.I \-?
Display a simple help usage message.
.TP
The
.I \-V
option causes the program to display copyright and version information, then
terminate.
.SH "SEE ALSO"
ftpaccess(5)
.SH BUGS
None known.
