'\" t
.\"     Title: grid-proxy-destroy
.\"    Author: University of Chicago
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 04/25/2011
.\"    Manual: Globus Commands
.\"    Source: Globus Toolkit 5.0.2
.\"  Language: English
.\"
.TH "GRID\-PROXY\-DESTROY" "1" "04/25/2011" "Globus Toolkit 5.0.2" "Globus Commands"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
grid-proxy-destroy \- Destroy the default proxy certificate
.SH "SYNOPSIS"
.HP \w'\fBgrid\-proxy\-destroy\fR\ 'u
\fBgrid\-proxy\-destroy\fR [\-help] [\-usage] [\-version]
.HP \w'\fBgrid\-proxy\-destroy\fR\ 'u
\fBgrid\-proxy\-destroy\fR [\-debug] [\-dryrun] [\-default] [\-all] [\-\-] [FILENAME...]
.SH "DESCRIPTION"
.PP
The
\fBgrid\-proxy\-destroy\fR
program removes X\&.509 proxy files from the local filesystem\&. It overwrites the data in the files and removes the files from the filesystem\&. By default, it removes the current user\'s default proxy (either
/tmp/x509up_u\fIUID\fR
where
\fIUID\fR
is the current POSIX user id, or the file pointed to by the
\fBX509_USER_PROXY\fR
environment variable) unless a list of proxy file paths are included as part of the command line\&.
.PP
Use the
\-\-
command\-line option to separate a list of proxy paths from command line options if the proxy file begins with the
\-
character\&.
.PP
The full list of command\-line options to
\fBgrid\-proxy\-destroy\fR
are:
.PP
\fB\-help\fR, \fB\-usage\fR
.RS 4
Display the command\-line options to
\fBgrid\-proxy\-destroy\fR\&.
.RE
.PP
\fB\-version\fR
.RS 4
Display the version number of the
\fBgrid\-proxy\-destroy\fR
command
.RE
.PP
\fB\-debug\fR
.RS 4
Display verbose error messages\&.
.RE
.PP
\fB\-dryrun\fR
.RS 4
Do not remove the proxy, but display the path of the files that would have been removed, or the directory where they would have been removed from if the
\fB\-all\fR
command\-line option is used\&.
.RE
.PP
\fB\-default\fR
.RS 4
Remove the default proxy in addition to the files included on the command\-line\&. Only needed if other paths are included on the command\-line\&.
.RE
.PP
\fB\-all\fR
.RS 4
Remove the default proxy and all delegated proxies in the temporary file directory\&.
.RE
.SH "ENVIRONMENT VARIABLES"
.PP
The following environment variables affect the execution of
\fBgrid\-proxy\-destroy\fR:
.PP
\fBX509_USER_PROXY\fR
.RS 4
Path to the default user proxy\&.
.RE
.SH "SEE ALSO"
.PP
\fBgrid-proxy-init\fR(1),
\fBgrid-proxy-info\fR(1)
.SH "AUTHOR"
.PP
\fBUniversity of Chicago\fR
