'\" t
.\"     Title: grid-proxy-destroy
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/25/2014
.\"    Manual: Globus Toolkit
.\"    Source: University of Chicago
.\"  Language: English
.\"
.TH "GRID\-PROXY\-DESTROY" "1" "09/25/2014" "University of Chicago" "Globus Toolkit"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
grid-proxy-destroy \- Destroy the default proxy certificate
.SH "SYNOPSIS"
.sp
grid\-proxy\-destroy \-help | \-usage | \-version
.sp
grid\-proxy\-destroy [\-debug] [\-dryrun] [\-default] [\-\- FILENAME \&...]
.SH "DESCRIPTION"
.sp
The grid\-proxy\-destroy program removes X\&.509 proxy files from the local filesystem\&. It overwrites the data in the files and removes the files from the filesystem\&. By default, it removes the current user\(cqs default proxy (either /tmp/x509up_u\(cqUID\*(Aq where \fIUID\fR is the current POSIX user id, or the file pointed to by the X509_USER_PROXY environment variable) unless a list of proxy file paths are included as part of the command line\&.
.sp
Use the \fB\-\-\fR command\-line option to separate a list of proxy paths from command line options if the proxy file begins with the \fB\-\fR character\&.
.SH "OPTIONS"
.sp
The full list of command\-line options to \fBgrid\-proxy\-destroy\fR are:
.PP
\fB\-help, \-usage\fR
.RS 4
Display the command\-line options to
\fBgrid\-proxy\-destroy\fR\&.
.RE
.PP
\fB\-version\fR
.RS 4
Display the version number of the
\fBgrid\-proxy\-destroy\fR
command\&.
.RE
.PP
\fB\-debug\fR
.RS 4
Display verbose error messages\&.
.RE
.PP
\fB\-dryrun\fR
.RS 4
Do not remove the proxy, but display the path of the files that would have been removed, or the directory where they would have been removed from if the
\fI\-all\fR
command\-line option is used\&.
.RE
.PP
\fB\-default\fR
.RS 4
Remove the default proxy in addition to the files included on the command\-line\&. Only needed if other paths are included on the command\-line\&.
.RE
.PP
\fB\-all\fR
.RS 4
Remove the default proxy and all delegated proxies in the temporary file directory\&.
.RE
.SH "ENVIRONMENT"
.sp
The following environment variables affect the execution of grid\-proxy\-destroy:
.PP
\fBX509_USER_PROXY\fR
.RS 4
Path to the default user proxy\&.
.RE
.SH "SEE ALSO"
.sp
grid\-proxy\-init(1), grid\-proxy\-info(1)
.SH "AUTHOR"
.sp
Copyright \(co 1999\-2014 University of Chicago
