'\" t
.\"     Title: grid-proxy-info
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/25/2014
.\"    Manual: Globus Toolkit
.\"    Source: University of Chicago
.\"  Language: English
.\"
.TH "GRID\-PROXY\-INFO" "1" "09/25/2014" "University of Chicago" "Globus Toolkit"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
grid-proxy-info \- Display information about a proxy certificate
.SH "SYNOPSIS"
.sp
\fBgrid\-proxy\-info\fR \-help | \-usage | \-version
.sp
\fBgrid\-proxy\-info\fR \-e | \-exists [\-valid \fIHOURS:MINUTES\fR | \-v \fIHOURS:MINUTES\fR] [\-hours \fIHOURS\fR | \-h \fIHOURS\fR] [\-bits \fIBITS\fR | \-b \fIBITS\fR]
.sp
\fBgrid\-proxy\-info\fR [OPTIONS]
.SH "DESCRIPTION"
.sp
The \fBgrid\-proxy\-info\fR program extracts information from an X\&.509 proxy certificates, and optionally displays or returns an exit code based on that information\&.
.sp
The default mode of operation is to print the following facts about the current user\(cqs default proxy: subject, issuer, identity, type, strength, path, and time left\&. If the command\-line option \fI\-exists\fR or \fI\-e\fR is included in the command\-line, nothing is printed unless one of the print options is specified\&. Instead, \fBgrid\-proxy\-info\fR determines if a valid proxy exists and, if so, exits with the exit code 0; if a proxy does not exist or is not valid, \fBgrid\-proxy\-info\fR exits with the exit code 1\&. Additional validity criteria can be added by using the \fI\-valid\fR, \fI\-v\fR, \fI\-hours\fR, \fI\-h\fR, \fI\-bits\fR, or \fI\-b\fR command\-line options\&. If used, these options must occur \fBafter\fR the \fI\-e\fR or \fI\-exists\fR command\-line options\&. Those options are only valid if one of the \fI\-e\fR or \fI\-exists\fR command\-line options is used\&.
.SH "OPTIONS"
.sp
The complete set of command\-line options to \fBgrid\-proxy\-info\fR are:
.PP
\fB\-help, \-usage\fR
.RS 4
Display the command\-line options to
\fBgrid\-proxy\-info\fR\&.
.RE
.PP
\fB\-version\fR
.RS 4
Display the version number of the
\fBgrid\-proxy\-info\fR
command\&.
.RE
.PP
\fB\-debug\fR
.RS 4
Display verbose error messages\&.
.RE
.PP
\fB\-file \fR\fB\fIPROXYFILE\fR\fR\fB, \-f \fR\fB\fIPROXYFILE\fR\fR
.RS 4
Read the proxy located in the file
\fIPROXYFILE\fR
instead of using the default proxy\&.
.RE
.PP
\fB\-subject, \-s\fR
.RS 4
Display the proxy certificate\(cqs subject distinguished name\&.
.RE
.PP
\fB\-issuer, \-i\fR
.RS 4
Display the proxy certificate issuer\(cqs distinguished name\&.
.RE
.PP
\fB\-identity\fR
.RS 4
Display the proxy certificate\(cqs identity\&. For non\-independent proxies, the identity is the subject of the certificate which issued the first proxy in the proxy chain\&.
.RE
.PP
\fB\-type\fR
.RS 4
Display the type of proxy certificate\&. The type string includes the format ("legacy", "draft", or RFC 3280 compliant), identity type ("impersonation" or "independent"), and policy ("limited" or "full")\&. See
\fBgrid\-proxy\-init(1)\fR
for information about how to create different types of proxies\&.
.RE
.PP
\fB\-timeleft\fR
.RS 4
Display the number of seconds remaining until the proxy certificate expires\&.
.RE
.PP
\fB\-strength\fR
.RS 4
Display the strength (in bits) of the key associated with the proxy certificate\&.
.RE
.PP
\fB\-all\fR
.RS 4
Display the default information for the proxy when also using the
\fI\-e\fR
or
\fI\-exists\fR
command\-line option\&.
.RE
.PP
\fB\-text\fR
.RS 4
Display the proxy certificate contents to standard output, including policy information, issuer, public key, and modulus\&.
.RE
.PP
\fB\-path\fR
.RS 4
Display the path to the file containing the default proxy certificate\&.
.RE
.PP
\fB\-rfc2253\fR
.RS 4
Display distinguished names for the subject, issuer, and identity using the string representation described in RFC 2253, instead of the legacy format\&.
.RE
.PP
\fB\-exists, \-e\fR
.RS 4
Perform an existence and validity check for the proxy\&. If a valid proxy exists and matches the criteria described by other command\-line options (if any), exit with 0; otherwise, exit with 1\&. This option must be before other validity check predicate in the command\-line options\&. If this option is specified, the output of the default facts about the proxy is disabled\&. Use the
\fI\-all\fR
option to have the information displayed as well as the exit code set\&.
.RE
.PP
\fB\-valid \fR\fB\fIHOURS:MINUTES\fR\fR\fB, \-v \fR\fB\fIHOURS:MINUTES\fR\fR\fB, \-hours \fR\fB\fIHOURS\fR\fR\fB, \-h \fR\fB\fIHOURS\fR\fR
.RS 4
Check that the proxy certificate is valid for at least
\fIHOURS\fR
hours and
\fIMINUTES\fR
minutes\&. If it is not,
\fBgrid\-proxy\-info\fR
will exit with exit code
1\&.
.RE
.PP
\fB\-bits \fR\fB\fIBITS\fR\fR\fB, \-b \fR\fB\fIBITS\fR\fR
.RS 4
Check that the proxy certificate key strength is at least
\fIBITS\fR
bits\&.
.RE
.SH "ENVIRONMENT"
.sp
The following environment variables affect the execution of \fBgrid\-proxy\-info\fR:
.PP
\fBX509_USER_PROXY\fR
.RS 4
Path to the default user proxy\&.
.RE
.SH "SEE ALSO"
.sp
grid\-proxy\-init(1), grid\-proxy\-destroy(1)
.SH "AUTHOR"
.sp
Copyright \(co 1999\-2014 University of Chicago
