.TH globus-connect-multiuser-setup 8
.SH NAME
.P
globus-connect-multiuser-setup - Configure a MyProxy, OAuth, and GridFTP server and create a Globus endpoint

.SH SYNOPSIS
.HP
globus-connect-multiuser-setup [-h|--help]
.HP
globus-connect-multiuser-setup
.br
{-c FILENAME|--config-file=FILENAME}
.br
{-v|--verbose}
.br
{-r PATH|--root=PATH}
.br
{-s|--reset-endpoint}

.SH DESCRIPTION
.P
The
.B globus-connect-multiuser-setup
command combines the functionality of
.BR "globus-connect-multiuser-io-setup" ,
.BR "globus-connect-multiuser-id-setup" ,
and
.B "globus-connect-multiuser-web-setup"
to configure a system to act as a GridFTP server, MyProxy ID server, and OAuth
server. It also registers the GridFTP server as a Globus endpoint.
Depending on features enabled in the configuration file, this process will
include fetching a service credential from the Globus Connect CA, writing
GridFTP configuration files in the
.I /etc/gridftp.d/
directory, adding trusted
certificates to the GridFTP server's trust roots, restarting the GridFTP
server, enabling the GridFTP server to start at boot, and creating or modifying
an endpoint to point to this server.
.P
If the
.B "-s"
or
.B "--reset-endpoint"
command-line option is used,
.B globus-connect-multiuser-setup
removes all other GridFTP servers associated with the endpoint before adding
this server if the endpoint already exists. Otherwise,
.B globus-connect-multiuser-setup
adds this server to the list of servers associated with the endpoint.
.P
If the 
.B "-r PATH"
or
.B "--root=PATH"
command-line option is used,
.B globus-connect-multiuser-setup
will write its GridFTP and MyProxy configuration files and certificates in a
subdirectory rooted at
.I PATH
instead of /. This means, for example, that
.B globus-connect-multiuser-setup
writes GridFTP configuration files in
.IB "PATH/etc/gridftp.d" .
.P
The following options are available:
.HP
-h, --help  Display help information
.HP
.B "-c FILENAME, --config-file=FILENAME"
.br
Use configuration file FILENAME instead of /etc/globus-connect-multiuser.conf
.HP
.B "-v, --verbose"
.br
Print more information about tasks
.HP
.B "-r PATH, --root=PATH"
.br
Add PATH as the directory prefix for the configuration files that
.B globus-connect-multiuser-io-setup
writes
.HP
.B "-s, --reset-endpoint"
.br
Remove all other GridFTP servers from this endpoint before adding this one

.SH ENVIRONMENT
.HP
.B GLOBUS_USER
.br
Default Globus user name
.HP
.B GLOBUS_PASSWORD
.br
Default Globus password

.SH SEE ALSO
.B globus-connect-multiuser-cleanup(8), globus-connect-multiuser-io-setup(8), globus-connect-multiuser-id-setup(8), globus-connect-multiuser-web-setup(8)
