.TH globus-connect-server-web-setup 8
.SH NAME
globus-connect-server-web-setup - Configure a MyProxy OAuth server to work with Globus

.SH SYNOPSIS
.HP
globus-connect-server-web-setup [-h|--help]
.HP
globus-connect-server-web-setup
.br
{-c FILENAME|--config-file=FILENAME}
.br
{-v|--verbose}
.br
{-r PATH|--root=PATH}

.SH DESCRIPTION
.P
The
.B globus-connect-server-web-setup
command generates a web configuration to run the MyProxy OAuth service in an
apache web server based on the globus-connect-server configuration file,
restarts the web server, and registers the Globus as a client to the
MyProxy server.
.P
If the
.B "-r PATH"
or
.B "--root=PATH" command-line option is used,
.B globus-connect-server-web-setup
will write its web configuration in a subdirectory rooted at
.I PATH
instead of /. This means, for example, that
.B globus-connect-server-web-setup
writes apache configuration files in
.I PATH/etc/apache2
or
.IR "PATH/etc/httpd/" .
.P
The following options are available:
.HP
.B -h, --help
.br Display help information
.HP
.B "-c FILENAME, --config-file=FILENAME"
.br
Use configuration file
.I FILENAME
instead of
.I /etc/globus-connect-server.conf
.HP
.B "-v, --verbose"
.br
Print more information about tasks
.HP
.B "-r PATH, --root=PATH"
.br
Add
.I PATH
as the directory prefix for the configuration files that
.B globus-connect-server-web-setup
writes

.SH ENVIRONMENT
.HP
.B GLOBUS_USER
.br
Default Globus user name
.HP
.B GLOBUS_PASSWORD
.br
Default Globus password

.SH "SEE ALSO"
.B globus-connect-server-web-cleanup(8)
