#!/bin/sh

if test "X${GT_PROXY_MODE}" = "Xold" ; then
    if echo $@ | egrep -e '^-new' -e '\ -new' > /dev/null 2>&1 ; then
        ARGS=`echo $@ | sed -e 's/\ -new//g' -e 's/^-new//g'`
        grid-proxy-init-bin $ARGS
    else
        grid-proxy-init-bin -old $@
    fi
else
    ARGS=`echo $@ | sed -e 's/\ -new//g' -e 's/^-new//g'`
    grid-proxy-init-bin $ARGS
fi

exit $?
