#!/bin/sh

# 
# Copyright 1999-2006 University of Chicago
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 


#
# Inspired by Keith Thompson <kst@sdsc.edu>'s wrapper
# http://bugzilla.globus.org/bugzilla/attachment.cgi?id=299&action=view
#


ARGS=''
BINDIR="${GLOBUS_LOCATION}/bin"

if test "X${GT_PROXY_MODE}" = "Xold" ; then
    STYLE='old'
else
    STYLE='new'
fi

for ARG in "$@" ; do
    case "$ARG" in
	-help)
            if test "X${GT_PROXY_MODE}" = "Xold" ; then
                ${BINDIR}/grid-proxy-init-bin -help 2>&1 | \
                    sed -e 's/grid-proxy-init-bin/grid-proxy-init/' \
                        -e '/-old/s/$/ (default)/' \
		        -e '/-old/a\
    -new                      Creates a new-style globus proxy' 1>&2
            else
                ${BINDIR}/grid-proxy-init-bin -help 2>&1 | \
                    sed -e 's/grid-proxy-init-bin/grid-proxy-init/' \
                        -e '/-old/a\
    -new                      Creates a new-style globus proxy (default)' 1>&2
            fi
	    exit 0
	    ;;
	-old)
	    STYLE=old
	    ;;
	-new)
	    STYLE=new
	    ;;
	*)
	    ARGS="$ARGS $ARG"
	    ;;
    esac
done

if [ $STYLE = 'old' ] ; then
    ${BINDIR}/grid-proxy-init-bin -old $ARGS
else
    ${BINDIR}/grid-proxy-init-bin $ARGS
fi

