AC_DEFUN(LAC_GLUNIX_PROGS,
[
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_GLURUN, glurun, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_GLUSTAT, glustat, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_PRINTENV, printenv, $1)
]
)

