AC_DEFUN(LAC_GRD_PROGS,
[
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_QDEL, qdel, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_QSTAT, qstat, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_QSUB, qsub, $1)

    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_QSELECT, qselect, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_QHOST, qhost, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_QCONF, qconf, $1)
]
)
