AC_DEFUN(LAC_LSF_PROGS,
[
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_BJOBS, bjobs, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_BKILL, bkill, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_BQUEUES, bqueues, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_BSUB, bsub, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_LSHOSTS, lshosts, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_LSLOAD, lsload, $1)

    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_MPIRUN, mpirun, $1)
]
)
