AC_DEFUN(LAC_PRUN_PROGS,
[
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_PKILL, pkill, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_POOL, pool, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_PRESERVE, preserve, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_PRUN, prun, $1)
    GLOBUS_GRAM_JOB_MANAGER_PATH_PROG(GLOBUS_GRAM_JOB_MANAGER_PS, ps, $1)
]
)
