#! /bin/sh

. $GLOBUS_LOCATION/libexec/globus-sh-tools.sh

GPATH=$GPT_LOCATION

if [ "$GPATH" = "" ]; then
    GPATH=$GLOBUS_LOCATION
fi

if [ "$GPATH" = "" ]; then
    echo "GPT_LOCATION or GLOBUS_LOCATION needs to be set before running this script."
fi

#
cp -f ./setup-globus-gram-scalability-tests.pl ${GLOBUS_LOCATION}/setup/globus/
#

$GLOBUS_SH_PERL -I${GPATH}/lib/perl ${GLOBUS_LOCATION}/setup/globus/setup-globus-gram-scalability-tests.pl "$@"
