283a284,297
> do_irix-shared:
> 	libs='-L. ${SHLIBDEPS}'; for i in ${SHLIBDIRS}; do \
> 	rm -f lib$$i.so \
> 		lib$$i.so.${SHLIB_MAJOR} \
> 		lib$$i.so.${SHLIB_MAJOR}.${SHLIB_MINOR}; \
> 	( set -x; ${CC}  -shared -all -o lib$$i.so.${SHLIB_MAJOR}.${SHLIB_MINOR} \
> 	lib$$i.a $$libs ${EX_LIBS} -lc ) || exit 1; \
> 	libs="$$libs -L. -l$$i"; \
> 	ln -s lib$$i.so.${SHLIB_MAJOR}.${SHLIB_MINOR} \
> 	lib$$i.so.${SHLIB_MAJOR}; \
> 	ln -s lib$$i.so.${SHLIB_MAJOR} lib$$i.so; \
> 	done
> 
> 
