#!/bin/sh
#

source ./scripts/version.sh

if [ ! -e work/sources/ ]; then
    mkdir -p work/sources/
fi

cp ../packages-harvest/gsi_openssh-$VERSION-src.tar.gz ./work/sources/
cp ../packages-harvest/gsi_openssh_setup-$VERSION-src.tar.gz ./work/sources/
