#!/bin/sh
#

source ./scripts/version.sh

if [ ! -e work/sources/ ]; then
    mkdir -p work/sources/
fi

dir="."
if [ -d ../packages-harvest/ ]; then
  dir="../packages-harvest"
fi

cp $dir/gsi_openssh-$VERSION-src.tar.gz ./work/sources/
cp $dir/gsi_openssh_setup-$VERSION-src.tar.gz ./work/sources/
