#!/bin/sh
#
# Usage:
#
#   1) Run the src-bundle creation script:
#
#        ./make-src-bundle
#

source ./scripts/version.sh

NAME="gsi_openssh_bundle-$VERSION-src.tar.gz"
XML="gsi_openssh_bundle-src.xml"

cp scripts/$XML work/

cd work/
$GPT_LOCATION/sbin/gpt-bundle -nodeps -nosetups -srcdir=sources/ -output=$NAME -bv=$VERSION -xml=$XML
mv $NAME ../
cd ../
