#!/bin/sh
#

source ./scripts/version.sh

NAME="gsi_openssh_bundle-$VERSION-src.tar.gz"

cd work/
$GPT_LOCATION/sbin/gpt-bundle -nodeps -srcdir=sources/ -output=$NAME gsi_openssh gsi_openssh_setup
mv sources/gsi_openssh_bundle-$VERSION-src_src.tar.gz ../$NAME
cd ../
