#! /bin/sh

# 
# Copyright 1999-2006 University of Chicago
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 


. $GLOBUS_LOCATION/libexec/globus-sh-tools.sh

GPATH=$GPT_LOCATION

if [ "$GPATH" = "" ]; then
    GPATH=$GLOBUS_LOCATION
fi

if [ "$GPATH" = "" ]; then
    echo "GPT_LOCATION or GLOBUS_LOCATION needs to be set before running this script."
fi

$GLOBUS_SH_PERL -I${GPATH}/lib/perl ${GLOBUS_LOCATION}/setup/globus/setup-globus-gaa-authz-callout-message.pl "$@"

exit 0
