'\" t
.\"     Title: globus-job-get-output-helper
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/18/2010
.\"    Manual: GRAM5 Commands
.\"    Source: University of Chicago
.\"  Language: English
.\"
.TH "GLOBUS\-JOB\-GET\-OU" "1" "03/18/2010" "University of Chicago" "GRAM5 Commands"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-job-get-output-helper \- Display the output or error stream from a GRAM job
.SH "SYNOPSIS"
.HP \w'\fBglobus\-job\-get\-output\-helper\fR\ 'u
\fBglobus\-job\-get\-output\-helper\fR 
.HP \w'\ 'u
\fITAG\fR \fIJOBID\fR {\fIstdout\fR | \fIstderr\fR} {no | \fILINES\fR} {no | \fILINES\fR} \fIURL\fR
.HP \w'\fBglobus\-job\-get\-output\-helper\fR\ 'u
\fBglobus\-job\-get\-output\-helper\fR [\-help] [\-h] [\-usage]
.SH "DESCRIPTION"
.PP
The
\fBglobus\-job\-get\-output\-helper\fR
program is an internal interface used by the
\fBglobus\-job\-get\-output\fR
program to copy output back to a GASS server\&. This program is submitted via the
\fBglobusrun\fR
command and executes
\fBglobus\-url\-copy\fR
to transfer the data\&.
.PP
The invocation to this command is created in the RSL arguments by the
\fBglobus\-job\-get\-output\fR
program\&. The arguments are positional and may change in future releases\&. Their meaning is
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
GASS cache tag for the output file
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
GRAM job id
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Stream to transfer (stdout or stderr)
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Number of lines to include (from the end of the file) for one time processing or
no
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
Number of lines to include (from the end of the file) for tail \-f processing or literal
no
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 6.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  6." 4.2
.\}
GASS server URL to send the data to
.RE
.sp
.RE
.SH "OPTIONS"
.PP
The full set of options to
\fBglobus\-job\-get\-output\-helper\fR
are:
.PP
\fB\-help\fR, \fB\-h\fR, \fB\-usage\fR
.RS 4
Display a help message to standard output and exit\&.
.RE
.SH "ENVIRONMENT"
.PP
If the following variables affect the execution of
\fBglobus\-job\-get\-output\-helper\fR\&.
.PP
\fBX509_USER_PROXY\fR
.RS 4
Path to proxy credential\&.
.RE
.PP
\fBX509_CERT_DIR\fR
.RS 4
Path to trusted certificate directory\&.
.RE
