'\" t
.\"     Title: globus-job-get-output-helper
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/08/2016
.\"    Manual: Globus Toolkit Manual
.\"    Source: Globus Toolkit 6
.\"  Language: English
.\"
.TH "GLOBUS\-JOB\-GET\-OU" "1" "09/08/2016" "Globus Toolkit 6" "Globus Toolkit Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-job-get-output-helper \- Display the output or error stream from a GRAM job
.SH "SYNOPSIS"
.sp
\fBglobus\-job\-get\-output\-helper\fR \fITAG\fR \fIJOBID\fR { \fIstdout\fR | \fIstderr\fR } { no | \fILINES\fR } { no | \fILINES\fR } URL
.sp
\fBglobus\-job\-get\-output\-helper\fR \-help | \-h | \-usage
.SH "DESCRIPTION"
.sp
The \fBglobus\-job\-get\-output\-helper\fR program is an internal interface used by the \fBglobus\-job\-get\-output\fR program to copy output back to a GASS server\&. This program is submitted via the \fBglobusrun\fR command and executes \fBglobus\-url\-copy\fR to transfer the data\&.
.sp
The invocation to this command is created in the RSL arguments by the \fBglobus\-job\-get\-output\fR program\&. The arguments are positional and may change in future releases\&. Their meaning is
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
GASS cache tag for the output file
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
GRAM job id
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Stream to transfer (stdout or stderr)
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Number of lines to include (from the end of the file) for one time processing or
no
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
Number of lines to include (from the end of the file) for tail \-f processing or literal
no
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 6.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  6." 4.2
.\}
GASS server URL to send the data to
.RE
.SH "OPTIONS"
.sp
The full set of options to \fBglobus\-job\-get\-output\-helper\fR are:
.PP
\fB\-help, \-h, \-usage\fR
.RS 4
Display a help message to standard output and exit\&.
.RE
.SH "ENVIRONMENT"
.sp
The following variables affect the execution of \fBglobus\-job\-get\-output\-helper\fR\&.
.PP
\fBX509_USER_PROXY\fR
.RS 4
Path to proxy credential\&.
.RE
.PP
\fBX509_CERT_DIR\fR
.RS 4
Path to trusted certificate directory\&.
.RE
.SH "AUTHOR"
.sp
Copyright \(co 1999\-2014 University of Chicago
