.TH globus-url-sync 1 "23 Feb 2010"
.SH NAME
globus-url-sync \- URL Synchronization
.SH SYNOPSIS
.B globus-url-sync
[-help | -usage] [-version] [-d | -v] [-c] [-m] [-s] [-t] <sourceURL> <destURL>
.SH SUMMARY
The program
.B globus-url-sync
compares two endpoints, using GridFTP, and prints a list of GSI file transfers that should be performed using 
.B globus-url-copy.
.SH OPTIONS
.TP
.B -help | -usage
Print help text.
.TP
.B -version
Print the version of this program.
.TP
.B -d | -debug | -v | -verbose
Print additional detail.
.TP
.B  -c | -connection-caching-off
Disable GridFTP client connection caching.
.B  -f | -full-file-pathname
Output full file pathnames (when recursive directory copy is not in use)."
.TP
.B -m | -modify
Compare files by last modified timestamp.
.TP
.B -s | -size
Compare files by size.
.SH DESCRIPTION
The current implementation of 
.B globus-url-sync
supports very basic features for directory synchronization.  It includes comparators 
for existence checks, file size checks, modification timestamp checks, but not 
checksum comparison.
.sp
URL scheme(s) supported:
.sp
.B gsiftp
.nf
    For example:
      File name, absolute path: "gsiftp://myhost.edu//tmp/file1"
                                "gsiftp://myhost.edu/~/file1"
      File name, relative path: "gsiftp://myhost.edu/file1"
      Directory, absolute path: "gsiftp://myhost.edu//tmp/dir1/"
.fi
.sp
.B sshftp
.nf
    For example:
      File name, absolute path: "sshftp://myhost.edu//tmp/file1"
                                "sshftp://myhost.edu/~/file1"
      File name, relative path: "sshftp://myhost.edu/file1"
      Directory, absolute path: "sshftp://myhost.edu//tmp/dir1/"
.fi
.SH Suggested Usage (shell script)
.nf
    #!/bin/bash

    globus-url-sync $1 $2 |
    while read line 
    do
      globus-url-copy -r -cd $line
    done

    exit 0
.fi
.SH BUGS
This is an early version of 
.B globus-url-sync.
In the event that unexpected results are returned, please re-run the command with the 
.B -verbose 
option.
.P
.B Known limitations:
.P
If the source directory hierarchy contains directories not present in the destination directory hierarchy, 
.B globus-url-copy 
must be invoked with the 
.B -cd 
(create directory) option.
.P 1
Empty directories, anywhere in the source directory hierarchy, are not currently handled, and will not be mentioned in the list of files to be transferred using 
.B globus-url-copy.
.P 1
Performance may be slow until it's been optimized to take advantage of
some new GridFTP features.
.P 1
The
.B -modify 
option:
.nf
  - Timezones are not taken into account.
  - Timestamps are matched exactly, so files on systems that are not 
    time-synchronized will never match.
  - In the future an inexact matching feature may be added.
.fi
.P 1
Authentication errors may be erroneously be reported as though a file is missing.
.P 1
Order of options does not currently effect order in which matching criteria are evaluated.
.P 1
Man-page for globus-url-sync is not automatically installed as part of the build process.
