# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






SHELL = /bin/sh

srcdir = .
top_srcdir = ../..
prefix = $(GLOBUS_LOCATION)
exec_prefix = $(GLOBUS_LOCATION)

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/globus_xio
pkglibdir = $(libdir)/globus_xio
pkgincludedir = $(includedir)/globus_xio

top_builddir = ../..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = @host_alias@
host_triplet = @host@
AR = /usr/bin/ar
ARFLAGS = ruv
AS = @AS@
CC = /usr/bin/gcc
CFLAGS = -g   -Wall
CPP = /usr/bin/gcc -E
CPPFLAGS =  -I/home/wellner/dev/globus/INSTALL/include -I/home/wellner/dev/globus/INSTALL/include/gcc32dbg
CROSS = no
CXX = /usr/bin/c++
CXXCPP = /usr/bin/c++ -E
CXXFLAGS = -g  
DIRT_BRANCH_ID = 38
DIRT_TIMESTAMP = 1055794395
DLLTOOL = @DLLTOOL@
DOT = 
DOXYFILE = Doxyfile
DOXYGEN = 
EXEEXT = 
F77 = 
F77FLAGS =  
F90 = 
F90FLAGS =  
FILELIST_FILE = /home/wellner/dev/globus/xio/src/pkgdata/master.filelist
GLOBUS_FLAVOR_NAME = gcc32dbg
GPT_CFLAGS =  -D_FILE_OFFSET_BITS=64 
GPT_CONFIG_CFLAGS =  -D_FILE_OFFSET_BITS=64 
GPT_CONFIG_INCLUDES =  
GPT_CONFIG_LIBS =  -ldl 
GPT_CONFIG_PKG_LIBS =  -lgssapi_error_gcc32dbg -lglobus_gss_assist_gcc32dbg -lglobus_gssapi_gsi_gcc32dbg -lglobus_gsi_proxy_core_gcc32dbg -lglobus_gsi_credential_gcc32dbg -lglobus_gsi_callback_gcc32dbg -lglobus_oldgaa_gcc32dbg -lglobus_gsi_cert_utils_gcc32dbg -lglobus_gsi_sysconfig_gcc32dbg -lglobus_openssl_error_gcc32dbg -lglobus_openssl_gcc32dbg -lglobus_common_gcc32dbg -lglobus_proxy_ssl_gcc32dbg -lssl_gcc32dbg -lcrypto_gcc32dbg 
GPT_EXTERNAL_INCLUDES = 
GPT_EXTERNAL_LIBS = 
GPT_INCLUDES = -I/home/wellner/dev/globus/INSTALL/include/gcc32dbg  
GPT_LDFLAGS =  -L/home/wellner/dev/globus/INSTALL/lib 
GPT_LIBS =  -lgssapi_error_gcc32dbg -lglobus_gss_assist_gcc32dbg -lglobus_gssapi_gsi_gcc32dbg -lglobus_gsi_proxy_core_gcc32dbg -lglobus_gsi_credential_gcc32dbg -lglobus_gsi_callback_gcc32dbg -lglobus_oldgaa_gcc32dbg -lglobus_gsi_cert_utils_gcc32dbg -lglobus_gsi_sysconfig_gcc32dbg -lglobus_openssl_error_gcc32dbg -lglobus_openssl_gcc32dbg -lglobus_common_gcc32dbg -lglobus_proxy_ssl_gcc32dbg -lssl_gcc32dbg -lcrypto_gcc32dbg   -ldl 
GPT_LIB_LINKS =  -lgssapi_error_gcc32dbg -lglobus_gss_assist_gcc32dbg -lglobus_gssapi_gsi_gcc32dbg -lglobus_gsi_proxy_core_gcc32dbg -lglobus_gsi_credential_gcc32dbg -lglobus_gsi_callback_gcc32dbg -lglobus_oldgaa_gcc32dbg -lglobus_gsi_cert_utils_gcc32dbg -lglobus_gsi_sysconfig_gcc32dbg -lglobus_openssl_error_gcc32dbg -lglobus_openssl_gcc32dbg -lglobus_common_gcc32dbg -lglobus_proxy_ssl_gcc32dbg -lssl_gcc32dbg -lcrypto_gcc32dbg   -ldl 
GPT_LINKTYPE = shared
GPT_LOCATION = /home/wellner/dev/globus/INSTALL
GPT_MAJOR_VERSION = 0
GPT_MINOR_VERSION = 1
GPT_PGM_LINKS =  -lgssapi_error_gcc32dbg -lglobus_gss_assist_gcc32dbg -lglobus_gssapi_gsi_gcc32dbg -lglobus_gsi_proxy_core_gcc32dbg -lglobus_gsi_credential_gcc32dbg -lglobus_gsi_callback_gcc32dbg -lglobus_oldgaa_gcc32dbg -lglobus_gsi_cert_utils_gcc32dbg -lglobus_gsi_sysconfig_gcc32dbg -lglobus_openssl_error_gcc32dbg -lglobus_openssl_gcc32dbg -lglobus_common_gcc32dbg -lglobus_proxy_ssl_gcc32dbg -lssl_gcc32dbg -lcrypto_gcc32dbg   -ldl 
GPT_PKG_CFLAGS = 
HAVE_DOT = 
INSURE = 
LD = /usr/bin/gcc
LDFLAGS = -L/home/wellner/dev/globus/INSTALL/lib 
LIBS =  
LIBTOOL = $(SHELL) $(GLOBUS_LOCATION)/sbin/libtool-$(GLOBUS_FLAVOR_NAME)
LN_S = 
MAINT = #
MAKEINFO = makeinfo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = globus_xio
PERL = /usr/bin/perl
RANLIB = /usr/bin/ranlib
VERSION = 0.1
XIO_BUILTIN_DIRS =  builtins/bounce builtins/debug builtins/file builtins/gsi builtins/gssapi_ftp builtins/null builtins/null_pass builtins/http builtins/tcp builtins/test builtins/udp builtins/verify
XIO_BUILTIN_HOOKS_DEC =   globus_i_xio_bounce_hook , globus_i_xio_debug_hook , globus_i_xio_file_hook , globus_i_xio_gsi_hook , globus_i_xio_gssapi_ftp_hook , globus_i_xio_null_hook , globus_i_xio_null_pass_hook , globus_i_xio_smtp_hook , globus_i_xio_http_hook ,globus_i_xio_tcp_hook , globus_i_xio_test_hook , globus_i_xio_udp_hook , globus_i_xio_verify_hook
XIO_BUILTIN_HOOKS_DEF =   &globus_i_xio_bounce_hook , &globus_i_xio_debug_hook , &globus_i_xio_file_hook , &globus_i_xio_gsi_hook , &globus_i_xio_gssapi_ftp_hook , &globus_i_xio_null_hook , &globus_i_xio_null_pass_hook , &globus_i_xio_smtp_hook , &globus_i_xio_http_hook , &globus_i_xio_tcp_hook , &globus_i_xio_test_hook , &globus_i_xio_udp_hook , &globus_i_xio_verify_hook
XIO_BUILTIN_LIBS =  builtins/bounce/libglobus_xio_bounce_driver_gcc32dbg.la builtins/debug/libglobus_xio_debug_driver_gcc32dbg.la builtins/file/libglobus_xio_file_driver_gcc32dbg.la builtins/gsi/libglobus_xio_gsi_driver_gcc32dbg.la builtins/gssapi_ftp/libglobus_xio_gssapi_ftp_driver_gcc32dbg.la builtins/null/libglobus_xio_null_driver_gcc32dbg.la builtins/null_pass/libglobus_xio_null_pass_driver_gcc32dbg.la builtins/smtp/libglobus_xio_smtp_driver_gcc32dbg.la builtins/tcp/libglobus_xio_tcp_driver_gcc32dbg.la builtins/test/libglobus_xio_test_driver_gcc32dbg.la builtins/udp/libglobus_xio_udp_driver_gcc32dbg.la builtins/verify/libglobus_xio_verify_driver_gcc32dbg.la
builddir = /home/wellner/dev/globus/xio/src
cross_compiling = no
lac_doxygen_examples = 
lac_doxygen_file_patterns = 
lac_doxygen_installdox = 
lac_doxygen_internal_tagfiles = 
lac_doxygen_output_tagfile = 
lac_doxygen_predefines = 
lac_doxygen_project = 
lac_doxygen_srcdirs = 
lac_doxygen_tagfiles = 

setupdir = $(GLOBUS_LOCATION)/setup/globus

testdir = $(GLOBUS_LOCATION)/test/$(PACKAGE)

scriptsysconfdir = $(GLOBUS_LOCATION)/etc

flavorincludedir = $(GLOBUS_LOCATION)/include/$(GLOBUS_FLAVOR_NAME)

pkgdir = $(GLOBUS_LOCATION)/etc/globus_packages/$(PACKAGE)

aclocaldir = $(GLOBUS_LOCATION)/share/globus_aclocal

amdirdir = $(GLOBUS_LOCATION)/share/globus_amdir

doxygendir = $(GLOBUS_LOCATION)/share/doxygen

docdir = $(GLOBUS_LOCATION)/share/doc

LINK_BAK = orig
AUTOMAKE_OPTIONS = no-dependencies

Sources =      globus_xio_http.c


flavorinclude_HEADERS =      globus_xio_http.h


noinst_LTLIBRARIES = libglobus_xio_http_driver_$(GLOBUS_FLAVOR_NAME).la 

INCLUDES = -I$(top_srcdir) $(GPT_INCLUDES)

libglobus_xio_http_driver___GLOBUS_FLAVOR_NAME__la_SOURCES = $(Sources)
libglobus_xio_http_driver___GLOBUS_FLAVOR_NAME__la_LDFLAGS = $(GPT_LDFLAGS)
libglobus_xio_http_driver___GLOBUS_FLAVOR_NAME__la_LIBADD = $(GPT_LIB_LINKS)

EXTRA_DIST =  bootstrap         globus_automake_pre         globus_automake_post         globus_automake_pre_top         globus_automake_post_top 	dirt.sh

mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(noinst_LTLIBRARIES)


DEFS =  -DPACKAGE=\"globus_xio\" -DVERSION=\"0.1\"  -I. -I$(srcdir) 
libglobus_xio_http_driver___GLOBUS_FLAVOR_NAME__la_DEPENDENCIES = 
libglobus_xio_http_driver___GLOBUS_FLAVOR_NAME__la_OBJECTS =  \
globus_xio_http.lo
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
HEADERS =  $(flavorinclude_HEADERS)

DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP_ENV = --best
SOURCES = $(libglobus_xio_http_driver___GLOBUS_FLAVOR_NAME__la_SOURCES)
OBJECTS = $(libglobus_xio_http_driver___GLOBUS_FLAVOR_NAME__la_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) $(top_srcdir)/globus_automake_pre $(top_srcdir)/globus_automake_pre_top $(top_srcdir)/globus_automake_post $(top_srcdir)/globus_automake_post_top
	cd $(top_srcdir) && $(AUTOMAKE) --foreign builtins/http/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-noinstLTLIBRARIES:

clean-noinstLTLIBRARIES:
	-test -z "$(noinst_LTLIBRARIES)" || rm -f $(noinst_LTLIBRARIES)

distclean-noinstLTLIBRARIES:

maintainer-clean-noinstLTLIBRARIES:

.c.o:
	$(COMPILE) -c $<

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libglobus_xio_http_driver_$(GLOBUS_FLAVOR_NAME).la: $(libglobus_xio_http_driver___GLOBUS_FLAVOR_NAME__la_OBJECTS) $(libglobus_xio_http_driver___GLOBUS_FLAVOR_NAME__la_DEPENDENCIES)
	$(LINK)  $(libglobus_xio_http_driver___GLOBUS_FLAVOR_NAME__la_LDFLAGS) $(libglobus_xio_http_driver___GLOBUS_FLAVOR_NAME__la_OBJECTS) $(libglobus_xio_http_driver___GLOBUS_FLAVOR_NAME__la_LIBADD) $(LIBS)

install-flavorincludeHEADERS: $(flavorinclude_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(flavorincludedir)
	@list='$(flavorinclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(flavorincludedir)/$$p"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(flavorincludedir)/$$p; \
	done

uninstall-flavorincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	list='$(flavorinclude_HEADERS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(flavorincludedir)/$$p; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = builtins/http

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) top_distdir="$(top_distdir)" distdir="$(distdir)" dist-hook
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am: install-flavorincludeHEADERS
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-flavorincludeHEADERS
uninstall: uninstall-am
all-am: Makefile $(LTLIBRARIES) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(flavorincludedir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-noinstLTLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-noinstLTLIBRARIES clean-compile clean-libtool \
		clean-tags clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-noinstLTLIBRARIES distclean-compile \
		distclean-libtool distclean-tags distclean-generic \
		clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-noinstLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-noinstLTLIBRARIES distclean-noinstLTLIBRARIES \
clean-noinstLTLIBRARIES maintainer-clean-noinstLTLIBRARIES \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool uninstall-flavorincludeHEADERS \
install-flavorincludeHEADERS tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir info-am info dvi-am dvi check \
check-am installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


dist-hook:
	$(GPT_LOCATION)/sbin/gpt_create_automake_rules --excludes=doxygen -srcdir=$(top_distdir)

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
link-am:

unlink-am:

filelist-am:

link: link-recursive link-flavorincludeHEADERS link-noinstLTLIBRARIES 
	:

unlink: unlink-recursive unlink-flavorincludeHEADERS unlink-noinstLTLIBRARIES 
	:

.PHONY: link unlink link-recursive unlink-recursive link-am unlink-am filelist-amlink-flavorincludeHEADERS unlink-flavorincludeHEADERS filelist-flavorincludeHEADERS link-noinstLTLIBRARIES unlink-noinstLTLIBRARIES filelist-noinstLTLIBRARIES 

filelist: filelist-recursive filelist-flavorincludeHEADERS filelist-noinstLTLIBRARIES 
	:




link-flavorincludeHEADERS: $(flavorinclude_HEADERS)
	@$(NORMAL_INSTALL)
	@$(mkinstalldirs) $(DESTDIR)$(flavorincludedir)
	@list='$(flavorinclude_HEADERS)'; for p in $$list; do \
	  	mydir=`pwd`; \
		target_p="$(DESTDIR)$(flavorincludedir)/$$p"; \
		cd $(srcdir); \
		fullsrcdir=`pwd`; \
		cd $$mydir; \
		if test -f "$$p"; then d="$$mydir/"; else d="$$fullsrcdir/"; fi; \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$d$$p $$target_p"; \
			ln -s $$d$$p $$target_p; \
		fi; \
	done

unlink-flavorincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(flavorinclude_HEADERS)'; for p in $$list; do \
		target_p="$(DESTDIR)$(flavorincludedir)/$$p"; \
		if test -h $$target_p; then \
			echo "rm $$target_p"; \
			rm $$target_p; \
		fi; \
		if test -f $$target_p.$(LINK_BAK); then \
			echo "mv $$target_p.$(LINK_BAK) $$target_p"; \
			mv $$target_p.$(LINK_BAK) $$target_p; \
		fi; \
	done

filelist-flavorincludeHEADERS:
	@list='$(flavorinclude_HEADERS)'; for p in $$list; do \
	  echo "$(DESTDIR)$(flavorincludedir)/$$p" >> $(FILELIST_FILE); \
	done





link-noinstLTLIBRARIES: $(noinst_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@$(mkinstalldirs) $(DESTDIR)$(noinstdir)
	@list='$(noinst_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	  	mydir=`pwd`; \
	    	target_p=$(DESTDIR)$(noinstdir)/$$p; \
		target_dir="$(DESTDIR)$(noinstdir)/"; \
		root_p=`echo $$p | sed "s,.la,,"`; \
		liblist=`ls $$mydir/.libs/$$root_p.s*`; for so in $$liblist; do \
			if test ! -h $$so; then \
				so_name=`echo $$so | sed "s,$$mydir/.libs/,,"`; \
				so_list="$$so_list $$so_name"; \
			fi; \
		done; \
		if test -f $$target_p -a ! -h $$target_p; then \
			echo "mv $$target_p $$target_p.$(LINK_BAK)"; \
			mv $$target_p $$target_p.$(LINK_BAK); \
			for so in $$so_list; do \
				echo "mv $$target_dir/$$so $$target_dir/$$so.$(LINK_BAK)"; \
				mv $$target_dir/$$so $$target_dir/$$so.$(LINK_BAK); \
			done; \
		fi; \
		if test ! -h $$target_p; then \
			echo "ln -s $$mydir/$$p $$target_p"; \
			ln -s $$mydir/$$p $$target_p; \
			for so in $$so_list; do \
				echo "ln -s $$mydir/.libs/$$so $$target_dir/$$so"; \
				ln -s $$mydir/.libs/$$so $$target_dir/$$so; \
			done; \
		fi; \
	  else :; fi; \
	done

unlink-noinstLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(noinst_LTLIBRARIES)'; for p in $$list; do \
	    	target_p=$(DESTDIR)$(noinstdir)/$$p; \
		target_dir="$(DESTDIR)$(noinstdir)/"; \
		root_p=`echo $$p | sed "s,.la,,"`; \
		so_list=`ls $$target_dir/$$root_p.s*.$(LINK_BAK)`; \
		if test -h $$target_p; then \
			echo "rm $$target_p"; \
			rm $$target_p; \
			for so in $$so_list; do \
				so_name=`echo $$so | sed "s,.$(LINK_BAK),,"`; \
				echo "rm $$so_name"; \
				rm $$so_name; \
			done; \
		fi; \
		if test -f $$target_p.$(LINK_BAK); then \
			echo "mv $$target_p.$(LINK_BAK) $$target_p"; \
			mv $$target_p.$(LINK_BAK) $$target_p; \
			for so in $$so_list; do \
				so_name=`echo $$so | sed "s,.$(LINK_BAK),,"`; \
				mv $$so_name.$(LINK_BAK) $$so_name; \
			done; \
		fi; \
	done

filelist-noinstLTLIBRARIES: $(noinst_LTLIBRARIES)
	@list='$(noinst_LTLIBRARIES)'; for p in $$list; do \
	  $(GPT_LOCATION)/sbin/gpt_get_lib_names $$p $(DESTDIR)$(noinstdir) >> $(FILELIST_FILE); \
	done


link-recursive unlink-recursive filelist-recursive:
	@set fnord $(MAKEFLAGS); amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

