#! /bin/sh

. ${GLOBUS_LOCATION}/libexec/globus-script-initializer

globus_source ${libexecdir}/globus-gram-protocol-constants.sh
globus_source ${libexecdir}/globus-sh-tools.sh
globus_source ${libexecdir}/globus-gram-job-manager-tools.sh

#
# Globus Job Manager prun/preserve interface script for killing jobs
# Author:               Alexander Adams (TU Delft)
# Last Modified:        9/8/98
#
#

################################################
# Site-specific settings
################################################
preserve=${GLOBUS_GRAM_JOB_MANAGER_PRESERVE-preserve}
pkill=${GLOBUS_SH_PKILL-pkill}
rm=${GLOBUS_SH_RM-rm}
awk=${GLOBUS_SH_AWK-awk}
################################################  

arg_file=$1
# check for the argument file if it does not exist
# then return with an error immediately.
if [ ! -f $arg_file ] ; then
   echo GRAM_SCRIPT_ERROR:$GLOBUS_GRAM_PROTOCOL_ERROR_BAD_SCRIPT_ARG_FILE
   exit 1
fi

# use the argument file to define all the arguments
. $arg_file

# if a logfile has been passed in then assume debug mode.
if [ $grami_logfile = "/dev/null" ] ; then
    DEBUG_ECHO=:
else
    DEBUG_ECHO=echo
fi

$DEBUG_ECHO "JM_SCRIPT: in gram_script_prun_rm" >> $grami_logfile

res_id=`echo ${grami_job_id} | ${awk} '-F:' '{print $1}'`
ps_id=`echo ${grami_job_id} | ${awk} '-F"' '{print $2}'`


$DEBUG_ECHO "JM_SCRIPT: executing ${pkill} ${grami_program}" >> $grami_logfile
${pkill} ${grami_program} > /dev/null

$DEBUG_ECHO "JM_SCRIPT: executing ${preserve} -c ${res_id} ">> $grami_logfile

${preserve} -c ${res_id} > /dev/null

prun_err_file="${local_tmpdir}/prun${res_id}.err"

$DEBUG_ECHO "JM_SCRIPT: removing prun error file ${prun_err_file}" >> $grami_logfile
${rm} -f $prun_err_file

# For now just hope for the best...
echo GRAM_SCRIPT_SUCCESS:999

$DEBUG_ECHO "JM_SCRIPT: exiting gram_script_prun_rm" >> $grami_logfile
