#! /bin/sh

. ${GLOBUS_LOCATION}/libexec/globus-script-initializer

globus_source ${libexecdir}/globus-gram-protocol-constants.sh
globus_source ${libexecdir}/globus-sh-tools.sh
globus_source ${libexecdir}/globus-gram-job-manager-tools.sh


llcancel=${GLOBUS_GRAM_JOB_MANAGER_LLCANCEL-llcancel}

arg_file=$1
# check for the argument file if it does not exist
# then return with an error immediately.
if [ ! -f $arg_file ] ; then
   echo GRAM_SCRIPT_ERROR:$GLOBUS_GRAM_PROTOCOL_ERROR_BAD_SCRIPT_ARG_FILE
   exit 1
fi

# use the argument file to define all the arguments
. $arg_file

# if a logfile has been passed in then assume debug mode.
if [ $grami_logfile = "/dev/null" ] ; then
    DEBUG_ECHO=:
else
    DEBUG_ECHO=echo
fi

$DEBUG_ECHO "GRAMI_JM: in easymcs_rm" >> $grami_logfile

$DEBUG_ECHO "GRAMI_JM: executing llcancel with job id "\
            "${grami_job_id}" >> $grami_logfile

${llcancel} ${grami_job_id}

# the job manager only cares about GRAM_SCRIPT_SUCCESS or
# GRAM_SCRIPT_ERROR from this script.  The value is inconsiquencial.
echo GRAM_SCRIPT_SUCCESS:999

$DEBUG_ECHO "GRAMI_JM: exiting easymcs_rm" >> $grami_logfile
