#! /bin/sh
#
# Signal an nswc job/mission.
#

. ${GLOBUS_LOCATION}/libexec/globus-script-initializer

globus_source ${libexecdir}/globus-gram-protocol-constants.sh
globus_source ${libexecdir}/globus-sh-tools.sh
globus_source ${libexecdir}/globus-gram-job-manager-tools.sh

kill=${GLOBUS_SH_KILL-kill}

########
# This is the directory where the proxy server will look for and this 
# script will place new mission signal files.
#
# Currently it must be *EDITTED BY HAND*
########
nswc_dir="/some/dir"

arg_file=$1
# check for the argument file if it does not exist
# then return with an error immediately.
if [ ! -f $arg_file ] ; then
   echo GRAM_SCRIPT_ERROR:$GLOBUS_GRAM_PROTOCOL_ERROR_BAD_SCRIPT_ARG_FILE
   exit 1
fi
 
signal_file=$2
# check for the signal file if it does not exist
# then return with an error immediately.
if [ ! -f $signal_file ] ; then
   echo GRAM_SCRIPT_ERROR:$GLOBUS_GRAM_PROTOCOL_ERROR_BAD_SCRIPT_ARG_FILE
   exit 1
fi

# use the argument file to define all the job arguments
. $arg_file
 
# use the signal file to define all the signal arguments
. $signal_file
 
if [ $grami_signal -eq $GLOBUS_GRAM_PROTOCOL_JOB_SIGNAL_CANCEL ] ; then
   ${kill} ${grami_job_id}
else
   mv ${signal_file} ${nswc_dir}
fi
 
# the job manager only cares about GRAM_SCRIPT_SUCCESS or
# GRAM_SCRIPT_ERROR from this script.  The value is inconsequential.
echo GRAM_SCRIPT_SUCCESS:999
