#! /bin/sh

. ${GLOBUS_LOCATION}/libexec/globus-script-initializer

globus_source ${libexecdir}/globus-gram-protocol-constants.sh
globus_source ${libexecdir}/globus-sh-tools.sh
globus_source ${libexecdir}/globus-gram-job-manager-tools.sh

condor_rm=${GLOBUS_GRAM_JOB_MANAGER_CONDOR_RM-condor_rm}
awk=${GLOBUS_SH_AWK-awk}
cut=${GLOBUS_SH_CUT-cut}
expr=${GLOBUS_SH_EXPR-expr}
grep=${GLOBUS_SH_GREP-grep}
rm=${GLOBUS_SH_RM-rm}
sort=${GLOBUS_SH_SORT-sort}
uniq=${GLOBUS_SH_UNIQ-uniq}
wc=${GLOBUS_SH_WC-wc}
sleep=${GLOBUS_SH_SLEEP-sleep}

arg_file=$1
# check for the argument file if it does not exist
# then return with an error immediately.
if [ ! -f $arg_file ] ; then
   echo GRAM_SCRIPT_ERROR:$GLOBUS_GRAM_PROTOCOL_ERROR_BAD_SCRIPT_ARG_FILE
   exit 1
fi

# use the argument file to define all the arguments
. $arg_file

# if a logfile has been passed in then assume debug mode.
if [ $grami_logfile = "/dev/null" ] ; then
    DEBUG_ECHO=:
else
    DEBUG_ECHO=echo
fi

grami_condor_ulog=${tmpdir}/condor_log.${grami_uniq_id}

$DEBUG_ECHO "JM_SCRIPT: in gram_script_condor_rm" >> $grami_logfile

$DEBUG_ECHO "JM_SCRIPT: executing condor_rm command with job id "\
            "${_job_id}" >> $grami_logfile

${condor_rm} ${grami_job_id} | ${awk} -F. '{print $1}' >> $grami_logfile
status=$?

if [ "${status}" = 0 ] ; then
#   the job manager only cares about GRAM_SCRIPT_SUCCESS or
#   GRAM_SCRIPT_ERROR from this script.  The value is inconsiquencial.
    echo GRAM_SCRIPT_SUCCESS:999
else
    echo GRAM_SCRIPT_ERROR:$GLOBUS_GRAM_PROTOCOL_ERROR_JOB_CANCEL_FAILED
fi

count=0

while [ $count -lt 15 ] ; do
    status=`${grep} -e '^005' -e '^013' ${grami_condor_ulog} | ${grep} -e ' ('${grami_job_id} | ${cut} -d' ' -f1,2 | ${sort} | ${uniq} | ${wc} -l`
    if [ $status -ge ${grami_count} ] ; then
       break
    fi
    count=`${expr} $count + 1`
    ${sleep} 1
done

${rm} ${grami_condor_ulog}

$DEBUG_ECHO "JM_SCRIPT: exiting gram_script_condor_rm" >> $grami_logfile
