#! /bin/sh
#
# Extract the ST (status) column from the condor_q output
# for our specific jobID.
#
# The Status field can contain one of the following strings:
#
# string  stands for          Globus context meaning
# --------------------------------------------------------------------
# U       Unexpanded (never been run)     PENDING
# R       Running          ACTIVE
# I       Idle (waiting for a machine to    ACTIVE? (need SUSPENDED)
#               execute on)
# C       Completed          DONE
# X       Removed          FAILED


. ${GLOBUS_LOCATION}/libexec/globus-script-initializer

globus_source ${libexecdir}/globus-gram-protocol-constants.sh
globus_source ${libexecdir}/globus-sh-tools.sh
globus_source ${libexecdir}/globus-gram-job-manager-tools.sh

awk=${GLOBUS_SH_AWK-awk}
cut=${GLOBUS_SH_CUT-cut}
grep=${GLOBUS_SH_GREP-grep}
rm=${GLOBUS_SH_RM-rm}
sort=${GLOBUS_SH_SORT-sort}
uniq=${GLOBUS_SH_UNIQ-uniq}
wc=${GLOBUS_SH_WC-wc}


arg_file=$1
# check for the argument file if it does not exist
# then return with an error immediately.
if [ ! -f $arg_file ] ; then
   echo GRAM_SCRIPT_ERROR:$GLOBUS_GRAM_PROTOCOL_ERROR_BAD_SCRIPT_ARG_FILE
   exit 1
fi


# use the argument file to define all the arguments.
# Of special interest here is the grami_job_id parameter.
. $arg_file


# if a logfile has been passed in then assume debug mode.
if [ $grami_logfile = "/dev/null" ] ; then
    DEBUG_ECHO=:
else
    DEBUG_ECHO=echo
fi


grami_condor_ulog=${tmpdir}/condor_log.${grami_uniq_id}


$DEBUG_ECHO "JM_SCRIPT: in gram_script_condor_poll" >> $grami_logfile


$DEBUG_ECHO "JM_SCRIPT: parsing condor log file ${grami_condor_ulog} "\
            "for job id ${grami_job_id}" >> $grami_logfile


status=`${grep} '^[0-9]* (0*'${grami_job_id} ${grami_condor_ulog} | ${cut} -d' ' -f1,2 | ${sort} | ${uniq}`


num_done=`echo "$status" | ${grep} '^005' | ${wc} -l`
num_run=`echo "$status" | ${grep} '^001' | ${wc} -l`
num_abort=`echo "$status" | ${grep} '^013' | ${wc} -l`


if [ ${num_abort} -gt 0 ] ; then
    gram_job_state=$GLOBUS_GRAM_PROTOCOL_JOB_STATE_FAILED
    ${rm} ${grami_condor_ulog}
elif [ ${num_done} -eq ${grami_count} ] ; then
    gram_job_state=$GLOBUS_GRAM_PROTOCOL_JOB_STATE_DONE
    ${rm} ${grami_condor_ulog}
elif [ ${num_done} -gt 0 ] || [ ${num_run} -gt 0 ] ; then
    gram_job_state=$GLOBUS_GRAM_PROTOCOL_JOB_STATE_ACTIVE
else
    gram_job_state=$GLOBUS_GRAM_PROTOCOL_JOB_STATE_PENDING
fi


$DEBUG_ECHO "JM_SCRIPT: returning success, job state: "\
            "${gram_job_state}" >> $grami_logfile


echo "GRAM_SCRIPT_SUCCESS:${gram_job_state}"


$DEBUG_ECHO "JM_SCRIPT: exiting gram_script_condor_poll" >> $grami_logfile
