#! /bin/sh

. ${GLOBUS_LOCATION}/libexec/globus-script-initializer

globus_source ${libexecdir}/globus-gram-protocol-constants.sh
globus_source ${libexecdir}/globus-sh-tools.sh
globus_source ${libexecdir}/globus-gram-job-manager-tools.sh

#
################################################
# Site-specific settings
################################################
ps=${GLOBUS_SH_PS-ps}
################################################

arg_file=$1
# check for the argument file if it does not exist
# then return with an error immediately.
if [ ! -f $arg_file ] ; then
   echo GRAM_SCRIPT_ERROR:$GLOBUS_GRAM_PROTOCOL_ERROR_BAD_SCRIPT_ARG_FILE
   exit 1
fi
 
# use the argument file to define all the arguments
. $arg_file
 
# if a logfile has been passed in then assume debug mode.
if [ ${grami_logfile} = "/dev/null" ] ; then
    DEBUG_ECHO=:
else
    DEBUG_ECHO=echo
fi

 
$DEBUG_ECHO "JM_SCRIPT: in nswc_status">> $grami_logfile

$DEBUG_ECHO ""                                            >> $grami_logfile
$DEBUG_ECHO ============================================  >> $grami_logfile
$DEBUG_ECHO "JM_SCRIPT: ====argument file contents===="   >> $grami_logfile
if [ "$DEBUG_ECHO" = "echo" ] ; then
   cat $arg_file                                          >> $grami_logfile
fi
$DEBUG_ECHO "JM_SCRIPT: ====argument file contents===="   >> $grami_logfile
$DEBUG_ECHO ""                                            >> $grami_logfile

${ps} -p ${grami_job_id}

if [ "$?" -eq "0" ]; then
     gram_job_state=$GLOBUS_GRAM_PROTOCOL_JOB_STATE_ACTIVE
else
     gram_job_state=$GLOBUS_GRAM_PROTOCOL_JOB_STATE_DONE
fi

echo "GRAM_SCRIPT_SUCCESS:${gram_job_state}"
$DEBUG_ECHO "returning success, job state: $gram_job_state" >> $grami_logfile
