#! /bin/sh
#
# cancel an nswc job/mission.
#

. ${GLOBUS_LOCATION}/libexec/globus-script-initializer

globus_source ${libexecdir}/globus-gram-protocol-constants.sh
globus_source ${libexecdir}/globus-sh-tools.sh
globus_source ${libexecdir}/globus-gram-job-manager-tools.sh


kill=${GLOBUS_SH_KILL-kill}

arg_file=$1
# check for the argument file if it does not exist
# then return with an error immediately.
if [ ! -f $arg_file ] ; then
   echo GRAM_SCRIPT_ERROR:$GLOBUS_GRAM_PROTOCOL_ERROR_BAD_SCRIPT_ARG_FILE
   exit 1
fi
 
# use the argument file to define all the job arguments
. $arg_file
 
${kill} ${grami_job_id}
 
# the job manager only cares about GRAM_SCRIPT_SUCCESS or
# GRAM_SCRIPT_ERROR from this script.  The value is inconsiquencial.
echo GRAM_SCRIPT_SUCCESS:999
