#! /bin/sh
#
# Signal a LoadLeveler job.
#

. ${GLOBUS_LOCATION}/libexec/globus-script-initializer

globus_source ${libexecdir}/globus-gram-protocol-constants.sh
globus_source ${libexecdir}/globus-sh-tools.sh
globus_source ${libexecdir}/globus-gram-job-manager-tools.sh

llcancel=${GLOBUS_GRAM_JOB_MANAGER_LLCANCEL-llcancel}

arg_file=$1
# check for the argument file if it does not exist
# then return with an error immediately.
if [ ! -f $arg_file ] ; then
   echo GRAM_SCRIPT_ERROR:$GLOBUS_GRAM_PROTOCOL_ERROR_BAD_SCRIPT_ARG_FILE
   exit 1
fi
 
# use the argument file to define all the arguments
. $arg_file
 
# if a logfile has been passed in then assume debug mode.
if [ $grami_logfile = "/dev/null" ] ; then
    DEBUG_ECHO=:
else
    DEBUG_ECHO=echo
fi
 
$DEBUG_ECHO "GRAMI_JMI: in loadleveler signal" >> $grami_logfile

#      signal types
# ----------------------
#    SIGNAL_CANCEL   = 1  ---->  supported
#    SIGNAL_SUSPEND  = 2  ---->  unsupported
#    SIGNAL_RESUME   = 3  ---->  unsupported
#    SIGNAL_PRIORITY = 4  ---->  unsupported
if [ $grami_signal -eq $GLOBUS_GRAM_PROTOCOL_JOB_SIGNAL_CANCEL ] ; then

   ${llcancel} ${grami_job_id}
#  on success the value is not used
   echo GRAM_SCRIPT_SUCCESS:999

else

   GRAM_SCRIPT_ERROR:$GLOBUS_GRAM_PROTOCOL_ERROR_UNKNOWN_SIGNAL_TYPE

fi
 
$DEBUG_ECHO "GRAMI_JMI: exiting loadleveler_signal" >> $grami_logfile
