#! /bin/sh

. ${GLOBUS_LOCATION}/libexec/globus-script-initializer

globus_source ${libexecdir}/globus-gram-protocol-constants.sh
globus_source ${libexecdir}/globus-sh-tools.sh
globus_source ${libexecdir}/globus-gram-job-manager-tools.sh


#
################################################
# Site-specific settings
################################################
################################################

arg_file=$1
# check for the argument file if it does not exist
# then return with an error immediately.
if [ ! -f $arg_file ] ; then
   echo GRAM_SCRIPT_ERROR:$GLOBUS_GRAM_PROTOCOL_ERROR_BAD_SCRIPT_ARG_FILE
   exit 1
fi
 
# use the argument file to define all the arguments
. $arg_file
 
# if a logfile has been passed in then assume debug mode.
if [ ${grami_logfile} = "/dev/null" ] ; then
    DEBUG_ECHO=:
else
    DEBUG_ECHO=echo
fi

 
$DEBUG_ECHO "JM_SCRIPT: in nswc_submit">> $grami_logfile

$DEBUG_ECHO ""                                            >> $grami_logfile
$DEBUG_ECHO ============================================  >> $grami_logfile
$DEBUG_ECHO "JM_SCRIPT: ====argument file contents===="   >> $grami_logfile
if [ "$DEBUG_ECHO" = "echo" ] ; then
   cat $arg_file                                          >> $grami_logfile
fi
$DEBUG_ECHO "JM_SCRIPT: ====argument file contents===="   >> $grami_logfile
$DEBUG_ECHO ""                                            >> $grami_logfile

if [ ! -z "${grami_env}" ] ; then
   eval set -- ${grami_env}
   x=0
   while [ "$#" -ne 0 ]; do
      if [ $x = 0 ] ; then
         save_variable=$1
         x=1
      else
         x=0
         eval ${save_variable}=$1; export ${save_variable};
      fi

      shift
   done
fi

grami_args=`eval echo ${grami_args}`

$grami_program $grami_args 1>$grami_stdout 2>$grami_stderr &

if [ "$?" -eq "0" ]; then
   job_id=$!
   echo "grami_job_id=$job_id" >> $arg_file
   echo "GRAM_SCRIPT_JOB_ID:$job_id"
   $DEBUG_ECHO "job submitted successfully!" >> $grami_logfile
   $DEBUG_ECHO "returning job state: 1" >> $grami_logfile
   echo "GRAM_SCRIPT_SUCCESS:$GLOBUS_GRAM_PROTOCOL_JOB_STATE_ACTIVE"
else
   $DEBUG_ECHO "job *NOT* submitted successfully!" >> $grami_logfile
   echo "GRAM_SCRIPT_ERROR:$GLOBUS_GRAM_PROTOCOL_ERROR_JOB_EXECUTION_FAILED"

   exit 1
fi
