.TH myproxy-admin-query 1 "2005-6-8" "NCSA" "MyProxy"
.SH NAME
myproxy-admin-query \- query MyProxy repository contents
.SH SYNOPSIS
.B myproxy-admin-query
[
.I options
]
.SH DESCRIPTION
The
.B myproxy-admin-query
command displays information about the credentials stored in the
MyProxy repository.
It can also be used to remove credentials from the repository.
It accesses the repository directly and must be run on the machine
where the
.BR myproxy-server (8)
is installed from the account that owns the repository.
.SH OPTIONS
.TP
.B -h, --help
Displays command usage text and exits.
.TP
.B -u, --usage
Displays command usage text and exits.
.TP
.B -v, --verbose
Enables verbose debugging output to the terminal.
.TP
.B -V, --version
Displays version information and exits.
.TP
.BI -l " name, " --username " name"
Return information on credentials for a single username.  By default,
the command returns information on all credentials for all usernames.
.TP
.BI -k " name, " --credname " name"
Return information on the credentials with the specified name.
.TP
.BI -e " hours, " --expiring_in " hours"
Return information on credentials with remaining lifetime less than the
specified number of hours.  For example, 
.BI -e " 0"
will return all expired credentials.
.TP
.BI -t " hours, " --time_left " hours"
Return information on credentials with remaining lifetime greater than the
specified number of hours.
.TP
.BI -s " dir, " --storage " dir"
Specifies the location of the credential storage directory.
The directory must be accessible only by the user running the 
.B myproxy-server
process for security reasons.  Default: /var/myproxy or $GLOBUS_LOCATION/var/myproxy
.TP
.B -r, --remove
Remove the credentials matching the query from the repository.
For example, 
.I myproxy-admin-query -e 0 -r
will remove all expired credentials from the repository.
.TP
.BI -L " 'msg', " --lock " 'msg'"
Places the credentials matching the query under an administrative
lock and specifies a message to be returned on access attempts.
Be sure to put the message in quotes so it is captured as one argument
to the command.
.TP
.B -U, --unlock
Removes any administrative locks for the credentials matching the query.
.SH "EXIT STATUS"
0 on success, >0 on error
.SH AUTHORS
Bill Baker,
Jim Basney,
Shiva Shankar Chetan,
Patrick Duda,
Jarek Gawor,
Monte Goode,
Daniel Kouril,
Zhenmin Li,
Jason Novotny,
Miroslav Ruda,
Benjamin Temko,
and Von Welch
.SH "SEE ALSO"
.BR myproxy-change-pass-phrase (1),
.BR myproxy-destroy (1),
.BR myproxy-init (1),
.BR myproxy-logon (1),
.BR myproxy-retrieve (1),
.BR myproxy-store (1),
.BR myproxy-server.config (5),
.BR myproxy-admin-adduser (8),
.BR myproxy-admin-change-pass (8),
.BR myproxy-admin-load-credential (8),
.BR myproxy-server (8)
