.TH myproxy-retrieve 1 "2005-12-2" "NCSA" "MyProxy"
.SH NAME
myproxy-retrieve \- retrieve an end-entity credential
.SH SYNOPSIS
.B myproxy-retrieve
[
.I options
]
.SH DESCRIPTION
The
.B myproxy-retrieve
command retrieves a credential directly from the
.BR myproxy-server (8)
that was previously stored using
.BR myproxy-init (1)
or
.BR myproxy-store (1).
Unlike 
.BR myproxy-logon (1),
this command transfers the private key in the repository over
the network (over a private channel).
To obtain a proxy credential, we recommend using
.BR myproxy-logon (1)
instead.
.PP
In the default mode, the command prompts for the 
pass phrase associated with the credential to be retrieved and
stores the retrieved credential in the standard location (
.I ~/.globus/usercert.pem
and
.IR ~/.globus/userkey.pem ).
You could then run
.B grid-proxy-init
to create a proxy credential from the retrieved credentials.
.SH OPTIONS
.TP
.B -h, --help
Displays command usage text and exits.
.TP
.B -u, --usage
Displays command usage text and exits.
.TP
.B -v, --verbose
Enables verbose debugging output to the terminal.
.TP
.B -V, --version
Displays version information and exits.
.TP
.BI -s " hostname, " --pshost " hostname"
Specifies the hostname of the myproxy-server.  This option is required
if the
.B MYPROXY_SERVER
environment variable is not defined.  If specified, this option
overrides the
.B MYPROXY_SERVER
environment variable.
.TP
.BI -p " port, " --psport " port"
Specifies the TCP port number of the
.BR myproxy-server (8).
Default: 7512
.TP
.B -l, --username
Specifies the MyProxy account under which the credential to retrieve is
stored.  By default, the command uses the value of the
.B LOGNAME
environment variable.
Use this option to specify a different account username on the MyProxy
server.
The MyProxy username need not correspond to a real Unix username.
.TP
.B -d, --dn_as_username
Use the certificate subject (DN) as the default username, instead
of the 
.B LOGNAME 
environment variable.  When used with the
.B -a
option, the certificate subject of the authorization credential is
used.  Otherwise, the certificate subject of the default credential is
used.
.TP
.BI -t " hours, " --proxy_lifetime " hours"
Specifies the lifetime of credentials retrieved from the
.BR myproxy-server (8)
using the stored credential.  The resulting lifetime is the shorter of
the requested lifetime and the lifetime specified when the credential
was stored using
.BR myproxy-init (1).
Default: 12 hours
.TP
.BI -c " filename, " --certfile " filename"
Specifies  the  filename  of  where the  certificate will be stored.
.TP
.BI -y " filename, " --keyfile " filename"
Specifies the filename of where the private  key will be stored.
.TP
.BI -a " file, " --authorization " file"
Use this option to
specify an existing, valid credential that you want to renew.
Renewing a credential generally requires two certificate-based
authentications.  The client authenticates with its identity, using
the credential in the standard location or specified by
.B X509_USER_PROXY
or
.B X509_USER_CERT
and
.B X509_USER_KEY
in addition to authenticating with the existing credential, in the
location specified by this option, that it wants to renew.
.TP
.BI -k " name, " --credname " name"
Specifies the name of the credential that is to be retrieved or renewed.
.TP
.B -S, --stdin_pass
By default, the command prompts for a passphrase and reads the
passphrase from the active tty.  When running the command
non-interactively, there may be no associated tty.  Specifying this
option tells the command to read passphrases from standard input
without prompts or confirmation.
.SH "EXIT STATUS"
0 on success, >0 on error
.SH ENVIRONMENT
.TP
.B MYPROXY_SERVER
Specifies the hostname where the
.BR myproxy-server (8)
is running.  This environment variable can be used in place of the 
.B -s
option.
.TP
.B MYPROXY_SERVER_PORT
Specifies the port where the
.BR myproxy-server (8)
is running.  This environment variable can be used in place of the 
.B -p
option.
.TP
.B MYPROXY_SERVER_DN
Specifies the distinguished name (DN) of the 
.BR myproxy-server (8).
All MyProxy client programs authenticate the server's identity.
By default, MyProxy servers run with host credentials, so the MyProxy
client programs expect the server to have a distinguished name of the
form "host/<fqhn>" or "myproxy/<fqhn>"
(where <fqhn> is the fully-qualified hostname of
the server).  If the server is running with some other DN, you can set
this environment variable to tell the MyProxy clients to accept the
alternative DN.
.TP
.B MYPROXY_TCP_PORT_RANGE
Specifies a range of valid port numbers 
in the form "min,max"
for the client side of the network connection to the server.
By default, the client will bind to any available port.
Use this environment variable to restrict the ports used to
a range allowed by your firewall.
If unset, MyProxy will follow the setting of the
.B GLOBUS_TCP_PORT_RANGE
environment variable.
.SH AUTHORS
Bill Baker,
Jim Basney,
Shiva Shankar Chetan,
Patrick Duda,
Jarek Gawor,
Monte Goode,
Daniel Kouril,
Zhenmin Li,
Jason Novotny,
Miroslav Ruda,
Benjamin Temko,
and Von Welch
.SH "SEE ALSO"
.BR myproxy-change-pass-phrase (1),
.BR myproxy-destroy (1),
.BR myproxy-info (1),
.BR myproxy-init (1),
.BR myproxy-logon (1),
.BR myproxy-store (1),
.BR myproxy-server.config (5),
.BR myproxy-admin-adduser (8),
.BR myproxy-admin-change-pass (8),
.BR myproxy-admin-load-credential (8),
.BR myproxy-admin-query (8),
.BR myproxy-server (8)
