.TH myproxy-admin-load-credential 8 "2005-6-8" "NCSA" "MyProxy"
.SH NAME
myproxy-admin-load-credential \- directly load repository
.SH SYNOPSIS
.B myproxy-admin-load-credential
[
.I options
]
.SH DESCRIPTION
The
.B myproxy-admin-load-credential
command stores a credential directly in the local MyProxy repository.
It must be run from the account that owns the repository.
Many of the options are similar to
.BR myproxy-init (1).
However, unlike
.BR myproxy-init ,
.B myproxy-admin-load-credential
does not create a proxy from the source credential but instead
directly loads a copy of the source credential into the repository.
The pass phrase of the source credential is unchanged.
Use 
.BR myproxy-admin-change-pass (8)
to change the pass phrase after the credential is stored if desired.
Proxy credentials with default lifetime of 12 hours can then be
retrieved by 
.BR myproxy-logon (1)
using the MyProxy passphrase.
The command's behavior is controlled by the following options.
.SH OPTIONS
.TP
.B -h, --help
Displays command usage text and exits.
.TP
.B -u, --usage
Displays command usage text and exits.
.TP
.B -v, --verbose
Enables verbose debugging output to the terminal.
.TP
.B -V, --version
Displays version information and exits.
.TP
.BI -s " dir, " --storage " dir"
Specifies the location of the credential storage directory.
The directory must be accessible only by the user running the 
.B myproxy-server
process for security reasons.  Default: /var/myproxy or $GLOBUS_LOCATION/var/myproxy
.TP
.BI -c " filename, " --certfile " filename"
Specifies the filename of the source certificate.  This is a required
parameter.
.TP
.BI -y " filename, " --keyfile " filename"
Specifies the filename of the source private key.  This is a required
parameter.
.TP
.BI -l " username, " --username " username"
Specifies the MyProxy account under which the credential should be
stored.  By default, the command uses the value of the
.B LOGNAME
environment variable.
Use this option to specify a different account username on the MyProxy
server.
The MyProxy username need not correspond to a real Unix username.
.TP
.BI -t " hours, " --proxy_lifetime " hours"
Specifies the maximum lifetime of credentials retrieved from the
.BR myproxy-server (8)
using the stored credential.  Default: 12 hours
.TP
.B -d, --dn_as_username
Use the certificate subject (DN) as the username.
.TP
.B -a, --allow_anonymous_retrievers
Allow credentials to be retrieved with just pass phrase authentication.
By default, only entities with credentials that match the
.BR myproxy-server.config (5)
default retriever policy may retrieve credentials.
This option allows entities without existing credentials to retrieve a
credential using pass phrase authentication by including "anonymous"
in the set of allowed retrievers.  The
.BR myproxy-server.config (5)
server-wide policy must also allow "anonymous" clients for this option
to have an effect.
.TP
.B -A, --allow_anonymous_renewers
Allow credentials to be renewed by any client.
Any client with a valid credential with a subject name that matches
the stored credential may retrieve a new credential from the MyProxy
repository if this option is given.
Since this effectively defeats the purpose of proxy credential
lifetimes, it is not recommended.  It is included only for sake of
completeness.
.TP
.BI -r " dn, " --retrievable_by " dn"
Allow the specified entity to retrieve credentials.  By default, the
argument will be matched against the common name (CN) of the client
(for example: "Jim Basney").  Specify
.B -x 
before this option to match against the full distinguished name (DN)
(for example: "/C=US/O=National Computational Science Alliance/CN=Jim
Basney") instead.
.TP
.BI -R " dn, " --renewable_by " dn"
Allow the specified entity to renew credentials.
By default, the
argument will be matched against the common name (CN) of the client
(for example: "condorg/modi4.ncsa.uiuc.edu").  Specify
.B -x 
before this option to match against the full distinguished name (DN)
(for example: "/C=US/O=National Computational Science Alliance/CN=condorg/modi4.ncsa.uiuc.edu") instead.
.TP
.B -x, --regex_dn_match
Specifies that the DN used by options 
.B -r
and 
.B -R
will be matched as a regular expression.
.TP
.B -X, --match_cn_only
Specifies that the DN used by options 
.B -r 
and 
.B -R 
will be matched against the Common Name (CN) of the subject.
.TP
.BI -k " name, " --credname " name"
Specifies the credential name.
.TP
.BI -K " description, " --creddesc " description"
Specifies credential description.
.SH "EXIT STATUS"
0 on success, >0 on error
.SH AUTHORS
Bill Baker,
Jim Basney,
Shiva Shankar Chetan,
Patrick Duda,
Jarek Gawor,
Monte Goode,
Daniel Kouril,
Zhenmin Li,
Jason Novotny,
Miroslav Ruda,
Benjamin Temko,
and Von Welch
.SH "SEE ALSO"
.BR myproxy-change-pass-phrase (1),
.BR myproxy-destroy (1),
.BR myproxy-info (1),
.BR myproxy-init (1),
.BR myproxy-logon (1),
.BR myproxy-retrieve (1),
.BR myproxy-store (1),
.BR myproxy-server.config (5),
.BR myproxy-admin-adduser (8),
.BR myproxy-admin-change-pass (8),
.BR myproxy-admin-query (8),
.BR myproxy-server (8)
