.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GLOBUS\-USAGE\-UPLOADE" "8" "11/17/2012" "University of Chicago" "Reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
globus\-usage\-uploader \- Store usage statistics packets in a database
.SH "SYNOPSIS"
.HP 22
\fBglobus\-usage\-uploader\fR [\-h] [\-d\ \fIDIRECTORY\fR] [\-n] [\-c\ \fICONFIG\-FILE\fR] [\-p\ \fIPIDFILE\fR]
.SH "DESCRIPTION"
.PP
The
\fBglobus\-usage\-uploader\fR
command is a utility which parses usage packets in directories of the form created by
\fBglobus\-usage\-collector\fR
and uploads them to a postgresql database.
.PP
The full set of command\-line options to
\fBglobus\-usage\-uploader\fR
consists of:
.TP
\-h
Display a help message and exit
.TP
\fB\-d \fR\fB\fIDIRECTORY\fR\fR
Read data from
\fIDIRECTORY\fR
instead of the configured path.
.TP
\fB\-n\fR
Don't commit usage packets to the database after processing files (for testing)
.TP
\fB\-c \fR\fB\fICONFIG\-FILE\fR\fR
Read configuration information from
\fICONFIG_FILE\fR
instead of the default location
\fI\fIPREFIX\fR\fR\fI/etc/globus/usage\-tools.conf\fR.
.TP
\fB\-p \fR\fB\fIPIDFILE\fR\fR
Don't run if
\fIPIDFILE\fR
exists and contains the PID of an existing process. Write the current process's PID to that file otherwise, and remove it when complete.
.SH "EXAMPLES"
.sp
.nf
% \fBglobus\-usage\-uploader\fR

Processing packets: 20090723
Processing packets: 20090724
14.gup... ok [2 packets]

Processed 1 file(s).
Processed 2 packet(s).
.fi
