.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GLOBUS\-USAGE\-COLLECT" "8" "11/17/2012" "University of Chicago" "Reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
globus\-usage\-collector \- Record usage statistics packets
.SH "SYNOPSIS"
.HP 23
\fBglobus\-usage\-collector\fR [\-h] [\-p\ \fIPORT\fR] [\-b] [\-f\ \fIFILE\fR]
.SH "DESCRIPTION"
.PP
The
\fBglobus\-usage\-collector\fR
command is a servivce which accepts usage packets on a UDP port and writes them to a file for later processing.
.PP
The full set of command\-line options to
\fBglobus\-usage\-collector\fR
consists of:
\-h Display a help message and exit .sp -p \fIPORT\fR Listen on UDP port \fIPORT\fR instead of the default port 4810 .sp -d \fIDIRECTORY\fR Write data to \fIDIRECTORY\fR instead of the configured path. .sp -b Run the \fBglobus\-usage\-collector\fR process in the background .sp -f \fIFILE\fR Write the process ID of the backgrounded \fBglobus\-usage\-collector\fR process to \fIFILE\fR. .sp
.SH "USAGE PACKET FILES"
.PP
The files are written in a subdirectory of the current directory with its name derived from the current time in UTC. The form of this directory name is
\fIYYYYMMDD\fR, (e.g. the date July 20, 2009 would be
\fI20090720\fR). Within that directory, files are generated with name based on the hour (again in UTC). The form of the filename is
\fIHH.gup\fR
.when the packet was processed. That is, a packet processed at 3:20 a.m. on that same day would be stored in the file
\fI20090720/03.gup\fR.
.PP
Each usage packet file consists of simple records containing the binary UDP usage packet data. Each packet record consists of 4 fields:
Address Length (2 bytes) .sp Big\-endian length of the Address .sp Address .sp Big\-endian packed binary address .sp Packet Length (2 bytes) .sp Big\-endian length of the packet .sp Packet .sp Binary packet data .sp
