#! /bin/sh

if [ -z "$DOCBOOK_XSL" ]; then
    if [ -d /usr/share/sgml/docbook/xsl-stylesheets ]; then
        DOCBOOK_XSL="/usr/share/sgml/docbook/xsl-stylesheets"
    elif [ -d /usr/share/xml/docbook/stylesheet/docbook-xsl ]; then
        DOCBOOK_XSL="/usr/share/xml/docbook/stylesheet/docbook-xsl"
    else
        fmt 1>&2 <<-EOF
	    Can't find docbook stylesheets: please set the
	    DOCBOOK_XSL environment variable to the path containing the
	    stylesheets
EOF
        exit 1
    fi
fi

echo "Generating manpages"
asciidoc -b docbook -d manpage globus-usage-collector.txt
asciidoc -b docbook -d manpage globus-usage-uploader.txt
xsltproc $DOCBOOK_XSL/manpages/docbook.xsl globus-usage-collector.xml
xsltproc $DOCBOOK_XSL/manpages/docbook.xsl globus-usage-uploader.xml

echo "Creating html manual"
asciidoc -b html -d book -a toc admin.txt

if command -v fop > /dev/null; then
    asciidoc -b docbook -d book -a toc admin.txt
    xsltproc --stringparam fop1.extensions 1 \
        $DOCBOOK_XSL/fo/docbook.xsl admin.xml > admin.fo
    fop admin.fo admin.pdf
else
    echo "Unable to locate fop, pdf manual not updated"
    exit 1
fi
