#!/bin/sh

# checking for the GLOBUS_LOCATION

if test "x$GLOBUS_LOCATION" = "x"; then
    echo "ERROR Please specify GLOBUS_LOCATION" >&2
    exit 1
fi

. ${GLOBUS_LOCATION}/libexec/globus-bootstrap.sh

echo "generating findshelltools"
autoconf findshelltools.in > findshelltools || error
chmod 755 findshelltools

exit 0
