#! /bin/sh

set -e
set -x

if [ -f build-number.txt ]; then
    build_number="$(awk -F= "/build.number/ { print \$2 }" < build-number.txt)"
else
    build_number=0
fi

if ! expr "$0" : / > /dev/null; then
    bamboodir="$(pwd)/$(dirname $0)"
else
    bamboodir="$(dirname $0)"
fi

cd "$bamboodir/.."
topdir="$(pwd)"

tag=''
flavor=''
while getopts t:f: i; do
    case $i in
        t)
            tag="$OPTARG"
            ;;
        f)
            flavor="$OPTARG"
            ;;
    esac
done

if [ "$flavor" = "" ]; then
    case $(uname -m) in
        x86_64 | ia64 | s390x | ppc64)
            flavor=gcc64
            ;;
        *)
            flavor=gcc32
            ;;
    esac
fi

if [ ! -d fait_accompli ]; then
    cvs update -Pd ${tag:+-r "$tag"}
fi

gtversion="$(cat fait_accompli/version)"

# fix bamboo cvs checkout losing executable permissions
chmod a+x *.pl fait_accompli/installer.sh \
    gpt/build_gpt gpt/make_gpt_dist gpt/setup_gpt_dist \
    gpt/packaging_tools/bootstrap gpt/check-gpt-prereqs \
    gpt/install-sh || :


./fait_accompli/installer.sh -a -f "$flavor" ${tag:+-t "$tag"}
installer_dir="gt${gtversion}-all-source-installer"
find "${installer_dir}" -name install-sh -exec chmod a+x {} +

tar cf "${installer_dir}.tar" "${installer_dir}"

gzip -9 "${installer_dir}.tar" 

# Copy installer and checksums to artifcacts dir
artifactsdir="${topdir}/artifacts"
mkdir "${artifactsdir}"

cp "${installer_dir}.tar.gz" "${artifactsdir}"

md5sum "${artifactsdir}/${installer_dir}.tar.gz" > "${artifactsdir}/${installer_dir}.tar.gz.md5"  || true
sha1sum "${artifactsdir}/${installer_dir}.tar.gz" > "${artifactsdir}/${installer_dir}.tar.gz.sha1"  || true

# Generate release frags and copy to artifacts dir
fragsdir="${artifactsdir}/frags"
mkdir -p "${fragsdir}"
cd "frag-generator"
make
cp "$(cat ../fait_accompli/version | sed -e 's/rc[0-9]\{1,\}//')" "${fragsdir}"
cd "$OLDPWD"
