#! /bin/sh

tag="${1:-globus_5_0_branch}"
umask 002
chmod a+x make-packages.pl gpt/packaging_tools/bootstrap gpt/build_gpt gpt/make_gpt_dist gpt/setup_gpt_dist gpt/packaging_tools/configure
chmod a+x bamboo-scripts/*
chmod a+x fait_accompli/installer.sh

./fait_accompli/installer.sh -a ${tag:+-t ${tag}}
version=$(cat fait_accompli/version)
tar zcf gt${version}-all-source-installer.tar.gz gt${version}-all-source-installer
