#! /bin/sh

set -e
umask 022

bamboodir=$(pwd)/bamboo
topdir=$(pwd)/rpmbuild
tmppath=$(pwd)/tmp

mkdir -p $topdir

# Reset home to this directory as it is a transient bamboo build dir
HOME=$topdir

args=$(getopt n:v:a:St:hg: $*)
set -- ${args}

tag=""
for i; do
    case "$i" in
        -t)
           tag="$2"
           shift 2
           ;;
        --)
           shift
           break
           ;;
    esac
done

# Remove everything prior to building
pkgs_to_rm="$(rpm -qa | (egrep '^grid-packaging-tools|^[Gg]lobus-|^myproxy|^gsi_openssh' || true) )"
if [ -n "$pkgs_to_rm" ]; then
    sudo rpm -e --allmatches $pkgs_to_rm
fi

bundles=globus-data-management-server,globus-data-management-client,globus-data-management-sdk,globus-simple-ca
packages_to_build=myproxy,gsi_openssh
chmod a+x make-packages.pl fait_accompli/installer.sh gpt/build_gpt gpt/make_gpt_dist gpt/setup_gpt_dist gpt/packaging_tools/bootstrap gpt/packaging_tools/configure gpt/check-gpt-prereqs

packages="$(echo gpt-*.tar.gz; ./make-packages.pl -a -lp -deps -deporder -bundles=$bundles -packages="$packages_to_build ${tag:+-t "$tag"}" | \
    awk "/at version/ { print \$1 \"-\" \$4 }")"
packages="$(echo "${packages}" | grep -Ev 'myproxy|gsi_openssh'; echo myproxy; echo gsi_openssh)"

echo "$packages" > bamboo-package-list

./make-packages.pl -a -deps -deporder -bundles=$bundles -packages="$packages_to_build" -a -flavor=gcc64dbg ${tag:+-t "${tag}"}
cd gpt-3.3/packaging_tools
make dist
cp gpt-3.3.tar.gz ../../package-output
