<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Portions of this file Copyright 1999-2005 University of Chicago
  Portions of this file Copyright 1999-2005 The University of Southern California.
  
  This file or a portion of this file is licensed under the
  terms of the Globus Toolkit Public License, found at
  http://www.globus.org/toolkit/download/license.html.
  If you redistribute this file, with or without
  modifications, you must include this notice in the file.
-->
<definitions name="GridFTPAdmin"
    targetNamespace="http://www.globus.org/namespaces/2005/09/GridFTPAdmin"
    xmlns:tns="http://www.globus.org/namespaces/2005/09/GridFTPAdmin"
    xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/03/addressing" 
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdlpp="http://www.globus.org/namespaces/2004/10/WSDLPreprocessor"
    xmlns:wsrlw=
    "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.wsdl"
    xmlns:wsrpw=
    "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.wsdl"
    xmlns:wsnt=
    "http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.xsd"
    xmlns:wsntw=
    "http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl"
    xmlns:wssg=
    "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ServiceGroup-1.2-draft-01.xsd"
    xmlns:wssgw=
    "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ServiceGroup-1.2-draft-01.wsdl"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <wsdl:import 
        namespace=
        "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.wsdl"
        location="../wsrf/properties/WS-ResourceProperties.wsdl" />

    <wsdl:import 
        namespace=
        "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.wsdl"
        location="../wsrf/lifetime/WS-ResourceLifetime.wsdl" />

    <wsdl:import 
        namespace=
        "http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl"
        location="../wsrf/notification/WS-BaseN.wsdl" />


    <wsdl:import 
        namespace=
        "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ServiceGroup-1.2-draft-01.wsdl"
        location="../wsrf/servicegroup/WS-ServiceGroup.wsdl" />


    <types>
        <xsd:schema targetNamespace="http://www.globus.org/namespaces/2005/09/GridFTPAdmin"
            xmlns:tns="http://www.globus.org/namespaces/2005/09/GridFTPAdmin"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">

            <xsd:import 
                namespace="http://schemas.xmlsoap.org/ws/2004/03/addressing"
                schemaLocation="../ws/addressing/WS-Addressing.xsd" 
                />

            <xsd:import 
                namespace="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ServiceGroup-1.2-draft-01.xsd"
                schemaLocation="../wsrf/servicegroup/WS-ServiceGroup.xsd" 
                />

            <xsd:include schemaLocation="FrontendStats_types.xsd"/>

        </xsd:schema>
    </types>

    <portType name="GridFTPAdminPortType"
            wsdlpp:extends="
            wsntw:NotificationProducer
            wsrpw:QueryResourceProperties
            wsrpw:SetResourceProperties
            wsrpw:GetMultipleResourceProperties
            wsrpw:GetResourceProperty"
        wsrpw:ResourceProperties ="tns:FrontendStats"/>
</definitions>
