#! /bin/sh

# 
# Copyright 1999-2006 University of Chicago
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 


if test x"$GLOBUS_LOCATION" = x ; then
    echo "Please set GLOBUS_LOCATION before running this script" 1>&2
    exit 1
fi

if test ! -r $GLOBUS_LOCATION/etc/globus-devel-env.sh; then
    echo "$GLOBUS_LOCATION/etc/globus-devel-env.sh not found" 1>&2 
    exit 1
fi

. $GLOBUS_LOCATION/etc/globus-devel-env.sh

if test $? != 0; then
    echo "Error setting Globus environment" 1>&2
    exit 1
fi

PREPROCESS="org.globus.wsrf.tools.wsdl.WSDLPreprocessor"
GENERATE_BINDING="org.globus.wsrf.tools.wsdl.GenerateBinding"

SCHEMA_DIR=$GLOBUS_LOCATION/share/schema/gridftp/
DEST_DIR="`pwd`"

mkdir -p "$SCHEMA_DIR"
HERE="`pwd`"
cp -f FrontendStats_types.wsdl "$SCHEMA_DIR"
cp -f FrontendStats_types.xsd "$SCHEMA_DIR"

for x in gridftp_admin ; do
    echo "---------> $x"
    processing="Processing $x"
    echo "$processing" | sed s/./-/g
    echo "Processing $x"
    echo "$processing" | sed s/./-/g
    echo ""
    cp "${x}_compact.wsdl" "${SCHEMA_DIR}"

    if [ -r "${x}.xsd" ];  then
        cp "${x}.xsd" "${SCHEMA_DIR}"
    fi

    cd "${SCHEMA_DIR}"

    echo "Preprocessing $x WSDL"
    java $PREPROCESS  -in "${SCHEMA_DIR}/${x}_compact.wsdl" \
        -out "${x}.wsdl"

    echo "Generating $x bindings"
    java $GENERATE_BINDING -in "${x}.wsdl" \
        -out "${x}"

    echo "Copying Generated files to $DEST_DIR"
    cp "$SCHEMA_DIR/${x}.wsdl" "$DEST_DIR"
    cp "$SCHEMA_DIR/${x}_bindings.wsdl" "$DEST_DIR"
    cp "$SCHEMA_DIR/${x}_service.wsdl" "$DEST_DIR"

    if [ -r "${SCHEMA_DIR}/${x}.xsd" ]; then
        cp "${SCHEMA_DIR}/${x}.xsd" "$DEST_DIR"
    fi

    cd "$HERE"
done
