#! /bin/sh

# Add the Globus GPG Key
echo "Adding Globus Package GPG Key"
apt-key add - <<EOF
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.5 (GNU/Linux)

mQGiBE0PXQkRBAC12PfwFzMyTKAvCp3AEbzdwwDyEaBHYmd1+Dv+q5c48fEZQrzA
PuZ75BnG8BRIo3ZSYJll9Xf5v8A0M6F35msBBdjUpI+PHZvSQ+yru6U3w9XCsmO9
jSGWM1XAw/hcDWOsETOsjJ56AqIKndOXtG2jeOMFD0MwJus9paDcv5pPkwCgk3Fk
I+GdLaZf0O6vGUtq2Fo2EgkD/14AQ4SyUufwztQeLwlYXyihdUoIVBl4wm4fndJb
TuzTlp3V/oabM8t+V92ftbqlAesFb1FdFQ9NeUEY0VIODR2OTsmEfLUSMK/kRfXM
4FatObXpEp58EydZb3oz/vwASEk1Nno5OW2noGZL3sCk+3j65MstI2q4kMvNSvl+
JEjUBACgNv/mDrn0UjWBuzxOuZrh1r2rBdsjIHx31o/vBF5YLfQhErZQTm6cfpRK
W32Nm18btrqgxxHFAMb4wxnVxAxdM3zLSAaiqvi33z2wHReh5TfaVKpJBj7LpMSI
hwu50iovsBjE7HiusJQBWBtk8Bqp4g9ic2sPV0caEMCUXU5R9bQjR2xvYnVzIFRv
b2xraXQgPHN1cHBvcnRAZ2xvYnVzLm9yZz6IYAQTEQIAIAUCTQ9dCQIbAwYLCQgH
AwIEFQIIAwQWAgMBAh4BAheAAAoJEESufsL68kNlb6IAoIemS8dr65xCkA4GQzgJ
ngXwZgtvAKCOKs5Ork6HiNKIrWRGMLvA7iktBbkCDQRND10SEAgA37cRQGj/QNcc
OjyBrL6e2wPT7UtpXBEHzfjhtmT8+VC+PSbKRxVfawLBtrfzSAAwsmye3c+XK/VB
Pa06vSSmezeyNau+XtEVLwrwQwO/kM6wgNtb7zYyI67Y6XEPP+ZlqpZ0W14cTZBD
3SXWuu6zqjdtUnJCg/j/j0zH5TZa40aCfisERxNCQeoePk2gmMTJDJF0ASM3Nhys
QIP9qpCA+eOJnKmMeEgDCW9j2mYO4tp9lCSbi15HAb41HKN6xypNWk+EHKyu9n50
88UocRHXLZFujzNTGIokWAcoC0D3qpVQehtAVgt1VPrE6MxFPek8ZN4Ho++92KB7
F6E0OsfF6wADBggAnNPguzYAIztF/EzZANUU/7Eon9zJaD4Lf/mnhB3bMuGvenY0
7HSBAXbUxVXs7uX3S6u9PZ9dytl2Fqh8w47TNcC0ACKLRnhxTJ92LLakzAGVGtNz
2W9l+YJaZ6qIQR9FmYpCyIWp6Vm47yOARThrMtnwUhb53g5ZfxgzpHNUDN/7utTy
3sUaMRiijecmSVhDFbrz7ryY2Btlcr7ZrBo0ODHohDkZVn2UrzE6qg9g5np03zYe
5OUM5Lt5GYZJSKZO81aJ5+9DlkiAev3BFEeCsSOwjrqLZpsr0olbIfeHCi8pvjOJ
SCfx4Qs/hI34ykaUn3AgbgxqT0mSKfMasg2bIIhJBBgRAgAJBQJND10SAhsMAAoJ
EESufsL68kNlBuAAnRRI5jFAvyjtQaoQpVqSL4/O45D7AJ9WrW/vxTzN0OyZyUU6
8T0dJyXArA==
=r6rU
-----END PGP PUBLIC KEY BLOCK-----
EOF

echo "Adding Globus Repo GPG Key"
apt-key add - <<EOF
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.14 (GNU/Linux)

mQENBFEvYhUBCAC8Ht+r2zwX8Tr3b13bb59Zsvnq3djTpkxUVQQZBvlohgPoRLr6
6TAEBijHifW1YSTYx9j0m8XdG+lSz8K9AKibQ+Xh189kdIci4ibJ3j5IOQk8qULh
yKdyowonUMSB4t72/Umt+jqcWul2TiU5UEcm1wooS618YIhgqLE28db9Mite1IFp
gH8mSFJzpmSVMYiqEA1YlXsl1t9EPgFJwzx3+Jq3LXho/C0Xu9vjWv8i5uWkj0S5
LviBbz4HS8APPdbqknFFiJdn1Nv1veUmJ7/TZxfcjntkRul3deP/vVDtCZi202E9
VwPSOpBORHj6T75Ck6KWbw9SD+eyqVz6t+cNABEBAAG0N0dsb2J1cyBUb29sa2l0
IEplbmtpbnMgUmVwbyA8amVua2luc0BidWlsZHMuZ2xvYnVzLm9yZz6JATgEEwEC
ACIFAlEvYhUCGwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELZ8EuYloyvA
DIUH/jZMBd4acY3TmmS8VkvjPOVuvw0zeAZRxPwVVwLGC4LwDqzpbaCN3tSGk/xG
uvrUveymeXed2Uk2adc1DVAM/V0qSUcyl/kS16jvokuRQmUSAs396PQOHjlfj5yv
uS0L9EYvSFOI9RUnmtjely6lqRImITPa0pX4hC1JPNRI/uSRWl38VAursPBnltvL
WiYYWVASWezg4XE7PzUdCnLUv1VfszrOqwvbQzfI7EllVhDEEKMn2MkBrPOE+CAZ
KOchKAVnRvN61ov4ZRhBaHpoj7ikOadal84omf5l65yWPtqWrSAjxeL2twfAivxa
m3Z+WS03fsq138cqCnwyTMR/49G5AQ0EUS9iFQEIAOa+WEUSMDom6XIRChSHSp5w
hD8Zpm//MkjX+yPskkGreiWIutCMoYWo86BoTS4+f5+mBaRg/e8/5XoGlbH9pAuz
sr3Z3WDvrcdnY8C0Im+vdzdHvAUbXgwRSi3KPjDVSV1sp5Jze1yDA0ssk4ryk9+R
+QHhsF793Kk7AYf8qNZePATsdhDekP5I70tOVjWyS37c1fwedkS0rS08KtuzW91u
HdXvaYveTywcPuDENeYy2fzD2SuGQc0Mcx7abTtoiOaKExc3ydn92JttnUdrFY/Y
QDESLZjWyEdp16W0BPWOVgP61vTfZyV2e3YR8XHSw82A3aaaa+Y12tl0Xxmf51MA
EQEAAYkBHwQYAQIACQUCUS9iFQIbDAAKCRC2fBLmJaMrwEmGB/4g7jsby6HkDRvr
VGa8KjBYHexx5Ws2jFFIHTSRhKH98cXVias9da7gxDMsqP7cGk2nQel8NHZ7pa0S
WeCeuJmLgco5W3SuMGl29gp1zyyT76aREG6UUJR0f2tHYOhhBZEkRIMyKlp2P3aL
SbzH2QfUhlnlQS02vHy+kUtpA3lryIY9ZgbQCnsJEC+PU4xjwmUQM8EALR9Iv2Xg
AS2E5avDGuLPGoFTEqhKIA1yNoag/9ixoesHbh2XjBR/zEcu5tjePRW4grRw4A5K
UKfBWNa6tr9AtM374ZkKMANcog6r0iP8MKsGF9+Wve+69zT1Ef5lFSy1GE+PzX3g
xj7TEZmv
=6jEj
-----END PGP PUBLIC KEY BLOCK-----
EOF

if [ -f /etc/os-release ]; then
    codename="$(awk -F"[)(]+" '/VERSION=/ {print $2}' /etc/os-release)"
elif [ -f /etc/lsb-release ]; then
    codename="$(awk -F= '/DISTRIB_CODENAME=/ {print $2}' /etc/lsb-release)"
fi
data="/usr/share/globus-toolkit-repo/sources.list.d"
list_d="/etc/apt/sources.list.d"

case "$1" in
configure)
    for repo in stable testing unstable; do
        list="globus-toolkit-6-${repo}-${codename}.list"
        if [ ! -f "${list_d}/${list}" ] || \
           cmp -s "${list_d}/${list}" "${data}/${list}"; then
            install -m 0644 -p "${data}/${list}" "${list_d}"
        else
            echo "Preserving existing ${list}."
            echo "There are changes in ${list}.dpkg-new which you should incorporate into ${list}"
        fi
    done
esac
