#! /bin/sh

############################################################
# main code section
############################################################
if test -z "${GLOBUS_LOCATION}"; then
    echo ""
    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory before"
    echo "running this script"
    echo ""
    exit 1
fi

. ${GLOBUS_LOCATION}/libexec/globus-script-initializer
globus_source ${libexecdir}/globus-sh-tools.sh

GRID_CA_DIR=${HOME}/.globus/simpleCA/

if [ ! -f ${GRID_CA_DIR}/cacert.pem ]; then
    echo 
    echo "No simple CA directory found.  Run setup-simple-ca before"
    echo "signing certificates"
    exit 1
fi

grid_ca_conf=${GRID_CA_DIR}/grid-ca-ssl.conf
openssl_cmd=${GLOBUS_LOCATION}/bin/openssl

TMP_REQ_FILE=${GLOBUS_SH_TMP-/tmp/}/tmp_cert_req.pem.$$
TMP_CERT_FILE=${GLOBUS_SH_TMP-/tmp/}/tmp_cert.pem.$$

while read INPUT_REQ ; do

	echo "${INPUT_REQ}" >> ${TMP_REQ_FILE}
done

tmp_input_file=${GLOBUS_SH_TMP-/tmp/}/tmp_input.$$
echo "y
y
" > $tmp_input_file

tmp_output=${GLOBUS_SH_TMP-/tmp/}/tmp_output.$$
${openssl_cmd} ca -config ${grid_ca_conf} -in ${TMP_REQ_FILE} -out ${TMP_CERT_FILE} < $tmp_input_file > $tmp_output

${GLOBUS_SH_RM-rm} -f ${tmp_input_file}
${GLOBUS_SH_RM-rm} -f ${tmp_output}


TMP_SUBJECT=`${openssl_cmd} x509 -in ${TMP_CERT_FILE} -noout -subject`
TMP_SUBJECT=`echo ${TMP_SUBJECT} | ${GLOBUS_SH_SED-sed} -e "s|^.*CN=||"`

HASH=`${openssl_cmd} x509 -in ${TMP_CERT_FILE} -noout -hash`
SUBJECT=`echo ${TMP_SUBJECT} | ${GLOBUS_SH_SED-sed} -e "s|[ ]|_|g"`

CERT_REQ_FILE=${GRID_CA_DIR}/certs/cert_req.pem.${SUBJECT}_${HASH}
CERT_FILE=${GRID_CA_DIR}/certs/cert.pem.${SUBJECT}_${HASH}

${GLOBUS_SH_CP-cp} ${TMP_REQ_FILE}   ${CERT_REQ_FILE}
${GLOBUS_SH_CP-cp} ${TMP_CERT_FILE}  ${CERT_FILE}

${GLOBUS_SH_RM-rm} -f ${TMP_REQ_FILE} ${TMP_CERT_FILE}

${GLOBUS_SH_CLEAR-clear}
cat ${CERT_FILE}