'\" t
.\"     Title: grid-ca-sign
.\"    Author: University of Chicago
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/30/2011
.\"    Manual: Globus Commands
.\"    Source: Globus Toolkit 5.2.0
.\"  Language: English
.\"
.TH "GRID\-CA\-SIGN" "1" "03/30/2011" "Globus Toolkit 5.2.0" "Globus Commands"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
grid-ca-sign \- Sign a certificate with a SimpleCA for use on a grid
.SH "SYNOPSIS"
.HP \w'\fBgrid\-ca\-sign\fR\ 'u
\fBgrid\-ca\-sign\fR [\-help] [\-h] [\-usage] [\-version] [\-versions]
.HP \w'\fBgrid\-ca\-sign\fR\ 'u
\fBgrid\-ca\-sign\fR \-in\ \fIREQUEST\fR \-out\ \fICERTIFICATE\fR
.br
[\-force] [\-dir\ \fIDIRECTORY\fR]
.br
[\-openssl\-help] [\fIOPENSSL\-OPTIONS\fR]
.SH "DESCRIPTION"
.PP
The
\fBgrid\-ca\-sign\fR
program signs a certificate based on a request file with a CA certificate created by
\fBgrid\-ca\-create\fR\&. The new certificate is written to a file\&. If the CA has already signed a certificate with the same subject name as contained in the certificate request, it will refuse to sign the new request unless the
\fB\-force\fR
option is provided on the command\-line\&.
.PP
If run as a privileged user,
\fBgrid\-ca\-sign\fR
uses the CA certificate and configuration located in
\fB${localstatedir}\fR/globus_simple_ca
to sign the certificate\&. For a non\-privileged user,
\fBgrid\-ca\-sign\fR
uses the CA certificate and configuration located in
\fB$HOME\fR/\&.globus/simpleCA\&. The
\fBgrid\-ca\-sign\fR
program an use a different CA configuration and certificate by using the
\fB\-dir\fR
option\&.
.PP
The full set of command\-line options to
\fBgrid\-ca\-sign\fR
follows\&. In addition to these, unknown options will be passed to the
\fBopenssl\fR
command when creating the self\-signed certificate\&.
.PP
\fB\-help\fR, \fB\-h\fR, \fB\-usage\fR
.RS 4
Display the command\-line options to
\fBgrid\-ca\-sign\fR
and exit\&.
.RE
.PP
\fB\-version\fR, \fB\-versions\fR
.RS 4
Display the version number of the
\fBgrid\-ca\-sign\fR
command\&. The second form includes details about the package containing
\fBgrid\-ca\-sign\fR\&.
.RE
.PP
\fB\-in \fR\fB\fIREQUEST\fR\fR
.RS 4
Sign the request contained in the
\fIREQUEST\fR
file\&.
.RE
.PP
\fB\-out \fR\fB\fICERTIFICATE\fR\fR
.RS 4
Write the signed request to the
\fICERTIFICATE\fR
file\&.
.RE
.PP
\fB\-force\fR
.RS 4
Revoke any previously issued certificate with the same subject name as in the certificate request and issue a new certificate\&. Otherwise,
\fBgrid\-ca\-sign\fR
will refuse to sign the request\&.
.RE
.PP
\fB\-dir \fR\fB\fIDIRECTORY\fR\fR
.RS 4
Sign the certificate using the Simple CA certificate and configuration located in
\fIDIRECTORY\fR
instead of the default\&.
.RE
.PP
\fB\-openssl\-help\fR
.RS 4
Print the command\-line options available for the
\fBopenssl ca\fR
command\&.
.RE
.SH "EXAMPLES"
.PP
Sign a certificate request using the simple CA in
\fB$HOME\fR/SimpleCA
.sp
.if n \{\
.RS 4
.\}
.nf
% \fBgrid\-ca\-sign\fR \fB\-in usercert_request\&.pem \-out usercert\&.pem\fR \fB\-dir \fR\fB\fB$HOME\fR\fR\fB/SimpleCA\fR

To sign the request
please enter the password for the CA key: 

The new signed certificate is at: /home/juser/\&.globus/simpleCA/newcerts/01\&.pem
.fi
.if n \{\
.RE
.\}
.sp
.SH "ENVIRONMENT VARIABLES"
.PP
The following environment variables affect the execution of
\fBgrid\-ca\-sign\fR:
.PP
\fBGLOBUS_LOCATION\fR
.RS 4
Non\-standard installation path of the Globus toolkit\&.
.RE
.SH "SEE ALSO"
.PP
\fBgrid-cert-request\fR(1),
\fBgrid-ca-create\fR(1),
\fBgrid-default-ca\fR(1),
\fBgrid-ca-package\fR(1)
.SH "AUTHOR"
.PP
\fBUniversity of Chicago\fR
