'\" t
.\"     Title: globus-update-certificate-dir
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/24/2014
.\"    Manual: Globus Toolkit
.\"    Source: University of Chicago
.\"  Language: English
.\"
.TH "GLOBUS\-UPDATE\-CERT" "8" "09/24/2014" "University of Chicago" "Globus Toolkit"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-update-certificate-dir \- Update symlinks in the trusted CA directory
.SH "SYNOPSIS"
.sp
\fBglobus\-update\-certificate\-dir\fR \-help
.sp
\fBglobus\-update\-certificate\-dir\fR [\-d \fIDIRECTORY\fR]
.SH "DESCRIPTION"
.sp
The \fBglobus\-update\-certificate\-dir\fR program creates symlinks between files (CA certificates, certificate revocation lists, signing policy, and certificate request configuration files) using the certificate hash the installed version of OpenSSL uses\&. OpenSSL 1\&.0\&.0 uses a different name hashing algorithm than previous versions, so CA distributions created with older versions of OpenSSL might not be able to locate trusted CAs and related files\&. Running \fBglobus\-update\-certificate\-dir\fR against a trusted CA directory will add symlinks to the files to the hash if needed\&.
.SH "OPTIONS"
.PP
\fB\-help\fR
.RS 4
Display a help message to standard output and exit
.RE
.PP
\fB\-d \fR\fB\fIDIRECTORY\fR\fR
.RS 4
Create links in the trusted CA directory
\fIDIRECTORY\fR
instead of using the default search path\&.
.RE
.SH "ENVIRONMENT"
.sp
The following variables affect the execution of \fBglobus\-update\-certificate\-dir\fR:
.PP
\fBX509_CERT_DIR\fR
.RS 4
Default trusted certificate directory\&.
.RE
.PP
\fBHOME\fR
.RS 4
Path to the current user\(cqs home directory\&.
.RE
.PP
\fBGLOBUS_LOCATION\fR
.RS 4
Path to the Globus installation\&.
.RE
.SH "AUTHOR"
.sp
Copyright \(co 1999\-2014 University of Chicago
