'\" t
.\"     Title: grid-cert-info
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/08/2016
.\"    Manual: Globus Toolkit Manual
.\"    Source: Globus Toolkit 6
.\"  Language: English
.\"
.TH "GRID\-CERT\-INFO" "1" "09/08/2016" "Globus Toolkit 6" "Globus Toolkit Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
grid-cert-info \- Display information about a certificate
.SH "SYNOPSIS"
.sp
\fBgrid\-cert\-info\fR \fI\-help\fR | \fI\-usage\fR | \fI\-version\fR | \fI\-versions\fR
.sp
\fBgrid\-cert\-info\fR OPTIONS
.SH "DESCRIPTION"
.sp
The \fBgrid\-cert\-info\fR program displays information contained within a certificate file\&. By default it shows a text representation of the entire certificate\&. Specific facts about the certificate can be shown instead by using command\-line options\&. If any of those options are used, then the default display is suppressed\&. This can be added to the output by using the \fI\-all\fR command\-line option\&.
.sp
If multiple display options are included on the command\-line, the facts related to those will be displayed on separate lines in the order that they occur\&. If an option is specified multiple time, that fact will be displayed multiple times\&.
.SH "OPTIONS"
.sp
The full set of command\-line options to \fBgrid\-cert\-info\fR are:
.PP
\fB\-help, \-usage\fR
.RS 4
Display the command\-line options to
\fBgrid\-cert\-info\fR
and exit\&.
.RE
.PP
\fB\-version, \-versions\fR
.RS 4
Display the version number of the
\fBgrid\-cert\-info\fR
command\&. The second form includes more details\&.
.RE
.PP
\fB\-file \fR\fB\fICERTIFICATE\-FILE\fR\fR
.RS 4
Display information about the first certificate contained in the file named by
\fICERTIFICATE\-FILE\fR
instead of the default user certificate\&.
.RE
.PP
\fB\-rfc2253\fR
.RS 4
Display X\&.509 distinguished names using the string representation defined in RFC 2253 instead of the default OpenSSL
\fIoneline\fR
format\&.
.RE
.PP
\fB\-all\fR
.RS 4
Display the text representation of the entire certificate in addition to any other facts requested by command\-line options\&. This is the default if no fact\-specific command\-line options are used\&.
.RE
.PP
\fB\-subject, \-s\fR
.RS 4
Display the subject name of the X\&.509 certificate\&.
.RE
.PP
\fB\-issuer, \-i\fR
.RS 4
Display the issuer name of the X\&.509 certificate\&.
.RE
.PP
\fB\-issuerhash, \-ih\fR
.RS 4
Display the default hash of the issuer name of the X\&.509 certificate\&. This can be used to locate which CA certificate in the trusted certificate directory issued the certificate being inspected\&.
.RE
.PP
\fB\-startdate, \-sd\fR
.RS 4
Display a string representation of the date and time when the certificate is valid from\&. This is displayed in the format used by the OpenSSL
\fBx509\fR
command\&.
.RE
.PP
\fB\-enddate, \-ed\fR
.RS 4
Display a string representation of the date and time when the certificate is valid until\&. This is displayed in the format used by the OpenSSL
\fBx509\fR
command\&.
.RE
.SH "EXAMPLES"
.sp
Display the validity times for the default certificate
.sp
.if n \{\
.RS 4
.\}
.nf
% grid\-cert\-info \-sd \-ed
Aug 31 12:33:47 2009 GMT
Aug 31 12:33:47 2010 GMT
.fi
.if n \{\
.RE
.\}
.sp
Display the same information about a different certificate specified on the command\-line
.sp
.if n \{\
.RS 4
.\}
.nf
% grid\-cert\-info \-sd \-ed \-f /etc/grid\-security/hostcert\&.pem
Jan 21 12:24:48 2003 GMT
Jul 15 11:30:57 2020 GMT
.fi
.if n \{\
.RE
.\}
.sp
Display the subject of a certificate in both the default and the RFC 2253 forms\&.
.sp
.if n \{\
.RS 4
.\}
.nf
% grid\-cert\-info \-subject
/DC=org/DC=example/DC=grid/CN=Joe User
% grid\-cert\-info \-subject \-rfc2253
CN=Joe User,DC=grid,DC=example,DC=org
.fi
.if n \{\
.RE
.\}
.SH "ENVIRONMENT"
.sp
The following environment variables affect the execution of \fBgrid\-cert\-info\fR:
.PP
\fBX509_USER_CERT\fR
.RS 4
Path to the default certificate file to inspect\&.
.RE
.SH "AUTHOR"
.sp
Copyright \(co 1999\-2014 University of Chicago
