'\" t
.\"     Title: globus-domainname
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/09/2012
.\"    Manual: Globus Tookit
.\"    Source: The Globus Alliance
.\"  Language: English
.\"
.TH "GLOBUS\-DOMAINNAME" "1" "02/09/2012" "The Globus Alliance" "Globus Tookit"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-domainname \- Print the local system\'s DNS domain name
.SH "SYNOPSIS"
.HP \w'\fBglobus\-domainname\fR\ 'u
\fBglobus\-domainname\fR [\fBoptions\fR]
.SH "DESCRIPTION"
.PP
The
\fBglobus\-domainname\fR
program prints the domain name of the host it is running on\&. It uses the same algorithm as the
\fBglobus\-hostname\fR
command\&. Setting the
\fBGLOBUS_HOSTNAME\fR
environment variable will override values returned from gethostname() and gethostbyname()\&.
.PP
\fB\-help\fR
.RS 4
Show usage information and exit\&.
.RE
.PP
\fB\-version\fR
.RS 4
Show version information and exit\&.
.RE
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Successful program execution\&.
.RE
.SH "AUTHOR"
.br
.br
The Globus Alliance, http://www\&.globus\&.org/
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 1999-2012 University of Chicago
.br
