'\" t
.\"     Title: globus-sh-exec
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/09/2012
.\"    Manual: Globus Tookit
.\"    Source: The Globus Alliance
.\"  Language: English
.\"
.TH "GLOBUS\-SH\-EXEC" "1" "02/09/2012" "The Globus Alliance" "Globus Tookit"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-sh-exec \- Defines a set of GLOBUS_SH_ variables\&.
.SH "SYNOPSIS"
.HP \w'\fBglobus\-sh\-exec\fR\ 'u
\fBglobus\-sh\-exec\fR [\fBoptions\fR]
.SH "DESCRIPTION"
.PP
Defines a set of GLOBUS_SH_ variables, then sources a user script\&. The user script is a local file, or can be referred to with a GASS URL\&.
.PP
Additional arguments "args \&.\&.\&." are passed on to the user script\&.
.PP
\fB\-help\fR
.RS 4
Shows help and exists
.RE
.PP
\fB\-usage\fR
.RS 4
Shows help and exists
.RE
.PP
\fB\-version\fR
.RS 4
Shows version and exits
.RE
.PP
\fB\-list\fR, \fB\-l\fR
.RS 4
Lists the defined GLOBUS_ variables and exits
.RE
.PP
\fB\-exec\fR, \fB\-e\fR
.RS 4
Commands are read from the argument line
.RE
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Successful program execution\&.
.RE
.SH "AUTHOR"
.br
.br
The Globus Alliance, http://www\&.globus\&.org/
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 1999-2012 University of Chicago
.br
