<TestDependencies>

<Binary_Dependencies Type="Compile">
<Dependency Name="foo1" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="foo2" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="foo3" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="foo4" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="foo5" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
</Binary_Dependencies>

<Binary_Dependencies Type="Build_Link">
<Dependency Name="fee1" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fee2" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fee3" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fee4" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fee5" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
</Binary_Dependencies>

<Binary_Dependencies Type="Regeneration">
<Dependency Name="fow1" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fow2" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fow3" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fow4" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fow5" Package="dev">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
</Binary_Dependencies>

<Binary_Dependencies Type="Runtime_Link">
<Dependency Name="fum1" Package="rtl">
<Version>
<Simple_Version Major="2"/>
<Version_Range Upper_Major="2" Lower_Major="2" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fum2" Package="rtl">
<Version>
<Simple_Version Major="2"/>
<Version_Range Upper_Major="2" Lower_Major="2" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fum3" Package="rtl">
<Version>
<Simple_Version Major="2"/>
<Version_Range Upper_Major="2" Lower_Major="2" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fum4" Package="rtl">
<Version>
<Simple_Version Major="2"/>
<Version_Range Upper_Major="2" Lower_Major="2" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fum5" Package="rtl">
<Version>
<Simple_Version Major="2"/>
<Version_Range Upper_Major="2" Lower_Major="2" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
</Binary_Dependencies>

<Binary_Dependencies Type="Runtime">
<Dependency Name="fewy1" Package="pgm">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fewy2" Package="pgm">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fewy3" Package="pgm">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fewy4" Package="pgm">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="fewy5" Package="pgm">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
</Binary_Dependencies>

</TestDependencies>
