<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gpt_package_metadata SYSTEM "globus_package.dtd">
<gpt_package_metadata Format_Version="0.01" Name="foo" >
<Aging_Version Age="1" Major="3" Minor="5" />
<Description >
        This is the brand new package foo.
        
        Its really cool!
 </Description>
<Functional_Group >I/Am/Somebody/Because/I/Belong</Functional_Group>
<Version_Stability Release="experimental" />
<data_pkg >
<Flavor >noflavor</Flavor>
<Binary_Dependencies Type="Runtime" >
<Dependency Name="data_fee" Package="data" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="data_fow" Package="data" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="data_fum" Package="data" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
</Binary_Dependencies>
<Post_Install_Message >
      You need to run run_me
 </Post_Install_Message>
<Post_Install_Program >
      run_me
 </Post_Install_Program>
<Setup Name="setmeup" >
<Aging_Version Age="2" Major="5" Minor="5" />
</Setup>
</data_pkg>
</gpt_package_metadata>
