$VAR1 = [
          bless( {
                   'versions' => [
                                   bless( {
                                            'minor' => undef,
                                            'lower_major' => undef,
                                            'major' => '2',
                                            'upper_minor' => undef,
                                            'lower_minor' => undef,
                                            'type' => 'simple',
                                            'age' => undef,
                                            'upper_major' => undef
                                          }, 'Grid::GPT::V1::Version' )
                                 ],
                   'deptype' => 'lib_link',
                   'flavor' => undef,
                   'depnode' => bless( {
                                         'versions' => $VAR1->[0]{'versions'},
                                         'index' => [
                                                      'name',
                                                      'type',
                                                      'pkg_type'
                                                    ],
                                         'pkg_type' => undef,
                                         'type' => 'lib_link',
                                         'name' => 'low'
                                       }, 'Grid::GPT::V1::SourceDependency' ),
                   'pkgtype' => undef,
                   'pkgname' => 'low'
                 }, 'Grid::GPT::DepNode' ),
          bless( {
                   'versions' => [
                                   bless( {
                                            'minor' => undef,
                                            'lower_major' => undef,
                                            'major' => '2',
                                            'upper_minor' => undef,
                                            'lower_minor' => undef,
                                            'type' => 'simple',
                                            'age' => undef,
                                            'upper_major' => undef
                                          }, 'Grid::GPT::V1::Version' )
                                 ],
                   'deptype' => 'lib_link',
                   'flavor' => undef,
                   'depnode' => bless( {
                                         'versions' => $VAR1->[1]{'versions'},
                                         'index' => [
                                                      'name',
                                                      'type',
                                                      'pkg_type'
                                                    ],
                                         'pkg_type' => undef,
                                         'type' => 'lib_link',
                                         'name' => 'lee'
                                       }, 'Grid::GPT::V1::SourceDependency' ),
                   'pkgtype' => undef,
                   'pkgname' => 'lee'
                 }, 'Grid::GPT::DepNode' ),
          bless( {
                   'versions' => [
                                   bless( {
                                            'minor' => undef,
                                            'lower_major' => undef,
                                            'major' => '2',
                                            'upper_minor' => undef,
                                            'lower_minor' => undef,
                                            'type' => 'simple',
                                            'age' => undef,
                                            'upper_major' => undef
                                          }, 'Grid::GPT::V1::Version' )
                                 ],
                   'deptype' => 'lib_link',
                   'flavor' => undef,
                   'depnode' => bless( {
                                         'versions' => $VAR1->[2]{'versions'},
                                         'index' => [
                                                      'name',
                                                      'type',
                                                      'pkg_type'
                                                    ],
                                         'pkg_type' => undef,
                                         'type' => 'lib_link',
                                         'name' => 'lum'
                                       }, 'Grid::GPT::V1::SourceDependency' ),
                   'pkgtype' => undef,
                   'pkgname' => 'lum'
                 }, 'Grid::GPT::DepNode' )
        ];
