<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gpt_package_metadata SYSTEM "package.dtd">
<flavors Format_Version="0.1" >
<flavor_definition label="dingbat1" >
<config nolabel="CPP" switch="CPP='/usr/bin/cc -E'" />
<config nolabel="CFLAGS" switch="CFLAGS='-g   '" />
<config nolabel="LD" switch="LD=/usr/bin/cc" />
<config nolabel="LIBS" switch="LIBS='  -lpthread'" />
<config nolabel="CXX" switch="CXX=/usr/bin/c++" />
<config nolabel="CXXCPP" switch="CXXCPP='/usr/bin/c++ -E'" />
<config nolabel="CXXFLAGS" switch="CXXFLAGS='-g   '" />
<config nolabel="F77" switch="F77=/usr/bin/f77" />
<config nolabel="AR" switch="AR=/usr/bin/ar" />
<config nolabel="ARFLAGS" switch="ARFLAGS=ruv" />
<config nolabel="RANLIB" switch="RANLIB=/usr/bin/ranlib" />
<config label="gcc" switch="CC=/usr/bin/cc" />
<config label="32" />
<config label="solthr" switch="--with-threads=solaristhreads" />
<config label="dbg" switch="--enable-debug" />
<config nolabel="nomp" />
</flavor_definition>
</flavors>
