GPT_DESCRIPTION_GPT: 
              This is the brand new package foo.
              
              Its really cool!
       
GPT_FLAVOR_GPT: noflavor
GPT_GROUP_GPT: I/Am/Somebody/Because/I/Belong
GPT_NAME_GPT: foo
GPT_PACKAGE_GPT: foo_noflavor_doc
GPT_PKGTYPE_GPT: doc
GPT_PROVIDES_GPT: foo_doc-2, foo_doc-3, foo_doc-3.5, foo_doc
GPT_REQUIRES_GPT: Requires:  doc_fee_doc-2,  doc_fow_doc-2,  doc_fum_doc-2
GPT_SUMMARY_GPT: foo_noflavor_doc experimental version
GPT_VERSION_GPT: 3.5
