++++++++++++++++Table++++++++++++++++++
/pkgname=cfee/flavor=bitter/pkgtype=dev/setupname=NONE-> cfee-bitter-dev
Dependencies:
----------
/deptype=Compile/pkgname=cfum/flavor=bitter/pkgtype=dev-> /from=cfee-bitter-dev/dep=cfum-bitter-dev/to=cfum-bitter-dev/tag=cfum-bitter-dev
----------
Provides:
----------
/deptype=Compile/pkgname=cfoo/flavor=bitter/pkgtype=dev-> /from=cfoo-bitter-dev/dep=cfee-bitter-dev/to=cfee-bitter-dev/tag=cfee-bitter-dev
/deptype=Compile/pkgname=cfuu/flavor=bitter/pkgtype=dev-> /from=cfuu-bitter-dev/dep=cfee-bitter-dev/to=cfee-bitter-dev/tag=cfee-bitter-dev
----------
/pkgname=cfoo/flavor=bitter/pkgtype=dev/setupname=NONE-> cfoo-bitter-dev
Dependencies:
----------
/deptype=Compile/pkgname=cfee/flavor=bitter/pkgtype=dev-> /from=cfoo-bitter-dev/dep=cfee-bitter-dev/to=cfee-bitter-dev/tag=cfee-bitter-dev
/deptype=Compile/pkgname=cfue/flavor=bitter/pkgtype=dev-> /from=cfoo-bitter-dev/dep=cfue-bitter-dev/to=cfue-bitter-dev/tag=cfue-bitter-dev
----------
Provides:
----------
----------
/pkgname=cfue/flavor=bitter/pkgtype=dev/setupname=NONE-> cfue-bitter-dev
Dependencies:
----------
----------
Provides:
----------
/deptype=Compile/pkgname=cfoo/flavor=bitter/pkgtype=dev-> /from=cfoo-bitter-dev/dep=cfue-bitter-dev/to=cfue-bitter-dev/tag=cfue-bitter-dev
/deptype=Compile/pkgname=cfuu/flavor=bitter/pkgtype=dev-> /from=cfuu-bitter-dev/dep=cfue-bitter-dev/to=cfue-bitter-dev/tag=cfue-bitter-dev
----------
/pkgname=cfum/flavor=bitter/pkgtype=dev/setupname=NONE-> cfum-bitter-dev
Dependencies:
----------
----------
Provides:
----------
/deptype=Compile/pkgname=cfee/flavor=bitter/pkgtype=dev-> /from=cfee-bitter-dev/dep=cfum-bitter-dev/to=cfum-bitter-dev/tag=cfum-bitter-dev
----------
/pkgname=cfuu/flavor=bitter/pkgtype=dev/setupname=NONE-> cfuu-bitter-dev
Dependencies:
----------
/deptype=Compile/pkgname=cfee/flavor=bitter/pkgtype=dev-> /from=cfuu-bitter-dev/dep=cfee-bitter-dev/to=cfee-bitter-dev/tag=cfee-bitter-dev
/deptype=Compile/pkgname=cfue/flavor=bitter/pkgtype=dev-> /from=cfuu-bitter-dev/dep=cfue-bitter-dev/to=cfue-bitter-dev/tag=cfue-bitter-dev
----------
Provides:
----------
----------
/pkgname=crtfee/flavor=bitter/pkgtype=data/setupname=NONE-> crtfee-bitter-data
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=crtfee/flavor=bitter/pkgtype=doc/setupname=NONE-> crtfee-bitter-doc
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=crtfee/flavor=bitter/pkgtype=pgm/setupname=NONE-> crtfee-bitter-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=crtfee/flavor=bitter/pkgtype=rtl/setupname=NONE-> crtfee-bitter-rtl
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=crtfix/flavor=bitter/pkgtype=pgm_static/setupname=NONE-> crtfix-bitter-pgm_static
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=crtfoo/flavor=bitter/pkgtype=pgm/setupname=NONE-> crtfoo-bitter-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=crtfox/flavor=noflavor/pkgtype=pgm/setupname=NONE-> crtfox-noflavor-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=crtfue/flavor=bitter/pkgtype=data/setupname=NONE-> crtfue-bitter-data
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=crtfue/flavor=bitter/pkgtype=doc/setupname=NONE-> crtfue-bitter-doc
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=crtfue/flavor=bitter/pkgtype=pgm/setupname=NONE-> crtfue-bitter-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=crtfue/flavor=bitter/pkgtype=rtl/setupname=NONE-> crtfue-bitter-rtl
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=crtfum/flavor=bitter/pkgtype=doc/setupname=NONE-> crtfum-bitter-doc
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=crtfur/flavor=noflavor/pkgtype=pgm_static/setupname=NONE-> crtfur-noflavor-pgm_static
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=crtfuu/flavor=bitter/pkgtype=doc/setupname=NONE-> crtfuu-bitter-doc
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=installed_complex_link_dev/flavor=bitter/pkgtype=dev/setupname=NONE-> installed_complex_link_dev-bitter-dev
Dependencies:
----------
/deptype=Build_Link/pkgname=lcomplexfigi/flavor=bitter/pkgtype=dev-> /from=installed_complex_link_dev-bitter-dev/dep=lcomplexfigi-bitter-dev/to=lcomplexfigi-bitter-dev/tag=lcomplexfigi-bitter-dev
/deptype=Build_Link/pkgname=lcomplexfoo/flavor=bitter/pkgtype=dev-> /from=installed_complex_link_dev-bitter-dev/dep=lcomplexfoo-bitter-dev/to=lcomplexfoo-bitter-dev/tag=lcomplexfoo-bitter-dev
/deptype=Build_Link/pkgname=lcomplexfuu/flavor=bitter/pkgtype=dev-> /from=installed_complex_link_dev-bitter-dev/dep=lcomplexfuu-bitter-dev/to=lcomplexfuu-bitter-dev/tag=lcomplexfuu-bitter-dev
----------
Provides:
----------
----------
/pkgname=installed_complex_link_rtl/flavor=bitter/pkgtype=rtl/setupname=NONE-> installed_complex_link_rtl-bitter-rtl
Dependencies:
----------
/deptype=Runtime_Link/pkgname=lcomplexfigi/flavor=bitter/pkgtype=rtl-> /from=installed_complex_link_rtl-bitter-rtl/dep=lcomplexfigi-bitter-rtl/to=lcomplexfigi-bitter-rtl/tag=lcomplexfigi-bitter-rtl
/deptype=Runtime_Link/pkgname=lcomplexfoo/flavor=bitter/pkgtype=rtl-> /from=installed_complex_link_rtl-bitter-rtl/dep=lcomplexfoo-bitter-rtl/to=lcomplexfoo-bitter-rtl/tag=lcomplexfoo-bitter-rtl
/deptype=Runtime_Link/pkgname=lcomplexfuu/flavor=bitter/pkgtype=rtl-> /from=installed_complex_link_rtl-bitter-rtl/dep=lcomplexfuu-bitter-rtl/to=lcomplexfuu-bitter-rtl/tag=lcomplexfuu-bitter-rtl
----------
Provides:
----------
----------
/pkgname=installed_complexruntime_data/flavor=bitter/pkgtype=data/setupname=NONE-> installed_complexruntime_data-bitter-data
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=installed_complexruntime_doc/flavor=bitter/pkgtype=doc/setupname=NONE-> installed_complexruntime_doc-bitter-doc
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=installed_complexruntime_lib/flavor=bitter/pkgtype=rtl/setupname=NONE-> installed_complexruntime_lib-bitter-rtl
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=installed_complexruntime_pgm/flavor=bitter/pkgtype=pgm/setupname=NONE-> installed_complexruntime_pgm-bitter-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=installed_link_dev/flavor=bitter/pkgtype=dev/setupname=NONE-> installed_link_dev-bitter-dev
Dependencies:
----------
/deptype=Build_Link/pkgname=lfoo/flavor=bitter/pkgtype=dev-> /from=installed_link_dev-bitter-dev/dep=lfoo-bitter-dev/to=lfoo-bitter-dev/tag=lfoo-bitter-dev
/deptype=Build_Link/pkgname=lfuu/flavor=bitter/pkgtype=dev-> /from=installed_link_dev-bitter-dev/dep=lfuu-bitter-dev/to=lfuu-bitter-dev/tag=lfuu-bitter-dev
----------
Provides:
----------
----------
/pkgname=installed_link_rtl/flavor=bitter/pkgtype=rtl/setupname=NONE-> installed_link_rtl-bitter-rtl
Dependencies:
----------
/deptype=Runtime_Link/pkgname=lfoo/flavor=bitter/pkgtype=rtl-> /from=installed_link_rtl-bitter-rtl/dep=lfoo-bitter-rtl/to=lfoo-bitter-rtl/tag=lfoo-bitter-rtl
/deptype=Runtime_Link/pkgname=lfuu/flavor=bitter/pkgtype=rtl-> /from=installed_link_rtl-bitter-rtl/dep=lfuu-bitter-rtl/to=lfuu-bitter-rtl/tag=lfuu-bitter-rtl
----------
Provides:
----------
----------
/pkgname=installed_runtime_data/flavor=bitter/pkgtype=data/setupname=NONE-> installed_runtime_data-bitter-data
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=installed_runtime_doc/flavor=bitter/pkgtype=doc/setupname=NONE-> installed_runtime_doc-bitter-doc
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=installed_runtime_lib/flavor=bitter/pkgtype=rtl/setupname=NONE-> installed_runtime_lib-bitter-rtl
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=installed_runtime_pgm/flavor=bitter/pkgtype=pgm/setupname=NONE-> installed_runtime_pgm-bitter-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=installed_setup_data/flavor=bitter/pkgtype=data/setupname=NONE-> installed_setup_data-bitter-data
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=installed_setup_doc/flavor=bitter/pkgtype=doc/setupname=NONE-> installed_setup_doc-bitter-doc
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=installed_setup_lib/flavor=bitter/pkgtype=rtl/setupname=NONE-> installed_setup_lib-bitter-rtl
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=installed_setup_pgm/flavor=bitter/pkgtype=pgm/setupname=NONE-> installed_setup_pgm-bitter-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=lcomplexfee/flavor=bitter/pkgtype=dev/setupname=NONE-> lcomplexfee-bitter-dev
Dependencies:
----------
/deptype=Build_Link/pkgname=lcomplexfum/flavor=bitter/pkgtype=dev-> /from=lcomplexfee-bitter-dev/dep=lcomplexfum-bitter-dev/to=lcomplexfum-bitter-dev/tag=lcomplexfum-bitter-dev
----------
Provides:
----------
/deptype=Build_Link/pkgname=lcomplexfoo/flavor=bitter/pkgtype=dev-> /from=lcomplexfoo-bitter-dev/dep=lcomplexfee-bitter-dev/to=lcomplexfee-bitter-dev/tag=lcomplexfee-bitter-dev
/deptype=Build_Link/pkgname=lcomplexfue/flavor=bitter/pkgtype=dev-> /from=lcomplexfue-bitter-dev/dep=lcomplexfee-bitter-dev/to=lcomplexfee-bitter-dev/tag=lcomplexfee-bitter-dev
/deptype=Build_Link/pkgname=lcomplexfuu/flavor=bitter/pkgtype=dev-> /from=lcomplexfuu-bitter-dev/dep=lcomplexfee-bitter-dev/to=lcomplexfee-bitter-dev/tag=lcomplexfee-bitter-dev
----------
/pkgname=lcomplexfee/flavor=bitter/pkgtype=rtl/setupname=NONE-> lcomplexfee-bitter-rtl
Dependencies:
----------
/deptype=Runtime_Link/pkgname=lcomplexfum/flavor=bitter/pkgtype=rtl-> /from=lcomplexfee-bitter-rtl/dep=lcomplexfum-bitter-rtl/to=lcomplexfum-bitter-rtl/tag=lcomplexfum-bitter-rtl
----------
Provides:
----------
/deptype=Runtime_Link/pkgname=lcomplexfoo/flavor=bitter/pkgtype=rtl-> /from=lcomplexfoo-bitter-rtl/dep=lcomplexfee-bitter-rtl/to=lcomplexfee-bitter-rtl/tag=lcomplexfee-bitter-rtl
/deptype=Runtime_Link/pkgname=lcomplexfue/flavor=bitter/pkgtype=rtl-> /from=lcomplexfue-bitter-rtl/dep=lcomplexfee-bitter-rtl/to=lcomplexfee-bitter-rtl/tag=lcomplexfee-bitter-rtl
/deptype=Runtime_Link/pkgname=lcomplexfuu/flavor=bitter/pkgtype=rtl-> /from=lcomplexfuu-bitter-rtl/dep=lcomplexfee-bitter-rtl/to=lcomplexfee-bitter-rtl/tag=lcomplexfee-bitter-rtl
----------
/pkgname=lcomplexfigi/flavor=bitter/pkgtype=dev/setupname=NONE-> lcomplexfigi-bitter-dev
Dependencies:
----------
----------
Provides:
----------
/deptype=Build_Link/pkgname=installed_complex_link_dev/flavor=bitter/pkgtype=dev-> /from=installed_complex_link_dev-bitter-dev/dep=lcomplexfigi-bitter-dev/to=lcomplexfigi-bitter-dev/tag=lcomplexfigi-bitter-dev
/deptype=Build_Link/pkgname=lcomplexfue/flavor=bitter/pkgtype=dev-> /from=lcomplexfue-bitter-dev/dep=lcomplexfigi-bitter-dev/to=lcomplexfigi-bitter-dev/tag=lcomplexfigi-bitter-dev
/deptype=Build_Link/pkgname=lcomplexfum/flavor=bitter/pkgtype=dev-> /from=lcomplexfum-bitter-dev/dep=lcomplexfigi-bitter-dev/to=lcomplexfigi-bitter-dev/tag=lcomplexfigi-bitter-dev
/deptype=Build_Link/pkgname=lcomplexfuu/flavor=bitter/pkgtype=dev-> /from=lcomplexfuu-bitter-dev/dep=lcomplexfigi-bitter-dev/to=lcomplexfigi-bitter-dev/tag=lcomplexfigi-bitter-dev
/deptype=pgm_link/pkgname=source_complex_link_dev/flavor=ANY/pkgtype=dev-> /from=source_complex_link_dev-ANY-src/dep=lcomplexfigi-ANY-dev/to=lcomplexfigi-bitter-dev/tag=lcomplexfigi-ANY-dev
/deptype=pgm_link/pkgname=source_complex_link_rtl/flavor=ANY/pkgtype=dev-> /from=source_complex_link_rtl-ANY-src/dep=lcomplexfigi-ANY-dev/to=lcomplexfigi-bitter-dev/tag=lcomplexfigi-ANY-dev
----------
/pkgname=lcomplexfigi/flavor=bitter/pkgtype=rtl/setupname=NONE-> lcomplexfigi-bitter-rtl
Dependencies:
----------
----------
Provides:
----------
/deptype=Runtime_Link/pkgname=installed_complex_link_rtl/flavor=bitter/pkgtype=rtl-> /from=installed_complex_link_rtl-bitter-rtl/dep=lcomplexfigi-bitter-rtl/to=lcomplexfigi-bitter-rtl/tag=lcomplexfigi-bitter-rtl
/deptype=Runtime_Link/pkgname=lcomplexfue/flavor=bitter/pkgtype=rtl-> /from=lcomplexfue-bitter-rtl/dep=lcomplexfigi-bitter-rtl/to=lcomplexfigi-bitter-rtl/tag=lcomplexfigi-bitter-rtl
/deptype=Runtime_Link/pkgname=lcomplexfum/flavor=bitter/pkgtype=rtl-> /from=lcomplexfum-bitter-rtl/dep=lcomplexfigi-bitter-rtl/to=lcomplexfigi-bitter-rtl/tag=lcomplexfigi-bitter-rtl
/deptype=Runtime_Link/pkgname=lcomplexfuu/flavor=bitter/pkgtype=rtl-> /from=lcomplexfuu-bitter-rtl/dep=lcomplexfigi-bitter-rtl/to=lcomplexfigi-bitter-rtl/tag=lcomplexfigi-bitter-rtl
/deptype=pgm_link/pkgname=source_complex_link_dev/flavor=ANY/pkgtype=rtl-> /from=source_complex_link_dev-ANY-src/dep=lcomplexfigi-ANY-dev/to=lcomplexfigi-bitter-rtl/tag=lcomplexfigi-ANY-rtl
/deptype=pgm_link/pkgname=source_complex_link_rtl/flavor=ANY/pkgtype=rtl-> /from=source_complex_link_rtl-ANY-src/dep=lcomplexfigi-ANY-dev/to=lcomplexfigi-bitter-rtl/tag=lcomplexfigi-ANY-rtl
----------
/pkgname=lcomplexfoo/flavor=bitter/pkgtype=dev/setupname=NONE-> lcomplexfoo-bitter-dev
Dependencies:
----------
/deptype=Build_Link/pkgname=lcomplexfee/flavor=bitter/pkgtype=dev-> /from=lcomplexfoo-bitter-dev/dep=lcomplexfee-bitter-dev/to=lcomplexfee-bitter-dev/tag=lcomplexfee-bitter-dev
/deptype=Build_Link/pkgname=lcomplexfue/flavor=bitter/pkgtype=dev-> /from=lcomplexfoo-bitter-dev/dep=lcomplexfue-bitter-dev/to=lcomplexfue-bitter-dev/tag=lcomplexfue-bitter-dev
----------
Provides:
----------
/deptype=Build_Link/pkgname=installed_complex_link_dev/flavor=bitter/pkgtype=dev-> /from=installed_complex_link_dev-bitter-dev/dep=lcomplexfoo-bitter-dev/to=lcomplexfoo-bitter-dev/tag=lcomplexfoo-bitter-dev
/deptype=Build_Link/pkgname=lcomplexfuu/flavor=bitter/pkgtype=dev-> /from=lcomplexfuu-bitter-dev/dep=lcomplexfoo-bitter-dev/to=lcomplexfoo-bitter-dev/tag=lcomplexfoo-bitter-dev
/deptype=pgm_link/pkgname=source_complex_link_dev/flavor=ANY/pkgtype=dev-> /from=source_complex_link_dev-ANY-src/dep=lcomplexfoo-ANY-dev/to=lcomplexfoo-bitter-dev/tag=lcomplexfoo-ANY-dev
/deptype=pgm_link/pkgname=source_complex_link_rtl/flavor=ANY/pkgtype=dev-> /from=source_complex_link_rtl-ANY-src/dep=lcomplexfoo-ANY-dev/to=lcomplexfoo-bitter-dev/tag=lcomplexfoo-ANY-dev
----------
/pkgname=lcomplexfoo/flavor=bitter/pkgtype=rtl/setupname=NONE-> lcomplexfoo-bitter-rtl
Dependencies:
----------
/deptype=Runtime_Link/pkgname=lcomplexfee/flavor=bitter/pkgtype=rtl-> /from=lcomplexfoo-bitter-rtl/dep=lcomplexfee-bitter-rtl/to=lcomplexfee-bitter-rtl/tag=lcomplexfee-bitter-rtl
/deptype=Runtime_Link/pkgname=lcomplexfue/flavor=bitter/pkgtype=rtl-> /from=lcomplexfoo-bitter-rtl/dep=lcomplexfue-bitter-rtl/to=lcomplexfue-bitter-rtl/tag=lcomplexfue-bitter-rtl
----------
Provides:
----------
/deptype=Runtime_Link/pkgname=installed_complex_link_rtl/flavor=bitter/pkgtype=rtl-> /from=installed_complex_link_rtl-bitter-rtl/dep=lcomplexfoo-bitter-rtl/to=lcomplexfoo-bitter-rtl/tag=lcomplexfoo-bitter-rtl
/deptype=Runtime_Link/pkgname=lcomplexfuu/flavor=bitter/pkgtype=rtl-> /from=lcomplexfuu-bitter-rtl/dep=lcomplexfoo-bitter-rtl/to=lcomplexfoo-bitter-rtl/tag=lcomplexfoo-bitter-rtl
/deptype=pgm_link/pkgname=source_complex_link_dev/flavor=ANY/pkgtype=rtl-> /from=source_complex_link_dev-ANY-src/dep=lcomplexfoo-ANY-dev/to=lcomplexfoo-bitter-rtl/tag=lcomplexfoo-ANY-rtl
/deptype=pgm_link/pkgname=source_complex_link_rtl/flavor=ANY/pkgtype=rtl-> /from=source_complex_link_rtl-ANY-src/dep=lcomplexfoo-ANY-dev/to=lcomplexfoo-bitter-rtl/tag=lcomplexfoo-ANY-rtl
----------
/pkgname=lcomplexfue/flavor=bitter/pkgtype=dev/setupname=NONE-> lcomplexfue-bitter-dev
Dependencies:
----------
/deptype=Build_Link/pkgname=lcomplexfee/flavor=bitter/pkgtype=dev-> /from=lcomplexfue-bitter-dev/dep=lcomplexfee-bitter-dev/to=lcomplexfee-bitter-dev/tag=lcomplexfee-bitter-dev
/deptype=Build_Link/pkgname=lcomplexfigi/flavor=bitter/pkgtype=dev-> /from=lcomplexfue-bitter-dev/dep=lcomplexfigi-bitter-dev/to=lcomplexfigi-bitter-dev/tag=lcomplexfigi-bitter-dev
----------
Provides:
----------
/deptype=Build_Link/pkgname=lcomplexfoo/flavor=bitter/pkgtype=dev-> /from=lcomplexfoo-bitter-dev/dep=lcomplexfue-bitter-dev/to=lcomplexfue-bitter-dev/tag=lcomplexfue-bitter-dev
----------
/pkgname=lcomplexfue/flavor=bitter/pkgtype=rtl/setupname=NONE-> lcomplexfue-bitter-rtl
Dependencies:
----------
/deptype=Runtime_Link/pkgname=lcomplexfee/flavor=bitter/pkgtype=rtl-> /from=lcomplexfue-bitter-rtl/dep=lcomplexfee-bitter-rtl/to=lcomplexfee-bitter-rtl/tag=lcomplexfee-bitter-rtl
/deptype=Runtime_Link/pkgname=lcomplexfigi/flavor=bitter/pkgtype=rtl-> /from=lcomplexfue-bitter-rtl/dep=lcomplexfigi-bitter-rtl/to=lcomplexfigi-bitter-rtl/tag=lcomplexfigi-bitter-rtl
----------
Provides:
----------
/deptype=Runtime_Link/pkgname=lcomplexfoo/flavor=bitter/pkgtype=rtl-> /from=lcomplexfoo-bitter-rtl/dep=lcomplexfue-bitter-rtl/to=lcomplexfue-bitter-rtl/tag=lcomplexfue-bitter-rtl
----------
/pkgname=lcomplexfum/flavor=bitter/pkgtype=dev/setupname=NONE-> lcomplexfum-bitter-dev
Dependencies:
----------
/deptype=Build_Link/pkgname=lcomplexfigi/flavor=bitter/pkgtype=dev-> /from=lcomplexfum-bitter-dev/dep=lcomplexfigi-bitter-dev/to=lcomplexfigi-bitter-dev/tag=lcomplexfigi-bitter-dev
----------
Provides:
----------
/deptype=Build_Link/pkgname=lcomplexfee/flavor=bitter/pkgtype=dev-> /from=lcomplexfee-bitter-dev/dep=lcomplexfum-bitter-dev/to=lcomplexfum-bitter-dev/tag=lcomplexfum-bitter-dev
----------
/pkgname=lcomplexfum/flavor=bitter/pkgtype=rtl/setupname=NONE-> lcomplexfum-bitter-rtl
Dependencies:
----------
/deptype=Runtime_Link/pkgname=lcomplexfigi/flavor=bitter/pkgtype=rtl-> /from=lcomplexfum-bitter-rtl/dep=lcomplexfigi-bitter-rtl/to=lcomplexfigi-bitter-rtl/tag=lcomplexfigi-bitter-rtl
----------
Provides:
----------
/deptype=Runtime_Link/pkgname=lcomplexfee/flavor=bitter/pkgtype=rtl-> /from=lcomplexfee-bitter-rtl/dep=lcomplexfum-bitter-rtl/to=lcomplexfum-bitter-rtl/tag=lcomplexfum-bitter-rtl
----------
/pkgname=lcomplexfuu/flavor=bitter/pkgtype=dev/setupname=NONE-> lcomplexfuu-bitter-dev
Dependencies:
----------
/deptype=Build_Link/pkgname=lcomplexfee/flavor=bitter/pkgtype=dev-> /from=lcomplexfuu-bitter-dev/dep=lcomplexfee-bitter-dev/to=lcomplexfee-bitter-dev/tag=lcomplexfee-bitter-dev
/deptype=Build_Link/pkgname=lcomplexfigi/flavor=bitter/pkgtype=dev-> /from=lcomplexfuu-bitter-dev/dep=lcomplexfigi-bitter-dev/to=lcomplexfigi-bitter-dev/tag=lcomplexfigi-bitter-dev
/deptype=Build_Link/pkgname=lcomplexfoo/flavor=bitter/pkgtype=dev-> /from=lcomplexfuu-bitter-dev/dep=lcomplexfoo-bitter-dev/to=lcomplexfoo-bitter-dev/tag=lcomplexfoo-bitter-dev
----------
Provides:
----------
/deptype=Build_Link/pkgname=installed_complex_link_dev/flavor=bitter/pkgtype=dev-> /from=installed_complex_link_dev-bitter-dev/dep=lcomplexfuu-bitter-dev/to=lcomplexfuu-bitter-dev/tag=lcomplexfuu-bitter-dev
/deptype=pgm_link/pkgname=source_complex_link_dev/flavor=ANY/pkgtype=dev-> /from=source_complex_link_dev-ANY-src/dep=lcomplexfuu-ANY-dev/to=lcomplexfuu-bitter-dev/tag=lcomplexfuu-ANY-dev
/deptype=pgm_link/pkgname=source_complex_link_rtl/flavor=ANY/pkgtype=dev-> /from=source_complex_link_rtl-ANY-src/dep=lcomplexfuu-ANY-dev/to=lcomplexfuu-bitter-dev/tag=lcomplexfuu-ANY-dev
----------
/pkgname=lcomplexfuu/flavor=bitter/pkgtype=rtl/setupname=NONE-> lcomplexfuu-bitter-rtl
Dependencies:
----------
/deptype=Runtime_Link/pkgname=lcomplexfee/flavor=bitter/pkgtype=rtl-> /from=lcomplexfuu-bitter-rtl/dep=lcomplexfee-bitter-rtl/to=lcomplexfee-bitter-rtl/tag=lcomplexfee-bitter-rtl
/deptype=Runtime_Link/pkgname=lcomplexfigi/flavor=bitter/pkgtype=rtl-> /from=lcomplexfuu-bitter-rtl/dep=lcomplexfigi-bitter-rtl/to=lcomplexfigi-bitter-rtl/tag=lcomplexfigi-bitter-rtl
/deptype=Runtime_Link/pkgname=lcomplexfoo/flavor=bitter/pkgtype=rtl-> /from=lcomplexfuu-bitter-rtl/dep=lcomplexfoo-bitter-rtl/to=lcomplexfoo-bitter-rtl/tag=lcomplexfoo-bitter-rtl
----------
Provides:
----------
/deptype=Runtime_Link/pkgname=installed_complex_link_rtl/flavor=bitter/pkgtype=rtl-> /from=installed_complex_link_rtl-bitter-rtl/dep=lcomplexfuu-bitter-rtl/to=lcomplexfuu-bitter-rtl/tag=lcomplexfuu-bitter-rtl
/deptype=pgm_link/pkgname=source_complex_link_dev/flavor=ANY/pkgtype=rtl-> /from=source_complex_link_dev-ANY-src/dep=lcomplexfuu-ANY-dev/to=lcomplexfuu-bitter-rtl/tag=lcomplexfuu-ANY-rtl
/deptype=pgm_link/pkgname=source_complex_link_rtl/flavor=ANY/pkgtype=rtl-> /from=source_complex_link_rtl-ANY-src/dep=lcomplexfuu-ANY-dev/to=lcomplexfuu-bitter-rtl/tag=lcomplexfuu-ANY-rtl
----------
/pkgname=lfee/flavor=bitter/pkgtype=dev/setupname=NONE-> lfee-bitter-dev
Dependencies:
----------
/deptype=Build_Link/pkgname=lfum/flavor=bitter/pkgtype=dev-> /from=lfee-bitter-dev/dep=lfum-bitter-dev/to=lfum-bitter-dev/tag=lfum-bitter-dev
----------
Provides:
----------
/deptype=Build_Link/pkgname=lfoo/flavor=bitter/pkgtype=dev-> /from=lfoo-bitter-dev/dep=lfee-bitter-dev/to=lfee-bitter-dev/tag=lfee-bitter-dev
/deptype=Build_Link/pkgname=lfuu/flavor=bitter/pkgtype=dev-> /from=lfuu-bitter-dev/dep=lfee-bitter-dev/to=lfee-bitter-dev/tag=lfee-bitter-dev
----------
/pkgname=lfee/flavor=bitter/pkgtype=rtl/setupname=NONE-> lfee-bitter-rtl
Dependencies:
----------
/deptype=Runtime_Link/pkgname=lfum/flavor=bitter/pkgtype=rtl-> /from=lfee-bitter-rtl/dep=lfum-bitter-rtl/to=lfum-bitter-rtl/tag=lfum-bitter-rtl
----------
Provides:
----------
/deptype=Runtime_Link/pkgname=lfoo/flavor=bitter/pkgtype=rtl-> /from=lfoo-bitter-rtl/dep=lfee-bitter-rtl/to=lfee-bitter-rtl/tag=lfee-bitter-rtl
/deptype=Runtime_Link/pkgname=lfuu/flavor=bitter/pkgtype=rtl-> /from=lfuu-bitter-rtl/dep=lfee-bitter-rtl/to=lfee-bitter-rtl/tag=lfee-bitter-rtl
----------
/pkgname=lfoo/flavor=bitter/pkgtype=dev/setupname=NONE-> lfoo-bitter-dev
Dependencies:
----------
/deptype=Build_Link/pkgname=lfee/flavor=bitter/pkgtype=dev-> /from=lfoo-bitter-dev/dep=lfee-bitter-dev/to=lfee-bitter-dev/tag=lfee-bitter-dev
/deptype=Build_Link/pkgname=lfue/flavor=bitter/pkgtype=dev-> /from=lfoo-bitter-dev/dep=lfue-bitter-dev/to=lfue-bitter-dev/tag=lfue-bitter-dev
----------
Provides:
----------
/deptype=Build_Link/pkgname=installed_link_dev/flavor=bitter/pkgtype=dev-> /from=installed_link_dev-bitter-dev/dep=lfoo-bitter-dev/to=lfoo-bitter-dev/tag=lfoo-bitter-dev
/deptype=pgm_link/pkgname=source_link_dev/flavor=ANY/pkgtype=dev-> /from=source_link_dev-ANY-src/dep=lfoo-ANY-dev/to=lfoo-bitter-dev/tag=lfoo-ANY-dev
/deptype=pgm_link/pkgname=source_link_rtl/flavor=ANY/pkgtype=dev-> /from=source_link_rtl-ANY-src/dep=lfoo-ANY-dev/to=lfoo-bitter-dev/tag=lfoo-ANY-dev
----------
/pkgname=lfoo/flavor=bitter/pkgtype=rtl/setupname=NONE-> lfoo-bitter-rtl
Dependencies:
----------
/deptype=Runtime_Link/pkgname=lfee/flavor=bitter/pkgtype=rtl-> /from=lfoo-bitter-rtl/dep=lfee-bitter-rtl/to=lfee-bitter-rtl/tag=lfee-bitter-rtl
/deptype=Runtime_Link/pkgname=lfue/flavor=bitter/pkgtype=rtl-> /from=lfoo-bitter-rtl/dep=lfue-bitter-rtl/to=lfue-bitter-rtl/tag=lfue-bitter-rtl
----------
Provides:
----------
/deptype=Runtime_Link/pkgname=installed_link_rtl/flavor=bitter/pkgtype=rtl-> /from=installed_link_rtl-bitter-rtl/dep=lfoo-bitter-rtl/to=lfoo-bitter-rtl/tag=lfoo-bitter-rtl
/deptype=pgm_link/pkgname=source_link_dev/flavor=ANY/pkgtype=rtl-> /from=source_link_dev-ANY-src/dep=lfoo-ANY-dev/to=lfoo-bitter-rtl/tag=lfoo-ANY-rtl
/deptype=pgm_link/pkgname=source_link_rtl/flavor=ANY/pkgtype=rtl-> /from=source_link_rtl-ANY-src/dep=lfoo-ANY-dev/to=lfoo-bitter-rtl/tag=lfoo-ANY-rtl
----------
/pkgname=lfue/flavor=bitter/pkgtype=dev/setupname=NONE-> lfue-bitter-dev
Dependencies:
----------
----------
Provides:
----------
/deptype=Build_Link/pkgname=lfoo/flavor=bitter/pkgtype=dev-> /from=lfoo-bitter-dev/dep=lfue-bitter-dev/to=lfue-bitter-dev/tag=lfue-bitter-dev
/deptype=Build_Link/pkgname=lfuu/flavor=bitter/pkgtype=dev-> /from=lfuu-bitter-dev/dep=lfue-bitter-dev/to=lfue-bitter-dev/tag=lfue-bitter-dev
----------
/pkgname=lfue/flavor=bitter/pkgtype=rtl/setupname=NONE-> lfue-bitter-rtl
Dependencies:
----------
----------
Provides:
----------
/deptype=Runtime_Link/pkgname=lfoo/flavor=bitter/pkgtype=rtl-> /from=lfoo-bitter-rtl/dep=lfue-bitter-rtl/to=lfue-bitter-rtl/tag=lfue-bitter-rtl
/deptype=Runtime_Link/pkgname=lfuu/flavor=bitter/pkgtype=rtl-> /from=lfuu-bitter-rtl/dep=lfue-bitter-rtl/to=lfue-bitter-rtl/tag=lfue-bitter-rtl
----------
/pkgname=lfum/flavor=bitter/pkgtype=dev/setupname=NONE-> lfum-bitter-dev
Dependencies:
----------
----------
Provides:
----------
/deptype=Build_Link/pkgname=lfee/flavor=bitter/pkgtype=dev-> /from=lfee-bitter-dev/dep=lfum-bitter-dev/to=lfum-bitter-dev/tag=lfum-bitter-dev
----------
/pkgname=lfum/flavor=bitter/pkgtype=rtl/setupname=NONE-> lfum-bitter-rtl
Dependencies:
----------
----------
Provides:
----------
/deptype=Runtime_Link/pkgname=lfee/flavor=bitter/pkgtype=rtl-> /from=lfee-bitter-rtl/dep=lfum-bitter-rtl/to=lfum-bitter-rtl/tag=lfum-bitter-rtl
----------
/pkgname=lfuu/flavor=bitter/pkgtype=dev/setupname=NONE-> lfuu-bitter-dev
Dependencies:
----------
/deptype=Build_Link/pkgname=lfee/flavor=bitter/pkgtype=dev-> /from=lfuu-bitter-dev/dep=lfee-bitter-dev/to=lfee-bitter-dev/tag=lfee-bitter-dev
/deptype=Build_Link/pkgname=lfue/flavor=bitter/pkgtype=dev-> /from=lfuu-bitter-dev/dep=lfue-bitter-dev/to=lfue-bitter-dev/tag=lfue-bitter-dev
----------
Provides:
----------
/deptype=Build_Link/pkgname=installed_link_dev/flavor=bitter/pkgtype=dev-> /from=installed_link_dev-bitter-dev/dep=lfuu-bitter-dev/to=lfuu-bitter-dev/tag=lfuu-bitter-dev
/deptype=pgm_link/pkgname=source_link_dev/flavor=ANY/pkgtype=dev-> /from=source_link_dev-ANY-src/dep=lfuu-ANY-dev/to=lfuu-bitter-dev/tag=lfuu-ANY-dev
/deptype=pgm_link/pkgname=source_link_rtl/flavor=ANY/pkgtype=dev-> /from=source_link_rtl-ANY-src/dep=lfuu-ANY-dev/to=lfuu-bitter-dev/tag=lfuu-ANY-dev
----------
/pkgname=lfuu/flavor=bitter/pkgtype=rtl/setupname=NONE-> lfuu-bitter-rtl
Dependencies:
----------
/deptype=Runtime_Link/pkgname=lfee/flavor=bitter/pkgtype=rtl-> /from=lfuu-bitter-rtl/dep=lfee-bitter-rtl/to=lfee-bitter-rtl/tag=lfee-bitter-rtl
/deptype=Runtime_Link/pkgname=lfue/flavor=bitter/pkgtype=rtl-> /from=lfuu-bitter-rtl/dep=lfue-bitter-rtl/to=lfue-bitter-rtl/tag=lfue-bitter-rtl
----------
Provides:
----------
/deptype=Runtime_Link/pkgname=installed_link_rtl/flavor=bitter/pkgtype=rtl-> /from=installed_link_rtl-bitter-rtl/dep=lfuu-bitter-rtl/to=lfuu-bitter-rtl/tag=lfuu-bitter-rtl
/deptype=pgm_link/pkgname=source_link_dev/flavor=ANY/pkgtype=rtl-> /from=source_link_dev-ANY-src/dep=lfuu-ANY-dev/to=lfuu-bitter-rtl/tag=lfuu-ANY-rtl
/deptype=pgm_link/pkgname=source_link_rtl/flavor=ANY/pkgtype=rtl-> /from=source_link_rtl-ANY-src/dep=lfuu-ANY-dev/to=lfuu-bitter-rtl/tag=lfuu-ANY-rtl
----------
/pkgname=rtfee/flavor=bitter/pkgtype=data/setupname=NONE-> rtfee-bitter-data
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=rtfee/flavor=bitter/pkgtype=doc/setupname=NONE-> rtfee-bitter-doc
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=rtfee/flavor=bitter/pkgtype=pgm/setupname=NONE-> rtfee-bitter-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=rtfee/flavor=bitter/pkgtype=rtl/setupname=NONE-> rtfee-bitter-rtl
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=rtfoo/flavor=bitter/pkgtype=pgm/setupname=NONE-> rtfoo-bitter-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=rtfue/flavor=bitter/pkgtype=data/setupname=NONE-> rtfue-bitter-data
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=rtfue/flavor=bitter/pkgtype=doc/setupname=NONE-> rtfue-bitter-doc
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=rtfue/flavor=bitter/pkgtype=pgm/setupname=NONE-> rtfue-bitter-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=rtfue/flavor=bitter/pkgtype=rtl/setupname=NONE-> rtfue-bitter-rtl
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=rtfum/flavor=bitter/pkgtype=doc/setupname=NONE-> rtfum-bitter-doc
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=rtfuu/flavor=bitter/pkgtype=doc/setupname=NONE-> rtfuu-bitter-doc
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=setfee/flavor=noflavor/pkgtype=pgm/setupname=setfee-> /setupname=setfee:setfee-noflavor-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=setfoo/flavor=noflavor/pkgtype=pgm/setupname=setfoo-> /setupname=setfoo:setfoo-noflavor-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=setfue/flavor=noflavor/pkgtype=pgm/setupname=setfue-> /setupname=setfue:setfue-noflavor-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=setfum/flavor=noflavor/pkgtype=pgm/setupname=setfum-> /setupname=setfum:setfum-noflavor-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=setfuu/flavor=noflavor/pkgtype=pgm/setupname=setfoo-> /setupname=setfoo:setfuu-noflavor-pgm
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=source_compile_src/flavor=ANY/pkgtype=src/setupname=NONE-> source_compile_src-ANY-src
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=source_complex_link_dev/flavor=ANY/pkgtype=src/setupname=NONE-> source_complex_link_dev-ANY-src
Dependencies:
----------
/deptype=pgm_link/pkgname=lcomplexfigi/flavor=ANY/pkgtype=dev-> /from=source_complex_link_dev-ANY-src/dep=lcomplexfigi-ANY-dev/to=lcomplexfigi-bitter-dev/tag=lcomplexfigi-ANY-dev
/deptype=pgm_link/pkgname=lcomplexfigi/flavor=ANY/pkgtype=rtl-> /from=source_complex_link_dev-ANY-src/dep=lcomplexfigi-ANY-dev/to=lcomplexfigi-bitter-rtl/tag=lcomplexfigi-ANY-rtl
/deptype=pgm_link/pkgname=lcomplexfoo/flavor=ANY/pkgtype=dev-> /from=source_complex_link_dev-ANY-src/dep=lcomplexfoo-ANY-dev/to=lcomplexfoo-bitter-dev/tag=lcomplexfoo-ANY-dev
/deptype=pgm_link/pkgname=lcomplexfoo/flavor=ANY/pkgtype=rtl-> /from=source_complex_link_dev-ANY-src/dep=lcomplexfoo-ANY-dev/to=lcomplexfoo-bitter-rtl/tag=lcomplexfoo-ANY-rtl
/deptype=pgm_link/pkgname=lcomplexfuu/flavor=ANY/pkgtype=dev-> /from=source_complex_link_dev-ANY-src/dep=lcomplexfuu-ANY-dev/to=lcomplexfuu-bitter-dev/tag=lcomplexfuu-ANY-dev
/deptype=pgm_link/pkgname=lcomplexfuu/flavor=ANY/pkgtype=rtl-> /from=source_complex_link_dev-ANY-src/dep=lcomplexfuu-ANY-dev/to=lcomplexfuu-bitter-rtl/tag=lcomplexfuu-ANY-rtl
----------
Provides:
----------
----------
/pkgname=source_complex_link_rtl/flavor=ANY/pkgtype=src/setupname=NONE-> source_complex_link_rtl-ANY-src
Dependencies:
----------
/deptype=pgm_link/pkgname=lcomplexfigi/flavor=ANY/pkgtype=dev-> /from=source_complex_link_rtl-ANY-src/dep=lcomplexfigi-ANY-dev/to=lcomplexfigi-bitter-dev/tag=lcomplexfigi-ANY-dev
/deptype=pgm_link/pkgname=lcomplexfigi/flavor=ANY/pkgtype=rtl-> /from=source_complex_link_rtl-ANY-src/dep=lcomplexfigi-ANY-dev/to=lcomplexfigi-bitter-rtl/tag=lcomplexfigi-ANY-rtl
/deptype=pgm_link/pkgname=lcomplexfoo/flavor=ANY/pkgtype=dev-> /from=source_complex_link_rtl-ANY-src/dep=lcomplexfoo-ANY-dev/to=lcomplexfoo-bitter-dev/tag=lcomplexfoo-ANY-dev
/deptype=pgm_link/pkgname=lcomplexfoo/flavor=ANY/pkgtype=rtl-> /from=source_complex_link_rtl-ANY-src/dep=lcomplexfoo-ANY-dev/to=lcomplexfoo-bitter-rtl/tag=lcomplexfoo-ANY-rtl
/deptype=pgm_link/pkgname=lcomplexfuu/flavor=ANY/pkgtype=dev-> /from=source_complex_link_rtl-ANY-src/dep=lcomplexfuu-ANY-dev/to=lcomplexfuu-bitter-dev/tag=lcomplexfuu-ANY-dev
/deptype=pgm_link/pkgname=lcomplexfuu/flavor=ANY/pkgtype=rtl-> /from=source_complex_link_rtl-ANY-src/dep=lcomplexfuu-ANY-dev/to=lcomplexfuu-bitter-rtl/tag=lcomplexfuu-ANY-rtl
----------
Provides:
----------
----------
/pkgname=source_complexruntime_data/flavor=ANY/pkgtype=src/setupname=NONE-> source_complexruntime_data-ANY-src
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=source_complexruntime_doc/flavor=ANY/pkgtype=src/setupname=NONE-> source_complexruntime_doc-ANY-src
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=source_complexruntime_lib/flavor=ANY/pkgtype=src/setupname=NONE-> source_complexruntime_lib-ANY-src
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=source_complexruntime_pgm/flavor=ANY/pkgtype=src/setupname=NONE-> source_complexruntime_pgm-ANY-src
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=source_link_dev/flavor=ANY/pkgtype=src/setupname=NONE-> source_link_dev-ANY-src
Dependencies:
----------
/deptype=pgm_link/pkgname=lfoo/flavor=ANY/pkgtype=dev-> /from=source_link_dev-ANY-src/dep=lfoo-ANY-dev/to=lfoo-bitter-dev/tag=lfoo-ANY-dev
/deptype=pgm_link/pkgname=lfoo/flavor=ANY/pkgtype=rtl-> /from=source_link_dev-ANY-src/dep=lfoo-ANY-dev/to=lfoo-bitter-rtl/tag=lfoo-ANY-rtl
/deptype=pgm_link/pkgname=lfuu/flavor=ANY/pkgtype=dev-> /from=source_link_dev-ANY-src/dep=lfuu-ANY-dev/to=lfuu-bitter-dev/tag=lfuu-ANY-dev
/deptype=pgm_link/pkgname=lfuu/flavor=ANY/pkgtype=rtl-> /from=source_link_dev-ANY-src/dep=lfuu-ANY-dev/to=lfuu-bitter-rtl/tag=lfuu-ANY-rtl
----------
Provides:
----------
----------
/pkgname=source_link_rtl/flavor=ANY/pkgtype=src/setupname=NONE-> source_link_rtl-ANY-src
Dependencies:
----------
/deptype=pgm_link/pkgname=lfoo/flavor=ANY/pkgtype=dev-> /from=source_link_rtl-ANY-src/dep=lfoo-ANY-dev/to=lfoo-bitter-dev/tag=lfoo-ANY-dev
/deptype=pgm_link/pkgname=lfoo/flavor=ANY/pkgtype=rtl-> /from=source_link_rtl-ANY-src/dep=lfoo-ANY-dev/to=lfoo-bitter-rtl/tag=lfoo-ANY-rtl
/deptype=pgm_link/pkgname=lfuu/flavor=ANY/pkgtype=dev-> /from=source_link_rtl-ANY-src/dep=lfuu-ANY-dev/to=lfuu-bitter-dev/tag=lfuu-ANY-dev
/deptype=pgm_link/pkgname=lfuu/flavor=ANY/pkgtype=rtl-> /from=source_link_rtl-ANY-src/dep=lfuu-ANY-dev/to=lfuu-bitter-rtl/tag=lfuu-ANY-rtl
----------
Provides:
----------
----------
/pkgname=source_runtime_data/flavor=ANY/pkgtype=src/setupname=NONE-> source_runtime_data-ANY-src
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=source_runtime_doc/flavor=ANY/pkgtype=src/setupname=NONE-> source_runtime_doc-ANY-src
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=source_runtime_lib/flavor=ANY/pkgtype=src/setupname=NONE-> source_runtime_lib-ANY-src
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=source_runtime_pgm/flavor=ANY/pkgtype=src/setupname=NONE-> source_runtime_pgm-ANY-src
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=source_setup_data/flavor=ANY/pkgtype=src/setupname=NONE-> source_setup_data-ANY-src
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=source_setup_doc/flavor=ANY/pkgtype=src/setupname=NONE-> source_setup_doc-ANY-src
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=source_setup_lib/flavor=ANY/pkgtype=src/setupname=NONE-> source_setup_lib-ANY-src
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=source_setup_pgm/flavor=ANY/pkgtype=src/setupname=NONE-> source_setup_pgm-ANY-src
Dependencies:
----------
----------
Provides:
----------
----------
/pkgname=lcomplexfuu-bitter-rtl/missing=lcomplexfewy-bitter-rtl
/pkgname=lcomplexfuu-bitter-dev/missing=lcomplexfewy-bitter-dev
++++++++++++++++Sorted++++++++++++++++++
cfue-bitter-dev
cfum-bitter-dev
crtfee-bitter-data
crtfee-bitter-doc
crtfee-bitter-pgm
crtfee-bitter-rtl
crtfix-bitter-pgm_static
crtfoo-bitter-pgm
crtfox-noflavor-pgm
crtfue-bitter-data
crtfue-bitter-doc
crtfue-bitter-pgm
crtfue-bitter-rtl
crtfum-bitter-doc
crtfur-noflavor-pgm_static
crtfuu-bitter-doc
installed_complexruntime_data-bitter-data
installed_complexruntime_doc-bitter-doc
installed_complexruntime_lib-bitter-rtl
installed_complexruntime_pgm-bitter-pgm
installed_runtime_data-bitter-data
installed_runtime_doc-bitter-doc
installed_runtime_lib-bitter-rtl
installed_runtime_pgm-bitter-pgm
installed_setup_data-bitter-data
installed_setup_doc-bitter-doc
installed_setup_lib-bitter-rtl
installed_setup_pgm-bitter-pgm
lcomplexfigi-bitter-dev
lcomplexfigi-bitter-rtl
lfue-bitter-dev
lfue-bitter-rtl
lfum-bitter-dev
lfum-bitter-rtl
rtfee-bitter-data
rtfee-bitter-doc
rtfee-bitter-pgm
rtfee-bitter-rtl
rtfoo-bitter-pgm
rtfue-bitter-data
rtfue-bitter-doc
rtfue-bitter-pgm
rtfue-bitter-rtl
rtfum-bitter-doc
rtfuu-bitter-doc
/setupname=setfee:setfee-noflavor-pgm
/setupname=setfoo:setfoo-noflavor-pgm
/setupname=setfue:setfue-noflavor-pgm
/setupname=setfum:setfum-noflavor-pgm
/setupname=setfoo:setfuu-noflavor-pgm
source_compile_src-ANY-src
source_complexruntime_data-ANY-src
source_complexruntime_doc-ANY-src
source_complexruntime_lib-ANY-src
source_complexruntime_pgm-ANY-src
source_runtime_data-ANY-src
source_runtime_doc-ANY-src
source_runtime_lib-ANY-src
source_runtime_pgm-ANY-src
source_setup_data-ANY-src
source_setup_doc-ANY-src
source_setup_lib-ANY-src
source_setup_pgm-ANY-src
cfee-bitter-dev
lcomplexfum-bitter-dev
lcomplexfum-bitter-rtl
lfee-bitter-dev
lfee-bitter-rtl
cfoo-bitter-dev
cfuu-bitter-dev
lcomplexfee-bitter-dev
lcomplexfee-bitter-rtl
lfoo-bitter-dev
lfoo-bitter-rtl
lfuu-bitter-dev
lfuu-bitter-rtl
installed_link_dev-bitter-dev
installed_link_rtl-bitter-rtl
lcomplexfue-bitter-dev
lcomplexfue-bitter-rtl
source_link_dev-ANY-src
source_link_rtl-ANY-src
lcomplexfoo-bitter-dev
lcomplexfoo-bitter-rtl
lcomplexfuu-bitter-dev
lcomplexfuu-bitter-rtl
installed_complex_link_dev-bitter-dev
installed_complex_link_rtl-bitter-rtl
source_complex_link_dev-ANY-src
source_complex_link_rtl-ANY-src
++++++++++++++++Missing+++++++++++++++++
Package lcomplexfuu-bitter-rtl
Needs /deptype=Runtime_Link->lcomplexfewy-bitter-rtl
Package lcomplexfuu-bitter-dev
Needs /deptype=Build_Link->lcomplexfewy-bitter-dev
