++++++++++++++++Sorted++++++++++++++++++
lcomplexfigi-bitter-dev
lcomplexfigi-bitter-rtl
lfue-bitter-dev
lfue-bitter-rtl
lfum-bitter-dev
lfum-bitter-rtl
lcomplexfum-bitter-dev
lcomplexfum-bitter-rtl
lfee-bitter-dev
lfee-bitter-rtl
lcomplexfee-bitter-dev
lcomplexfee-bitter-rtl
lfoo-bitter-dev
lfoo-bitter-rtl
lfuu-bitter-dev
lfuu-bitter-rtl
lcomplexfue-bitter-dev
lcomplexfue-bitter-rtl
source_link_dev-ANY-src
lcomplexfoo-bitter-dev
lcomplexfoo-bitter-rtl
lcomplexfuu-bitter-dev
lcomplexfuu-bitter-rtl
source_complex_link_dev-ANY-src
++++++++++++++++Missing+++++++++++++++++
Package lcomplexfuu-bitter-rtl
Needs /deptype=Runtime_Link->lcomplexfewy-bitter-rtl
Package lcomplexfuu-bitter-dev
Needs /deptype=Build_Link->lcomplexfewy-bitter-dev
++++++++++++++++Libraries+++++++++++++++++
/ext_libs=-lsocket/pkglibs=-lcomplexfigi
/ext_libs=-lsocket/pkglibs=-lfue
/ext_libs=-lsocket/pkglibs=-lfum
/ext_libs=-lsocket/pkglibs=-lcomplexfum
/ext_libs=/pkglibs=-lfee
/ext_libs=/pkglibs=-lcomplexfee
/ext_libs=/pkglibs=-lfoo
/ext_libs=/pkglibs=-lfuu
/ext_libs=-lsocket/pkglibs=-lcomplexfue
/ext_libs=/pkglibs=-lcomplexfoo
/ext_libs=/pkglibs=-lcomplexfuu
Warning: PkgNode: Package /setupname=setfum:setfum-noflavor-pgm
contains a dependency to itself...SKIPPING
++++++++++++++++Sorted++++++++++++++++++
lcomplexfigi-bitter-dev
lcomplexfigi-bitter-rtl
lcomplexfum-bitter-dev
lcomplexfum-bitter-rtl
lcomplexfee-bitter-dev
lcomplexfee-bitter-rtl
lcomplexfue-bitter-dev
lcomplexfue-bitter-rtl
lcomplexfoo-bitter-dev
lcomplexfoo-bitter-rtl
lcomplexfuu-bitter-dev
lcomplexfuu-bitter-rtl
source_complex2_src-ANY-src
/setupname=setcomplex:source_complex2_setup_src-ANY-src
++++++++++++++++Missing+++++++++++++++++
Package lcomplexfuu-bitter-rtl
Needs /deptype=Runtime_Link->lcomplexfewy-bitter-rtl
Package lcomplexfuu-bitter-dev
Needs /deptype=Build_Link->lcomplexfewy-bitter-dev
++++++++++++++++Libraries+++++++++++++++++
/ext_libs=-lsocket/pkglibs=-lcomplexfigi
/ext_libs=-lsocket/pkglibs=-lcomplexfum
/ext_libs=/pkglibs=-lcomplexfee
/ext_libs=-lsocket/pkglibs=-lcomplexfue
/ext_libs=/pkglibs=-lcomplexfoo
/ext_libs=/pkglibs=-lcomplexfuu
++++++++++++++++Sorted++++++++++++++++++
lcomplexfigi-bitter-dev
lcomplexfigi-bitter-rtl
lcomplexfum-bitter-dev
lcomplexfum-bitter-rtl
lcomplexfee-bitter-dev
lcomplexfee-bitter-rtl
lcomplexfue-bitter-dev
lcomplexfue-bitter-rtl
lcomplexfoo-bitter-dev
lcomplexfoo-bitter-rtl
lcomplexfuu-bitter-dev
lcomplexfuu-bitter-rtl
++++++++++++++++Missing+++++++++++++++++
Package lcomplexfuu-bitter-rtl
Needs /deptype=Runtime_Link->lcomplexfewy-bitter-rtl
Package lcomplexfuu-bitter-dev
Needs /deptype=Build_Link->lcomplexfewy-bitter-dev
++++++++++++++++Libraries+++++++++++++++++
/ext_libs=-lsocket/pkglibs=-lcomplexfigi
/ext_libs=-lsocket/pkglibs=-lcomplexfum
/ext_libs=/pkglibs=-lcomplexfee
/ext_libs=-lsocket/pkglibs=-lcomplexfue
/ext_libs=/pkglibs=-lcomplexfoo
/ext_libs=/pkglibs=-lcomplexfuu
