GPT_DESCRIPTION_GPT: 
              This is the brand new package foo.
              
              Its really cool!
       
GPT_FLAVOR_GPT: spicy
GPT_GROUP_GPT: I/Am/Somebody/Because/I/Belong
GPT_NAME_GPT: foo
GPT_PACKAGE_GPT: foo_spicy_pgm_static
GPT_PKGTYPE_GPT: pgm_static
GPT_PROVIDES_GPT: foo_pgm-2, foo_pgm-3, foo_pgm-3.5, foo_pgm
GPT_REQUIRES_GPT: Requires:  pgm_fee_pgm-2,  pgm_fow_pgm-2,  pgm_fum_pgm-2
GPT_SUMMARY_GPT: foo_spicy_pgm_static experimental version
GPT_VERSION_GPT: 3.5
