<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gpt_package_metadata SYSTEM "globus_package.dtd">
<gpt_package_metadata Format_Version="0.01" Name="foo" >
<Aging_Version Age="1" Major="3" Minor="5" />
<Description >
              This is the brand new package foo.
              
              Its really cool!
       </Description>
<Functional_Group >I/Am/Somebody/Because/I/Belong</Functional_Group>
<Version_Stability Release="experimental" />
<ComponentInformation Name="DooDah" >
<Description >
              This is component DooDah.
              
              Its really cool!
 </Description>
<VersionLabel >3.2productionRun3</VersionLabel>
</ComponentInformation>
<ComponentInformation Name="DooDaad" >
<VersionLabel >1.1</VersionLabel>
</ComponentInformation>
<PackageIdentifier Release="Xfqw743123-3424524" />
<PackagingTool ToolName="GPT" ToolVersion="3.1a2" />
<pgm_static_pkg >
<Flavor ColocateLibraries="yes" >spicy</Flavor>
<Version_Label >3.4.5beta3p</Version_Label>
<Binary_Dependencies Type="Regeneration" >
<Dependency Name="plee" Package="rtl" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="plow" Package="rtl" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="plum" Package="rtl" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
</Binary_Dependencies>
<Binary_Dependencies Type="Runtime" >
<Dependency Name="pgm_fee" Package="pgm" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="pgm_fow" Package="pgm" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="pgm_fum" Package="pgm" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
</Binary_Dependencies>

<Setup_Dependency Name="foo_pgm_setup" >
<Version >
<Simple_Version Major="2" />
</Version>
</Setup_Dependency>

<Post_Install_Message >
            You need to run run_me
       </Post_Install_Message>
<Post_Install_Program >
            run_me
       </Post_Install_Program>
<Setup Name="setmeup" >
<Aging_Version Age="2" Major="5" Minor="5" />
</Setup>
</pgm_static_pkg>
</gpt_package_metadata>
