GPT_DESCRIPTION_GPT: 
              This is the brand new package foo.
              
              Its really cool!
       
GPT_FLAVOR_GPT: spicy
GPT_GROUP_GPT: I/Am/Somebody/Because/I/Belong
GPT_NAME_GPT: foo
GPT_PACKAGE_GPT: foo_spicy_rtl
GPT_PKGTYPE_GPT: rtl
GPT_PROVIDES_GPT: foo_spicy_rtl-2, foo_spicy_rtl-3, foo_spicy_rtl-3.5, foo_spicy_rtl
GPT_REQUIRES_GPT: Requires:  rtl_fee_data-2,  rtl_fow_data-2,  rtl_fum_data-2,  lee_spicy_rtl-2,  low_spicy_rtl-2,  lum_spicy_rtl-2
GPT_SUMMARY_GPT: foo_spicy_rtl experimental version
GPT_VERSION_GPT: 3.5
