<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE 0.01 SYSTEM "no.dtd">
<Test_Dependencies >
<Binary_Dependencies Type="Build_Link" >
<Dependency Name="ll_foo1" Package="dev" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="ll_foo2" Package="dev" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="ll_foo3" Package="dev" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="ll_foo4" Package="dev" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="ll_foo5" Package="dev" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
</Binary_Dependencies>
<Binary_Dependencies Type="Compile" >
<Dependency Name="foo1" Package="dev" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="foo2" Package="dev" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="foo3" Package="dev" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="foo4" Package="dev" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="foo5" Package="dev" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
</Binary_Dependencies>
</Test_Dependencies>
