<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE 0.01 SYSTEM "no.dtd">
<Test_Dependencies >
<Binary_Dependencies Type="Runtime" >
<Dependency Name="pr_foo1" Package="data" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="pr_foo2" Package="data" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="pr_foo3" Package="data" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="pr_foo4" Package="data" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="pr_foo5" Package="data" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
</Binary_Dependencies>
<Binary_Dependencies Type="Runtime_Link" >
<Dependency Name="pl_foo1" Package="rtl" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="pl_foo2" Package="rtl" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="pl_foo3" Package="rtl" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="pl_foo4" Package="rtl" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
<Dependency Name="pl_foo5" Package="rtl" >
<Version >
<Simple_Version Major="1" />
<Version_Range Lower_Major="3" Lower_Minor="2" Upper_Major="3" Upper_Minor="4" />
</Version>
</Dependency>
</Binary_Dependencies>
</Test_Dependencies>
