<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gpt_package_metadata SYSTEM "globus_package.dtd">
<gpt_package_metadata Format_Version="0.01" Name="foo" >
<Aging_Version Age="1" Major="3" Minor="5" />
<Description >
           This is the brand new package foo.
           
           Its really cool!
    </Description>
<Functional_Group >I/Am/Somebody/Because/I/Belong</Functional_Group>
<Version_Stability Release="experimental" />
<src_pkg >
<With_Flavors build="yes" />
<Source_Dependencies Type="compile" >
<Dependency Name="fee" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="fow" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="fum" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
</Source_Dependencies>
<Source_Dependencies Type="data_runtime" >
<Dependency Name="data_fee" Package="data" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="data_fow" Package="data" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="data_fum" Package="data" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
</Source_Dependencies>
<Source_Dependencies Type="doc_runtime" >
<Dependency Name="doc_fee" Package="doc" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="doc_fow" Package="doc" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="doc_fum" Package="doc" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
</Source_Dependencies>
<Source_Dependencies Type="lib_link" >
<Dependency Name="lee" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="low" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="lum" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
</Source_Dependencies>
<Source_Dependencies Type="lib_runtime" >
<Dependency Name="rtl_fee" Package="data" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="rtl_fow" Package="data" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="rtl_fum" Package="data" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
</Source_Dependencies>
<Source_Dependencies Type="pgm_link" >
<Dependency Name="plee" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="plow" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="plum" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
</Source_Dependencies>
<Source_Dependencies Type="pgm_runtime" >
<Dependency Name="pgm_fee" Package="pgm" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="pgm_fow" Package="pgm" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
<Dependency Name="pgm_fum" Package="pgm" >
<Version >
<Simple_Version Major="2" />
</Version>
</Dependency>
</Source_Dependencies>
<Source_Setup_Dependency PkgType="doc" >
<Setup_Dependency Name="foo_doc_setup" >
<Version >
<Simple_Version Major="2" />
</Version>
</Setup_Dependency>
</Source_Setup_Dependency>
<Source_Setup_Dependency PkgType="pgm" >
<Setup_Dependency Name="foo_pgm_setup" >
<Version >
<Simple_Version Major="2" />
</Version>
</Setup_Dependency>
</Source_Setup_Dependency>
<Source_Setup_Dependency PkgType="rtl" >
<Setup_Dependency Name="foo_rtl_setup" >
<Version >
<Simple_Version Major="2" />
</Version>
</Setup_Dependency>
</Source_Setup_Dependency>
<Build_Environment >
<cflags >-Dfoo</cflags>
<external_includes >-Imath.h -Issl.h</external_includes>
<pkg_libs >-lfoo -lfee -lfum_2</pkg_libs>
<external_libs >-lm -lssl</external_libs>
</Build_Environment>
<Build_Instructions >
<Build_Step Macro_Args="--some-arguments" >  first step to building our package.  </Build_Step>
<Build_Step >  second step to building our package.  </Build_Step>
<Build_Step Macro_Args="--some-more-arguments" >  third step to building our package.  </Build_Step>
<Build_Step >  fourth step to building our package.  </Build_Step>
<flavors >
</flavors>
</Build_Instructions>
<Post_Install_Message >
         You need to run run_me
    </Post_Install_Message>
<Post_Install_Program >
         run_me
    </Post_Install_Program>
<Setup Name="setmeup" >
<Aging_Version Age="2" Major="5" Minor="5" />
</Setup>
</src_pkg>
</gpt_package_metadata>
