<TestDependencies>

<Source_Dependencies Type="compile">
<Dependency Name="foo1" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="foo2" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="foo3" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="foo4" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="foo5" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
</Source_Dependencies>

<Source_Dependencies Type="pgm_link">
<Dependency Name="pl_foo1" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="pl_foo2" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="pl_foo3" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="pl_foo4" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="pl_foo5" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
</Source_Dependencies>

<Source_Dependencies Type="lib_link">
<Dependency Name="ll_foo1" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="ll_foo2" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="ll_foo3" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="ll_foo4" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="ll_foo5" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
</Source_Dependencies>

<Source_Dependencies Type="data_runtime">
<Dependency Name="dr_foo1" Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="dr_foo2"  Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="dr_foo3"  Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="dr_foo4"  Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="dr_foo5"  Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
</Source_Dependencies>

<Source_Dependencies Type="doc_runtime">
<Dependency Name="docr_foo1"  Package="doc">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="docr_foo2"  Package="doc">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="docr_foo3" Package="doc" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="docr_foo4" Package="doc" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="docr_foo5" Package="doc" >
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
</Source_Dependencies>

<Source_Dependencies Type="pgm_runtime">
<Dependency Name="pr_foo1"  Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="pr_foo2" Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="pr_foo3" Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="pr_foo4" Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="pr_foo5" Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
</Source_Dependencies>

<Source_Dependencies Type="lib_runtime">
<Dependency Name="lr_foo1" Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="lr_foo2" Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="lr_foo3" Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="lr_foo4" Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
<Dependency Name="lr_foo5" Package="data">
<Version>
<Simple_Version Major="1"/>
<Version_Range Upper_Major="3" Lower_Major="3" Upper_Minor="4" Lower_Minor="2"/>
</Version>
</Dependency>
</Source_Dependencies>

</TestDependencies>
