<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE globus_flavors SYSTEM "globus_flavors.dtd">
<flavors >
<flavor_choice >
<flavor_label conf="CC=googoo" label="gcc" />
<flavor_label conf="CC=gaagaa" label="vendorcc" />
</flavor_choice>
<flavor_choice >
<flavor_label conf="--enable-64business" label="64" />
<noflavor_label label="32" />
</flavor_choice>
<flavor_choice >
<flavor_label conf="--enable-debugksy" label="dbg" />
<noflavor_label />
</flavor_choice>
<flavor_choice >
<flavor_label conf="--enable-insurance" label="insure" />
<noflavor_label />
</flavor_choice>
<flavor_choice >
<flavor_label conf="pthreads are cool" label="pthr" />
<flavor_label conf="solaris threads are cooler" label="solthr" />
<flavor_label conf="sproc is weird" label="sproc" />
<noflavor_label />
</flavor_choice>
<flavor_choice >
<flavor_label conf="mpliving" label="mpl" />
<flavor_label conf="mpeying" label="mpi" />
<flavor_label conf="inxess" label="inx" />
<noflavor_label />
</flavor_choice>
</flavors>
