Error: 6 -  Tag <With_Flavors oops build="yes" /> is malformed
Error: 8 -  Tag <Source_Dependencies oops> is malformed
Error: 16 - Ending tag <lib_Link_Dependencies oops> cannot contain any spaces
Error: 16 - Ending tag <lib_Link_Dependencies oops> does not have a corresponding start tag
Error: 14 - Tag <lib_Link_Dependencies> needs end tag before <lib_Link_Dependencies oops> at line 16
Error: 13 - Tag <Source_Link_Dependencies> needs end tag before <lib_Link_Dependencies oops> at line 16
Error: 8 - Tag <Source_Dependencies> needs end tag before <lib_Link_Dependencies oops> at line 16
Error: 4 - Tag <src_pkg> needs end tag before <lib_Link_Dependencies oops> at line 16
Error: 3 - Tag <gpt_package_metadata> needs end tag before <lib_Link_Dependencies oops> at line 16
Error: 26 -  Tag <Source_Runtime_Dependencies oops=booboo> is malformed
Error: 47 - Ending tag <Source_Dependencies>  is out of sequence

Error: 25 - Tag <Source_Runtime_Dependencies> needs end tag before <Source_Dependencies> at line 47
Error: 60 - Ending tag <oops> does not have a corresponding start tag
Error: 58 - Tag <external_libs> needs end tag before <oops> at line 60
Error: 49 - Tag <Build_Environment> needs end tag before <oops> at line 60
Error: 8 - Tag <Source_Dependencies> needs end tag before <oops> at line 60
Error: 4 - Tag <src_pkg> needs end tag before <oops> at line 60
Error: 3 - Tag <gpt_package_metadata> needs end tag before <oops> at line 60
Error: 69 - Ending tag <src_pkg>  is out of sequence

Error: 8 - Tag <Source_Dependencies> needs end tag before <src_pkg> at line 69
Error: 72 - Ending tag <gpt_package_metadata>  is out of sequence

Error: 4 - Tag <src_pkg> needs end tag before <gpt_package_metadata> at line 72
Error: 3 - Tag <gpt_package_metadata> does not have an end tag
