<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gpt_package_metadata SYSTEM "package.dtd">
<gpt_package_metadata Format_Version="0.01" Name="foo" Version="2.0.0" >
   <src_pkg >
   <With_Flavors build="yes" />
   
   <Source_Dependencies >
   <Compile_Dependencies >
   fee fow fum
   </Compile_Dependencies>
   
   <Source_Link_Dependencies >
   <lib_Link_Dependencies >
   lee low lum
   </lib_Link_Dependencies>
   
   <pgm_Link_Dependencies >
   plee plow plum
   </pgm_Link_Dependencies>
   
   
   </Source_Link_Dependencies>
   
   <Source_Runtime_Dependencies >
   <data_Runtime_Dependencies >
   data_fee data_fow  data_fum
   </data_Runtime_Dependencies>
   
   <doc_Runtime_Dependencies >
   doc_fee  doc_fow doc_fum
   </doc_Runtime_Dependencies>
   
   <lib_Runtime_Dependencies >
   rtl_fee rtl_fow  rtl_fum
   </lib_Runtime_Dependencies>
   
   <pgm_Runtime_Dependencies >
   pgm_fee pgm_fow pgm_fum
   </pgm_Runtime_Dependencies>
   
   
   </Source_Runtime_Dependencies>
   
   
   </Source_Dependencies>
   
   <Build_Environment >
   <cflags >
   -Dfoo
   </cflags>
   
   <external_includes >
   -Imath.h -Issl.h
   </external_includes>
   
   <external_libs >
   -lm -lssl
   </external_libs>
   
   <pkg_libs >
   -lfoo
   </pkg_libs>
   
   
   </Build_Environment>
   
   
   </src_pkg>
   
   
   </gpt_package_metadata>
