#!/bin/bash
# 
# Copyright 2010-2011 University of Chicago
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# The script contains all commands requiring root privileges to finish
# installing Globus Connect Multi-User. The commands are the only ones
# that make changes outside the directory with Globus Connect Multi-User.
# To revert the changes, run ./root-unsetup.

if [ `id -u` -ne 0 ]; then
    echo "You must be logged in as root to run this script."
    exit 1
fi

error()
{
    echo $1
    echo "Exiting..."
    exit 1
}

SYSTEM=`uname -s`
[ -z "$SYSTEM" ] && error "Could not determine the operating system."

echo "Changing ownership of '$GC_ROOT/etc/grid-security/ltacert.pem',
echo '$GC_ROOT/etc/grid-security/ltakey.pem' and '$GC_ROOT/var/myproxy' to root."
chown root "$GC_ROOT/etc/grid-security/ltacert.pem" \
|| error "Could not change owner of the file '$GC_ROOT/etc/grid-security/ltacert.pem' to root."
chown root "$GC_ROOT/etc/grid-security/ltakey.pem" \
|| error "Could not change owner of the file '$GC_ROOT/etc/grid-security/ltakey.pem' to root."
if [ -e "$GC_ROOT/var/myproxy" ]; then
    chown root "$GC_ROOT/var/myproxy" \
    || error "Could not change owner of the file '$GC_ROOT/var/myproxy' to root."
else
    mkdir "$GC_ROOT/var/myproxy" \
    || error "Could not create the directory '$GC_ROOT/var/myproxy'."
fi
chmod 0700 "$GC_ROOT/var/myproxy"

case "$SYSTEM" in
Linux)
    echo "Copying gridftp-go to /etc/xinetd.d."
    cp "$GC_ROOT/usr/share/gcmu/gridftp-go" /etc/xinetd.d/ \
    || error "Could not copy gridftp-go to /etc/xinetd.d/"

    if [ -e "$GC_ROOT/usr/share/gcmu/myproxy-go" ]; then
        echo "Copying myproxy-go to /etc/xinetd.d."
        cp "$GC_ROOT/usr/share/gcmu/myproxy-go" /etc/xinetd.d/ \
        || error "Could not copy myproxy-go to /etc/xinetd.d/."
    fi

    service xinetd stop
    service xinetd start
    ;;
Darwin)
    launchctl list org.globusonline.gridftp >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo "Unloading the existing configuration file 'org.globusonline.gridftp.plist'"
        launchctl unload /System/Library/LaunchDaemons/org.globusonline.gridftp.plist
    fi
    echo "Copying 'org.globusonline.gridftp.plist' to '/System/Library/LaunchDaemons'"
    cp org.globusonline.gridftp.plist /System/Library/LaunchDaemons \
    || error "Could not copy 'org.globusonline.gridftp.plist' to '/System/Library/LaunchDaemons'"
    echo "Loading the new configuration file 'org.globusonline.gridftp.plist'"
    launchctl load /System/Library/LaunchDaemons/org.globusonline.gridftp.plist

    if [ -e org.globusonline.myproxy.plist ]; then
        launchctl list org.globusonline.myproxy >/dev/null 2>&1
        if [ $? -eq 0 ]; then
            echo "Unloading the existing configuration file 'org.globusonline.myproxy.plist'"
            launchctl unload /System/Library/LaunchDaemons/org.globusonline.myproxy.plist
        fi
        echo "Copying 'org.globusonline.myproxy.plist' to '/System/Library/LaunchDaemons'"
        cp org.globusonline.myproxy.plist /System/Library/LaunchDaemons \
        || error "Could not copy 'org.globusonline.myproxy.plist' to '/System/Library/LaunchDaemons'"
        echo "Loading the new configuration file 'org.globusonline.myproxy.plist'"
        launchctl load /System/Library/LaunchDaemons/org.globusonline.myproxy.plist
    fi
    ;;
*)
    error "The system $SYSTEM is not supported."
    ;;
esac

