#!/bin/bash
# 
# Copyright 2010-2011 University of Chicago
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

error()
{
    echo -e $1
    echo "Exiting..."
    exit 1
}

SYSTEM=`uname -s`
[ -z $SYSTEM ] && error "Could not determine the operating system."

cd `dirname "$0"`
GC_LOCATION="${PWD}"

case "$SYSTEM" in
Linux)
    if [ -e /etc/xinetd.d/gridftp-go -o -e /etc/xinetd.d/myproxy-go ]; then
	if [ `id -u` -eq 0 ]; then 
	    ./root-unsetup
	else
	    echo "Please, run the script './root-unsetup' as root first."
	    exit 0
	fi
    fi
    ;;
Darwin)
    if [ -e /System/Library/LaunchDaemons/org.globusonline.gridftp.plist -o \
         -e /System/Library/LaunchDaemons/org.globusonline.myproxy.plist ]; then
	if [ `id -u` -eq 0 ]; then 
	    ./root-unsetup
	else
	    echo "Please, run the script './root-unsetup' as root first."
	    exit 0
	fi
    fi
    ;;
*)
    error "The system $SYSTEM is not supported."
    ;;
esac

echo "Do you really want to remove the directory $GC_LOCATION"
echo "and irreversibly uninstall Globus Connect Multi-User?"
echo -n "Y/N [N]: "
read ANSWER
if [ "x$ANSWER" = "xY" -o "x$ANSWER" = "xy" ]; then
    echo "Removing $GC_LOCATION..."
    rm -rf $GC_LOCATION
    echo "Done"
fi
