#! perl

if ( ! ( defined eval "require 5.005" ) )
{
    die "GPT requires at least Perl version 5.005";
}

system("./gpt_version") == 0
         or die "GPT died due to Version mismatch.  Check PATH and GPT_LOCATION\n" ;


my $gpath = $ENV{GPT_LOCATION};
my $globus_path = $ENV{GLOBUS_LOCATION};

if (!defined($gpath))
{
  $gpath = $ENV{GLOBUS_LOCATION};

}

if (!defined($gpath))
{
   error_out("GPT_LOCATION or GLOBUS_LOCATION needs to be set before running this script");
}

@INC = ("$gpath/lib/perl", "$gpath/lib/perl/$Config{'archname'}", @INC);

if ( ! ( defined eval "require Grid::GPT::GPTObject" ) )
{
    die("$gpath does not appear to hold a valid GPT installation\n");
}

print "WARNING: gpt-update will soon be depreciated. Use gpt-install instead.\n";
sleep 1;

my @sysArgs = ( "$gpath/sbin/gpt-install", @ARGV );
system( @sysArgs ) == 0 or print STDERR "couldn't exec gpt-install: $!\n";
exit;
