#if !defined GLOBUS_XIO_RATE_DRIVER_H
#define GLOBUS_XIO_RATE_DRIVER_H 1

enum
{
    GLOBUS_XIO_RATE_SET_RATE = 1,
    GLOBUS_XIO_RATE_SET_PERIOD,
    GLOBUS_XIO_RATE_SET_READ_RATE,
    GLOBUS_XIO_RATE_SET_READ_PERIOD,
    GLOBUS_XIO_RATE_SET_WRITE_RATE,
    GLOBUS_XIO_RATE_SET_WRITE_PERIOD,
    GLOBUS_XIO_RATE_SET_BURST,
    GLOBUS_XIO_RATE_SET_READ_BURST,
    GLOBUS_XIO_RATE_SET_WRITE_BURST,
    GLOBUS_XIO_RATE_SET_GROUP,
    GLOBUS_XIO_RATE_SET_READ_GROUP,
    GLOBUS_XIO_RATE_SET_WRITE_GROUP
};

#endif
