#! /usr/bin/env perl 

use strict;

local(*APPEND_IN);

my $audit_dir = &get_audit_dir();
my $audit_conf = "$ENV{GLOBUS_LOCATION}/etc/globus-job-manager-audit.conf";

if ($audit_dir eq '')
{
    print "No -audit-directory in job-manager.conf. Nothing to do\n";
    exit(0);
}

my $pid = open(APPEND_IN, "|$ENV{GLOBUS_LOCATION}/libexec/globus-gram-append-audit-records -c  $audit_conf");
select APPEND_IN; $|=1;
select STDOUT;
my @cleanup_list = ();

foreach (glob("$audit_dir/*.gramaudit"))
{
    local (*F);
    my $record_file = $_;
    my $owner = (stat($record_file))[4];
    my $record;
    my @record_entries;

    open(F, "<$record_file") || next;

    chomp($record = <F>);
    @record_entries = split(/"[^"]"/, $record);
    close(F);

    push(@cleanup_list, $record_file);

    # don't process entries where the owner != the job user
    if ($record_entries[3] ne (getpwuid($owner))[0])
    {
        next;
    }

    print APPEND_IN "$record\n" || die "Unable to write record to appender\n";
}

close(APPEND_IN);

if ($? == 0)
{
    unlink(@cleanup_list);
}


sub get_audit_dir
{
    local(*F);
    my $jmconf = "$ENV{GLOBUS_LOCATION}/etc/globus-job-manager.conf";
    my $audit_dir = '';

    open(F, "<$jmconf");

    while(<F>)
    {
        if (m/-audit-directory\s+(\S+)\s+/)
        {
            $audit_dir = $1;
            last;
        }
    }
    close(F);

    return $audit_dir;
}
