'\" t
.\"     Title: globus-gram-audit
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 08/30/2011
.\"    Manual: GRAM5 Commands
.\"    Source: University of Chicago
.\"  Language: English
.\"
.TH "GLOBUS\-GRAM\-AUDIT" "8" "08/30/2011" "University of Chicago" "GRAM5 Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-gram-audit \- Load GRAM4 and GRAM5 audit records into a database
.SH "SYNOPSIS"
.HP \w'\fBglobus\-gram\-audit\fR\ 'u
\fBglobus\-gram\-audit\fR [\-\-conf\ \fICONFIG_FILE\fR] [[\-\-create] | [\-\-update=\fIOLD\-VERSION\fR]] [\-\-check] [\-\-delete] [\-\-audit\-directory\ \fIAUDITDIR\fR] [\-\-quiet]
.SH "DESCRIPTION"
.PP
The
\fBglobus\-gram\-audit\fR
program loads audit records to an SQL\-based database\&. It reads
\fB$GLOBUS_LOCATION\fR/etc/globus\-job\-manager\&.conf
by default to determine the audit directory and then uploads all files in that directory that contain valid audit records to the database configured by the
\fBglobus_gram_job_manager_auditing_setup_scripts\fR
package\&. If the upload completes successfully, the audit files will be removed\&.
.PP
The full set of command\-line options to
\fBglobus\-gram\-audit\fR
consist of:
.TS
tab(:);
l l
l l
l l
l l
l l
l l.
T{
\fB\-\-conf \fR\fB\fICONFIG_FILE\fR\fR
T}:T{
.sp
Use \fICONFIG_FILE\fR instead of the default from the configuration file for audit database configuration\&.
T}
T{
\fB\-\-check\fR
T}:T{
.sp
Check whether the insertion of a record was successful by querying the database after inserting the records\&. This is used in tests\&.
T}
T{
\fB\-\-delete\fR
T}:T{
Delete audit records from the database right after inserting them\&. This is used in tests to avoid filling the databse with test records\&.
T}
T{
\fB\-\-audit\-directory \fR\fB\fIDIR\fR\fR
T}:T{
Look for audit records in \fIDIR\fR, instead of looking in the directory specified in the job manager configuration\&. This is used in tests to control which records are loaded to the database and then deleted\&.
T}
T{
\fB\-\-query \fR\fB\fISQL\fR\fR
T}:T{
Perform the given SQL query on the audit database\&. This uses the database information from the configuration file to determine how to contact the database\&.
T}
T{
\fB\-\-quiet\fR
T}:T{
Reduce the amount of output for common operations\&.
T}
.TE
.sp 1
.SH "FILES"
.PP
The
\fBglobus\-gram\-audit\fR
uses the following files (paths relative to
\fB$GLOBUS_LOCATION\fR\&.
.TS
tab(:);
l l
l l.
T{
etc/globus\-gram\-job\-manager\&.conf
T}:T{
.sp
GRAM5 job manager configuration\&. It includes the default path to the audit directory
T}
T{
etc/globus\-gram\-audit\&.conf
T}:T{
.sp
Audit configuration\&. It includes the information needed to contact the audit database\&.
T}
.TE
.sp 1

