#! /usr/bin/env perl 

=head1 NAME

globus-gram-audit - Upload audit records to a database.

=head1 SYNOPSIS

B<globus-job-manager-service>

=head1 DESCRIPTION

Upload audit records to a database. Reads $GLOBUS_LOCATION/etc/globus-job-manager.conf
to determine the audit directory and then uploads all files in that directory that
contain valid audit records to the database configured by the 
globus_gram_job_manager_auditing_setup_scripts package. If the upload completes successfully,
the audit files will be removed. 

=cut

use strict;

local(*APPEND_IN);

my $audit_dir = &get_audit_dir();
my $datadir = "$ENV{GLOBUS_LOCATION}/share/globus_gram_job_manager_auditing";
my $audit_conf = "$ENV{GLOBUS_LOCATION}/etc/globus-job-manager-audit.conf";
my $argument_string = "-c $audit_conf";

if (! exists $ENV{GLOBUS_OPTIONS})
{
    $ENV{GLOBUS_OPTIONS} = "";
}
$ENV{GLOBUS_OPTIONS} .= " -Dlog4j.configuration=file://$datadir/log4j.properties";

if ($audit_dir eq '')
{
    print "No -audit-directory in job-manager.conf. Nothing to do\n";
    exit(0);
}

# Check if "--check" was added as commandline argument.
# This will cause the AuditDatabaseAppender to check the database
# connection and that the record with the given job_grid_id was inserted 
# into the database successfully
my $count = scalar(@ARGV);
for(my $i=0; $i<$count; $i++)
{
  if ($ARGV[$i] eq "--check") 
  {
    $argument_string = $argument_string . " $ARGV[$i]";
  }
} 

my $pid = open(APPEND_IN, "|$ENV{GLOBUS_LOCATION}/libexec/globus-gram-append-audit-records $argument_string");
select APPEND_IN; $|=1;
select STDOUT;
my @cleanup_list = ();

foreach (glob("$audit_dir/*.gramaudit"))
{
    local (*F);
    my $record_file = $_;
    my $owner = (stat($record_file))[4];
    my $record;
    my @record_entries;

    open(F, "<$record_file") || next;

    chomp($record = <F>);
    @record_entries = split(/"[^"]"/, $record);
    close(F);

    push(@cleanup_list, $record_file);

    # don't process entries where the owner != the job user
    if ($record_entries[3] ne (getpwuid($owner))[0])
    {
        next;
    }
    print APPEND_IN "$record\n" || die "Unable to write record to appender\n";
}

close(APPEND_IN);

# 0 or 1 as return value expected:
# 0=success, 1=failure in the AuditDatabaseAppender class
my $success = $?;

if ($success == 0)
{
    unlink(@cleanup_list);
}

exit $success >> 8;




sub get_audit_dir
{
    local(*F);
    my $jmconf = "$ENV{GLOBUS_LOCATION}/etc/globus-job-manager.conf";
    my $audit_dir = '';

    open(F, "<$jmconf");

    while(<F>)
    {
        if (m/-audit-directory\s+(\S+)\s+/)
        {
            $audit_dir = $1;
            last;
        }
    }
    close(F);

    return $audit_dir;
}
