#!/bin/sh
set -e # exit on any error
if test "$NMI_PLATFORM" = "ia64_sles_9" -o \
        "$NMI_PLATFORM" = "sun4u_sol_5.9"; then
  GT_INSTALLER=gt4.0.4-all-source-installer.tar.gz
  GT_INSTALLER_URL=http://www.globus.org/ftppub/gt4/4.0/4.0.4/installers/src/$GT_INSTALLER
else
  GT_INSTALLER=gt4.0.4-$NMI_PLATFORM-installer.tar.gz
  GT_INSTALLER_URL=http://www.globus.org/ftppub/gt4/4.0/4.0.4/installers/bin/$GT_INSTALLER
fi
GLOBUS_LOCATION=$_CONDOR_SCRATCH_DIR/globus
LOGNAME=$USER
X509_CERT_DIR=$GLOBUS_LOCATION/share/certificates
export GLOBUS_LOCATION LOGNAME X509_CERT_DIR
(
echo ==================================================
echo Environment variables:
env
echo ==================================================
echo Directory contents:
ls -Rl
echo ==================================================
echo PATHs:
echo `which wget`
echo `which curl`
echo `which ncftpget`
echo `which ftp`
echo ==================================================
echo Installing Globus Toolkit...
if test -x `which wget`; then
  wget $GT_INSTALLER_URL
else
  curl $GT_INSTALLER_URL > $GT_INSTALLER
fi
tar xfz $GT_INSTALLER
cd gt4*-installer
./configure --prefix=$GLOBUS_LOCATION --with-buildopts="-verbose"
make gsi-myproxy install
. $GLOBUS_LOCATION/etc/globus-user-env.sh
echo ==================================================
flavor=`gpt-query -name=myproxy | perl -n -e 'if (/myproxy-(.*)-pgm/){print "$1\n";}'|head -1`
echo GPT flavor is $flavor.  Installing globus_core.
gpt-build -nosrc $flavor
echo ==================================================
echo Installing autotools...
cd ../autotools
./install-autotools $GLOBUS_LOCATION
echo ==================================================
echo Building MyProxy...
cd ../myproxy
./bootstrap
./configure --with-flavor=$flavor
make dist
gpt-uninstall myproxy
gpt-build -verbose myproxy-*.tar.gz $flavor
echo ==================================================
echo Testing MyProxy...
mkdir $X509_CERT_DIR
cp nmi/*.0 nmi/*.signing_policy $X509_CERT_DIR
chmod 0600 nmi/userkey.pem
grid-proxy-init -debug -verify -cert nmi/usercert.pem -key nmi/userkey.pem
myproxy-test -startserver
myproxy-test-replicate
if test -f gtTRUNK-all-source-installer.tar.gz; then
    echo ==================================================
    echo Installing GT CVS Trunk...
    GLOBUS_LOCATION=$_CONDOR_SCRATCH_DIR/globus-trunk
    tar xfz gtTRUNK-all-source-installer.tar.gz
    cd gtTRUNK-all-source-installer
    ./configure --prefix=$GLOBUS_LOCATION --with-buildopts="-verbose"
    make gsi-myproxy install
    . $GLOBUS_LOCATION/etc/globus-user-env.sh
    echo ==================================================
    flavor=`gpt-query -name=myproxy | perl -n -e 'if (/myproxy-(.*)-pgm/){print "$1\n";}'|head -1`
    echo GPT flavor is $flavor.
    echo ==================================================
    echo Installing autotools...
    cd ../autotools
    ./install-autotools $GLOBUS_LOCATION
    echo ==================================================
    echo Building MyProxy...
    cd ../myproxy
    ./bootstrap
    ./configure --with-flavor=$flavor
    make dist
    gpt-uninstall myproxy
    gpt-build -verbose myproxy-*.tar.gz $flavor
    echo ==================================================
    echo Testing MyProxy...
    mkdir $X509_CERT_DIR
    cp nmi/*.0 nmi/*.signing_policy $X509_CERT_DIR
    chmod 0600 nmi/userkey.pem
    grid-proxy-init -debug -verify -cert nmi/usercert.pem -key nmi/userkey.pem
    myproxy-test -startserver
    myproxy-test-replicate
fi
) 2>&1 # we want stdout & stderr mixed in the output file
