'\" t
.\"     Title: globus-url-copy
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/09/2012
.\"    Manual: Globus Tookit
.\"    Source: The Globus Alliance
.\"  Language: English
.\"
.TH "GLOBUS\-URL\-COPY" "1" "02/09/2012" "The Globus Alliance" "Globus Tookit"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-url-copy \- globus\-url\-copy
.SH "SYNOPSIS"
.HP \w'\fBglobus\-url\-copy\fR\ 'u
\fBglobus\-url\-copy\fR [\fBoptions\fR] [SOURCE\-URL] [DESTINATION\-URL]
.SH "DESCRIPTION"
.PP
The
\fBglobus\-url\-copy\fR
program is a command line tool for multi\-protocol data movement\&. It supports gsiftp:// (GridFTP), ftp://, http://, https://, sshftp:// and file:/// protocol specifiers in the URL\&.
.SH "OPTIONS"
.PP
\fB\-help\fR, \fB\-usage\fR
.RS 4
Print help\&.
.RE
.PP
\fB\-versions\fR
.RS 4
Print the versions of all modules that this program uses
.RE
.PP
\fB\-c\fR, \fB\-continue\-on\-error\fR
.RS 4
Do not die after any errors\&. By default, program will exit after most errors\&.
.RE
.PP
\fB\-a\fR, \fB\-ascii\fR
.RS 4
Convert the file to/from ASCII format to/from local file format
.RE
.PP
\fB\-b\fR, \fB\-binary\fR
.RS 4
Do not apply any conversion to the files\&. *default*
.RE
.PP
\fB\-f filename\fR
.RS 4
Read a list of url pairs from filename\&. Each line should contain sourceURL destURL\&. Enclose URLs with spaces in double qoutes (")\&. Blank lines and lines beginning with # will be ignored\&.
.RE
.PP
\fB\-cd\fR, \fB\-create\-dest\fR
.RS 4
Create destination directory if needed\&.
.RE
.PP
\fB\-r\fR
.RS 4
Copy files in subdirectories
.RE
.PP
\fB\-fast\fR
.RS 4
Recommended when using GridFTP servers\&. Use MODE E for all data transfers, including reusing data channels between list and transfer operations\&.
.RE
.PP
\fB\-t transfer time in seconds\fR
.RS 4
Run the transfer for this number of seconds and then end\&. Useful for performance testing or forced restart loops\&.
.RE
.PP
\fB\-q\fR, \fB\-quiet\fR
.RS 4
Suppress all output for successful operation
.RE
.PP
\fB\-v\fR, \fB\-verbose\fR
.RS 4
Display urls being transferred
.RE
.PP
\fB\-vb\fR, \fB\-verbose\-perf\fR
.RS 4
During the transfer, display the number of bytes transferred and the transfer rate per second\&. Show urls being transferred
.RE
.PP
\fB\-dbg\fR, \fB\-debugftp\fR
.RS 4
Debug ftp connections\&. Prints control channel communication to stderr
.RE
.PP
\fB\-rst\fR, \fB\-restart\fR
.RS 4
Restart failed ftp operations\&.
.RE
.PP
\fB\-rst\-retries retries\fR
.RS 4
The maximum number of times to retry the operation before giving up on the transfer\&. Use 0 for infinite\&. Default is 5\&.
.RE
.PP
\fB\-rst\-interval seconds\fR
.RS 4
The interval in seconds to wait after a failure before retrying the transfer\&. Use 0 for an exponential backoff\&. Default is 0\&.
.RE
.PP
\fB\-rst\-timeout seconds\fR
.RS 4
Maximum time after a failure to keep retrying\&. Use 0 for no timeout\&. Default is 0\&.
.RE
.PP
\fB\-stall\-timeout SECONDS\fR, \fB\-st SECONDS\fR
.RS 4
How long before cancelling/restarting a transfer with no data movement\&. Set to 0 to disable\&. Default is 600 seconds\&.
.RE
.PP
\fB\-df FILENAME\fR, \fB\-dumpfile FILENAME\fR
.RS 4
Path to file where untransferred urls will be saved for later restarting\&. Resulting file is the same format as the \-f input file\&. If file exists, it will be read and all other url input will be ignored\&.
.RE
.PP
\fB\-do FILENAME\fR, \fB\-dump\-only FILENAME\fR
.RS 4
Perform no write operations on the destination\&. Instead, all files that would be transferred are enumerated and dumped to the specified file\&. Resulting file is the same format as the \-f input file\&. Note: if you intend to use this file as input for a future transfer, the \-create\-dest option will be required if any destination directories do not already exist\&.
.RE
.PP
\fB\-rp\fR, \fB\-relative\-paths\fR
.RS 4
The path portion of ftp urls will be interpereted as relative to the user\'s starting directory on the server\&. By default, all paths are root\-relative\&. When this flag is set, the path portion of the ftp url must start with %2F if it designates a root\-relative path\&.
.RE
.PP
\fB\-s SUBJECT\fR, \fB\-subject SUBJECT\fR
.RS 4
Use this subject to match with both the source and dest servers
.RE
.PP
\fB\-ss SUBJECT\fR, \fB\-source\-subject SUBJECT\fR
.RS 4
Use this subject to match with the source server
.RE
.PP
\fB\-ds SUBJECT\fR, \fB\-dest\-subject SUBJECT\fR
.RS 4
Use this subject to match with the destionation server
.RE
.PP
\fB\-tcp\-bs SIZE\fR, \fB\-tcp\-buffer\-size SIZE\fR
.RS 4
Specify the size (in bytes) of the buffer to be used by the underlying ftp data channels\&.
.RE
.PP
\fB\-bs block SIZE\fR, \fB\-block\-size block SIZE\fR
.RS 4
Specify the size (in bytes) of the buffer to be used by the underlying transfer methods
.RE
.PP
\fB\-p PARALLELISM\fR, \fB\-parallel PARALLELISM\fR
.RS 4
Specify the number of parallel data connections should be used\&.
.RE
.PP
\fB\-notpt\fR, \fB\-no\-third\-party\-transfers\fR
.RS 4
Turn third\-party transfers off (on by default)\&.
.RE
.PP
\fB\-nodcau\fR, \fB\-no\-data\-channel\-authentication\fR
.RS 4
Turn off data channel authentication for ftp transfers\&.
.RE
.PP
\fB\-dcsafe\fR, \fB\-data\-channel\-safe\fR
.RS 4
Set data channel protection mode to SAFE
.RE
.PP
\fB\-dcpriv\fR, \fB\-data\-channel\-private\fR
.RS 4
Set data channel protection mode to PRIVATE
.RE
.PP
\fB\-off\fR, \fB\-partial\-offset\fR
.RS 4
Offset for partial ftp file transfers, defaults to 0
.RE
.PP
\fB\-len\fR, \fB\-partial\-length\fR
.RS 4
Length for partial ftp file transfers, used only for the source url, defaults the full file\&.
.RE
.PP
\fB\-list URL\fR
.RS 4
List the files located at URL\&.
.RE
.PP
\fB\-stripe\fR
.RS 4
Enable striped transfers on supported servers
.RE
.PP
\fB\-striped\-block\-size\fR, \fB\-sbs\fR
.RS 4
Set layout mode and blocksize for striped transfers\&. If not set, server defaults will be used\&. If set to 0, Partitioned mode will be used\&. If set to >0, Blocked mode will be used, with this as the blocksize\&.
.RE
.PP
\fB\-ipv6\fR
.RS 4
Use ipv6 when available (EXPERIMENTAL)
.RE
.PP
\fB\-udt\fR
.RS 4
Use UDT, a reliable udp based transport protocol, for data transfers
.RE
.PP
\fB\-g2\fR, \fB\-gridftp2\fR
.RS 4
Use GridFTP v2 protocol enhancements when possible
.RE
.PP
\fB\-dp\fR, \fB\-delayed\-pasv\fR
.RS 4
Enable delayed passive
.RE
.PP
\fB\-mn\fR, \fB\-module\-name gridftp storage module name\fR
.RS 4
Set the backend storage module to use for both the source and destination in a GridFTP transfer
.RE
.PP
\fB\-mp\fR, \fB\-module\-parameters gridftp storage module parameters\fR
.RS 4
Set the backend storage module arguments to use for both the source and destination in a GridFTP transfer
.RE
.PP
\fB\-smn\fR, \fB\-src\-module\-name gridftp storage module name\fR
.RS 4
Set the backend storage module to use for the source in a GridFTP transfer
.RE
.PP
\fB\-smp\fR, \fB\-src\-module\-parameters gridftp storage module parameters\fR
.RS 4
Set the backend storage module arguments to use for the source in a GridFTP transfer
.RE
.PP
\fB\-dmn\fR, \fB\-dst\-module\-name gridftp storage module name\fR
.RS 4
Set the backend storage module to use for the destination in a GridFTP transfer
.RE
.PP
\fB\-dmp\fR, \fB\-dst\-module\-parameters gridftp storage module parameters\fR
.RS 4
Set the backend storage module arguments to use for the destination in a GridFTP transfer
.RE
.PP
\fB\-aa\fR, \fB\-authz\-assert authorization assertion file\fR
.RS 4
Use the assertions in this file to authorize the access with both source and dest servers
.RE
.PP
\fB\-saa\fR, \fB\-src\-authz\-assert authorization assertion file\fR
.RS 4
Use the assertions in this file to authorize the access with source server
.RE
.PP
\fB\-daa\fR, \fB\-dst\-authz\-assert authorization assertion file\fR
.RS 4
Use the assertions in this file to authorize the access with dest server
.RE
.PP
\fB\-cache\-aa\fR, \fB\-cache\-authz\-assert\fR
.RS 4
Cache the authz assertion for subsequent transfers
.RE
.PP
\fB\-cache\-saa\fR, \fB\-cache\-src\-authz\-assert\fR
.RS 4
Cache the src authz assertion for subsequent transfers
.RE
.PP
\fB\-cache\-daa\fR, \fB\-cache\-dst\-authz\-assert\fR
.RS 4
Cache the dst authz assertion for subsequent transfers
.RE
.PP
\fB\-pipeline\fR, \fB\-pp\fR
.RS 4
Enable pipelining support for multi\-file ftp transfers\&. Currently third\-party transfers benefit from this\&. *EXPERIMENTAL*
.RE
.PP
\fB\-concurrency\fR, \fB\-cc\fR
.RS 4
Number of concurrent ftp connections to use for multiple transfers\&.
.RE
.PP
\fB\-nl\-bottleneck\fR, \fB\-nlb\fR
.RS 4
Use NetLogger to estimate speeds of disk and network read/write system calls, and attempt to determine the bottleneck component
.RE
.PP
\fB\-src\-pipe\fR, \fB\-SP command line\fR
.RS 4
Set the source end of a remote transfer to use piped in input with the given command line\&. Do not use with \-fsstack
.RE
.PP
\fB\-dst\-pipe\fR, \fB\-DP command line\fR
.RS 4
Set the destination end of a remote transfer to write data to then standard input of the program run via the given command line\&. Do not use with \-fsstack
.RE
.PP
\fB\-pipe command line\fR
.RS 4
Sets both \-src\-pipe and \-dst\-pipe to the same thing\&.
.RE
.PP
\fB\-dcstack\fR, \fB\-data\-channel\-stack\fR
.RS 4
Set the XIO driver stack for the network on both the source and the destination\&. Both must be GridFTP servers\&.
.RE
.PP
\fB\-fsstack\fR, \fB\-file\-system\-stack\fR
.RS 4
Set the XIO driver stack for the disk on both the source and the destination\&. Both must be GridFTP servers\&.
.RE
.PP
\fB\-src\-dcstack\fR, \fB\-source\-data\-channel\-stack\fR
.RS 4
Set the XIO driver stack for the network on the source GridFTP server\&.
.RE
.PP
\fB\-src\-fsstack\fR, \fB\-source\-file\-system\-stack\fR
.RS 4
Set the XIO driver stack for the disk on the source GridFTP server\&.
.RE
.PP
\fB\-dst\-dcstack\fR, \fB\-dest\-data\-channel\-stack\fR
.RS 4
Set the XIO driver stack for the network on the destination GridFTP server\&.
.RE
.PP
\fB\-dst\-fsstack\fR, \fB\-dest\-file\-system\-stack\fR
.RS 4
Set the XIO driver stack for the disk on the destination GridFTP server\&.
.RE
.PP
\fB\-cred path to credentials or proxy file\fR
.RS 4
Set the credentials to use for both ftp connections\&.
.RE
.PP
\fB\-src\-cred CRED\-FILE\fR, \fB\-sc CRED\-FILE\fR
.RS 4
Set the credentials to use for source ftp connections\&.
.RE
.PP
\fB\-dst\-cred\fR, \fB\-dc path to credentials or proxy file\fR
.RS 4
Set the credentials to use for destination ftp connections\&.
.RE
.PP
\fB\-af filename\fR, \fB\-alias\-file filename\fR
.RS 4
File with mapping of logical host aliases to lists of physical hosts\&. When used with multiple conncurrent connections, each connection uses the next host in the list\&. Each line should either be an alias, noted with the @ symbol, or a hostname[:port]\&. Currently, only the aliases @source and @destination are valid, and they are used for every source or destination url\&.
.RE
.PP
\fB\-sync\fR
.RS 4
Only transfer files where the destination does not exist or differs from the source\&. \-sync\-level controls how to determine if files differ\&.
.RE
.PP
\fB\-sync\-level number\fR
.RS 4
Choose critera for determining if files differ when performing a sync transfer\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Level 0 will only transfer if the destination does not exist\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Level 1 will transfer if the size of the destination does not match the size of the source\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Level 2 will transfer if the timestamp of the destination is older than the timestamp of the source\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Level 3 will perform a checksum of the source and destination and transfer if the checksums do not match\&.
.RE
.RS 4
.sp
The default sync level is 2\&.
.RE
.SH "AUTHOR"
.br
.br
The Globus Alliance, http://www\&.globus\&.org/
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 1999-2010 University of Chicago
.br
