include makefile-header

grim-assertion-test: grim_assertion_test.c
	$(GLOBUS_CC) $(GLOBUS_INCLUDES) $(GLOBUS_CFLAGS) \
        -o grim-assertion-test grim_assertion_test.c \
            $(GLOBUS_LDFLAGS) $(GLOBUS_PKG_LIBS)
