#! /bin/sh
version="$(./setup.py --version)"
major="${version%%.*}"
minor="${version##*.}"
cat <<EOF > gptdata.sh
GPT_NAME='myproxy_oauth'
GPT_MAJOR_VERSION='$major'
GPT_MINOR_VERSION='$minor'
GPT_AGE_VERSION='$major'
GPT_CFLAGS='@GPT_PKG_CFLAGS@'
GPT_INCLUDES='@GPT_EXTERNAL_INCLUDES@'
GPT_LIBS='@GPT_EXTERNAL_LIBS@'
GPT_BUILD_WITH_FLAVORS='no'

