#!/bin/sh                                                            
                                                                      
exec /opt/globus/sbin/globus-gridftp-server -c /usr/local/share/GridftpHdfs/gridftp.conf -dsi hdfs -no-fork

