#!/bin/sh                                                            
                                                                      
exec /opt/globus//sbin/globus-gridftp-server -c /tmp/blah/share/GridftpHdfs/gridftp.conf -dsi hdfs -no-fork

