'\" t
.\"     Title: globus-k5
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/08/2016
.\"    Manual: Globus Toolkit Manual
.\"    Source: Globus Toolkit 6
.\"  Language: English
.\"
.TH "GLOBUS\-K5" "8" "09/08/2016" "Globus Toolkit 6" "Globus Toolkit Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-k5 \- Acquire Kerberos Credentials for use with Grid Services
.SH "SYNOPSIS"
.sp
\fBglobus\-k5\fR \fISERVICE\-COMMAND\fR \fISERVICE\-ARGS\fR\&...
.SH "DESCRIPTION"
.sp
The \fBglobus\-k5\fR program is an authorization module used by the globus\-gatekeeper program to acquire Kerberos 5 Credentials prior to executing a Grid Service\&. This may be accomplished by running \fBkinit\fR with a password stored in the globuskmap file, using the NCSA \fBkrb525\fR command, or the \fBsslk5\fR command to use the X509 user proxy\&.
.sp
The arguments passed to \fBglobus\-k5\fR will not be used by it, but will be passed onto the job manager\&. The first parameter must be the path to the Grid Service\&.
.sp
It is expected that the environment will contain the variables GLOBUSID and USER for the Grid and local POSIX user identities\&. This program is normally run as root, and will call seteuid() prior to executing the Grid Service\&.
.sp
The parameters to use and the mapping for the globus to K5 user are located in the globuskmap file\&.
.SS "Format of the globuskmap file"
.sp
The globuskmap file is a line\-oriented file which each line containing a command to run to acquire Kerberos 5 credentials for a Grid identity\&. Each line consists of an optionally\-quoted \fIGLOBUSID\fR value followed by a command\-line for running a process to acquire a Kerberos credential\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
"/O=Example/OU=Grid/CN=Joe User" /usr/afsws/bin/klog \-principal juser \-password mypasswd \-cell infn\&.it
.fi
.if n \{\
.RE
.\}
.SH "ENVIRONMENT"
.sp
The following variables affect the execution of \fBglobus\-k5\fR:
.PP
\fBGLOBUSKMAP\fR
.RS 4
Path to the globuskmap file\&.
.RE
.PP
\fBUSER\fR
.RS 4
POSIX username that the service will run as\&.
.RE
.PP
\fBKRB5CCNAME\fR
.RS 4
Path to a Kerberos credential cache\&.
.RE
.PP
\fBGLOBUS_ID\fR
.RS 4
Grid identity to generate Kerberos credentials for\&.
.RE
.SH "FILES"
.sp
The following files affect the execution of \fBglobus\-k5\fR:
.PP
\fB/etc/globuskmap\fR
.RS 4
Default file mapping Grid identities to Kerberos 5 principals\&.
.RE
.SH "SEE ALSO"
.sp
\fBglobus\-k5\fR(8), \fBglobus\-job\-manager\fR(8)
.SH "AUTHOR"
.sp
Copyright \(co 1999\-2016 University of Chicago
