'\" t
.\"     Title: globus-gatekeeper
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 10/27/2009
.\"    Manual: GRAM5 Commands
.\"    Source: University of Chicago
.\"  Language: English
.\"
.TH "GLOBUS\-GATEKEEPER" "8" "10/27/2009" "University of Chicago" "GRAM5 Commands"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-gatekeeper \- Authorize and execute a grid service on behalf of a user
.SH "SYNOPSIS"
.HP \w'\fBglobus\-gatekeeper\fR\ 'u
\fBglobus\-gatekeeper\fR [\-help] [\-conf\ \fIPARAMETER_FILE\fR] [\-test] [\-d | \-debug] {\-inetd | \-f} [\-p\ \fIPORT\fR | \-port\ \fIPORT\fR] [\-home\ \fIPATH\fR] [\-l\ \fILOGFILE\fR | \-logfile\ \fILOGFILE\fR] [\-acctfile\ \fIACCTFILE\fR] [\-e\ \fILIBEXECDIR\fR] [\-launch_method\ {fork_and_exit\ |\ fork_and_wait\ |\ dont_fork}] [\-grid_services\ \fISERVICEDIR\fR] [\-globusid\ \fIGLOBUSID\fR] [\-gridmap\ \fIGRIDMAP\fR] [\-x509_cert_dir\ \fITRUSTED_CERT_DIR\fR] [\-x509_cert_file\ \fITRUSTED_CERT_FILE\fR] [\-x509_user_cert\ \fICERT_PATH\fR] [\-x509_user_key\ \fIKEY_PATH\fR] [\-x509_user_proxy\ \fIPROXY_PATH\fR] [\-k] [\-globuskmap\ \fIKMAP\fR]
.SH "DESCRIPTION"
.PP
The
\fBglobus\-gatekeeper\fR
program is a meta\-server similar to
\fBinetd\fR
or
\fBxinetd\fR
that starts other services after authenticating the TCP connection using GSSAPI\&.
.PP
The most common use for the
\fBglobus\-gatekeeper\fR
program is to start instances of the
\fBglobus-job-manager\fR(8)
service\&. A single
\fBglobus\-gatekeeper\fR
deployment can handle multiple different service configurations by having entries in the grid\-services directory\&.
.PP
Typically, users interact with the
\fBglobus\-gatekeeper\fR
program via client applications such as
\fBglobusrun\fR(1),
\fBglobus\-job\-submit\fR, or tools such as CoG jglobus or Condor\-G\&.
.PP
The full set of command\-line options to
\fBglobus\-job\-manager\fR
consists of:
.TS
allbox tab(:);
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l
l l.
T{
\-help
T}:T{
Display a help message to standard error and exit
T}
T{
\-conf \fIPARAMETER_FILE\fR
T}:T{
Load configuration parameters from \fIPARAMETER_FILE\fR\&. The parameters in that file are treated as additional command\-line options\&.
T}
T{
\-test
T}:T{
Parse the configuration file and print out the POSIX user id of the \fBglobus\-gatekeeper\fR process, service home directory, service execution directory, and X\&.509 subject name and then exits\&.
T}
T{
\-d | \-debug
T}:T{
Run the \fBglobus\-gatekeeper\fR process in the foreground\&.
T}
T{
\-inetd
T}:T{
Flag to indicate that the \fBglobus\-gatekeeper\fR process was started via \fBinetd\fR or a similar super\-server\&. If this flag is set and the \fBglobus\-gatekeeper\fR was not started via inetd, a warning will be printed in the gatekeeper log\&.
T}
T{
\-f
T}:T{
Flag to indicate that the \fBglobus\-gatekeeper\fR process should run in the foreground\&. This flag has no effect when the \fBglobus\-gatekeeper\fR is started via inetd\&.
T}
T{
\-p \fIPORT\fR | \-port \fIPORT\fR
T}:T{
Listen for connections on the TCP/IP port \fIPORT\fR\&. This option has no effect if the \fBglobus\-gatekeeper\fR is started via inetd or a similar service\&. If not specified and the gatekeeper is running as root, the default of 754 is used\&. Otherwise, the gatekeeper defaults to an ephemeral port\&.
T}
T{
\-home \fIPATH\fR
T}:T{
Sets the gatekeeper deployment directory to \fIPATH\fR\&. This is used to interpret relative paths for accounting files, libexecdir, certificate paths, and also to set the \fBGLOBUS_LOCATION\fR environment variable in the service environment\&. If not specified, the gatekeeper uses its working directory\&.
T}
T{
\-l \fILOGFILE\fR | \-logfile \fILOGFILE\fR
T}:T{
Write status log entries to \fILOGFILE\fR
T}
T{
\-acctfile \fIACCTFILE\fR
T}:T{
Set the path to write accounting records to \fIACCTFILE\fR\&. If not set, no accounting records will be written\&.
T}
T{
\-e \fILIBEXECDIR\fR
T}:T{
Look for service executables in \fILIBEXECDIR\fR\&. If not specified, the default of \fIHOME\fR/libexec is used\&.
T}
T{
\-launch_method fork_and_exit|fork_and_wait|dont_fork
T}:T{
Determine how to launch services\&. The method may be either fork_and_exit (the service runs completely independently of the gatekeeper, which exits after creating the new service process), fork_and_wait (the service is run in a separate process from the gatekeeper but the gatekeeper does not exit until the service terminates), or dont_fork, where the gatekeeper process becomes the service process via the \fBexec()\fR system call\&.
T}
T{
\-grid_services \fISERVICEDIR\fR
T}:T{
Look for service descriptions in \fISERVICEDIR\fR\&. If this is a relative path, it is interpreted relative to the \fIHOME\fR value\&. If this is not specified, the default of \fIHOME\fR/etc/grid\-services is used\&.
T}
T{
\-globusid \fIGLOBUSID\fR
T}:T{
Sets the \fBGLOBUSID\fR environment variable to \fIGLOBUSID\fR\&. This variable is used to construct the gatekeeper contact string if it can not be parsed from the service credential\&.
T}
T{
\-gridmap \fIGRIDMAP\fR
T}:T{
Use the file at \fIGRIDMAP\fR to map GSSAPI names to POSIX user names\&. If not specified, the default of \fIHOME\fR/etc/grid\-mapfile is used\&.
T}
T{
\-x509_cert_dir \fITRUSTED_CERT_DIR\fR
T}:T{
Use the directory \fITRUSTED_CERT_DIR\fR to locate trusted CA X\&.509 certificates\&. The gatekeeper sets the environment variable \fBX509_CERT_DIR\fR to this value\&.
T}
T{
\-x509_cert_file \fITRUSTED_CERT_FILE\fR
T}:T{
OBSOLETE GSI OPTION
T}
T{
\-x509_user_cert \fICERT_PATH\fR
T}:T{
Read the service X\&.509 certificate from \fICERT_PATH\fR\&. The gatekeeper sets the \fBX509_USER_CERT\fR environment variable to this value\&.
T}
T{
\-x509_user_key \fIKEY_PATH\fR
T}:T{
Read the private key for the service from \fIKEY_PATH\fR\&. The gatekeeper sets the \fBX509_USER_KEY\fR environment variable to this value\&.
T}
T{
\-x509_user_proxy \fIPROXY_PATH\fR
T}:T{
Read the X\&.509 proxy certificate from \fIPROXY_PATH\fR\&. The gatekeeper sets the \fBX509_USER_PROXY\fR environment variable to this value\&.
T}
T{
\-k
T}:T{
Assume authentication with Kerberos 5 GSSAPI instead of X\&.509 GSSAPI\&.
T}
T{
\-globuskmap \fIKMAP\fR
T}:T{
Assume authentication with Kerberos 5 GSSAPI instead of X\&.509 GSSAPI and use \fIKMAP\fR as the path to the kerberos principal to POSIX user mapping file\&.
T}
.TE
.sp 1
.SH "ENVIRONMENT"
.PP
If the following variables affect the execution of
\fBglobus\-job\-manager\fR
.TS
allbox tab(:);
l l
l l
l l
l l.
T{
X509_CERT_DIR
T}:T{
Directory containing X\&.509 trust anchors and signing policy files\&.
T}
T{
X509_USER_PROXY
T}:T{
Path to file containing an X\&.509 proxy\&.
T}
T{
X509_USER_CERT
T}:T{
Path to file containing an X\&.509 user certificate\&.
T}
T{
X509_USER_KEY
T}:T{
Path to file containing an X\&.509 user key\&.
T}
.TE
.sp 1
.SH "FILES"
.PP
.TS
allbox tab(:);
l l
l l.
T{
\fB$GLOBUS_LOCATION\fR/etc/globus\-gatekeeper\&.conf
T}:T{
Default path to gatekeeper configuration file\&.
T}
T{
\fB$GLOBUS_LOCATION\fR/etc/grid\-services/\fISERVICENAME\fR
T}:T{
Service configuration for \fISERVICENAME\fR\&.
T}
.TE
.sp 1
.SH "SEE ALSO"
.PP

\fBglobusrun\fR(1),
\fBglobus-job-manager\fR(8)
