'\" t
.\"     Title: globus-rvf-check
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/08/2016
.\"    Manual: Globus Toolkit Manual
.\"    Source: Globus Toolkit 6
.\"  Language: English
.\"
.TH "GLOBUS\-RVF\-CHECK" "8" "09/08/2016" "Globus Toolkit 6" "Globus Toolkit Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-rvf-check \- Edit a GRAM5 RSL validation file
.SH "SYNOPSIS"
.sp
\fBglobus\-rvf\-check\fR \fI\-h\fR \fI\-help\fR
.SH "DESCRIPTION"
.sp
The \fBglobus\-rvf\-check\fR command is a utility which checks the syntax of a RSL validation file, and prints out parse errors when encountered\&. It can also parse the RVF file contents and then dump file\(cqs contents to stdout, after canonicalizing values and quoting\&. The exit code of command is a utility which checks the syntax of a RSL validation file, and prints out parse errors when encountered\&. It can also parse the RVF file contents and then dump file\(cqs contents to stdout, after canonicalizing values and quoting\&. The exit code of \fBglobus\-rvf\-check\fR is 0 if all files specified on the command line exist and have no parse errors\&. is 0 if all files specified on the command line exist and have no parse errors\&.
.sp
The full set of command\-line options to \fBglobus\-rvf\-check\fR consists of: consists of:
.PP
\fB\fI\-h\fR\fR\fB,\fR\fB\fI\-help\fR\fR\fB,\fR\fB\fI\-\-help\fR\fR
.RS 4
Print command\-line option summary and exit
.RE
.PP
\fB\fI\-d\fR\fR
.RS 4
Dump the RVF contents to stdout\&. In the output, Each file which is parsed will be prefixed by an RVF comment which contains the input filename\&. If not specified,
\fBglobus\-rvf\-check\fR
just prints a diagnostic message to standard output indicating whether the file could be parsed\&. just prints a diagnostic message to standard output indicating whether the file could be parsed\&.
.RE
.SH "SEE ALSO"
.sp
globus\-rvf\-edit(8)
.SH "AUTHOR"
.sp
Copyright \(co 1999\-2016 University of Chicago
