'\" t
.\"     Title: globus-rvf-edit
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/08/2016
.\"    Manual: Globus Toolkit Manual
.\"    Source: Globus Toolkit 6
.\"  Language: English
.\"
.TH "GLOBUS\-RVF\-EDIT" "8" "09/08/2016" "Globus Toolkit 6" "Globus Toolkit Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-rvf-edit \- Edit a GRAM5 RSL validation file
.SH "SYNOPSIS"
.sp
\fBglobus\-rvf\-edit\fR \fI\-h\fR
.SH "DESCRIPTION"
.sp
The \fBglobus\-rvf\-edit\fR command is a utility which opens the default editor on a specified RSL validation file, and then, when editing completes, runs the command is a utility which opens the default editor on a specified RSL validation file, and then, when editing completes, runs the \fBglobus\-rvf\-check\fR command to verify that the RVF file syntax is correct\&. If a parse error occurs, the user will be given an option to rerun the editor or discard the modifications\&. command to verify that the RVF file syntax is correct\&. If a parse error occurs, the user will be given an option to rerun the editor or discard the modifications\&.
.sp
The full set of command\-line options to \fBglobus\-rvf\-edit\fR consists of: consists of:
.PP
\fB\fI\-h\fR\fR
.RS 4
Print command\-line option summary and exit
.RE
.PP
\fB\fI\-s\fR\fR
.RS 4
Edit of the site\-specific RVF file, which provides override values applicable to all LRMs installed on the system\&.
.RE
.PP
\fB\*(Aq\-l \*(Aq\fR
.RS 4
Edit the site\-specific LRM overrides for the LRM named by the
\fI\*(AqLRM\fR\*(Aq parameter to the option\&.
.RE
.PP
\fB\*(Aq\-f \*(Aq\fR
.RS 4
Edit the RVF file located at
\fI\*(AqPATH\fR\*(Aq
.RE
.SH "SEE ALSO"
.sp
globus\-rvf\-check(8)
.SH "AUTHOR"
.sp
Copyright \(co 1999\-2016 University of Chicago
