/* Application specific options */VE_STDARG_H

#undef HAVE_POLL

#undef ssize_t

#undef HAVE_SEEKDIR
#undef HAVE_TELLDIR

#undef HAVE_GETHOSTBYNAME
#undef HAVE_GETHOSTBYNAME_R

#undef HAVE_GETHOSTBYADDR
#undef HAVE_GETHOSTBYADDR_R

#undef HAVE_CTIME
#undef HAVE_CTIME_R

#undef HAVE_STDARG_H

#undef HAVE_MKTIME

#undef HAVE_GETPWNAM
#undef HAVE_GETPWNAM_R

#undef HAVE_GETPWUID
#undef HAVE_GETPWUID_R

#undef GLOBUS_HAVE_PW_AGE
#undef GLOBUS_HAVE_PW_COMMENT

#undef GLOBUS_HAVE_GETHOSTBYNAME_R_3
#undef GLOBUS_HAVE_GETHOSTBYNAME_R_5
#undef GLOBUS_HAVE_GETHOSTBYNAME_R_6

#undef GLOBUS_HAVE_GETHOSTBYADDR_R_5
#undef GLOBUS_HAVE_GETHOSTBYADDR_R_7
#undef GLOBUS_HAVE_GETHOSTBYADDR_R_8

#undef GLOBUS_HAVE_CTIME_R_2
#undef GLOBUS_HAVE_CTIME_R_3
#undef GLOBUS_HAVE_GETPWNAM_R_4
#undef GLOBUS_HAVE_GETPWNAM_R_5
#undef GLOBUS_HAVE_GETPWUID_R_4
#undef GLOBUS_HAVE_GETPWUID_R_5

#undef GLOBUS_HAVE_READDIR_R_2
#undef GLOBUS_HAVE_READDIR_R_3

#undef GLOBUS_HAVE_DIRENT_OFFSET
#undef GLOBUS_HAVE_DIRENT_OFF
#undef GLOBUS_HAVE_DIRENT_TYPE
#undef GLOBUS_HAVE_DIRENT_RECLEN

#undef HAVE_ATEXIT
#undef HAVE_ONEXIT
