#! /bin/sh

# check for autotools

for program in automake aclocal autoconf autoheader
    do
    ($program --version ) > /dev/null 2>&1 || { 
    echo "ERROR: $program not found" >&2
    exit 1
    }
done

# checking for the GLOBUS_INSTALL_PATH

if test "x$GLOBUS_INSTALL_PATH" = "x"; then
    echo "ERROR Please specify GLOBUS_INSTALL_PATH" >&2
    exit 1
fi

echo "running aclocal -I $GLOBUS_INSTALL_PATH/share/globus_aclocal"
aclocal -I $GLOBUS_INSTALL_PATH/share/globus_aclocal

echo "running autoheader"
autoheader

if test ! -f globus_automake_targets; then
    cp $GLOBUS_INSTALL_PATH/share/globus_aclocal/automake_targets \
    globus_automake_targets
    cp $GLOBUS_INSTALL_PATH/share/globus_aclocal/automake_rules \
    globus_automake_rules
fi

echo "installing extra automake file"
echo "running automake -c -a --foreign"
automake -c -a --foreign

echo "running autoconf"
autoconf
