#! /bin/sh

# checking for the GLOBUS_LOCATION

if test "x$GLOBUS_LOCATION" = "x"; then
    echo "ERROR Please specify GLOBUS_LOCATION" >&2
    exit 1
fi

if [ ! -f ${GLOBUS_LOCATION}/libexec/globus-bootstrap.sh ]; then
    echo "ERROR: Unable to locate \${GLOBUS_LOCATION}/libexec/globus-bootstrap.sh"
    echo "       Please ensure that you have installed the globus-core package and"
    echo "       that GLOBUS_LOCATION is set to the proper directory"
    exit
fi

echo -n "Checking for data modules... "
modules=`ls modules | grep -v CVS | grep -v Makefile`
modules_makefiles=
delim=
if test "X$modules" != "X" ; then
  echo
  for module in $modules ; do
    modules_makefiles="$modules_makefiles modules/$module/Makefile"
    echo "Including module: $module"
  done
else
  echo "none found"
fi

echo -n "Checking for commands... "
commands=`ls commands | grep -v CVS | grep -v Makefile`
commands_makefiles=
delim=
if test "X$commands" != "X" ; then
  echo
  for command in $commands ; do
    commands_makefiles="$commands_makefiles commands/$command/Makefile"
    echo "Including command: $command"
  done
else
  echo "none found"
fi

cp -f configure.in.in configure.in
echo "$modules_makefiles $commands_makefiles)" >> configure.in

. ${GLOBUS_LOCATION}/libexec/globus-bootstrap.sh
