'\" t
.\"     Title: grid-mapfile-delete-entry
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/08/2016
.\"    Manual: Globus Toolkit Manual
.\"    Source: Globus Toolkit 6
.\"  Language: English
.\"
.TH "GRID\-MAPFILE\-DELET" "8" "09/08/2016" "Globus Toolkit 6" "Globus Toolkit Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
grid-mapfile-delete-entry \- Remove entries from a gridmap file
.SH "SYNOPSIS"
.sp
\fBgrid\-mapfile\-delete\-entry\fR [ \-help | \-usage | \-version | \-versions ]
.sp
\fBgrid\-mapfile\-delete\-entry\fR \-dn \fIDISTINGUISHED\-NAME\fR \-ln LOCAL\-NAME\&... [ \-d | \-dryrun ] [ \-mapfile MAPFILE | \-f MAPFILE ]
.SH "DESCRIPTION"
.sp
The \fBgrid\-mapfile\-delete\-entry\fR program deletes mappings from a gridmap file\&. If both the \fI\-dn\fR and \fI\-ln\fR options are specified, \fBgrid\-mapfile\-delete\-entry\fR removes entries which meet both criteria (remove entries mapping \fIDISTINGUISHED\-NAME\fR to \fILOCAL\-NAME\fR for each \fILOCAL\-NAME\fR specified)\&. If only \fI\-dn\fR or \fI\-ln\fR is specified \fBall\fR entries for the specified \fIDISTINGUISHED\-NAME\fR or \fILOCAL\-NAME\fR are removed\&.
.sp
By default, \fBgrid\-mapfile\-delete\-entry\fR will modify the gridmap file named by the GRIDMAP environment variable if present, or the file /etc/grid\-security/grid\-mapfile if not\&. This can be changed by the use of the \fI\-mapfile\fR or \*(Aq\-f command\-line options\&.
.sp
Prior to modifying a gridmap file, \fBgrid\-mapfile\-delete\-entry\fR saves its current contents to a file with the string \&.old appended to the original file name\&.
.sp
The full set of command\-line options to \fBgrid\-mapfile\-delete\-entry\fR are:
.PP
\fB\-help, \-usage\fR
.RS 4
Display the command\-line options to
\fBgrid\-mapfile\-delete\-entry\fR\&.
.RE
.PP
\fB\-version, \-versions\fR
.RS 4
Display the version number of the
\fBgrid\-mapfile\-delete\-entry\fR
command\&. The second form includes more details\&.
.RE
.PP
\fB\-dn DISTINGUISHED\-NAME\fR
.RS 4
The X\&.509 distinguished name to remove from the gridmap file\&. If the
\fI\-ln\fR
option is not specified, remove all entries for this name; otherwise, remove entries that match both this name and the local name\&. The name should be in OpenSSL\(cqs
oneline
format\&.
.RE
.PP
\fB\-ln LOCAL\-NAME\&...\fR
.RS 4
The POSIX user name to remove from the gridmap file\&. Include multiple
\fILOCAL\-NAME\fR
strings after the
\fI\-ln\fR
command\-line option to remove multiple names from the gridmap\&. If the
\fI\-dn\fR
option is not specifeid, remove all entries for these names; otherwise, remove entries that match the
\fIDISTINGUISHED\-NAME\fR
and any of the
\fILOCAL\-NAME\fR
values\&.
.RE
.PP
\fB\-d, \-dryrun\fR
.RS 4
Display diagnostics about what would be removed from the gridmap file, but don\(cqt actually modify the file\&.
.RE
.PP
\fB\-mapfile MAPFILE, \-f MAPFILE\fR
.RS 4
Modify the gridmap file named by
\fIMAPFILE\fR
instead of the default\&.
.RE
.SH "EXAMPLES"
.sp
Remove all mappings for a distinguished name:
.sp
.if n \{\
.RS 4
.\}
.nf
% grid\-mapfile\-delete\-entry "/DC=org/DC=example/DC=grid/CN=Joe User"
Modifying /etc/grid\-security/grid\-mapfile \&.\&.\&.
Deleting entry: "/DC=org/DC=example/DC=grid/CN=Joe User" juser,juser2
(1) entry deleted
.fi
.if n \{\
.RE
.\}
.sp
Remove the mapping between a distinguished name and a single local username:
.sp
.if n \{\
.RS 4
.\}
.nf
% grid\-mapfile\-delete\-entry "/DC=org/DC=example/DC=grid/CN=Joe User" \-ln juser2
Modifying /etc/grid\-security/grid\-mapfile \&.\&.\&.
Current entry: "/DC=org/DC=example/DC=grid/CN=Joe User" juser
(1) mapping removed: (juser2), (0) not present and ignored
(0) entries deleted
.fi
.if n \{\
.RE
.\}
.SH "ENVIRONMENT"
.sp
The following environment variables affect the execution of \fBgrid\-mapfile\-delete\-entry\fR:
.PP
\fBGRIDMAP\fR
.RS 4
Path to the gridmap to modify\&.
.RE
.SH "FILES"
.sp
The following files affect the execution of \fBgrid\-mapfile\-delete\-entry\fR:
.PP
\fB/etc/grid\-security/grid\-mapfile\fR
.RS 4
Path to the default gridmap to modify if
GRIDMAP
environment variable is not set\&.
.RE
.SH "SEE ALSO"
.sp
grid\-mapfile\-add\-entry(8), grid\-mapfile\-check\-consistency(8)
.SH "AUTHOR"
.sp
Copyright \(co 1999\-2016 University of Chicago
