<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ReliableTransferServiceDefinition"
  targetNamespace="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:gsdl="http://www.gridforum.org/namespaces/2002/07/gridServices"
  xmlns:reliable-transfer-types="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer_types"
  xmlns:reliable-transfer-bindings="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer_bindings"
  xmlns:grid-service-bindings="http://ogsa.gridforum.org/service/grid_service/bindings"
  xmlns:notification-source-bindings="http://ogsa.gridforum.org/notification/notification_source/bindings"
  xmlns:auth-bindings="http://ogsa.globus.org/security/authentication/bindings"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">


<import location="reliable_transfer_bindings.wsdl"
        namespace="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer_bindings"/>

<import location="../../core/service/grid_service_bindings.wsdl"
        namespace="http://ogsa.gridforum.org/service/grid_service/bindings"/>

<import location="../../core/notification/notification_source_bindings.wsdl"
        namespace="http://ogsa.gridforum.org/notification/notification_source/bindings"/>

<import location="../../security/authentication/gss_secure_conversation_bindings.wsdl"
        namespace="http://ogsa.globus.org/security/authentication/bindings"/>

<service name="ReliableFileTransferService">
  <documentation>Globus Reliable Transfer service (management of remote job execution)</documentation>

  <port binding="reliable-transfer-bindings:ReliableTransferSOAPBinding"
        name="ReliableTransferPort">
    <soap:address location="http://localhost:8443/ogsa/services"/>
  </port>

  <port binding="grid-service-bindings:GridServiceSOAPBinding"
        name="GridServicePort">
    <soap:address location="http://localhost:8443/ogsa/services"/>
  </port>

  
  <port binding="notification-source-bindings:NotificationSourceSOAPBinding"
        name="NotificationSourcePort">
    <soap:address location="http://localhost:8080/ogsa/services"/>
  </port>

<port binding="auth-bindings:SecureContextEstablishmentSOAPBinding"
        name="SecureContextEstablishmentPort">
   <soap:address location="http://localhost:8080/ogsa/services"/>
</port>

</service>
</definitions>
