<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ReliableTransferDefinition"
             targetNamespace="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer_bindings"
             xmlns:reliable-transfer-port-type="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer_port_type"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

<import location="reliable_transfer_port_type.wsdl"
        namespace="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer_port_type"/>

<binding name="ReliableTransferSOAPBinding" type="reliable-transfer-port-type:ReliableTransferPortType">
  <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="submitTransferJob">
    <soap:operation soapAction="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer#submitTransferJob"/>
    <input>
      <soap:body use="literal" namespace="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer"/>
    </input>
    <output>
      <soap:body use="literal" namespace="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer"/>
    </output>
  </operation>
  <operation name="getStatus">
    <soap:operation soapAction="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer#getStatus"/>
    <input>
      <soap:body use="literal" namespace="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer"/>
    </input>
    <output>
      <soap:body use="literal" namespace="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer"/>
    </output>
  </operation>
  <operation name="cancelTransfer">
    <soap:operation soapAction="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer#cancelTransfer"/>
    <input>
      <soap:body use="literal" namespace="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer"/>
    </input>
    <output>
      <soap:body use="literal" namespace="http://reliabletransfer.base.ogsa.globus.org/reliable_transfer"/>
    </output>
  </operation>
</binding>

</definitions>
