#ifndef GLOBUS_XIO_MODE_E_DRIVER_INCLUDE
#define GLOBUS_XIO_MODE_E_DRIVER_INCLUDE

#include "globus_xio_system.h"
#include "globus_common.h"

typedef enum
{
    GLOBUS_XIO_MODE_E_SET_STACK,

    GLOBUS_XIO_MODE_E_GET_STACK,

    GLOBUS_XIO_MODE_E_SET_NUM_STREAMS,

    GLOBUS_XIO_MODE_E_GET_NUM_STREAMS,

    GLOBUS_XIO_MODE_E_APPLY_ATTR_CNTLS,

    GLOBUS_XIO_MODE_E_SET_CLOSE,

    GLOBUS_XIO_MODE_E_GET_CLOSE,

    GLOBUS_XIO_MODE_E_SET_EOF,

    GLOBUS_XIO_MODE_E_GET_EOF

} globus_xio_mode_e_cmd_t;	

#endif
