#! /bin/sh

DIRT_BRANCH_DEF="$(git rev-parse --show-toplevel)/branch.def"
current_branch="$(git branch | awk "/\*/ {print \$2}")"
current_branch_id="$(awk "/$current_branch/ {print \$2}" < "$DIRT_BRANCH_DEF")"
current_timestamp="$(git log -n 1 --pretty=format:%ct%n .)"

dirtfile=$(basename "$2" .in)
exec 3> $(dirname "$2")/$dirtfile

case "$1" in 
    --smudge)
        while read line; do
            echo "$line" | \
            sed -e "s/DIRT_TIMESTAMP=.*/DIRT_TIMESTAMP=${current_timestamp:-0}/" \
                -e "s/DIRT_BRANCH_ID=.*/DIRT_BRANCH_ID=${current_branch_id:-0}/"\
                1>&3

            echo "$line"
        done
        ;;
    --clean)
        cat
        ;;
esac

