#-----------------------------------------------------------------------------
#
# NcFTP binary distribution makefile 
#
#-----------------------------------------------------------------------------

PREFIX=/usr/local
SHELL=/bin/sh

all:
	-@echo "Try \"make install\" to install the package into the $(PREFIX) hierarchy."

install:
	-@echo '..... Installing the programs .....'
	-mkdir $(PREFIX)/bin $(PREFIX)/man $(PREFIX)/man/man1 2>/dev/null
	-for f in ncftp ncftpget ncftpput ncftpbatch ncftpls ; do \
		/bin/rm -f $(PREFIX)/bin/$$f ; \
		cp bin/$$f $(PREFIX)/bin/$$f ; \
		chmod 755 $(PREFIX)/bin/$$f ; \
		chown bin $(PREFIX)/bin/$$f 2>/dev/null ; \
		chgrp bin $(PREFIX)/bin/$$f 2>/dev/null ; \
		: ; \
	done
	-@cp bin/ncftpbookmarks $(PREFIX)/bin/ncftpbookmarks 2>/dev/null
	-@chmod 755 $(PREFIX)/bin/ncftpbookmarks 2>/dev/null
	-@chown bin $(PREFIX)/bin/ncftpbookmarks 2>/dev/null
	-@chgrp bin $(PREFIX)/bin/ncftpbookmarks 2>/dev/null
	-@/bin/ls -l $(PREFIX)/bin/ncftp $(PREFIX)/bin/ncftpget $(PREFIX)/bin/ncftpput $(PREFIX)/bin/ncftpbatch $(PREFIX)/bin/ncftpls $(PREFIX)/bin/ncftpbookmarks
	-@echo '..... Installing the manual pages .....'
	for f in ncftp.1 ncftpget.1 ncftpput.1 ncftpbatch.1 ncftpls.1 ; do \
		/bin/rm -f $(PREFIX)/man/man1/$$f ; \
		cp doc/man/$$f $(PREFIX)/man/man1/$$f ; \
		chmod 644 $(PREFIX)/man/man1/$$f ; \
	done
	-@echo 'Done installing NcFTP.'
