#!/bin/sh

dir=$1; shift;

GPT_LOCATION=$1
GLOBUS_LOCATION=$2
FLAVOR=$3
export GLOBUS_LOCATION GPT_LOCATION

echo GPT_LOCATION is $GPT_LOCATION
echo GLOBUS_LOCATION is $GLOBUS_LOCATION
echo FLAVOR is $FLAVOR

cd ogsa-cvs/ogsa-c/build_tools
./cvs-build-ogsa --force libxml gcc32dbg
