#if !defined GLOBUS_XIO_TOKEN_BUCKET_DRIVER_H
#define GLOBUS_XIO_TOKEN_BUCKET_DRIVER_H 1

enum
{
    GLOBUS_XIO_TOKEN_BUCKET_SET_RATE = 1,
    GLOBUS_XIO_TOKEN_BUCKET_SET_PERIOD,
    GLOBUS_XIO_TOKEN_BUCKET_SET_READ_RATE,
    GLOBUS_XIO_TOKEN_BUCKET_SET_READ_PERIOD,
    GLOBUS_XIO_TOKEN_BUCKET_SET_WRITE_RATE,
    GLOBUS_XIO_TOKEN_BUCKET_SET_WRITE_PERIOD
};

#endif
