#!/bin/sh
#
# Usage:
#
#   1) Run the src-bundle creation script:
#
#        ./make-src-bundle
#

NAME="gsi_openssh_bundle-2.1-src.tar.gz"

if [ ! -e $NAME ]; then
    $GPT_LOCATION/sbin/gpt-bundle -srcdir=sources/ -output=$NAME -xml=gsi_openssh_bundle-src.xml
fi
