#!/bin/sh
#
# Usage:
#
#   1) Run the src-bundle creation script, passing as its only argument the path to the
#      directory containing all of the source packages to be included in the source bundle:
#
#        ./make-src-bundle <pathToSourcePackages>
#

NAME="gsi_openssh_bundle-2.1-src.tar.gz"

if [ ! -e $NAME ]; then
    $GPT_LOCATION/sbin/gpt-bundle -srcdir=$1 -output=$NAME -xml=gsi_openssh_bundle-src.xml
fi
