#!/bin/sh
#
# Usage:
#
#   1) Verify that your GLOBUS_LOCATION is set to the installation from which you
#      wish to create a binary bundle.
#
#   2) Run the bin-bundle creation script:
#
#        ./make-bin-bundle
#

NAME="gsi_openssh_bundle-2.1-i686-pc-linux-gnu.tar.gz"

if [ ! -e $NAME ]; then
    $GPT_LOCATION/sbin/gpt-bundle -output=$NAME -xml=gsi_openssh_bundle-bin.xml
fi
