#!/bin/sh
#
# Usage:
#
#   1) Run the src-bundle creation script:
#
#        ./make-src-bundle
#

source version.sh

NAME="gsi_openssh_bundle-$VERSION-src.tar.gz"

if [ ! -e $NAME ]; then
    $GPT_LOCATION/sbin/gpt-bundle -srcdir=sources/ -output=$NAME -bv=$VERSION -xml=gsi_openssh_bundle-src.xml
else; then
    echo "Please remove $NAME before running this script."
fi
