#!/usr/bin/env perl

# Run as $0 makefile.in > binary-makefile.in
# <makefile.in> - the Makefile.in from a source installer

my $package;
my $deps;

while (<>)
{
   # The -only: and -only-thr: targets only make sense for source.
   # Skip 'em.  The undef setting on package will also keep us
   # from printing out a line if they're followed by a gpt-build command.
   if (/-only:/ || /-thr:/) { $package = undef; next;}

   # When we hit a source package line (like foo_pkg: gpt globus_core)
   # or globus-data-bundle: package1 package2
   if ( /([a-z_\-0-9]+): (.*)/ )
   {
      $package = $1;
      $deps = $2;
      # There are no binary -thr packages
      $deps =~ s/([a-z_\-0-9]+)-thr/\1/g;
      # There's no binary version of globus_core, leave it out;
      $deps =~ s/globus_core//;
      print "${package}: ${deps}\n";
   } elsif ( /gpt-build/ )
   {
      if ( $package )
      {
         print "\ttar -C \${GLOBUS_LOCATION} -xzf binary-trees/${package}-*/*.tar.gz\n";
      }
      $package = undef;
   } else
   {
     # This is one of the preamble lines, or a non-gpt-build target.
     print;
   }
}
