#!/bin/sh

if [ x$1 = "x" ]; then
   echo Please supply a GLOBUS_LOCATION as the first argument
   exit 253
fi

GLOBUS_LOCATION=$1
SOURCE_MAKEFILE=$2

PATH="$GLOBUS_LOCATION/bin:$GLOBUS_LOCATION/sbin:$PATH"
LD_LIBRARY_PATH="$GLOBUS_LOCATION/lib:$PATH"
export PATH LD_LIBRARY_PATH GLOBUS_LOCATION

echo Generating GPT bundle definition for $GLOBUS_LOCATION
fait_accompli/gpt-generate-bundle-definition > abc.xml
if [ $? -ne 0 ]; then
   echo Error creating bundle definition.
   exit 1
fi

echo Generating GPT binary bundle.
$GLOBUS_LOCATION/sbin/gpt-bundle -xml=abc.xml -nodeps
if [ $? -ne 0 ]; then
   echo Error creating bundle. 
   exit 2
fi

mkdir -p tmp
if [ $? -ne 0 ]; then
   echo Error creating temp directory
   exit 3
fi

echo Re-organizing GPT binary bundle into binary installer in tmp/
cd tmp/
tar xzf ../notname*.tar.gz
mkdir binary-trees
for f in *.tar.gz; do
   FILENAME=`echo $f | awk -F- '{print $1 "-" $2}' `
   mkdir -p binary-trees/$FILENAME
   mv $f binary-trees/$FILENAME
done

cd binary-trees/
for f in *; do
  cd $f;
  for g in *.tar.gz; do
    tar xzf $g
    rm $g
  done
  BADFILES=`ls`
  tar czf $f.tar.gz *
  rm -fr ${BADFILES}
  cd ..
done

# Get out of tmp/binary-trees/
cd ../
rm notnamed_bundle*
rm packagelist
cd ../

echo Generating configure/Makefile.in for binary installer
if [ -f $SOURCE_MAKEFILE ]; then
   fait_accompli/binary-makefile-generator < $SOURCE_MAKEFILE > tmp/Makefile.in
else
   cp fait_accompli/binary.Makefile.in tmp/Makefile.in
fi

source-trees/autotools/bin/autoconf fait_accompli/binary.configure.in > tmp/configure
chmod +x tmp/configure

echo Adding GPT source to binary installer
tar -C tmp -xzf gpt-*.tar.gz

echo Adding README/INSTALL
cp fait_accompli/binary.INSTALL tmp/INSTALL
cp fait_accompli/binary.README tmp/README

echo Done.
