#!/bin/sh

short_usage="$0 [-help] <install-dir>";
long_usage()
{
   cat 1>&2 <<END

${short_usage}

    Installs GT3 to the directory <install-dir>.

    Example: $0 /opt/gt3
END
}

if [ $# -eq 0 ]; then
    echo "Usage: ${short_usage}"
    exit 1
fi

while [ -n "$1" ]; do
    case "$1" in
        -help)
            long_usage;
            exit 0
            ;;
        *)
            if [ $# -gt 1 ]; then
                echo "Unrecognized option $1"
                exit 1;
            fi
            destdir=$1
            ;;
    esac
    shift
done

if [ -z "${destdir}" ]; then
    echo "" >&2
    echo "ERROR: install-dir is missing" >&2
    echo "${short_usage}"
    exit 1
fi

GPT_LOCATION="$destdir"
GLOBUS_LOCATION="$destdir"
GPT_BUILD="$GPT_LOCATION"/sbin/gpt-build
GPT_INSTALL="$GPT_LOCATION"/sbin/gpt-install

export GPT_LOCATION GLOBUS_LOCATION
echo Install environment:
type ant
if [ $? -ne 0 ]; then
   echo You need a working version of ant.
   exit
fi
type java
if [ $? -ne 0 ]; then
   echo You need a working version of java.
   exit
fi

if [ ! -f gpt-3.0.1/sbin/gpt-build ]; then
    echo Building GPT ...
    gzip -dc gpt-3.0.1-src.tar.gz | tar xf -
    cd gpt-3.0.1

    LANG="" ./build_gpt
    if [ $? -ne 0 ]; then
        echo Error building GPT
        exit;
    fi

    cd ..
fi

$GPT_INSTALL BUNDLE_GOES_HERE
if [ $? -ne 0 ]; then
    echo Error installing binary bundle
    exit;
fi

if [ ! -d $GLOBUS_LOCATION/contrib ]; then
    cp -Rp contrib/ $GLOBUS_LOCATION;
fi

cd $GLOBUS_LOCATION
ant setup

$GPT_LOCATION/sbin/gpt-postinstall
