#!/bin/sh

if [ x$1 = "x" ]; then
	echo $0: Usage: $0 install-directory
	exit;
fi

GPT_LOCATION=`pwd`/gpt-2.2.5
GLOBUS_LOCATION=$1
GT3_LOCATION=$1

export GPT_LOCATION GLOBUS_LOCATION GT3_LOCATION

echo Building GPT ...
gzip -dc gpt-2.2.5-src.tar.gz | tar xf -

cd gpt-2.2.5
./build_gpt
cd ..

$GPT_LOCATION/sbin/gpt-install gt3_alpha2_bin_bundle-r1_bin.tar.gz
$GPT_LOCATION/sbin/gpt-install gt3-all-bin-1-i686-pc-linux-gnu-bin.tar.gz
$GPT_LOCATION/sbin/gpt-install gt3_hostinfo-1.0-i686-pc-linux-gnu-noflavor-pgm.tar.gz
$GPT_LOCATION/sbin/gpt-install globus-rls-server-1.1-i686-pc-linux-gnu-bin.tar.gz


$GPT_LOCATION/sbin/gpt-postinstall
