#!/bin/sh

if [ x$1 = "x" ]; then
	echo $0: Usage: $0 install-directory
	exit;
fi

GPT_LOCATION=$1
GLOBUS_LOCATION=$1
GT3_LOCATION=$1

export GPT_LOCATION GLOBUS_LOCATION GT3_LOCATION

echo Building GPT ...
gzip -dc gpt-2.2.5-src.tar.gz | tar xf -

cd gpt-2.2.5
./build_gpt
cd ..

$GPT_LOCATION/sbin/gpt-build gt3-all-src-1-src_bundle.tar.gz gcc32dbg
$GPT_LOCATION/sbin/gpt-build gt3_alpha2_src_bundle-r1_src.tar.gz gcc32dbg
mkdir -p $1/contrib
(cp OGSI.NET.zip $1/contrib; cd $1; unzip OGSI.NET.zip)

$GPT_LOCATION/sbin/gpt-postinstall
