#!/bin/sh

if [ x$1 = "x" ]; then
	echo $0: Usage: $0 install-directory
	exit;
fi

GPT_LOCATION=$1
GLOBUS_LOCATION=$1
GT3_LOCATION=$1

export GPT_LOCATION GLOBUS_LOCATION GT3_LOCATION

echo Building GPT ...
gzip -dc gpt-2.2.5-src.tar.gz | tar xf -

cd gpt-2.2.5
./build_gpt
cd ..

$GPT_LOCATION/sbin/gpt-install gt3_alpha2_bin_bundle-r1_bin.tar.gz
$GPT_LOCATION/sbin/gpt-install gt3-all-bin-1-i686-pc-linux-gnu-bin.tar.gz
$GPT_LOCATION/sbin/gpt-install globus-rls-server-1.1-i686-pc-linux-gnu-bin.tar.gz
mkdir -p $1/contrib
cp OGSI.NET.zip $1/contrib
cd $1/contrib
unzip OGSI.NET.zip
cd ../gars

for f in *; do
	ant -f ../build.xml deploy -Dgar.name=`pwd`/$f
	if [ $f = "mmjfs.gar" ]; then
		ant -f build-setuid.xml deploy
		ant -f build-setuid.xml mirrorConfig
	fi
done

$GPT_LOCATION/sbin/gpt-postinstall
