#!/bin/sh

# 
# Copyright 1999-2006 University of Chicago
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 


usage()
{
	echo "Usage: $0 [name of module]"
	echo "i.e. globus_common"
	exit 1;
}


CPP=`grep "^CPP =" Makefile|sed -e "s/^CPP =//"`;
CPPFLAGS=`grep "^CPPFLAGS =" Makefile | sed -e "s/^CPPFLAGS =//"`;
echo $CPP;
echo $CPPFLAGS;


rm -f masteri18nstrings; 
rm -f myi18nstrings;

list=`find ./ -name "*.[c|h]"`; for file in $list; do 
	 $CPP $CPPFLAGS $file |grep globus_common_i18n_get_string |sed -e "s/^.*globus_common_i18n_get_string[^\"]*//" -e "s/\"\s*).*/\"/"| sed -e "s/^\"//" -e "s/\"$//" -e "s/\"\s*\"//g"|grep .|sort -u >>myi18nstrings;
	done; 
	
sort -u myi18nstrings >masteri18nstrings;
	
$GLOBUS_LOCATION/bin/globus-i18n-resource-init masteri18nstrings $1.txt; \
	export LD_LIBRARY_PATH=$GLOBUS_LOCATION/lib; $GLOBUS_LOCATION/bin/genrb -q -p $1 $1.txt;

