#!/bin/bash
#
#	/etc/rc.d/init.d/globus-usage-collector
#
# Starts the globus-usage-collector daemon
#
# chkconfig: 345 26 74
# description: Listen for and save Globus usage stats packets
# processname: globus-usage-collector

### BEGIN INIT INFO
# Provides: globus-usage-collector
# Required-Start: $network
# Required-Stop: $network
# Default-Start:  
# Default-Stop: 
# Short-Description: start and stop globus-usage-collector
# Description: Listen for and save Globus usage stats packets
### END INIT INFO

# Source function library.
if [ -f /lib/lsb/init-functions ]; then
    lsb=1
    . /lib/lsb/init-functions
elif [ -f /etc/rc.d/init.d/functions ]; then
    rh=1
    . /etc/rc.d/init.d/functions
fi

USER=usagestats
PIDFILE=/var/run/globus-usage-collector
RETVAL=0

check() {
	# Check that we're a privileged user
	[ `id -u` = 0 ] || exit 4
	
	# Check if globus-usage-collector is executable
	test -x /usr/sbin/globus-usage-collector || exit 5
}

start() {

	check
        touch $PIDFILE
        chown $USER $PIDFILE
	
	printf "Starting globus-usage-collector daemon: "	
        if [ "$rh" = 1 ]; then
            daemon --user $USER /usr/sbin/globus-usage-collector -b -p $PIDFILE
        elif [ "$lsb" = 1 ]; then
            su $USER -s /bin/sh -c ". /lib/lsb/init-functions; start_daemon /usr/sbin/globus-usage-collector -b -p $PIDFILE"
        else
            su $USER -s /bin/sh -c "/usr/sbin/globus-usage-collector -b -p $PIDFILE"
        fi
	RETVAL=$?
	[ $RETVAL -eq 0 ] && [ "$rh" = "1" ] && touch /var/lock/subsys/globus-usage-collector
	echo
	return $RETVAL
}

stop() {

	check
	
	printf $"Stopping globus-usage-collector"
        if [ "$rh" = 1 ]; then
            killproc -p $PIDFILE /usr/sbin/globus-usage-collector
        elif [ "$lsb" = 1 ]; then
            stop_daemon -p $PIDFILE /usr/sbin/globus-usage-collector
        else
            read pid < $PIDFILE
            kill $pid
            rm -f $PIDFILE
        fi 
	RETVAL=$?
	[ $RETVAL -eq 0 ] [ "$rh" = "1" ] && rm -f /var/lock/subsys/globus-usage-collector
	echo
    return $RETVAL
}

restart() {
	stop
	start
}	

reload() {

	check
	
	trap "" SIGHUP
        RETVAL=0
        if [ "$rh" = 1 ]; then
            action $"Reloading globus-usage-collector daemon:" killall -HUP globus-usage-collector
            RETVAL=$?
        fi
	return $RETVAL
}


case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
force-reload)
	restart
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/globus-usage-collector ]; then
	    restart
	fi
	;;
status)
	status globus-usage-collector
	RETVAL=$?
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload|force-reload}"
	RETVAL=2
esac

exit $RETVAL
