#!/bin/sh

cd source

make dist

cp globus_simple_ca-0.8.tar.gz ../packages/

cd ../setup

make dist

cp globus_simple_ca_setup-0.12.tar.gz ../packages/

cd ../

$GLOBUS_LOCATION/sbin/gpt-bundle -nodeps -srcdir=packages -output=globus_simple_ca_bundle-0.12.tar.gz -config=packaging_list `cat packaging_list | xargs`

#scp globus_simple_ca_bundle-beta-r6.tar.gz slang@ept.mcs.anl.gov:/mcs/ftp.globus.org/pub/gsi/2.0/globus_simple_ca_bundle-beta-r6.tar.gz

